SONG_SRCS := \
	sound/songs/midi/mus_dummy.s \
	sound/songs/midi/se_use_item.s \
	sound/songs/midi/se_pc_login.s \
	sound/songs/midi/se_pc_off.s \
	sound/songs/midi/se_pc_on.s \
	sound/songs/midi/se_select.s \
	sound/songs/midi/se_win_open.s \
	sound/songs/midi/se_wall_hit.s \
	sound/songs/midi/se_door.s \
	sound/songs/midi/se_exit.s \
	sound/songs/midi/se_ledge.s \
	sound/songs/midi/se_bike_bell.s \
	sound/songs/midi/se_not_effective.s \
	sound/songs/midi/se_effective.s \
	sound/songs/midi/se_super_effective.s \
	sound/songs/midi/se_ball_open.s \
	sound/songs/midi/se_faint.s \
	sound/songs/midi/se_flee.s \
	sound/songs/midi/se_sliding_door.s \
	sound/songs/midi/se_ship.s \
	sound/songs/midi/se_bang.s \
	sound/songs/midi/se_pin.s \
	sound/songs/midi/se_boo.s \
	sound/songs/midi/se_ball.s \
	sound/songs/midi/se_contest_place.s \
	sound/songs/midi/se_a.s \
	sound/songs/midi/se_i.s \
	sound/songs/midi/se_u.s \
	sound/songs/midi/se_e.s \
	sound/songs/midi/se_o.s \
	sound/songs/midi/se_n.s \
	sound/songs/midi/se_success.s \
	sound/songs/midi/se_failure.s \
	sound/songs/midi/se_exp.s \
	sound/songs/midi/se_bike_hop.s \
	sound/songs/midi/se_switch.s \
	sound/songs/midi/se_click.s \
	sound/songs/midi/se_fu_zaku.s \
	sound/songs/midi/se_contest_condition_lose.s \
	sound/songs/midi/se_lavaridge_fall_warp.s \
	sound/songs/midi/se_ice_stairs.s \
	sound/songs/midi/se_ice_break.s \
	sound/songs/midi/se_ice_crack.s \
	sound/songs/midi/se_fall.s \
	sound/songs/midi/se_unlock.s \
	sound/songs/midi/se_warp_in.s \
	sound/songs/midi/se_warp_out.s \
	sound/songs/midi/se_repel.s \
	sound/songs/midi/se_rotating_gate.s \
	sound/songs/midi/se_truck_move.s \
	sound/songs/midi/se_truck_stop.s \
	sound/songs/midi/se_truck_unload.s \
	sound/songs/midi/se_truck_door.s \
	sound/songs/midi/se_berry_blender.s \
	sound/songs/midi/se_card.s \
	sound/songs/midi/se_save.s \
	sound/songs/midi/se_ball_bounce_1.s \
	sound/songs/midi/se_ball_bounce_2.s \
	sound/songs/midi/se_ball_bounce_3.s \
	sound/songs/midi/se_ball_bounce_4.s \
	sound/songs/midi/se_ball_trade.s \
	sound/songs/midi/se_ball_throw.s \
	sound/songs/midi/se_note_c.s \
	sound/songs/midi/se_note_d.s \
	sound/songs/midi/se_note_e.s \
	sound/songs/midi/se_note_f.s \
	sound/songs/midi/se_note_g.s \
	sound/songs/midi/se_note_a.s \
	sound/songs/midi/se_note_b.s \
	sound/songs/midi/se_note_c_high.s \
	sound/songs/midi/se_puddle.s \
	sound/songs/midi/se_bridge_walk.s \
	sound/songs/midi/se_itemfinder.s \
	sound/songs/midi/se_ding_dong.s \
	sound/songs/midi/se_balloon_red.s \
	sound/songs/midi/se_balloon_blue.s \
	sound/songs/midi/se_balloon_yellow.s \
	sound/songs/midi/se_breakable_door.s \
	sound/songs/midi/se_mud_ball.s \
	sound/songs/midi/se_field_poison.s \
	sound/songs/midi/se_escalator.s \
	sound/songs/midi/se_thunderstorm.s \
	sound/songs/midi/se_thunderstorm_stop.s \
	sound/songs/midi/se_downpour.s \
	sound/songs/midi/se_downpour_stop.s \
	sound/songs/midi/se_rain.s \
	sound/songs/midi/se_rain_stop.s \
	sound/songs/midi/se_thunder.s \
	sound/songs/midi/se_thunder2.s \
	sound/songs/midi/se_elevator.s \
	sound/songs/midi/se_low_health.s \
	sound/songs/midi/se_exp_max.s \
	sound/songs/midi/se_roulette_ball.s \
	sound/songs/midi/se_roulette_ball2.s \
	sound/songs/midi/se_taillow_wing_flap.s \
	sound/songs/midi/se_shop.s \
	sound/songs/midi/se_contest_heart.s \
	sound/songs/midi/se_contest_curtain_rise.s \
	sound/songs/midi/se_contest_curtain_fall.s \
	sound/songs/midi/se_contest_icon_change.s \
	sound/songs/midi/se_contest_icon_clear.s \
	sound/songs/midi/se_contest_mons_turn.s \
	sound/songs/midi/se_shiny.s \
	sound/songs/midi/se_intro_blast.s \
	sound/songs/midi/se_mugshot.s \
	sound/songs/midi/se_applause.s \
	sound/songs/midi/se_vend.s \
	sound/songs/midi/se_orb.s \
	sound/songs/midi/se_dex_scroll.s \
	sound/songs/midi/se_dex_page.s \
	sound/songs/midi/se_pokenav_on.s \
	sound/songs/midi/se_pokenav_off.s \
	sound/songs/midi/se_dex_search.s \
	sound/songs/midi/se_egg_hatch.s \
	sound/songs/midi/se_ball_tray_enter.s \
	sound/songs/midi/se_ball_tray_ball.s \
	sound/songs/midi/se_ball_tray_exit.s \
	sound/songs/midi/se_glass_flute.s \
	sound/songs/midi/se_m_thunderbolt.s \
	sound/songs/midi/se_m_thunderbolt2.s \
	sound/songs/midi/se_m_harden.s \
	sound/songs/midi/se_m_nightmare.s \
	sound/songs/midi/se_m_vital_throw.s \
	sound/songs/midi/se_m_vital_throw2.s \
	sound/songs/midi/se_m_bubble.s \
	sound/songs/midi/se_m_bubble2.s \
	sound/songs/midi/se_m_bubble3.s \
	sound/songs/midi/se_m_rain_dance.s \
	sound/songs/midi/se_m_cut.s \
	sound/songs/midi/se_m_string_shot.s \
	sound/songs/midi/se_m_string_shot2.s \
	sound/songs/midi/se_m_rock_throw.s \
	sound/songs/midi/se_m_gust.s \
	sound/songs/midi/se_m_gust2.s \
	sound/songs/midi/se_m_double_slap.s \
	sound/songs/midi/se_m_double_team.s \
	sound/songs/midi/se_m_razor_wind.s \
	sound/songs/midi/se_m_icy_wind.s \
	sound/songs/midi/se_m_thunder_wave.s \
	sound/songs/midi/se_m_comet_punch.s \
	sound/songs/midi/se_m_mega_kick.s \
	sound/songs/midi/se_m_mega_kick2.s \
	sound/songs/midi/se_m_crabhammer.s \
	sound/songs/midi/se_m_jump_kick.s \
	sound/songs/midi/se_m_flame_wheel.s \
	sound/songs/midi/se_m_flame_wheel2.s \
	sound/songs/midi/se_m_flamethrower.s \
	sound/songs/midi/se_m_fire_punch.s \
	sound/songs/midi/se_m_toxic.s \
	sound/songs/midi/se_m_sacred_fire.s \
	sound/songs/midi/se_m_sacred_fire2.s \
	sound/songs/midi/se_m_ember.s \
	sound/songs/midi/se_m_take_down.s \
	sound/songs/midi/se_m_blizzard.s \
	sound/songs/midi/se_m_blizzard2.s \
	sound/songs/midi/se_m_scratch.s \
	sound/songs/midi/se_m_vicegrip.s \
	sound/songs/midi/se_m_wing_attack.s \
	sound/songs/midi/se_m_fly.s \
	sound/songs/midi/se_m_sand_attack.s \
	sound/songs/midi/se_m_razor_wind2.s \
	sound/songs/midi/se_m_bite.s \
	sound/songs/midi/se_m_headbutt.s \
	sound/songs/midi/se_m_surf.s \
	sound/songs/midi/se_m_hydro_pump.s \
	sound/songs/midi/se_m_whirlpool.s \
	sound/songs/midi/se_m_horn_attack.s \
	sound/songs/midi/se_m_tail_whip.s \
	sound/songs/midi/se_m_mist.s \
	sound/songs/midi/se_m_poison_powder.s \
	sound/songs/midi/se_m_bind.s \
	sound/songs/midi/se_m_dragon_rage.s \
	sound/songs/midi/se_m_sing.s \
	sound/songs/midi/se_m_perish_song.s \
	sound/songs/midi/se_m_pay_day.s \
	sound/songs/midi/se_m_dig.s \
	sound/songs/midi/se_m_dizzy_punch.s \
	sound/songs/midi/se_m_self_destruct.s \
	sound/songs/midi/se_m_explosion.s \
	sound/songs/midi/se_m_absorb_2.s \
	sound/songs/midi/se_m_absorb.s \
	sound/songs/midi/se_m_screech.s \
	sound/songs/midi/se_m_bubble_beam.s \
	sound/songs/midi/se_m_bubble_beam2.s \
	sound/songs/midi/se_m_supersonic.s \
	sound/songs/midi/se_m_belly_drum.s \
	sound/songs/midi/se_m_metronome.s \
	sound/songs/midi/se_m_bonemerang.s \
	sound/songs/midi/se_m_lick.s \
	sound/songs/midi/se_m_psybeam.s \
	sound/songs/midi/se_m_faint_attack.s \
	sound/songs/midi/se_m_swords_dance.s \
	sound/songs/midi/se_m_leer.s \
	sound/songs/midi/se_m_swagger.s \
	sound/songs/midi/se_m_swagger2.s \
	sound/songs/midi/se_m_heal_bell.s \
	sound/songs/midi/se_m_confuse_ray.s \
	sound/songs/midi/se_m_snore.s \
	sound/songs/midi/se_m_brick_break.s \
	sound/songs/midi/se_m_giga_drain.s \
	sound/songs/midi/se_m_psybeam2.s \
	sound/songs/midi/se_m_solar_beam.s \
	sound/songs/midi/se_m_petal_dance.s \
	sound/songs/midi/se_m_teleport.s \
	sound/songs/midi/se_m_minimize.s \
	sound/songs/midi/se_m_sketch.s \
	sound/songs/midi/se_m_swift.s \
	sound/songs/midi/se_m_reflect.s \
	sound/songs/midi/se_m_barrier.s \
	sound/songs/midi/se_m_detect.s \
	sound/songs/midi/se_m_lock_on.s \
	sound/songs/midi/se_m_moonlight.s \
	sound/songs/midi/se_m_charm.s \
	sound/songs/midi/se_m_charge.s \
	sound/songs/midi/se_m_strength.s \
	sound/songs/midi/se_m_hyper_beam.s \
	sound/songs/midi/se_m_waterfall.s \
	sound/songs/midi/se_m_reversal.s \
	sound/songs/midi/se_m_acid_armor.s \
	sound/songs/midi/se_m_sandstorm.s \
	sound/songs/midi/se_m_tri_attack.s \
	sound/songs/midi/se_m_tri_attack2.s \
	sound/songs/midi/se_m_encore.s \
	sound/songs/midi/se_m_encore2.s \
	sound/songs/midi/se_m_baton_pass.s \
	sound/songs/midi/se_m_milk_drink.s \
	sound/songs/midi/se_m_attract.s \
	sound/songs/midi/se_m_attract2.s \
	sound/songs/midi/se_m_morning_sun.s \
	sound/songs/midi/se_m_flatter.s \
	sound/songs/midi/se_m_sand_tomb.s \
	sound/songs/midi/se_m_grasswhistle.s \
	sound/songs/midi/se_m_spit_up.s \
	sound/songs/midi/se_m_dive.s \
	sound/songs/midi/se_m_earthquake.s \
	sound/songs/midi/se_m_twister.s \
	sound/songs/midi/se_m_sweet_scent.s \
	sound/songs/midi/se_m_yawn.s \
	sound/songs/midi/se_m_sky_uppercut.s \
	sound/songs/midi/se_m_stat_increase.s \
	sound/songs/midi/se_m_heat_wave.s \
	sound/songs/midi/se_m_uproar.s \
	sound/songs/midi/se_m_hail.s \
	sound/songs/midi/se_m_cosmic_power.s \
	sound/songs/midi/se_m_teeter_dance.s \
	sound/songs/midi/se_m_stat_decrease.s \
	sound/songs/midi/se_m_haze.s \
	sound/songs/midi/se_m_hyper_beam2.s \
	sound/songs/midi/se_rg_door.s \
	sound/songs/midi/se_rg_card_flip.s \
	sound/songs/midi/se_rg_card_flipping.s \
	sound/songs/midi/se_rg_card_open.s \
	sound/songs/midi/se_rg_bag_cursor.s \
	sound/songs/midi/se_rg_bag_pocket.s \
	sound/songs/midi/se_rg_ball_click.s \
	sound/songs/midi/se_rg_shop.s \
	sound/songs/midi/se_rg_ss_anne_horn.s \
	sound/songs/midi/se_rg_help_open.s \
	sound/songs/midi/se_rg_help_close.s \
	sound/songs/midi/se_rg_help_error.s \
	sound/songs/midi/se_rg_deoxys_move.s \
	sound/songs/midi/se_rg_poke_jump_success.s \
	sound/songs/midi/se_rg_poke_jump_failure.s \
	sound/songs/midi/se_pokenav_call.s \
	sound/songs/midi/se_pokenav_hang_up.s \
	sound/songs/midi/se_arena_timeup1.s \
	sound/songs/midi/se_arena_timeup2.s \
	sound/songs/midi/se_pike_curtain_close.s \
	sound/songs/midi/se_pike_curtain_open.s \
	sound/songs/midi/se_sudowoodo_shake.s \
	sound/songs/midi/mus_littleroot_test.s \
	sound/songs/midi/mus_gsc_route38.s \
	sound/songs/midi/mus_caught.s \
	sound/songs/midi/mus_victory_wild.s \
	sound/songs/midi/mus_victory_gym_leader.s \
	sound/songs/midi/mus_victory_league.s \
	sound/songs/midi/mus_c_comm_center.s \
	sound/songs/midi/mus_gsc_pewter.s \
	sound/songs/midi/mus_c_vs_legend_beast.s \
	sound/songs/midi/mus_route101.s \
	sound/songs/midi/mus_route110.s \
	sound/songs/midi/mus_route120.s \
	sound/songs/midi/mus_petalburg.s \
	sound/songs/midi/mus_oldale.s \
	sound/songs/midi/mus_gym.s \
	sound/songs/midi/mus_surf.s \
	sound/songs/midi/mus_petalburg_woods.s \
	sound/songs/midi/mus_level_up.s \
	sound/songs/midi/mus_heal.s \
	sound/songs/midi/mus_obtain_badge.s \
	sound/songs/midi/mus_obtain_item.s \
	sound/songs/midi/mus_evolved.s \
	sound/songs/midi/mus_obtain_tmhm.s \
	sound/songs/midi/mus_lilycove_museum.s \
	sound/songs/midi/mus_route122.s \
	sound/songs/midi/mus_oceanic_museum.s \
	sound/songs/midi/mus_evolution_intro.s \
	sound/songs/midi/mus_evolution.s \
	sound/songs/midi/mus_move_deleted.s \
	sound/songs/midi/mus_encounter_girl.s \
	sound/songs/midi/mus_encounter_male.s \
	sound/songs/midi/mus_abandoned_ship.s \
	sound/songs/midi/mus_fortree.s \
	sound/songs/midi/mus_birch_lab.s \
	sound/songs/midi/mus_b_tower_rs.s \
	sound/songs/midi/mus_encounter_swimmer.s \
	sound/songs/midi/mus_cave_of_origin.s \
	sound/songs/midi/mus_obtain_berry.s \
	sound/songs/midi/mus_awaken_legend.s \
	sound/songs/midi/mus_slots_jackpot.s \
	sound/songs/midi/mus_slots_win.s \
	sound/songs/midi/mus_too_bad.s \
	sound/songs/midi/mus_roulette.s \
	sound/songs/midi/mus_link_contest_p1.s \
	sound/songs/midi/mus_link_contest_p2.s \
	sound/songs/midi/mus_link_contest_p3.s \
	sound/songs/midi/mus_link_contest_p4.s \
	sound/songs/midi/mus_encounter_rich.s \
	sound/songs/midi/mus_verdanturf.s \
	sound/songs/midi/mus_rustboro.s \
	sound/songs/midi/mus_poke_center.s \
	sound/songs/midi/mus_route104.s \
	sound/songs/midi/mus_route119.s \
	sound/songs/midi/mus_cycling.s \
	sound/songs/midi/mus_poke_mart.s \
	sound/songs/midi/mus_littleroot.s \
	sound/songs/midi/mus_mt_chimney.s \
	sound/songs/midi/mus_encounter_female.s \
	sound/songs/midi/mus_lilycove.s \
	sound/songs/midi/mus_route111.s \
	sound/songs/midi/mus_help.s \
	sound/songs/midi/mus_underwater.s \
	sound/songs/midi/mus_victory_trainer.s \
	sound/songs/midi/mus_title.s \
	sound/songs/midi/mus_intro.s \
	sound/songs/midi/mus_encounter_may.s \
	sound/songs/midi/mus_encounter_intense.s \
	sound/songs/midi/mus_encounter_cool.s \
	sound/songs/midi/mus_route113.s \
	sound/songs/midi/mus_encounter_aqua.s \
	sound/songs/midi/mus_follow_me.s \
	sound/songs/midi/mus_encounter_brendan.s \
	sound/songs/midi/mus_ever_grande.s \
	sound/songs/midi/mus_encounter_suspicious.s \
	sound/songs/midi/mus_victory_aqua_magma.s \
	sound/songs/midi/mus_cable_car.s \
	sound/songs/midi/mus_game_corner.s \
	sound/songs/midi/mus_dewford.s \
	sound/songs/midi/mus_safari_zone.s \
	sound/songs/midi/mus_victory_road.s \
	sound/songs/midi/mus_aqua_magma_hideout.s \
	sound/songs/midi/mus_sailing.s \
	sound/songs/midi/mus_mt_pyre.s \
	sound/songs/midi/mus_slateport.s \
	sound/songs/midi/mus_mt_pyre_exterior.s \
	sound/songs/midi/mus_school.s \
	sound/songs/midi/mus_hall_of_fame.s \
	sound/songs/midi/mus_fallarbor.s \
	sound/songs/midi/mus_sealed_chamber.s \
	sound/songs/midi/mus_contest_winner.s \
	sound/songs/midi/mus_contest.s \
	sound/songs/midi/mus_encounter_magma.s \
	sound/songs/midi/mus_intro_battle.s \
	sound/songs/midi/mus_abnormal_weather.s \
	sound/songs/midi/mus_weather_groudon.s \
	sound/songs/midi/mus_sootopolis.s \
	sound/songs/midi/mus_contest_results.s \
	sound/songs/midi/mus_hall_of_fame_room.s \
	sound/songs/midi/mus_trick_house.s \
	sound/songs/midi/mus_encounter_twins.s \
	sound/songs/midi/mus_encounter_elite_four.s \
	sound/songs/midi/mus_encounter_hiker.s \
	sound/songs/midi/mus_contest_lobby.s \
	sound/songs/midi/mus_encounter_interviewer.s \
	sound/songs/midi/mus_encounter_champion.s \
	sound/songs/midi/mus_credits.s \
	sound/songs/midi/mus_end.s \
	sound/songs/midi/mus_b_frontier.s \
	sound/songs/midi/mus_b_arena.s \
	sound/songs/midi/mus_obtain_b_points.s \
	sound/songs/midi/mus_register_match_call.s \
	sound/songs/midi/mus_b_pyramid.s \
	sound/songs/midi/mus_b_pyramid_top.s \
	sound/songs/midi/mus_b_palace.s \
	sound/songs/midi/mus_rayquaza_appears.s \
	sound/songs/midi/mus_b_tower.s \
	sound/songs/midi/mus_obtain_symbol.s \
	sound/songs/midi/mus_b_dome.s \
	sound/songs/midi/mus_b_pike.s \
	sound/songs/midi/mus_b_factory.s \
	sound/songs/midi/mus_vs_rayquaza.s \
	sound/songs/midi/mus_vs_frontier_brain.s \
	sound/songs/midi/mus_vs_mew.s \
	sound/songs/midi/mus_b_dome_lobby.s \
	sound/songs/midi/mus_vs_wild.s \
	sound/songs/midi/mus_vs_aqua_magma.s \
	sound/songs/midi/mus_vs_trainer.s \
	sound/songs/midi/mus_vs_gym_leader.s \
	sound/songs/midi/mus_vs_champion.s \
	sound/songs/midi/mus_vs_regi.s \
	sound/songs/midi/mus_vs_kyogre_groudon.s \
	sound/songs/midi/mus_vs_rival.s \
	sound/songs/midi/mus_vs_elite_four.s \
	sound/songs/midi/mus_vs_aqua_magma_leader.s \
	sound/songs/midi/mus_rg_follow_me.s \
	sound/songs/midi/mus_rg_game_corner.s \
	sound/songs/midi/mus_rg_rocket_hideout.s \
	sound/songs/midi/mus_rg_gym.s \
	sound/songs/midi/mus_rg_jigglypuff.s \
	sound/songs/midi/mus_rg_intro_fight.s \
	sound/songs/midi/mus_rg_title.s \
	sound/songs/midi/mus_rg_cinnabar.s \
	sound/songs/midi/mus_rg_lavender.s \
	sound/songs/midi/mus_rg_heal.s \
	sound/songs/midi/mus_rg_cycling.s \
	sound/songs/midi/mus_rg_encounter_rocket.s \
	sound/songs/midi/mus_rg_encounter_girl.s \
	sound/songs/midi/mus_rg_encounter_boy.s \
	sound/songs/midi/mus_rg_hall_of_fame.s \
	sound/songs/midi/mus_rg_viridian_forest.s \
	sound/songs/midi/mus_rg_mt_moon.s \
	sound/songs/midi/mus_rg_poke_mansion.s \
	sound/songs/midi/mus_rg_credits.s \
	sound/songs/midi/mus_rg_route1.s \
	sound/songs/midi/mus_rg_route24.s \
	sound/songs/midi/mus_rg_route3.s \
	sound/songs/midi/mus_rg_route11.s \
	sound/songs/midi/mus_rg_victory_road.s \
	sound/songs/midi/mus_rg_vs_gym_leader.s \
	sound/songs/midi/mus_rg_vs_trainer.s \
	sound/songs/midi/mus_rg_vs_wild.s \
	sound/songs/midi/mus_rg_vs_champion.s \
	sound/songs/midi/mus_rg_pallet.s \
	sound/songs/midi/mus_rg_oak_lab.s \
	sound/songs/midi/mus_rg_oak.s \
	sound/songs/midi/mus_rg_poke_center.s \
	sound/songs/midi/mus_rg_ss_anne.s \
	sound/songs/midi/mus_rg_surf.s \
	sound/songs/midi/mus_rg_poke_tower.s \
	sound/songs/midi/mus_rg_silph.s \
	sound/songs/midi/mus_rg_fuchsia.s \
	sound/songs/midi/mus_rg_celadon.s \
	sound/songs/midi/mus_rg_victory_trainer.s \
	sound/songs/midi/mus_rg_victory_wild.s \
	sound/songs/midi/mus_rg_victory_gym_leader.s \
	sound/songs/midi/mus_rg_vermillion.s \
	sound/songs/midi/mus_rg_pewter.s \
	sound/songs/midi/mus_rg_encounter_rival.s \
	sound/songs/midi/mus_rg_rival_exit.s \
	sound/songs/midi/mus_rg_dex_rating.s \
	sound/songs/midi/mus_rg_obtain_key_item.s \
	sound/songs/midi/mus_rg_caught_intro.s \
	sound/songs/midi/mus_rg_photo.s \
	sound/songs/midi/mus_rg_game_freak.s \
	sound/songs/midi/mus_rg_caught.s \
	sound/songs/midi/mus_rg_new_game_instruct.s \
	sound/songs/midi/mus_rg_new_game_intro.s \
	sound/songs/midi/mus_rg_new_game_exit.s \
	sound/songs/midi/mus_rg_poke_jump.s \
	sound/songs/midi/mus_rg_union_room.s \
	sound/songs/midi/mus_rg_net_center.s \
	sound/songs/midi/mus_rg_mystery_gift.s \
	sound/songs/midi/mus_rg_berry_pick.s \
	sound/songs/midi/mus_rg_sevii_cave.s \
	sound/songs/midi/mus_rg_teachy_tv_show.s \
	sound/songs/midi/mus_rg_sevii_route.s \
	sound/songs/midi/mus_rg_sevii_dungeon.s \
	sound/songs/midi/mus_rg_sevii_123.s \
	sound/songs/midi/mus_rg_sevii_45.s \
	sound/songs/midi/mus_rg_sevii_67.s \
	sound/songs/midi/mus_rg_poke_flute.s \
	sound/songs/midi/mus_rg_vs_deoxys.s \
	sound/songs/midi/mus_rg_vs_mewtwo.s \
	sound/songs/midi/mus_rg_vs_legend.s \
	sound/songs/midi/mus_rg_encounter_gym_leader.s \
	sound/songs/midi/mus_rg_encounter_deoxys.s \
	sound/songs/midi/mus_rg_trainer_tower.s \
	sound/songs/midi/mus_rg_slow_pallet.s \
	sound/songs/midi/mus_rg_teachy_tv_menu.s
