BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "トレーナーに　ひつような　もの⋯⋯\p"
	.string "ちしき⋯\n"
	.string "せんりゃく⋯\l"
	.string "うん⋯\l"
	.string "とうし⋯\l"
	.string "こころ⋯\l"
	.string "ゆうき⋯\l"
	.string "そして　さいのう　か⋯⋯\p"
	.string "ぼく　ぜんぶ　バッチリ　じゃん！\n"
	.string "どこの　しせつでも　らくしょー　だね\p"
	.string "えっ？　ポケモン？　なんのことだい？$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "フロンティアブレーンって　しってる？\p"
	.string "バトルフロンティアに　ある\n"
	.string "7つの　しせつを　かんりする\l"
	.string "とくべつな　トレーナーたちの　ことを\l"
	.string "エニシダは　そうよんでる　らしいわ$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "ぼく　バトルタワーで　おねえちゃんに\n"
	.string "たたかいの　さいのうが　あるねって\l"
	.string "すごく　ほめられたのー！\p"
	.string "でも　ぼく　ポケモン　コンテストの\n"
	.string "ほーが　すき　なの！\p"
	.string "でも　ポケモン　コンテストは\n"
	.string "ぜんぜん　だめだよ！\p"
	.string "さいのうって　すきとは　ちがうの？$"
