@ JP descriptions, physically 0x08580038..0x08580CD0.

DecorDesc_SMALL_DESK:
	.string "ひとり　サイズの\nちいさな　つくえ$"

DecorDesc_POKEMON_DESK:
	.string "モンスターボールの\nかたちをした\nちいさな　つくえ$"

DecorDesc_HEAVY_DESK:
	.string "てつで　つくられた\nおおきな　つくえ\nうえに　ものを　おける$"

DecorDesc_RAGGED_DESK:
	.string "きで　つくられた\nおおきな　つくえ\nうえに　ものを　おける$"

DecorDesc_COMFORT_DESK:
	.string "はっぱで　つくられた\nおおきな　つくえ\nうえに　ものを　おける$"

DecorDesc_PRETTY_DESK:
	.string "ガラスで　つくられた\nきょだいな　つくえ\nたくさん　ものを　おける$"

DecorDesc_BRICK_DESK:
	.string "レンガで　つくられた\nきょだいな　つくえ\nたくさん　ものを　おける$"

DecorDesc_CAMP_DESK:
	.string "まるたで　つくられた\nきょだいな　つくえ\nたくさん　ものを　おける$"

DecorDesc_HARD_DESK:
	.string "いしで　つくられた\nきょだいな　つくえ\nたくさん　ものを　おける$"

DecorDesc_SMALL_CHAIR:
	.string "ひとりで　すわる\nちいさな　イス$"

DecorDesc_POKEMON_CHAIR:
	.string "モンスターボールの\nかたちをした\nちいさな　イス$"

DecorDesc_HEAVY_CHAIR:
	.string "てつで　つくられた\nちいさな　イス$"

DecorDesc_PRETTY_CHAIR:
	.string "ガラスで　つくられた\nちいさな　イス$"

DecorDesc_COMFORT_CHAIR:
	.string "はっぱで　つくられた\nちいさな　イス$"

DecorDesc_RAGGED_CHAIR:
	.string "きで　つくられた\nちいさな　イス$"

DecorDesc_BRICK_CHAIR:
	.string "レンガで　つくられた\nちいさな　イス$"

DecorDesc_CAMP_CHAIR:
	.string "まるたで　つくられた\nちいさな　イス$"

DecorDesc_HARD_CHAIR:
	.string "いしで　つくられた\nちいさな　イス$"

DecorDesc_RED_PLANT:
	.string "まっかな　はなが\nうえられた　うえき$"

DecorDesc_TROPICAL_PLANT:
	.string "なんごくの　はなが\nうえられた　うえき$"

DecorDesc_PRETTY_FLOWERS:
	.string "かわいい　はなが\nうえられた　うえき$"

DecorDesc_COLORFUL_PLANT:
	.string "いろいろな　はなが\nうえられた\nおおきな　うえき$"

DecorDesc_BIG_PLANT:
	.string "カサのような　きが\nうえられた\nおおきな　うえき$"

DecorDesc_GORGEOUS_PLANT:
	.string "りっぱな　きが\nうえられた\nおおきな　うえき$"

DecorDesc_RED_BRICK:
	.string "あかいろの　レンガ\nうえに　ものを　おける$"

DecorDesc_YELLOW_BRICK:
	.string "きいろの　レンガ\nうえに　ものを　おける$"

DecorDesc_BLUE_BRICK:
	.string "あおいろの　レンガ\nうえに　ものを　おける$"

DecorDesc_RED_BALLOON:
	.string "みずの　はいった\nあかい　ふうせん\nふむと　われる$"

DecorDesc_BLUE_BALLOON:
	.string "みずの　はいった\nあおい　ふうせん\nふむと　われる$"

DecorDesc_YELLOW_BALLOON:
	.string "みずの　はいった\nきいろい　ふうせん\nふむと　われる$"

DecorDesc_RED_TENT:
	.string "おおきな　あかい　テント\nなかに　はいれる$"

DecorDesc_BLUE_TENT:
	.string "おおきな　あおい　テント\nなかに　はいれる$"

DecorDesc_SOLID_BOARD:
	.string "あなの　うえに　おけば\nむこうへ　わたれる$"

DecorDesc_SLIDE:
	.string "だいの　うえから\nすべって　したへ\nいくことが　できる$"

DecorDesc_FENCE_LENGTH:
	.string "ちいさい　さく\nとおることが　できない$"

DecorDesc_FENCE_WIDTH:
	.string "ちいさい　さく\nとおることが　できない$"

DecorDesc_TIRE:
	.string "ふるい　おおきな　タイヤ\nうえに　ものを　おける$"

DecorDesc_STAND:
	.string "かいだんを　のぼって\nだいに　あがれる$"

DecorDesc_MUD_BALL:
	.string "まるい　どろだんご\nふむと　こわれる$"

DecorDesc_BREAKABLE_DOOR:
	.string "とおりぬけ　できる\nおかしな　ドア$"

DecorDesc_SAND_ORNAMENT:
	.string "さわると　くずれる\nすなの　おきもの$"

DecorDesc_SILVER_SHIELD:
	.string "バトルタワーで\n50にん　かちぬいた\nきねんの　たて$"

DecorDesc_GOLD_SHIELD:
	.string "バトルタワーで\n100にん　かちぬいた\nきねんの　たて$"

DecorDesc_GLASS_ORNAMENT:
	.string "びじゅつかんに　ある\nゆうめいな　ちょうこくを\nガラスで　かたどったもの$"

DecorDesc_TV:
	.string "はいいろの　ちいさな\nおもちゃの　テレビ$"

DecorDesc_ROUND_TV:
	.string "タネボーの　イメージで\nつくられた\nおもちゃの　テレビ$"

DecorDesc_CUTE_TV:
	.string "エネコの　イメージで\nつくられた\nおもちゃの　テレビ$"

DecorDesc_GLITTER_MAT:
	.string "ふむと　きらきらする\nふしぎな　マット$"

DecorDesc_JUMP_MAT:
	.string "ふむと　ジャンプする\nいたずら　マット$"

DecorDesc_SPIN_MAT:
	.string "ふむと　くるくる　まわる\nいたずら　マット$"

DecorDesc_C_LOW_NOTE_MAT:
	.string "ふむと　ドの\nおとがなる　マット$"

DecorDesc_D_NOTE_MAT:
	.string "ふむと　レの\nおとがなる　マット$"

DecorDesc_E_NOTE_MAT:
	.string "ふむと　ミの\nおとがなる　マット$"

DecorDesc_F_NOTE_MAT:
	.string "ふむと　ファの\nおとがなる　マット$"

DecorDesc_G_NOTE_MAT:
	.string "ふむと　ソの\nおとがなる　マット$"

DecorDesc_A_NOTE_MAT:
	.string "ふむと　ラの\nおとがなる　マット$"

DecorDesc_B_NOTE_MAT:
	.string "ふむと　シの\nおとがなる　マット$"

DecorDesc_C_HIGH_NOTE_MAT:
	.string "ふむと　たかい　ドの\nおとがなる　マット$"

DecorDesc_SURF_MAT:
	.string "なみのりの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_THUNDER_MAT:
	.string "かみなりの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_FIRE_BLAST_MAT:
	.string "だいもんじの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_POWDER_SNOW_MAT:
	.string "こなゆきの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_ATTRACT_MAT:
	.string "メロメロの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_FISSURE_MAT:
	.string "じわれの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_SPIKES_MAT:
	.string "まきびしの　イメージで\nつくられた　マット\nうえに　ものを　おける$"

DecorDesc_BALL_POSTER:
	.string "モンスターボールが\nプリント　されている\nちいさいポスター$"

DecorDesc_GREEN_POSTER:
	.string "キモリが\nプリント　されている\nちいさいポスター$"

DecorDesc_RED_POSTER:
	.string "アチャモが\nプリント　されている\nちいさいポスター$"

DecorDesc_BLUE_POSTER:
	.string "ミズゴロウが\nプリント　されている\nちいさいポスター$"

DecorDesc_CUTE_POSTER:
	.string "ルリリが\nプリント　されている\nちいさいポスター$"

DecorDesc_PIKA_POSTER:
	.string "ピカチュウと　ピチューが\nプリント　されている\nおおきなポスター$"

DecorDesc_LONG_POSTER:
	.string "ハブネークが\nプリント　されている\nおおきなポスター$"

DecorDesc_SEA_POSTER:
	.string "ジーランスが\nプリント　されている\nおおきなポスター$"

DecorDesc_SKY_POSTER:
	.string "キャモメが\nプリント　されている\nおおきなポスター$"

DecorDesc_KISS_POSTER:
	.string "ムチュールが\nプリント　されている\nおおきなポスター$"

DecorDesc_PICHU_DOLL:
	.string "ピチューの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_PIKACHU_DOLL:
	.string "ピカチュウの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_MARILL_DOLL:
	.string "マリルの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_TOGEPI_DOLL:
	.string "トゲピーの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_CYNDAQUIL_DOLL:
	.string "ヒノアラシの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_CHIKORITA_DOLL:
	.string "チコリータの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_TOTODILE_DOLL:
	.string "ワニノコの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_JIGGLYPUFF_DOLL:
	.string "プリンの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_MEOWTH_DOLL:
	.string "ニャースの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_CLEFAIRY_DOLL:
	.string "ピッピの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_DITTO_DOLL:
	.string "メタモンの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_SMOOCHUM_DOLL:
	.string "ムチュールの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_TREECKO_DOLL:
	.string "キモリの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_TORCHIC_DOLL:
	.string "アチャモの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_MUDKIP_DOLL:
	.string "ミズゴロウの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_DUSKULL_DOLL:
	.string "ヨマワルの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_WYNAUT_DOLL:
	.string "ソーナノの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_BALTOY_DOLL:
	.string "ヤジロンの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_KECLEON_DOLL:
	.string "カクレオンの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_AZURILL_DOLL:
	.string "ルリリの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_SKITTY_DOLL:
	.string "エネコの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_SWABLU_DOLL:
	.string "チルットの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_GULPIN_DOLL:
	.string "ゴクリンの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_LOTAD_DOLL:
	.string "ハスボーの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_SEEDOT_DOLL:
	.string "タネボーの　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_PIKA_CUSHION:
	.string "ピカチュウの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_ROUND_CUSHION:
	.string "マリルリの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_KISS_CUSHION:
	.string "ムチュールの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_ZIGZAG_CUSHION:
	.string "ジグザグマの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_SPIN_CUSHION:
	.string "パッチールの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_DIAMOND_CUSHION:
	.string "ヤミラミの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_BALL_CUSHION:
	.string "ボールの　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_GRASS_CUSHION:
	.string "くさマーク　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_FIRE_CUSHION:
	.string "ほのおマーク　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_WATER_CUSHION:
	.string "みずマーク　クッション\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_SNORLAX_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_RHYDON_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_LAPRAS_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_VENUSAUR_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_CHARIZARD_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_BLASTOISE_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_WAILMER_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_REGIROCK_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_REGICE_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"

DecorDesc_REGISTEEL_DOLL:
	.string "おおきな　ぬいぐるみ\nマットや　つくえの\nうえに　おくもの$"
