#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/wild_encounters.json and Inja template src/data/wild_encounters.constants.json.txt
//


#define NUM_ALTERING_CAVE_TABLES 9

#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_0 (20)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_1 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_0 + 20)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_2 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_1 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_3 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_2 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_4 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_3 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_5 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_4 + 10)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_6 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_5 + 5)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_7 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_6 + 5)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_8 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_7 + 4)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_9 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_8 + 4)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_10 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_9 + 1)
#define ENCOUNTER_CHANCE_LAND_MONS_SLOT_11 (ENCOUNTER_CHANCE_LAND_MONS_SLOT_10 + 1)
#define ENCOUNTER_CHANCE_LAND_MONS_TOTAL (ENCOUNTER_CHANCE_LAND_MONS_SLOT_11)
#define NUM_LAND_MONS_ENCOUNTER_SLOTS (12)

#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_0 (60)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_1 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_0 + 30)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_2 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_1 + 5)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_3 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_2 + 4)
#define ENCOUNTER_CHANCE_WATER_MONS_SLOT_4 (ENCOUNTER_CHANCE_WATER_MONS_SLOT_3 + 1)
#define ENCOUNTER_CHANCE_WATER_MONS_TOTAL (ENCOUNTER_CHANCE_WATER_MONS_SLOT_4)
#define NUM_WATER_MONS_ENCOUNTER_SLOTS (5)

#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_0 (60)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_1 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_0 + 30)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_2 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_1 + 5)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_3 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_2 + 4)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_4 (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_3 + 1)
#define ENCOUNTER_CHANCE_ROCK_SMASH_MONS_TOTAL (ENCOUNTER_CHANCE_ROCK_SMASH_MONS_SLOT_4)
#define NUM_ROCK_SMASH_MONS_ENCOUNTER_SLOTS (5)


#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_2 (60)
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_3 (ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_2 + 20)
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_4 (ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_3 + 20)
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_TOTAL (ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_4)
#define NUM_FISHING_MONS_GOOD_ROD_ENCOUNTER_SLOTS (3)

#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0 (70)
#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_1 (ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0 + 30)
#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_TOTAL (ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_1)
#define NUM_FISHING_MONS_OLD_ROD_ENCOUNTER_SLOTS (2)

#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5 (40)
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_5 + 40)
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_6 + 15)
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_7 + 4)
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_9 (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_8 + 1)
#define ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_TOTAL (ENCOUNTER_CHANCE_FISHING_MONS_SUPER_ROD_SLOT_9)
#define NUM_FISHING_MONS_SUPER_ROD_ENCOUNTER_SLOTS (5)
#define NUM_FISHING_MONS_ENCOUNTER_SLOTS (10)


#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
