FallarborTown_BattleTentCorridor_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FallarborTown_BattleTentCorridor_OnFrame
	.byte 0

FallarborTown_BattleTentCorridor_OnFrame:
	map_script_2 VAR_TEMP_0, 0, FallarborTown_BattleTentCorridor_EventScript_EnterCorridor
	.2byte 0

FallarborTown_BattleTentCorridor_EventScript_EnterCorridor::
	lockall
	setvar VAR_TEMP_0, 1
	applymovement LOCALID_FALLARBOR_TENT_CORRIDOR_ATTENDANT, FallarborTown_BattleTentCorridor_Movement_WalkToDoor
	applymovement LOCALID_PLAYER, FallarborTown_BattleTentCorridor_Movement_WalkToDoor
	waitmovement 0
	opendoor 2, 1
	@ JP's door-wait byte is emitted through the historical waitmoncry macro slot.
	waitmoncry
	applymovement LOCALID_FALLARBOR_TENT_CORRIDOR_ATTENDANT, FallarborTown_BattleTentCorridor_Movement_AttendantEnterDoor
	applymovement LOCALID_PLAYER, FallarborTown_BattleTentCorridor_Movement_PlayerEnterDoor
	waitmovement 0
	closedoor 2, 1
	@ JP's door-wait byte is emitted through the historical waitmoncry macro slot.
	waitmoncry
	setvar VAR_0x8006, 0
	warp MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM, 4, 4
	waitstate
	releaseall
	end

FallarborTown_BattleTentCorridor_Movement_WalkToDoor:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

FallarborTown_BattleTentCorridor_Movement_PlayerEnterDoor:
	walk_up
FallarborTown_BattleTentCorridor_Movement_AttendantEnterDoor:
	walk_up
	set_invisible
	step_end

@ Leftover text from when this was a Contest Hall in R/S
@ Unused
FallarborTown_ContestHall_Text_DoAllRightInPreliminary:
	.string "1じ　しんさでは　いいセン　いくけど\n"
	.string "なぜか　アピールで　かてないんだ⋯⋯\p"
	.string "じぶんの　ポケモンばっかり　みてると\n"
	.string "かてないって　ことかなあ$"

@ Unused
FallarborTown_ContestHall_Text_MonAllTheseRibbons:
	.string "みて！　わたしの　ポケモン\n"
	.string "こんなに　リボンが　いっぱい！\p"
	.string "あなたの　ポケモンは　リボン　もらった？\n"
	.string "もらって　いれば　ポケナビで　みられるわよ！$"

@ Unused
FallarborTown_ContestHall_Text_CantWinEverywhere:
	.string "ジムリーダーにも　かてない⋯⋯\p"
	.string "コンテストでも　かてない⋯⋯\p"
	.string "あっちのまち　こっちのまちを\n"
	.string "いったり　きたり　だよ⋯⋯$"

@ Unused
FallarborTown_ContestHall_Text_SuperRankStage:
	.string "ポケモン　コンテスト\n"
	.string "スーパーランク　ステージ！$"
