BattleDome_Text_Potential1::
	.string "こんたいかいの　ゆうしょうこうほ　ナンバー1！$"

BattleDome_Text_Potential2::
	.string "けっしょうまでは　かくじつと　いわれる　チーム。$"

BattleDome_Text_Potential3::
	.string "ベスト3に　はいる　ちからを　もった　チーム。$"

BattleDome_Text_Potential4::
	.string "こんたいかい　ゆうしょうこうほの　1チーム。$"

BattleDome_Text_Potential5::
	.string "トップクラスの　ちからを　そなえた　チーム。$"

BattleDome_Text_Potential6::
	.string "こんたいかい　ちゅうもくの　ダークホース！$"

BattleDome_Text_Potential7::
	.string "へいきんより　すこし　ちからが　うえの　チーム。$"

BattleDome_Text_Potential8::
	.string "こんたいかいの　へいきんてきな　チーム。$"

BattleDome_Text_Potential9::
	.string "へいきん　レベルの　ちからを　もった　チーム。$"

BattleDome_Text_Potential10::
	.string "へいきんより　やや　ちからが　おちる　チーム。$"

BattleDome_Text_Potential11::
	.string "まず　1しょうが　もくひょうと　なる　チーム。$"

BattleDome_Text_Potential12::
	.string "1しょう　できれば　じょうじょうの　チーム。$"

BattleDome_Text_Potential13::
	.string "ぜんたいの　なかで　したの　レベルの　チーム。$"

BattleDome_Text_Potential14::
	.string "じつりょくは　かなり　したの　レベルの　チーム。$"

BattleDome_Text_Potential15::
	.string "ゆうしょうは　かなり　むずかしい　チーム。$"

BattleDome_Text_Potential16::
	.string "ゆうしょうから　もっとも　とおい　チーム。$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "かんぜん　むてきの　スーパースター！！$"

BattleDome_Text_StyleRiskDisaster::
	.string "ときには　はめつ　かくごで　たたかいを　いどむ。$"

BattleDome_Text_StyleEndureLongBattles::
	.string "ちょうきせんでの　ねばりが　とても　とくい。$"

BattleDome_Text_StyleVariesTactics::
	.string "あいてに　おうじて　たさいな　わざで　たたかう。$"

BattleDome_Text_StyleToughWinningPattern::
	.string "かちパターンを　もっていて　はまると　つよい。$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "とても　めずらしい　わざを　ときどき　つかう。$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "いひょうを　つく　わざで　たたかいを　みだす。$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "つねに　たいりょくに　きを　くばって　たたかう。$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "ちからを　ためて　いっきに　せめるのが　とくい。$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "あいての　ちからを　おとすのが　とくい。$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "うんに　まかせた　たたかいかたを　このむ。$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "おうじゃの　ふうかく　ただよう　せめを　する。$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "PPの　すくない　おおわざで　しょうぶする。$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "よわらせてから　こうげきを　するのが　とくい。$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "あらゆる　こうげきに　たえながら　たたかう。$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "あいての　こころを　かきみだすのが　とくい。$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "つよくて　あつかいやすい　わざを　つかう。$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "きょうりょくな　わざで　どんどん　おしまくる。$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "こうげきを　うまく　かわしながら　たたかう。$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "あいてが　いやがる　たたかいが　とくい。$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "にんきの　ある　わざを　たくさん　つかう。$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "きょうりょくな　コンボになる　わざを　もつ。$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "てがたい　わざで　きっちりと　こうげきする。$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "はでな　わざを　つかって　どんどん　せめる。$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "まもりより　とにかく　せめを　だいじに　する。$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "せめるより　まもりを　だいじに　する。$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "つよいわざで　しょうぶの　しかけが　はやい。$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "ついかこうかが　ある　わざを　よく　つかう。$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "バランスよく　いろいろな　わざで　たちむかう。$"

BattleDome_Text_StyleSampleMessage1::
	.string "ダミーメッセージ1です。$"

BattleDome_Text_StyleSampleMessage2::
	.string "ダミーメッセージ2です。$"

BattleDome_Text_StyleSampleMessage3::
	.string "ダミーメッセージ3です。$"

BattleDome_Text_StyleSampleMessage4::
	.string "ダミーメッセージ4です。$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "HPと　こうげきに　ちからを　いれている。$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "HPと　ぼうぎょに　ちからを　いれている。$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "HPと　すばやさに　ちからを　いれている。$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "HPと　とくこうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "HPと　とくぼうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "こうげきと　ぼうぎょに　ちからを　いれている。$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "こうげきと　すばやさに　ちからを　いれている。$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "こうげきと　とくこうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "こうげきと　とくぼうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "ぼうぎょと　すばやさに　ちからを　いれている。$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "ぼうぎょと　とくこうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "ぼうぎょと　とくぼうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "すばやさと　とくこうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "すばやさと　とくぼうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "とくこうと　とくぼうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesHP::
	.string "HPに　ちからを　いれている。$"

BattleDome_Text_EmphasizesAtk::
	.string "こうげきに　ちからを　いれている。$"

BattleDome_Text_EmphasizesDef::
	.string "ぼうぎょに　ちからを　いれている。$"

BattleDome_Text_EmphasizesSpeed::
	.string "すばやさに　ちからを　いれている。$"

BattleDome_Text_EmphasizesSpAtk::
	.string "とくこうに　ちからを　いれている。$"

BattleDome_Text_EmphasizesSpDef::
	.string "とくぼうに　ちからを　いれている。$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "HPと　こうげきに　ちからを　いれていない！$"

BattleDome_Text_NeglectsHPAndDef::
	.string "HPと　ぼうぎょに　ちからを　いれていない！$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "HPと　すばやさに　ちからを　いれていない！$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "HPと　とくこうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "HPと　とくぼうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "こうげきと　ぼうぎょに　ちからを　いれていない！$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "こうげきと　すばやさに　ちからを　いれていない！$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "こうげきと　とくこうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "こうげきと　とくぼうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "ぼうぎょと　すばやさに　ちからを　いれていない！$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "ぼうぎょと　とくこうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "ぼうぎょと　とくぼうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "すばやさと　とくこうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "すばやさと　とくぼうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "とくこうと　とくぼうに　ちからを　いれていない！$"

BattleDome_Text_NeglectsHP::
	.string "HPには　ちからを　いれていない！$"

BattleDome_Text_NeglectsAtk::
	.string "こうげきには　ちからを　いれていない！$"

BattleDome_Text_NeglectsDef::
	.string "ぼうぎょには　ちからを　いれていない！$"

BattleDome_Text_NeglectsSpeed::
	.string "すばやさには　ちからを　いれていない！$"

BattleDome_Text_NeglectsSpAtk::
	.string "とくこうには　ちからを　いれていない！$"

BattleDome_Text_NeglectsSpDef::
	.string "とくぼうには　ちからを　いれていない！$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "バランスよく　ポケモンを　そだてている。$"

BattleDome_Text_LetTheBattleBegin::
	.string "これより　たいけつ！$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_2}　などで　{STR_VAR_1}が　しょうり！$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_2}　などで　{STR_VAR_1}　ゆうしょう！$"

BattleDome_Text_TrainerWonByDefault::
	.string "あいての　リタイアで　{STR_VAR_1}が　しょうり！$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "あいての　リタイアで　{STR_VAR_1}　ゆうしょう！$"

BattleDome_Text_TrainerWonNoMoves::
	.string "わざを　つかわずに　{STR_VAR_1}が　しょうり！$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "わざを　つかわずに　{STR_VAR_1}　ゆうしょう！$"

BattleDome_Text_Round1Match1::
	.string "　1かいせん　だい1しあい$"

BattleDome_Text_Round1Match2::
	.string "　1かいせん　だい2しあい$"

BattleDome_Text_Round1Match3::
	.string "　1かいせん　だい3しあい$"

BattleDome_Text_Round1Match4::
	.string "　1かいせん　だい4しあい$"

BattleDome_Text_Round1Match5::
	.string "　1かいせん　だい5しあい$"

BattleDome_Text_Round1Match6::
	.string "　1かいせん　だい6しあい$"

BattleDome_Text_Round1Match7::
	.string "　1かいせん　だい7しあい$"

BattleDome_Text_Round1Match8::
	.string "　1かいせん　だい8しあい$"

BattleDome_Text_Round2Match1::
	.string "　2かいせん　だい1しあい$"

BattleDome_Text_Round2Match2::
	.string "　2かいせん　だい2しあい$"

BattleDome_Text_Round2Match3::
	.string "　2かいせん　だい3しあい$"

BattleDome_Text_Round2Match4::
	.string "　2かいせん　だい4しあい$"

BattleDome_Text_SemifinalMatch1::
	.string "じゅんけっしょう　だい1しあい$"

BattleDome_Text_SemifinalMatch2::
	.string "じゅんけっしょう　だい2しあい$"

BattleDome_Text_FinalMatch::
	.string "　　　　けっしょうせん$"
