BerryTree_Text_ItsSoftLoamySoil:
	.string "ふかふかの　つちだ！$"

BerryTree_Text_WantToPlant:
	.string "ふかふかの　つちだ！\n"
	.string "きのみを　うめますか？$"

BerryTree_Text_PlantedOneBerry:
	.string "{PLAYER}は　ふかふかの　つちに\n"
	.string "{STR_VAR_1}のみを　うめた！$"

BerryTree_Text_BerryGrowthStage1:
	.string "{STR_VAR_1}のみを　うめた　ばしょだ！$"

BerryTree_Text_BerryGrowthStage2:
	.string "{STR_VAR_1}の　めが　でてきた！$"

BerryTree_Text_BerryGrowthStage3:
	.string "{STR_VAR_1}の　みきが　おおきく　なってきた！$"

BerryTree_Text_BerryGrowthStage4:
	.string "{STR_VAR_1}の　はなが　{STR_VAR_2}　さいてる！$"

BerryTree_Text_CareAdverbGreat:
	.string "とてもうつくしく$"

BerryTree_Text_CareAdverbPoor:
	.string "かわいく$"

BerryTree_Text_CareAdverbGood:
	.string "きれいに$"

BerryTree_Text_WantToPick:
	.string "{STR_VAR_1}のみが　{STR_VAR_2}こ　できてる！\p"
	.string "{STR_VAR_1}のみを　とりますか？$"

BerryTree_Text_PickedTheBerry:
	.string "{PLAYER}は　{STR_VAR_1}のみを　{STR_VAR_2}こ　とった！$"

BerryTree_Text_PutAwayBerry:
	.string "{PLAYER}は　{STR_VAR_1}のみを\n"
	.string "きのみポケットに　しまった！\p"
	.string "つちは　もとの　ふかふかに　もどった！$"

BerryTree_Text_BerryPocketFull:
	.string "バッグの　きのみポケットが　いっぱいだった\p"
	.string "{STR_VAR_1}のみを　あきらめた$"

BerryTree_Text_BerryLeftUnpicked:
	.string "{PLAYER}は　{STR_VAR_1}のみを\n"
	.string "そのままに　しておいた$"

BerryTree_Text_WantToWater:
	.string "もっている　ホエルコじょうろ　で\n"
	.string "{STR_VAR_1}に　みずを　あげますか？$"

BerryTree_Text_WateredTheBerry:
	.string "{PLAYER}は　{STR_VAR_1}に　みずを　あげた！$"

BerryTree_Text_PlantIsDelighted:
	.string "とっても　よろこんでる　みたい！$"

BerryTree_Text_ExclamationPoint:
	.string "!$"
