CableClub_Text_WelcomeWhichCableClubService:
	.string "つうしん　ケーブル　クラブに\n"
	.string "ようこそ！\p"
	.string "どちらを　ごりよう　ですか？$"

CableClub_Text_WhichService:
	.string "どちらを　ごりよう　ですか？$"

CableClub_Text_TradeUsingLinkCable::
	.string "ケーブルで　つないだ　おともだちと\n"
	.string "ポケモン　こうかんが　できます$"

CableClub_Text_BattleUsingLinkCable::
	.string "ケーブルで　つないだ　おともだちと\n"
	.string "ポケモン　たいせんが　できます$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "ケーブルで　つないだ　おともだちと\n"
	.string "レコードコーナーが　できます$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "ダブルバトルでは　2ひき　いじょうの\n"
	.string "ポケモンが　ひつようです$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "こうかんでは　2ひき　いじょうの\n"
	.string "てもちが　ひつようです$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "{STR_VAR_1}のみを　もっている\n"
	.string "ポケモンは　こうかん　できません！$"
