CableClub_Text_WelcomeWhichCableClubService:
	.string "つうしん　ケーブル　クラブに\n"
	.string "ようこそ！\p"
	.string "どちらを　ごりよう　ですか？$"

CableClub_Text_WhichService:
	.string "どちらを　ごりよう　ですか？$"

CableClub_Text_TradeUsingLinkCable::
	.string "ケーブルで　つないだ　おともだちと\n"
	.string "ポケモン　こうかんが　できます$"

CableClub_Text_BattleUsingLinkCable::
	.string "ケーブルで　つないだ　おともだちと\n"
	.string "ポケモン　たいせんが　できます$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "ケーブルで　つないだ　おともだちと\n"
	.string "レコードコーナーが　できます$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "ダブルバトルでは　2ひき　いじょうの\n"
	.string "ポケモンが　ひつようです$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "こうかんでは　2ひき　いじょうの\n"
	.string "てもちが　ひつようです$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "{STR_VAR_1}のみを　もっている\n"
	.string "ポケモンは　こうかん　できません！$"

gText_PleaseWaitForLink::
	.string "しょうしょう　おまち　ください\n"
	.string "⋯⋯Bボタンで　キャンセル$"

gText_ConfirmLinkWhenPlayersReady::
	.string "そろったら　Aボタンで　すすむ\n"
	.string "⋯⋯Bボタンで　キャンセル$"

gText_ConfirmStartLinkWithXPlayers::
	.string "{STR_VAR_1}にんで　つうしんを　はじめます\n"
	.string "Aボタン⋯けってい　Bボタン⋯もどる$"

gText_AwaitingLinkup::
	.string "つうしんかいしを　まっています\n"
	.string "⋯⋯Bボタンで　キャンセル$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "はじめる　まえに　レポートを\n"
	.string "かきますが　よろしいですか？$"

CableClub_Text_PleaseEnter:
	.string "それでは　へやへ　どうぞ$"

CableClub_Text_DirectYouToYourRoom:
	.string "それでは\n"
	.string "へやに　ごあんないします$"

Text_SomeoneIsNotReadyToLink:
	.string "おともだちの　じゅんびが\n"
	.string "できて　いない　ようです\p"
	.string "じゅんびが　できましたら\n"
	.string "また　おこしください$"

Text_LinkErrorPleaseReset:
	.string "つうしんエラー　です\n"
	.string "リセットして　やりなおしてください$"

Text_PlayersMadeDifferentSelections:
	.string "おたがいが　えらんだ　ものが\n"
	.string "ちがっている　ようです$"

CableClub_Text_PleaseVisitAgain:
	.string "それでは　また　おこしください$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "さんかしている　にんずうが\n"
	.string "ただしく　ありません$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "シングルバトルは　{STR_VAR_1}にんで\n"
	.string "あそぶことは　できません！$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "ダブルバトルは　{STR_VAR_1}にんでは\n"
	.string "あそぶことは　できません！$"

CableClub_Text_NeedFourPlayers:
	.string "さんか　にんずうが　4にん　いないと\n"
	.string "たいせん　することが　できません！$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "もういちど　にんずうを　たしかめて\n"
	.string "はじめから　やりなおして　ください$"

Text_TerminateLinkConfirmation:
	.string "へやからでると　つうしんが\n"
	.string "おわりますが　よろしいですか？$"

Text_TerminateLinkPleaseWait:
	.string "つうしんを　しゅうりょう　します\n"
	.string "しばらく　おまちください$"

CableClub_Text_TooBusyToNotice:
	.string "とりこみちゅうの　ようだ⋯$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "{STR_VAR_1}の　トレーナーカードを\n"
	.string "みせてもらった！$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "{STR_VAR_1}の　トレーナーカードを\n"
	.string "みせてもらった！\p"
	.string "⋯{STR_VAR_2}カードだ！$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "しょていの　いちに　ついて\n"
	.string "たいせんを　はじめて　ください$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "しょていの　いちに　ついて\n"
	.string "こうかんを　はじめて　ください$"

RecordCorner_Text_ThanksForComing:
	.string "ごりよう　ありがとう　ございました$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "トレーナーカードの\n"
	.string "きろくを　かきかえます！$"

CableClub_Text_HopeToSeeYouAgain:
	.string "では　また　どうぞ！$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "おきゃくさま\n"
	.string "もうしわけ　ありません\p"
	.string "とおい　ちほうの　かたと\n"
	.string "ポケモンを　こうかん　することは\l"
	.string "いまは　できません⋯$"

CableClub_Text_OtherTrainerNotReady:
	.string "あいての　じゅんびが\n"
	.string "できていません$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "てもちに　つれていけない\n"
	.string "ポケモンが　います$"

RecordCorner_Text_TakeSeatAndWait:
	.string "しょていの　いちに　ついて\n"
	.string "おまち　ください$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1}さんから\n"
	.string "{STR_VAR_2}が　おくられてきた！$"

CableClub_Text_AdapterNotConnected:
	.string "ワイヤレスアダプタが\n"
	.string "つながって　いません$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "さんか　したい　ひとは\n"
	.string "カウンターに　おこしください$"

@ Unused
CableClub_Text_Hello:
	.string "こんにちは！$"

@ Unused
CableClub_Text_PleaseWait:
	.string "しょうしょう　おまちください$"

CableClub_Text_YouMayTradeHere::
	.string "ともだちと　ポケモンの\n"
	.string "こうかんが　たのしめます$"

CableClub_Text_YouMayBattleHere::
	.string "ともだちと　ポケモンの\n"
	.string "たいせんが　たのしめます$"

CableClub_Text_CanMakeBerryPowder::
	.string "2にんから　5にんの　ともだちと\n"
	.string "きのみで　こなを　つくります$"

CableClub_Text_CanMixRecords::
	.string "2にんから　4にんの　ともだちと\n"
	.string "レコードを　まぜます$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめいします$"

CableClub_Text_CancelSelectedItem::
	.string "やめます$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "どちらの　しょうぶに　しますか？$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "ひとつ　まえに　もどります$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "きのみを　もって　いないと\n"
	.string "きのみクラッシュは　できません$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "ユニオンルームに　はいるには\n"
	.string "2ひき　いじょうの　ポケモンを\l"
	.string "もって　おこしください$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "{STR_VAR_1}のみを　もっている\n"
	.string "ポケモンを　おもちの　かたは\l"
	.string "ユニオンルームには　はいれません⋯$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "こちらは\n"
	.string "ポケモン　ワイヤレス　クラブ\l"
	.string "ユニオン　ルームです\p"
	.string "ワイヤレスアダプタが\n"
	.string "つながって　いません\p"
	.string "また　おこしください$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "あ⋯⋯\n"
	.string "おきゃくさま！$"

CableClub_Text_PlayerIsWaiting:
	.string "あら！　いま　{STR_VAR_1}さんも\n"
	.string "プレイちゅう　みたいですね\l"
	.string "がんばって　くださいね！$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "ぼくは　ゲームの　せつめいを\n"
	.string "しますよ！\l"
	.string "どの　せつめいを　ききますか？$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "‘ミニポケモンでジャンプ’は\n"
	.string "ツルの　なわを　Aボタンで\l"
	.string "タイミングよく　とぶ　ゲームです\p"
	.string "さんか　できる　ポケモンは\n"
	.string "たかさ　70センチくらい　までの\l"
	.string "ちいさい　ポケモンに　なります\p"
	.string "もぐっていたり　とんでいたり　する\n"
	.string "ポケモンは　ジャンプが\l"
	.string "じょうずに　できないので\l"
	.string "ざんねんながら　さんか　できません\p"
	.string "みんなの　ジャンプの　タイミングが\n"
	.string "ピッタリ　あえば\l"
	.string "よいことが　ありますよ！$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "‘ドードリオのきのみどり’は\n"
	.string "ドードリオの　3つの　あたまに\l"
	.string "めいれいして　うえから　おちてくる\l"
	.string "きのみを　おとさないように\l"
	.string "とりつづける　ゲームです\p"
	.string "じゅうじボタンの\n"
	.string "うえ　みぎ　ひだりを　つかいます\p"
	.string "この　ゲームを　あそぶには\n"
	.string "ドードリオが　ひつようです$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "ゲームを　するなら\n"
	.string "おとなりの　おじいさんに　いってね$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "やあ　いらっしゃい\n"
	.string "ワイヤレスつうしんの　ゲームかな？\l"
	.string "ちょっと　まってね$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "また　おいでね$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "ワイヤレスアダプタを　つなげて\n"
	.string "あそびに　おいで！$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "さて　どの　ゲームを\n"
	.string "やりたいのかな？$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "どの　ポケモンを\n"
	.string "さんか　させるのかな？$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "じゅんびが　できたよ\n"
	.string "げんきに　あそんで　おいで！$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "きょうは　かえるのかい？\n"
	.string "また　おいでね$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "ゲームに　さんかできる\n"
	.string "ポケモンを　もって　いないんだね\p"
	.string "だれが　さんか　できるか\n"
	.string "せつめいを　しようか？$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "‘ミニポケモンでジャンプ’に\n"
	.string "さんか　できる　ポケモンは\l"
	.string "たかさ　70センチくらい　までだよ\p"
	.string "じめんに　もぐったり\n"
	.string "うかんでいる　ポケモンは\l"
	.string "ジャンプ　できないから\l"
	.string "でられないんだよ$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "‘ドードリオのきのみどり’は\n"
	.string "ドードリオ　だけが\l"
	.string "さんか　できる　ゲームなんだよ$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "もういちど　はじめから\n"
	.string "やりなおして　みて　くれるかな？$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "ポケモン　ワイヤレス　クラブ\n"
	.string "ダイレクト　コーナーに　ようこそ！\p"
	.string "こちらでは　ともだちと　ちょくせつ\n"
	.string "やりとり　できます\p"
	.string "どの　へやに　はいりますか？$"

CableClub_Text_TradePokemon:
	.string "こうかんを　しますか？$"

CableClub_Text_PlayWhichBattleMode:
	.string "どちらの　たいせんを　しますか？$"

CableClub_Text_AccessRecordCorner:
	.string "レコードコーナーを　しますか？$"

CableClub_Text_UseBerryCrush:
	.string "きのみクラッシュを　しますか？$"

CableClub_Text_ExplainBattleModes:
	.string "たいせんには　3しゅるいの\n"
	.string "モードが　あります\p"
	.string "シングルバトルは　たたかいの　ばに\n"
	.string "ポケモンを　1ひきだして\l"
	.string "ふたりで　たいせんします\p"
	.string "ダブルバトルは　たたかいの　ばに\n"
	.string "ポケモンを　2ひきずつ　だして\l"
	.string "ふたりで　たいせんします\p"
	.string "マルチバトルは　たたかいの　ばに\n"
	.string "4にんで　ポケモンを　1ひきずつ\l"
	.string "だして　2たい2で　たいせんします$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "ふたりで　はなしあって　ひとりが\n"
	.string "リーダーに　なってください\p"
	.string "もうひとりは　グループにはいる　を\n"
	.string "えらんでください$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "4にんで　はなしあって　ひとりが\n"
	.string "グループリーダーに　なってください\p"
	.string "ほかの　ひとは　グループにはいる　を\n"
	.string "えらんで　ください$"

CableClub_Text_ChooseGroupLeader:
	.string "みんなで　はなしあって　ひとりが\n"
	.string "グループリーダーに　なってください\p"
	.string "ほかの　ひとは　グループにはいる　を\n"
	.string "えらんでください$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "ポケモン　ワイヤレス　クラブ\n"
	.string "ユニオン　ルームに　ようこそ！\p"
	.string "こちらでは　みしらぬ　ともだちと\n"
	.string "やりとり　できます\p"
	.string "へやに　はいりますか？$"

CableClub_Text_UnionRoomInfo:
	.string "ユニオン　ルーム　は　あなたの\n"
	.string "ちかくで　ユニオン　ルームに\l"
	.string "はいっている　ひとが　あらわれます\p"
	.string "かんたんな　あいさつをしたり\p"
	.string "レベル30までの　ポケモン2ひきで\n"
	.string "1たい1の　たいせん\p"
	.string "2にんから　5にんまで　どうじに\n"
	.string "おしゃべりが　できる　チャット\p"
	.string "そして　とうろくしき\n"
	.string "ポケモン　こうかんが　たのしめます\p"
	.string "へやに　はいりますか？$"

CableClub_Text_EnjoyUnionRoom:
	.string "それでは　ユニオン　ルームで\n"
	.string "おたのしみ　ください$"

CableClub_Text_FirstTimeRightThisWay:
	.string "こんにちは！\p"
	.string "ワイヤレス　つうしんが\n"
	.string "はじめての　かたですね？\p"
	.string "わたくし　あんないやくの\n"
	.string "アオナと　もうします\p"
	.string "ポケモンセンター　2かいの\n"
	.string "ごあんないを　いたしますので\l"
	.string "こちらへ　どうぞ！$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "こちら　2かいには\n"
	.string "ふたつの　おへやが　ございます\p"
	.string "ひとつめは　ひだりがわの　おへや\n"
	.string "ユニオン　ルーム！\p"
	.string "あなたの　ちかくで\n"
	.string "ユニオン　ルームに　はいっている\l"
	.string "みしらぬ　おともだちと\l"
	.string "いろいろな　コミュニケーションが\l"
	.string "たのしめます！\p"
	.string "ふたつめは　みぎがわの　おへや\n"
	.string "ダイレクト　コーナー！\p"
	.string "あなたの　しっている　おともだちと\n"
	.string "ポケモンの　こうかんや\l"
	.string "たいせん　などを\l"
	.string "たのしむ　ことが　できます！\p"
	.string "もし　ワイヤレスアダプタが\n"
	.string "つながって　いない　ばあいでも\p"
	.string "みぎがわの　おへやで\n"
	.string "ケーブル　つうしんが　たのしめます\p"
	.string "それでは\p"
	.string "ワイヤレス　つうしんを\n"
	.string "たのしんで　くださいね！$"

CableClub_Text_AskAboutLinking:
	.string "こんにちは！　{PLAYER}さん！\p"
	.string "ポケモンセンター　2かいの\n"
	.string "あんないやく　アオナです\p"
	.string "なにか　つうしんで　おこまりですか？$"

CableClub_Text_ExplainWirelessClub:
	.string "ポケモン　ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめい　します！\p"
	.string "こちら　2かいには\n"
	.string "ふたつの　おへやが　ございます\p"
	.string "ひとつめは　ひだりがわの　おへや\n"
	.string "ユニオン　ルーム！\p"
	.string "あなたの　ちかくで\n"
	.string "ユニオン　ルームに　はいっている\l"
	.string "みしらぬ　おともだちと\l"
	.string "いろいろな　コミュニケーションが\l"
	.string "たのしめます！\p"
	.string "ふたつめは　みぎがわの　おへや\n"
	.string "ダイレクト　コーナー！\p"
	.string "あなたの　しっている　おともだちと\n"
	.string "ポケモンの　こうかんや\l"
	.string "たいせん　などを\l"
	.string "たのしむ　ことが　できます！\p"
	.string "もし　ユニオン　ルームや\n"
	.string "ダイレクト　コーナーで\l"
	.string "おともだちが　みつからない　ときは\p"
	.string "もうすこし　おともだちと\n"
	.string "ちかづいて　みて　ください\p"
	.string "また　ワイヤレスアダプタが\n"
	.string "つながって　いない　ばあいでも\p"
	.string "みぎがわの　おへやで\n"
	.string "ケーブル　つうしんが　たのしめます\p"
	.string "それでは\p"
	.string "ワイヤレス　つうしんを\n"
	.string "たのしんで　くださいね！$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "ポケモン　ワイヤレス　クラブで\n"
	.string "おたのしみ　ください$"
