Text_PictureBookShelf: @ 0x0826426B
	.string "ポケモンえほんが　そろってる！$"

Text_BookShelf: @ 0x0826427B
	.string "いろんな　ほんが　いっぱいだ！$"

Text_PokemonCenterBookShelf: @ 0x0826428B
	.string "ポケモンざっしが　ならんでる！\p"
	.string "⋯⋯‘ポケモンのとも'\n"
	.string "⋯⋯‘ポケモン　てちょう'\l"
	.string "⋯⋯‘かわいい　ポケモン'$"

Text_Vase: @ 0x082642C3
	.string "たかそうな　つぼが　ある！\n"
	.string "のぞきこむと⋯⋯\p"
	.string "なかは　からっぽ　だ！$"

Text_EmptyTrashCan: @ 0x082642E6
	.string "なかは　からっぽ　だ！$"

Text_ShopShelf: @ 0x082642F2
	.string "たくさんの　ポケモン　グッズが\n"
	.string "ところせましと　ならべられてる！$"

Text_Blueprint: @ 0x08264313
	.string "なにかの　せっけいず⋯⋯？\n"
	.string "みても　チンプンカンプン！$"
