@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "やすみ$"

gText_LinkStandby4::
	.string "つうしん　たいきちゅう！$"

gText_WinnerIsPlayersMonCongrats::
	.string "ゆうしょうは　{B_COPY_VAR_1}の　{B_COPY_VAR_2}！\n"
	.string "おめでとう！$"

gText_WinnerIsPlayersMon::
	.string "ゆうしょうは{B_COPY_VAR_1}の{B_COPY_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "いちじしんさ{B_COPY_VAR_1}い{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "にじしんさ{B_COPY_VAR_1}い{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "セットされたイベントは{B_COPY_VAR_1}ばん{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "いちばんおおくつかったわざは\n"
	.string "{B_COPY_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "いんしょうにのこったのは\n"
	.string "{B_COPY_VAR_1}の{B_COPY_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "セットされたイベントは{B_COPY_VAR_1}ばん{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "ゆうしょう　しなかったので\n"
	.string "つうしんテレビはつくられません{PAUSE_UNTIL_PRESS}$"
