@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "たくさん　アピール　できる$"

gText_UserMoreEasilyStartled::
	.string "この　アピールの　あと\n"
	.string "びっくり　しやすく　なってしまう$"

gText_GreatAppealButNoMoreToEnd::
	.string "すごいアピールに　なるが　このあと\n"
	.string "さいごまで　なにも　できなくなる$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "つづけて　だしても　しんさいんに\n"
	.string "あきられずに　アピール　できる$"

gText_AvoidStartledByOthersOnce::
	.string "ほかの　ポケモンに　おどかされても\n"
	.string "1ど　くらいは　がまんできる$"

gText_AvoidStartledByOthers::
	.string "ほかの　ポケモンに　おどかされても\n"
	.string "がまんできる$"

gText_AvoidStartledByOthersLittle::
	.string "ほかの　ポケモンに　おどかされても\n"
	.string "すこし　くらいなら　がまんできる$"

gText_UserLessLikelyStartled::
	.string "この　わざを　だした　あとは\n"
	.string "あまり　びっくり　しなくなる$"

gText_SlightlyStartleFrontMon::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　ちょっと　おどろかす$"

gText_SlightlyStartleAppealed::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　ちょっと　おどろかす$"

gText_StartleAppealedBeforeUser::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　おどろかす$"

gText_StartleAllAppealed::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　おどろかす$"

gText_BadlyStartleFrontMon::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleAppealed::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　かなり　おどろかす$"

gText_StartleAppealedBeforeUser2::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　おどろかす$"

gText_StartleAllAppealed2::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　おどろかす$"

gText_ShiftJudgesAttentionFromOthers::
	.string "しんさいんの　ほかの　ポケモンへの\n"
	.string "ちゅうもくを　そらすことが　できる$"

gText_StartleMonHasJudgesAttention::
	.string "しんさいんに　ちゅうもく　されている\n"
	.string "ポケモンを　とくに　おどろかす$"

gText_JamOthersMissesTurn::
	.string "みんなの　じゃまを　しまくって\n"
	.string "つぎの　アピールは　さんか　しない$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "おなじ　タイプの　アピールを　した\n"
	.string "ポケモンを　とくに　おどろかす$"

gText_BadlyStartleCoolAppeals::
	.string "かっこいい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleBeautyAppeals::
	.string "うつくしい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleCuteAppeals::
	.string "かわいい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleSmartAppeals::
	.string "かしこい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleToughAppeals::
	.string "たくましい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_MakeMonAfterUserNervous::
	.string "このあと　アピールする　ポケモン\n"
	.string "1ひきを　きんちょう　させる$"

gText_MakeAllMonsAfterUserNervous::
	.string "このあと　アピールする　ポケモン\n"
	.string "みんなを　きんちょう　させる$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "アピールが　おわった　ポケモンの\n"
	.string "ちょうしを　さげる$"

gText_BadlyStartleMonsGoodCondition::
	.string "ちょうしの　いい　ポケモン\n"
	.string "みんなを　かなり　おどろかす$"

gText_AppealGreatIfPerformedFirst::
	.string "1ばん　はじめに　アピールすると\n"
	.string "アピールが　すごく　うまくいく$"

gText_AppealGreatIfPerformedLast::
	.string "1ばん　さいごに　アピールすると\n"
	.string "アピールが　すごく　うまくいく$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "それまでの　ポケモンの　アピールと\n"
	.string "おなじくらいの　アピールに　みせる$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "1つまえの　ポケモンの　アピールと\n"
	.string "おなじくらい　うまく　できる$"

gText_AppealBetterLaterItsPerformed::
	.string "みんなの　あとで　アピールするほど\n"
	.string "すごい　アピールに　みせられる$"

gText_AppealVariesDependingOnTiming::
	.string "だすときに　よって　アピールの\n"
	.string "できぐあいが　いろいろと　かわる$"

gText_WorksWellIfSameTypeAsBefore::
	.string "1つまえの　ポケモンの　アピールと\n"
	.string "タイプが　おなじなら　きにいられる$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "1つまえの　ポケモンの　アピールと\n"
	.string "タイプが　ちがうなら　きにいられる$"

gText_AffectedByAppealInFront::
	.string "1つまえの　ポケモンの　アピールの\n"
	.string "うまさに　えいきょう　される$"

gText_UpsConditionHelpsPreventNervousness::
	.string "アピールの　ちょうしが　あがる\n"
	.string "きんちょうも　しにくくなる$"

gText_AppealWorksWellIfConditionGood::
	.string "ちょうしが　いいときに　だすと\n"
	.string "アピールが　とても　うまくいく$"

gText_NextAppealMadeEarlier::
	.string "このつぎの　アピールを\n"
	.string "はじめの　ほうに　だすことが　できる$"

gText_NextAppealMadeLater::
	.string "このつぎの　アピールを\n"
	.string "おわりの　ほうに　だすことが　できる$"

gText_TurnOrderMoreEasilyScrambled::
	.string "このつぎの　アピールの\n"
	.string "じゅんばんが　かわりやすく　なる$"

gText_ScrambleOrderOfNextAppeals::
	.string "このつぎの　アピールの\n"
	.string "じゅんばんを　めちゃくちゃに　する$"

gText_AppealExcitesAudienceInAnyContest::
	.string "どの　コンテストで　みせても\n"
	.string "かならず　もりあがる　アピール$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "アピールが　うまくいった　ポケモン\n"
	.string "みんなを　かなり　おどろかす$"

gText_AppealBestMoreCrowdExcited::
	.string "かいじょうが　もりあがっている　ほど\n"
	.string "アピールが　きにいられる$"

gText_TemporarilyStopCrowdExcited::
	.string "このアピールのあと　かいじょうが\n"
	.string "しばらく　もりあがらなく　なる$"

@ Unused move names

gText_RainDance::
	.string "あまごい$"

gText_Rage::
	.string "いかり$"

gText_FocusEnergy::
	.string "きあいだめ$"

gText_Hypnosis::
	.string "さいみんじゅつ$"

gText_Softboiled::
	.string "タマゴうみ$"

gText_HornAttack::
	.string "つのでつく$"

gText_SwordsDance::
	.string "つるぎのまい$"

gText_Conversion::
	.string "テクスチャー$"

gText_SunnyDay::
	.string "にほんばれ$"

gText_Rest2::
	.string "ねむる$"

gText_Vicegrip::
	.string "はさむ$"

gText_DefenseCurl::
	.string "まるくなる$"

gText_LockOn::
	.string "ロックオン$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "かっこいい$"

gContestMoveTypeBeautyText::
	.string "うつくしい$"

gContestMoveTypeCuteText::
	.string "かわいい$"

gContestMoveTypeSmartText::
	.string "かしこい$"

gContestMoveTypeToughText::
	.string "たくましい$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "かいめの　アピール！\n"
	.string "どの　わざを　だす？$"

gText_AppealNumButItCantParticipate::
	.string "かいめの　アピール！\n"
	.string "しかし　さんか　できない！$"

gText_MonAppealedWithMove::
	.string "{B_COPY_VAR_1}は\n{B_COPY_VAR_2}で　アピール！$"

gText_MonWasWatchingOthers::
	.string "{B_COPY_VAR_1}は\n"
	.string "みんなを　みていた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "アピールタイム　しゅうりょう！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "しかし　じゃまを　された！$"

gText_FollowedAnotherMonsLead::
	.string "ほかの　ポケモンに　つられた！$"

gText_ButItMessedUp::
	.string "しかし　しっぱいして\n"
	.string "しまった！$"

gText_WentBetterThanUsual::
	.string "いつもより　うまく　いった！$"

gText_JudgeLookedAwayForSomeReason::
	.string "しんさいんが　なぜか\n"
	.string "めを　そらした！$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "これまでの　しっぱいを\n"
	.string "いかして　がんばってみた！$"

gText_CantMakeAnyMoreMoves::
	.string "これいじょう　わざを\n"
	.string "だせなくなった！$"

gText_WorkedFrighteninglyWell::
	.string "こわいくらい　うまく　いった！$"

gText_WorkedHardAsStandoutMon::
	.string "めだっている　ポケモンと\n"
	.string "おなじくらい　がんばった！$"

gText_JudgedLookedOnExpectantly::
	.string "しんさいんが　きたいを\n"
	.string "こめた　めで　みつめた！$"

gText_WorkedRatherWell::
	.string "かなり　うまく　いった！$"

gText_WorkedLittleBetterThanUsual::
	.string "ふつうより　ちょっと\n"
	.string "うまく　いった！$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{B_COPY_VAR_1}は\n"
	.string "ぜんぜん　めだたなかった⋯{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{B_COPY_VAR_1}は\n"
	.string "あんまり　めだたなかった⋯{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{B_COPY_VAR_1}は\n"
	.string "まあまあ　めだった！{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{B_COPY_VAR_1}は\n"
	.string "かなり　めだった！{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{B_COPY_VAR_1}は\n"
	.string "ものすごく　めだった！{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{B_COPY_VAR_1}は\n"
	.string "アピール　していない！{PAUSE_UNTIL_PRESS}$"

@ Unused

gText_AnticipationSwelledForMonsAppealNext2::
	.string "つぎの　{B_COPY_VAR_1}の　アピールに\n"
	.string "きたいが　たかまった！$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "しんさいんの　{B_COPY_VAR_1}への\n"
	.string "いんしょうは　かわらない！$"

gText_MonsXChangedPerceptions::
	.string "{B_COPY_VAR_1}の　{B_COPY_VAR_3}は\n"
	.string "いんしょうを　はねかえした！$"

gText_MonsAppealEffectWoreOff::
	.string "{B_COPY_VAR_1}の\n"
	.string "アピールこうかが　なくなった！$"

gText_SpecialAppealsEffectWoreOff::
	.string "スペシャル　アピールの\n"
	.string "こうかが　なくなった！$"

gText_EveryonesAppealsMadeToLookSame::
	.string "ぜんいんの　アピールを\n"
	.string "おなじくらいに　みせた！$"

gText_CheapenedMonsAppeal::
	.string "{B_COPY_VAR_2}の\n"
	.string "アピールを　ひくくみせた！$"

gText_CheapenedAppealOfThoseAhead::
	.string "{B_COPY_VAR_1}より　めだつ\n"
	.string "アピールを　ひくくみせた！$"

gText_StoleAttentionAwayFromMon::
	.string "{B_COPY_VAR_2}の\n"
	.string "ちゅうもくを　うばった！$"

gText_CheapenedMonsAppeal2::
	.string "{B_COPY_VAR_2}の\n"
	.string "アピールを　ひくくみせた！$"

gText_SeverelyCheapenedOtherAppeals::
	.string "みんなの　アピールを\n"
	.string "おおはばに　ひくくみせた！$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "つぎの　{B_COPY_VAR_1}の　アピールに\n"
	.string "きたいが　たかまった！$"

gText_CheapenedAppealOfThoseAhead2::
	.string "{B_COPY_VAR_1}より　めだっている\n"
	.string "アピールを　ひくくみせた！$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "しんさいんの　すきなアピールを\n"
	.string "いつもより　ひくくみせた！$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "じぶんいがいの　アピールを\n"
	.string "はんぶんの　できにみせた！$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "いままで　じゃまされた\n"
	.string "うっぷんを　はらして　めだった！$"

gText_CantParticipateInAppealsAnyMore::
	.string "もう　アピールに\n"
	.string "さんか　できなくなった！$"

gText_TouchedJudgeForFantasticAppeal::
	.string "しんさいんの　こころに　うったえ\n"
	.string "すごい　アピールになった！$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "つぎからの　アピールに\n"
	.string "すこし　きたいが　たかまった！$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "スペシャル　アピールがある\n"
	.string "かずだけ　めだった！$"

gText_StoodOutAsMuchAsMon::
	.string "{B_COPY_VAR_1}と\n"
	.string "おなじくらい　めだった！$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "じゃまされた　アピールを\n"
	.string "さらに　めだたなくした！$"

gText_EveryonesAppealsMadeSame::
	.string "ぜんいんの　アピールと\n"
	.string "おなじくらいに　みせた！$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "ほかの　ポケモンが　いつもより\n"
	.string "きに　なって　きた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{B_COPY_VAR_1}は　このあと\n"
	.string "アピール　できなく　なった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_SettledDownJustLittleBit::
	.string "ちょっと　だけ\n"
	.string "きもちが　おちついた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BecameObliviousToOtherMons::
	.string "ほかの　ポケモンが　ぜんぜん\n"
	.string "きに　ならなく　なった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BecameLessAwareOfOtherMons::
	.string "ほかの　ポケモンが　あまり\n"
	.string "きに　ならなく　なった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StoppedCaringAboutOtherMons::
	.string "ほかの　ポケモンを　あまり\n"
	.string "きに　しないように　なった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherMons::
	.string "ほかの　ポケモンを\n"
	.string "びっくり　させようと　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToDazzleOthers::
	.string "みんなの　めを\n"
	.string "くらませようと　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_JudgeLookedAwayFromMon::
	.string "しんさいんは　{B_COPY_VAR_1}から\n"
	.string "めを　そらして　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToUnnerveNextMon::
	.string "つぎに　まっている　ポケモンを\n"
	.string "きんちょう　させようと　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameNervous::
	.string "{B_COPY_VAR_1}は\n"
	.string "きんちょう　してしまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "アピールが　まだの　ポケモンを\n"
	.string "きんちょう　させようと　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TauntedMonsDoingWell::
	.string "ちょうしが　いい　ポケモンを\n"
	.string "からかってみた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonRegainedItsForm::
	.string "{B_COPY_VAR_1}の　ちょうしが\n"
	.string "もとに　もどって　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToJamMonDoingWell::
	.string "ちょうしが　いい　ポケモンの\n"
	.string "じゃまを　しようと　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StandoutMonHustledEvenMore::
	.string "めだっている　{B_COPY_VAR_1}は\n"
	.string "さらに　はりきった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "めだっていない　{B_COPY_VAR_1}は\n"
	.string "がんばりまくった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_WorkedAsMuchAsMonBefore::
	.string "まえの　ポケモンたちに\n"
	.string "まけないくらい　はりきった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell::
	.string "{B_COPY_VAR_1}は　アピールを\n"
	.string "うまく　みせられなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "まえの　ポケモンと\n"
	.string "おなじくらい　はりきった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell2::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "うまく　みせられなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotGoWell3::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "うまく　みせられなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentSlightlyWell::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "すこし　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentPrettyWell::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "まあまあ　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentExcellently::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "とても　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWasDud::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "しっぱい　して　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "あまり　うまく　いかなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "すこし　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentPrettyWell2::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "まあまあ　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentVeryWell::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "かなり　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsAppealWentExcellently2::
	.string "{B_COPY_VAR_1}の　アピールは\n"
	.string "とても　うまく　いった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_SameTypeAsOneBeforeGood::
	.string "まえの　ポケモンと\n"
	.string "おなじタイプで　きにいられた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "まえの　ポケモンと\n"
	.string "ちがうタイプで　きにいられた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "まえの　ポケモンより\n"
	.string "だいぶ　めだった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_DidntDoAsWellAsMonBefore::
	.string "まえの　ポケモンより\n"
	.string "うまく　できなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsConditionRoseAboveUsual::
	.string "{B_COPY_VAR_1}の　ちょうしが\n"
	.string "いつもより　あがった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{B_COPY_VAR_1}は　ちょうしが　よくて\n"
	.string "ぜっこうの　アピールに　なった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MovedUpInLineForNextAppeal::
	.string "つぎの　アピールを　はやく\n"
	.string "しようと　まえに　でた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MovedBackInLineForNextAppeal::
	.string "つぎの　アピールを　おそく\n"
	.string "しようと　1ぽ　さがった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ScrambledUpOrderForNextTurn::
	.string "つぎの　ターンの　じゅんばんを\n"
	.string "おかしく　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_JudgeLookedAtMonExpectantly::
	.string "しんさいんが　きたいして\n"
	.string "{B_COPY_VAR_1}を　みつめた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "アピールの　くみあわせが\n"
	.string "きに　いって　もらえた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "アピールの　くみあわせが\n"
	.string "かなり　きに　いられた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "アピールの　くみあわせが\n"
	.string "ものすごく　きに　いられた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{B_COPY_VAR_1}は　なんとか\n"
	.string "めを　そらした！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{B_COPY_VAR_1}は\n"
	.string "そっちを　みずに　すんだ！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{B_COPY_VAR_1}は\n"
	.string "このくらいは　へいきだった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{B_COPY_VAR_1}は　ちょっと\n"
	.string "きを　とられて　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "ほかの　ポケモンを\n"
	.string "びっくり　させようと　した！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{B_COPY_VAR_1}は　きを　とられて\n"
	.string "したを　むいて　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{B_COPY_VAR_1}は　きを　とられて\n"
	.string "ふりかえって　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{B_COPY_VAR_1}は　おもわず\n"
	.string "こえを　あげて　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{B_COPY_VAR_1}は　おもわず\n"
	.string "とびあがって　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{B_COPY_VAR_1}は　きを　とられて\n"
	.string "ひっくり　かえって　しまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{B_COPY_VAR_1}は　きんちょうして\n"
	.string "アピールが　できなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "でも　しっぱい　してしまった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "でも　きんちょう\n"
	.string "させられなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "でも　だれも\n"
	.string "きんちょう　しなかった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "でも　むし　されて　しまった⋯{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "でも　ちょうしは\n"
	.string "あがらなかった⋯{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "ちょうしが　よく　なくて\n"
	.string "あまり　うまく　できなかった⋯{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{B_COPY_VAR_1}は\n"
	.string "へいき　だった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{B_COPY_VAR_1}は　おなじアピールを\n"
	.string "つづけて　がっかり　された！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{B_COPY_VAR_1}の　{B_COPY_VAR_3}が\n"
	.string "まわりに　とても　うけた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{B_COPY_VAR_1}の　{B_COPY_VAR_3}は\n"
	.string "ここでは　うけなかった⋯{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{B_COPY_VAR_1}の　{B_COPY_VAR_3}に\n"
	.string "まわりが　もりあがった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{B_COPY_VAR_1}は　つぎの　アピールに\n"
	.string "さんか　できなくなった！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "かんきゃくの\n"
	.string "ちゅうもくを　あつめた！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "かんきゃくは\n"
	.string "{B_COPY_VAR_3}を　みつづけている！{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{B_COPY_VAR_1}の　{B_COPY_VAR_2}は\n"
	.string "めを　むけられなかった⋯{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "モジモジ$"

gText_Contest_Anxiety::
	.string "ドキドキ$"

gText_Contest_Laziness::
	.string "デレデレ$"

gText_Contest_Hesitancy::
	.string "オロオロ$"

gText_Contest_Fear::
	.string "ビクビク$"

gText_Contest_Coolness::
	.string "かっこよさ$"

gText_Contest_Beauty::
	.string "うつくしさ$"

gText_Contest_Cuteness::
	.string "かわいさ$"

gText_Contest_Smartness::
	.string "かしこさ$"

gText_Contest_Toughness::
	.string "たくましさ$"

@ Unused

gText_Tension::
	.string "テンション$"

gText_CoolMove::
	.string "かっこいい　わざ$"

gText_BeautyMove::
	.string "うつくしい　わざ$"

gText_CuteMove::
	.string "かわいい　わざ$"

gText_SmartMove::
	.string "かしこい　わざ$"

gText_ToughMove::
	.string "たくましい　わざ$"

gText_3QuestionMarks::
	.string "？？？$"
