gContestHallPaintingCaption::
	.string "{B_COPY_VAR_1}\n"
	.string "{B_COPY_VAR_2}　の　{B_COPY_VAR_3}$"

@ Unused

gContestPaintingContest::
	.string "コンテスト$"

gContestRankNormal::
	.string "ノーマルランク$"

gContestRankSuper::
	.string "スーパーランク$"

gContestRankHyper::
	.string "ハイパーランク$"

gContestRankMaster::
	.string "マスターランク$"

gContestLink::
	.string "つうしん$"

gContestCoolness::
	.string "かっこよさ$"

gContestBeauty::
	.string "うつくしさ$"

gContestCuteness::
	.string "かわいさ$"

gContestSmartness::
	.string "かしこさ$"

gContestToughness::
	.string "たくましさ$"

gContestPaintingCool1::
	.string "スーパー　クール\n"
	.string "ノンストップ　{B_COPY_VAR_1}$"

gContestPaintingCool2::
	.string "グッドルッキン　ポケモン　{B_COPY_VAR_1}$"

gContestPaintingCool3::
	.string "マーベラス　ワンダフル\n"
	.string "グレート　{B_COPY_VAR_1}$"

gContestPaintingBeauty1::
	.string "こんせいき　さいごの　ビーナス\n"
	.string "ビューティー　{B_COPY_VAR_1}$"

gContestPaintingBeauty2::
	.string "{B_COPY_VAR_1}　クンの　マブシイ\n"
	.string "キラキラ　スマイル$"

gContestPaintingBeauty3::
	.string "ポケモンセンター　の\n"
	.string "スーパー　アイドル　{B_COPY_VAR_1}$"

gContestPaintingCute1::
	.string "ラブリー　スウィート　{B_COPY_VAR_1}　ちゃん$"

gContestPaintingCute2::
	.string "プリティー　{B_COPY_VAR_1}たんの\n"
	.string "おすまし　ショット$"

gContestPaintingCute3::
	.string "こっち　むいて！\n"
	.string "キュート　ポケモン　{B_COPY_VAR_1}　ちゃん$"

gContestPaintingSmart1::
	.string "かしこさ　マエストロ\n"
	.string "ワイズ　ポケモン　{B_COPY_VAR_1}$"

gContestPaintingSmart2::
	.string "えらばれた　ポケモン⋯\n"
	.string "ポケモンの　なかの　ポケモン　{B_COPY_VAR_1}$"

gContestPaintingSmart3::
	.string "エクセレント　{B_COPY_VAR_1}　の\n"
	.string "ゆうがな　ひととき$"

gContestPaintingTough1::
	.string "パワフル　マッスル\n"
	.string "ハッスル　{B_COPY_VAR_1}$"

gContestPaintingTough2::
	.string "ストロング　ストロンガー\n"
	.string "ストロンゲスト　{B_COPY_VAR_1}$"

gContestPaintingTough3::
	.string "タフネス　マイティー\n"
	.string "ハイパーポケモン　{B_COPY_VAR_1}！$"
