@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "たくさん　アピール　できる$"

gText_UserMoreEasilyStartled::
	.string "この　アピールの　あと\n"
	.string "びっくり　しやすく　なってしまう$"

gText_GreatAppealButNoMoreToEnd::
	.string "すごいアピールに　なるが　このあと\n"
	.string "さいごまで　なにも　できなくなる$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "つづけて　だしても　しんさいんに\n"
	.string "あきられずに　アピール　できる$"

gText_AvoidStartledByOthersOnce::
	.string "ほかの　ポケモンに　おどかされても\n"
	.string "1ど　くらいは　がまんできる$"

gText_AvoidStartledByOthers::
	.string "ほかの　ポケモンに　おどかされても\n"
	.string "がまんできる$"

gText_AvoidStartledByOthersLittle::
	.string "ほかの　ポケモンに　おどかされても\n"
	.string "すこし　くらいなら　がまんできる$"

gText_UserLessLikelyStartled::
	.string "この　わざを　だした　あとは\n"
	.string "あまり　びっくり　しなくなる$"

gText_SlightlyStartleFrontMon::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　ちょっと　おどろかす$"

gText_SlightlyStartleAppealed::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　ちょっと　おどろかす$"

gText_StartleAppealedBeforeUser::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　おどろかす$"

gText_StartleAllAppealed::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　おどろかす$"

gText_BadlyStartleFrontMon::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleAppealed::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　かなり　おどろかす$"

gText_StartleAppealedBeforeUser2::
	.string "じぶんの　まえに　アピールした\n"
	.string "ポケモンを　おどろかす$"

gText_StartleAllAppealed2::
	.string "アピールが　おわっている　ポケモン\n"
	.string "みんなを　おどろかす$"

gText_ShiftJudgesAttentionFromOthers::
	.string "しんさいんの　ほかの　ポケモンへの\n"
	.string "ちゅうもくを　そらすことが　できる$"

gText_StartleMonHasJudgesAttention::
	.string "しんさいんに　ちゅうもく　されている\n"
	.string "ポケモンを　とくに　おどろかす$"

gText_JamOthersMissesTurn::
	.string "みんなの　じゃまを　しまくって\n"
	.string "つぎの　アピールは　さんか　しない$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "おなじ　タイプの　アピールを　した\n"
	.string "ポケモンを　とくに　おどろかす$"

gText_BadlyStartleCoolAppeals::
	.string "かっこいい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleBeautyAppeals::
	.string "うつくしい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleCuteAppeals::
	.string "かわいい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleSmartAppeals::
	.string "かしこい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_BadlyStartleToughAppeals::
	.string "たくましい　アピールを　した\n"
	.string "ポケモンを　かなり　おどろかす$"

gText_MakeMonAfterUserNervous::
	.string "このあと　アピールする　ポケモン\n"
	.string "1ひきを　きんちょう　させる$"

gText_MakeAllMonsAfterUserNervous::
	.string "このあと　アピールする　ポケモン\n"
	.string "みんなを　きんちょう　させる$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "アピールが　おわった　ポケモンの\n"
	.string "ちょうしを　さげる$"

gText_BadlyStartleMonsGoodCondition::
	.string "ちょうしの　いい　ポケモン\n"
	.string "みんなを　かなり　おどろかす$"

gText_AppealGreatIfPerformedFirst::
	.string "1ばん　はじめに　アピールすると\n"
	.string "アピールが　すごく　うまくいく$"

gText_AppealGreatIfPerformedLast::
	.string "1ばん　さいごに　アピールすると\n"
	.string "アピールが　すごく　うまくいく$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "それまでの　ポケモンの　アピールと\n"
	.string "おなじくらいの　アピールに　みせる$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "1つまえの　ポケモンの　アピールと\n"
	.string "おなじくらい　うまく　できる$"

gText_AppealBetterLaterItsPerformed::
	.string "みんなの　あとで　アピールするほど\n"
	.string "すごい　アピールに　みせられる$"

gText_AppealVariesDependingOnTiming::
	.string "だすときに　よって　アピールの\n"
	.string "できぐあいが　いろいろと　かわる$"

gText_WorksWellIfSameTypeAsBefore::
	.string "1つまえの　ポケモンの　アピールと\n"
	.string "タイプが　おなじなら　きにいられる$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "1つまえの　ポケモンの　アピールと\n"
	.string "タイプが　ちがうなら　きにいられる$"

gText_AffectedByAppealInFront::
	.string "1つまえの　ポケモンの　アピールの\n"
	.string "うまさに　えいきょう　される$"

gText_UpsConditionHelpsPreventNervousness::
	.string "アピールの　ちょうしが　あがる\n"
	.string "きんちょうも　しにくくなる$"

gText_AppealWorksWellIfConditionGood::
	.string "ちょうしが　いいときに　だすと\n"
	.string "アピールが　とても　うまくいく$"

gText_NextAppealMadeEarlier::
	.string "このつぎの　アピールを\n"
	.string "はじめの　ほうに　だすことが　できる$"

gText_NextAppealMadeLater::
	.string "このつぎの　アピールを\n"
	.string "おわりの　ほうに　だすことが　できる$"

gText_TurnOrderMoreEasilyScrambled::
	.string "このつぎの　アピールの\n"
	.string "じゅんばんが　かわりやすく　なる$"

gText_ScrambleOrderOfNextAppeals::
	.string "このつぎの　アピールの\n"
	.string "じゅんばんを　めちゃくちゃに　する$"

gText_AppealExcitesAudienceInAnyContest::
	.string "どの　コンテストで　みせても\n"
	.string "かならず　もりあがる　アピール$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "アピールが　うまくいった　ポケモン\n"
	.string "みんなを　かなり　おどろかす$"

gText_AppealBestMoreCrowdExcited::
	.string "かいじょうが　もりあがっている　ほど\n"
	.string "アピールが　きにいられる$"

gText_TemporarilyStopCrowdExcited::
	.string "このアピールのあと　かいじょうが\n"
	.string "しばらく　もりあがらなく　なる$"

@ Unused move names

gText_RainDance::
	.string "あまごい$"

gText_Rage::
	.string "いかり$"

gText_FocusEnergy::
	.string "きあいだめ$"

gText_Hypnosis::
	.string "さいみんじゅつ$"

gText_Softboiled::
	.string "タマゴうみ$"

gText_HornAttack::
	.string "つのでつく$"

gText_SwordsDance::
	.string "つるぎのまい$"

gText_Conversion::
	.string "テクスチャー$"

gText_SunnyDay::
	.string "にほんばれ$"

gText_Rest2::
	.string "ねむる$"

gText_Vicegrip::
	.string "はさむ$"

gText_DefenseCurl::
	.string "まるくなる$"

gText_LockOn::
	.string "ロックオン$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "かっこいい$"

gContestMoveTypeBeautyText::
	.string "うつくしい$"

gContestMoveTypeCuteText::
	.string "かわいい$"

gContestMoveTypeSmartText::
	.string "かしこい$"

gContestMoveTypeToughText::
	.string "たくましい$"
