@ Battle Tower
gText_AnabelWonSilver::
	.string "ざんねん　だよ⋯⋯$"

gText_AnabelDefeatSilver::
	.string "なるほどね⋯⋯$"

gText_AnabelWonGold::
	.string "ごめんね⋯⋯$"

gText_AnabelDefeatGold::
	.string "ありがとう⋯⋯$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "アッハッハッ！！　はずかしく　ないのっ！？\n"
	.string "みんなが　みてるよっ！！$"

gText_TuckerDefeatSilver::
	.string "クッ⋯⋯　なんて　こと⋯⋯$"

gText_TuckerWonGold::
	.string "ドームスーパースターの\n"
	.string "なまえは　かざりじゃ　ないっ！！$"

gText_TuckerDefeatGold::
	.string "アッハッハッ！！　ステキっ！！$"

@ Battle Factory
gText_NolandWonSilver::
	.string "おつかれさん！\n"
	.string "イイ　べんきょうに　なったろ？$"

gText_NolandDefeatSilver::
	.string "イイねぇー！\n"
	.string "おめえ　わかってる　ねぇー！$"

gText_NolandWonGold::
	.string "おいおいおいーー！！\n"
	.string "もう　おしまいかー？$"

gText_NolandDefeatGold::
	.string "なんだとぉ⋯⋯$"

@ Battle Pike
gText_LucyWonSilver::
	.string "フン⋯⋯$"

gText_LucyDefeatSilver::
	.string "くっ⋯⋯$"

gText_LucyWonGold::
	.string "ハッ！！$"

gText_LucyDefeatGold::
	.string "ちくしょおぉぉぉっーーー！！$"

@ Battle Arena
gText_GretaWonSilver::
	.string "ちょっと　ちょっとぉー！\n"
	.string "もっと　がんばってよねー！！$"

gText_GretaDefeatSilver::
	.string "うっそ！　やるじゃんー！！$"

gText_GretaWonGold::
	.string "ウィーッス！　とうぜん！！$"

gText_GretaDefeatGold::
	.string "いーっ！？　マジっ！？$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "ポケモンが　なんじゃく　なのは\n"
	.string "トレーナーが　なんじゃく　だからだ！！$"

gText_SpenserDefeatSilver::
	.string "ほほぅ⋯⋯\n"
	.string "これは　これは⋯⋯$"

gText_SpenserWonGold::
	.string "ぐわはっはっは！！\n"
	.string "わが　きょうだいの　まえに　てき　なし！！$"

gText_SpenserDefeatGold::
	.string "ぐわーーーはっはっは！！$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "おい！　なにを　やってるんだ！\n"
	.string "ほら　がんばれ！　たちあがるんだ！！$"

gText_BrandonDefeatSilver::
	.string "よおしっ！　がんばった！\n"
	.string "よく　がんばったぞ！！$"

gText_BrandonWonGold::
	.string "おい！　あきらめるんじゃ　ない！\n"
	.string "さあ　たつんだ！　がんばるんだ！！$"

gText_BrandonDefeatGold::
	.string "よおしっ！　よく　やったぞ！\n"
	.string "がんばった！　がんばった　じゃないか！！$"

	.align 2
