@ Physical continuation of the Lilycove Contest Lobby's map-owned text.
@ It follows the Lobby script owner at 0x08207640 and precedes the Contest
@ Hall map-script table at 0x082077B9, so it remains a top-level include.

LilycoveCity_ContestLobby_Text_MasterRankHereICome:: @ 0x08207640
	.string "いっ　いよいよ\n"
	.string "マスターランクに　でるぞ⋯⋯\p"
	.string "おれの　ポケモンちゃんが\n"
	.string "このよで　いちばん\l"
	.string "かわいいって　ことを\l"
	.string "しょうめいする　ときが　きたんだ⋯⋯\l"
	.string "うへへへへ$"

LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere:: @ 0x08207692
	.string "ここに　くれば\n"
	.string "ポケモンを　たくさん　みられるから\l"
	.string "さんぽコースに　してるの！$"

LilycoveCity_ContestLobby_Text_ContestFeastForEyes:: @ 0x082076BA
	.string "いやあ　コンテストかいじょうに　くると\n"
	.string "かきがいの　ある　ポケモンが\l"
	.string "いっぱい　だね！$"

LilycoveCity_ContestLobby_Text_ToughContestIsExtreme:: @ 0x082076E6
	.string "たくましさコンテストって\n"
	.string "さいこう　だよな！\p"
	.string "ちからづよい　アピール⋯⋯\n"
	.string "ほとばしる　あせ⋯⋯　たまらん！$"

LilycoveCity_ContestLobby_Text_LavishedCareOnMon:: @ 0x0820771C
	.string "まいにち　だいじに　だいじに\n"
	.string "そだてあげた　わしの　ポケモン\l"
	.string "コンディションは　カンペキ！\l"
	.string "きょうは　かつぞおおおおおうう！$"

LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily:: @ 0x0820775B
	.string "ママと　パパと　おねえちゃんと\n"
	.string "4にんで　ポロックを　つくったら\l"
	.string "すごく　いいやつが　できたんだ！\p"
	.string "きっと　おおぜいで　つくれば　つくるほど\n"
	.string "なめらかで　いい　ポロックが　できるんだよ！$"
