MatchCall_WildBattleText1::
	.string "あ！　{PLAYER}{KUN}　こんにちは！\n"
	.string "{STR_VAR_1}　です\p"
	.string "このまえ　{STR_VAR_2}を　みつけたんだけど\n"
	.string "つかまえられなかったよ\p"
	.string "おしかったなー\n"
	.string "じゃあ　またね！$"

MatchCall_WildBattleText2::
	.string "こんにちは　{PLAYER}{KUN}！\n"
	.string "{STR_VAR_1}　です\p"
	.string "このまえ　{STR_VAR_2}　を\n"
	.string "つかまえようと　したんだけど\p"
	.string "にげられちゃったの\n"
	.string "ざんねん　だったなあ\p"
	.string "じゃあ　またね！$"

MatchCall_WildBattleText3::
	.string "おーっす　{PLAYER}！\n"
	.string "{STR_VAR_1}　だ！\p"
	.string "このまえ　{STR_VAR_2}　を\n"
	.string "つかまえようと　したんだけど\l"
	.string "あとすこしの　ところで　にげられたんだ！\p"
	.string "くやしかった　なあ···\n"
	.string "じゃあ　またなー$"

MatchCall_WildBattleText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "{STR_VAR_2}って　ポケモン　しってるかい？\n"
	.string "このまえ　あとすこしで\p"
	.string "つかまえられそう　だったんだけど\n"
	.string "にげられて　しまったよ\p"
	.string "こんど　みつけたら　ぜったい\n"
	.string "つかまえて　みせるよ\p"
	.string "じゃあ　またな$"

MatchCall_WildBattleText5::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だけど\l"
	.string "ポケモン　つかまえてる？\p"
	.string "おれも　このまえ　もうすこしで\n"
	.string "つかまえられそう　だったけど\p"
	.string "にげられちゃったよ\n"
	.string "じゃあ　またな$"

MatchCall_WildBattleText6::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だけど\l"
	.string "ポケモン　つかまえてる？\p"
	.string "おれも　このまえ　もうすこしで\n"
	.string "つかまえられそう　だったけど\p"
	.string "にげられちゃったよ\n"
	.string "じゃあ　またな$"

MatchCall_WildBattleText7::
	.string "···あ　{PLAYER}{KUN}？\n"
	.string "{STR_VAR_1}　だけど···\p"
	.string "あ　ちょっと　まって！\n"
	.string "いま　{STR_VAR_2}を　つかまえ···\p"
	.string "ああああ　にげられたー！\n"
	.string "もうすこし　だったのに！$"

MatchCall_WildBattleText8::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "あれから　ポケモン　つかまえた？\n"
	.string "わたし　このまえ　もうすこしで\p"
	.string "つかまえられそう　だったのに\n"
	.string "にげられちゃった\p"
	.string "もっと　がんばらなきゃ！\n"
	.string "じゃあ　またね$"

MatchCall_WildBattleText9::
	.string "あ　{PLAYER}{KUN}　こんにちはー！\n"
	.string "{STR_VAR_1}　です！\p"
	.string "どう？　ポケモン　あつまってる？\n"
	.string "わたしは　にげられて　ばっかりで\p"
	.string "ぜんぜん　うまく　いかないの\n"
	.string "じゃあ　またね！$"

MatchCall_WildBattleText10::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "もうすこしで　{STR_VAR_2}　を\n"
	.string "つかまえられそう　だったのに\l"
	.string "にげられちゃった\p"
	.string "もっと　がんばらなきゃ！\n"
	.string "じゃあ　またね$"

MatchCall_WildBattleText11::
	.string "ああ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だけど\l"
	.string "ちょうしは　どうだい？\p"
	.string "おれは　このまえ　{STR_VAR_2}　を\n"
	.string "つかまえようと　したんだけど\p"
	.string "にげられちゃったよ\n"
	.string "がっくり$"

MatchCall_WildBattleText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが\l"
	.string "ポケモン　つかまえとるかな？\p"
	.string "わしも　つかまえようと　おもったが\n"
	.string "なかなか　うまくいかん\p"
	.string "ポケモンの　みちは\n"
	.string "おくが　ふかいのう$"

MatchCall_WildBattleText13::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが\l"
	.string "ポケモン　つかまえとるかな？\p"
	.string "わしも　つかまえようと　おもったが\n"
	.string "なかなか　うまくいかん\p"
	.string "ポケモンの　みちは\n"
	.string "おくが　ふかいのう$"

MatchCall_WildBattleText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "さっき　{STR_VAR_2}ちゃんを\n"
	.string "つかまえようと　したんだけど\p"
	.string "にげられちゃったのよ　ざんねん！\n"
	.string "じゃあ　またね$"

MatchCall_WildBattleText15::
	.string "おーっす　{PLAYER}！\n"
	.string "{STR_VAR_1}　だ！\p"
	.string "ポケモンを　つかまえようと\n"
	.string "おもってるんだが\l"
	.string "みつからなくてさー\l"
	.string "おじさん　こまってる　とこなのよ\p"
	.string "まいったなー\n"
	.string "じゃあ　またなー$"

MatchCall_NegativeBattleText1::
	.string "{PLAYER}{KUN}　こんにちは！\n"
	.string "{STR_VAR_1}　です！\p"
	.string "ほかのひとと　しょうぶ　したんだけど\n"
	.string "まけちゃったよ　がっくし\p"
	.string "じゃあ　またね$"

MatchCall_NegativeBattleText2::
	.string "{PLAYER}{KUN}　こんにちは！\n"
	.string "{STR_VAR_1}よ！\p"
	.string "わたし　ね\n"
	.string "あれから　また　しょうぶ　してみたの\p"
	.string "でも　あとちょっとの　ところで\n"
	.string "まけちゃった　あーあ$"

MatchCall_NegativeBattleText3::
	.string "おーっす　{PLAYER}！\n"
	.string "{STR_VAR_1}　だ！\p"
	.string "しょうぶ　に　まけたよー\n"
	.string "もっと　そだてないと　だめだなー$"

MatchCall_NegativeBattleText4::
	.string "やあ　{PLAYER}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "きのう　また　しょうぶ　してみたんだ\n"
	.string "でも　かてなかったよ\p"
	.string "もっと　そだてが　ひつようだな\n"
	.string "じゃあ　またな$"

MatchCall_NegativeBattleText5::
	.string "やあ　{PLAYER}\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "ちょうしは　どうだい？\n"
	.string "おれは　しょうぶ　しても\l"
	.string "あまり　かてないんだよ\p"
	.string "ちょうし　わるいなあ\n"
	.string "じゃあ　またな$"

MatchCall_NegativeBattleText6::
	.string "やあ　{PLAYER}\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "ちょうしは　どうだい？\n"
	.string "おれは　しょうぶ　しても\l"
	.string "あまり　かてないんだよ\p"
	.string "ちょうし　わるいなあ\n"
	.string "じゃあ　またな$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1}　だけどー\n"
	.string "さいきん　どう？\p"
	.string "きのう　しょうぶに　まけてさ\n"
	.string "そのことで　あたまが　いっぱいなんだ\p"
	.string "たいさく　かんがえないと···\n"
	.string "じゃあ　また$"

MatchCall_NegativeBattleText8::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "ポケモンの　ちょうしは　どう？\n"
	.string "わたしは　このまえの　しょうぶで\l"
	.string "まけちゃった\p"
	.string "もっと　がんばらなきゃ！\n"
	.string "じゃあ　またね$"

MatchCall_NegativeBattleText9::
	.string "あ　{PLAYER}{KUN}　こんにちはー！\n"
	.string "{STR_VAR_1}　でーす\p"
	.string "ねー　きいて　きいて！\n"
	.string "このまえ　ポケモン　しょうぶ　したんだけど\p"
	.string "あとちょっとの　ところで\n"
	.string "まけちゃったのよー！　くやしい！$"

MatchCall_NegativeBattleText10::
	.string "あら　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　です\p"
	.string "さっき　しょうぶ　したんだけど\n"
	.string "まけちゃった\p"
	.string "もっと　ポケモン　そだてないと　だめね\n"
	.string "じゃあ　またね$"

MatchCall_NegativeBattleText11::
	.string "やあ　{PLAYER}{KUN}　げんきかい？\n"
	.string "{STR_VAR_1}　だよ\l"
	.string "ポケモンの　ちょうしは　どう？\p"
	.string "こっちは　また　しょうぶに\n"
	.string "まけちゃったよ\p"
	.string "じゃあ　また$"

MatchCall_NegativeBattleText12::
	.string "やあやあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが\l"
	.string "しょうぶ　しておるのかな？\p"
	.string "わしのほうは　このまえ　まけてしまって\n"
	.string "また　ポケモンを\l"
	.string "そだてておる　ところじゃよ\p"
	.string "では　またな$"

MatchCall_NegativeBattleText13::
	.string "おお　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃ\p"
	.string "げんき　かのう？\n"
	.string "さっきまで　ポケモン　しょうぶを\l"
	.string "しておったよ\p"
	.string "{PLAYER}{KUN}も　がんばるんじゃぞ\n"
	.string "では　またの$"

MatchCall_NegativeBattleText14::
	.string "あら　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　よ\p"
	.string "ちょうしは　どうなの？\n"
	.string "たまには　いえに　かえらないと　だめよ\l"
	.string "じゃあ　またね$"

MatchCall_PositiveBattleText1::
	.string "こんにちは　{PLAYER}{KUN}！\n"
	.string "{STR_VAR_1}　です！\p"
	.string "さっき　しょうぶ　したんだけど\n"
	.string "かったよ！　かったよ！\p"
	.string "ぼくの　{STR_VAR_2}　が\n"
	.string "すごく　がんばったんだ！　うれしいなー$"

MatchCall_PositiveBattleText2::
	.string "こんにちは　{PLAYER}{KUN}！\n"
	.string "{STR_VAR_1}　です！\p"
	.string "きのう　しょうぶ　したんだけど\n"
	.string "かったのよ！　うれしいー！$"

MatchCall_PositiveBattleText3::
	.string "おーっす　{PLAYER}！\n"
	.string "{STR_VAR_1}　だぞ\p"
	.string "ちょうしは　どうだ？\n"
	.string "おれも　このまえ　しょうぶ　したんだけど\l"
	.string "おれの　{STR_VAR_2}が　だいかつやく　さ！\p"
	.string "つぎ　{PLAYER}と　しょうぶ　するときは\n"
	.string "ぜったい　まけない　からなー！$"

MatchCall_PositiveBattleText4::
	.string "やあ　{PLAYER}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "さっき　しょうぶ　したんだけど\n"
	.string "なんとか　かつ　ことが　できたよ\p"
	.string "ぼくの　{STR_VAR_2}が\n"
	.string "すごく　がんばったんだ$"

MatchCall_PositiveBattleText5::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "ちょうしは　どうだい？\n"
	.string "しょうぶ　してる？\p"
	.string "おれ　このまえ　かったよ！\n"
	.string "{STR_VAR_2}が　だいかつやく　さ！\p"
	.string "つぎこそ　きみに　かつからね！\n"
	.string "じゃあ　またね$"

MatchCall_PositiveBattleText6::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "げんき　かい？\n"
	.string "おれは　さいきん　ちょうしが　よくて\l"
	.string "さっきも　しょうぶに　かったところだ\p"
	.string "つぎに　きみと　しょうぶ　するときは\n"
	.string "ぜったいに　まけないからな$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}？\n"
	.string "{STR_VAR_1}　だけど\p"
	.string "ぼくの　{STR_VAR_2}　つよいわけよ！\n"
	.string "さっきも　しょうぶで　かったわけよ！\p"
	.string "つぎに　きみと　しょうぶ　するのが\n"
	.string "たのしみだなあ$"

MatchCall_PositiveBattleText8::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "げんき　かしら？\n"
	.string "わたしね　さっき　しょうぶ　して　かったの\p"
	.string "{STR_VAR_2}　が　とっても　がんばったのよ\n"
	.string "じゃあ　またね$"

MatchCall_PositiveBattleText9::
	.string "こんにちは　{PLAYER}{KUN}！\n"
	.string "{STR_VAR_1}　でーす！\p"
	.string "ポケモンの　ちょうしは　どう？\n"
	.string "わたしのほうは　さっき　しょうぶして\l"
	.string "かった　ところよ！\p"
	.string "わたしの　{STR_VAR_2}　が\n"
	.string "すごい　かつやく　だったのよ\p"
	.string "みせたかったなー\n"
	.string "じゃあ　またね！$"

MatchCall_PositiveBattleText10::
	.string "あら　こんにちは　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　よ\p"
	.string "ちょうしは　どうかしら？\n"
	.string "わたしの　ポケモン　ちょうし　いいみたい\p"
	.string "さっきも　しょうぶで　かてたのよ\n"
	.string "じゃあ　またね$"

MatchCall_PositiveBattleText11::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "ポケモン　しょうぶ　してるかい？\n"
	.string "おじさん　きょうも　しょうぶに　かってねー\p"
	.string "ちょうし　いいんだよ　がははは\n"
	.string "じゃあ　またね$"

MatchCall_PositiveBattleText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃよ\p"
	.string "げんきに　してるかのう？\n"
	.string "わしは　げんき　じゃぞ\p"
	.string "さっきも　しょうぶに　かった　ところじゃ\n"
	.string "わかいもんには　まだまだ　まけんぞ$"

MatchCall_PositiveBattleText13::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃよ\p"
	.string "げんきに　してるかのう？\n"
	.string "わしは　げんき　じゃぞ\p"
	.string "さっきも　しょうぶに　かった　ところじゃ\n"
	.string "わかいもんには　まだまだ　まけんぞ\p"
	.string "じゃあ　またのう$"

MatchCall_PositiveBattleText14::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "このまえ　しょうぶ　したんだけど\n"
	.string "わたしの　{STR_VAR_2}が　だいかつやく！\p"
	.string "{PLAYER}{KUN}にも　みせたかったな\n"
	.string "じゃあ　また$"

MatchCall_SameRouteBattleRequestText1::
	.string "{PLAYER}さん　こんにちは！\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "え！　いま　{STR_VAR_2}　に　いるの？\n"
	.string "じゃあ　いまから　しょうぶ　しようよ！\l"
	.string "まってるよ！　じゃあね！$"

MatchCall_SameRouteBattleRequestText2::
	.string "{PLAYER}さん　こんにちは！\n"
	.string "{STR_VAR_1}　でーす\p"
	.string "え！　いま　{STR_VAR_2}　に　いるの？\n"
	.string "じゃあ　いまから　しょうぶ　しない？\l"
	.string "まってるわよ！　じゃあね！$"

MatchCall_SameRouteBattleRequestText3::
	.string "おーっす　{PLAYER}！\n"
	.string "{STR_VAR_1}　だ！\p"
	.string "お　いま　{STR_VAR_2}にいるのか？\n"
	.string "じゃあ　これから　しょうぶ　しないか？\p"
	.string "こんどこそ　まけない　からな！\n"
	.string "まってるぞー　じゃあな$"

MatchCall_SameRouteBattleRequestText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "いま　どこに　いるんだい？\n"
	.string "え　{STR_VAR_2}？\p"
	.string "じゃあ　これから　しょうぶ　しないか？\n"
	.string "まってるよ　じゃあね$"

MatchCall_SameRouteBattleRequestText5::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "ちょうしは　どうだい？\n"
	.string "え？　いま　{STR_VAR_2}に　いるの？\p"
	.string "それなら　これから　おれと\n"
	.string "しょうぶ　してみないかい？\p"
	.string "まってるよ　じゃあね$"

MatchCall_SameRouteBattleRequestText6::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "ポケモンの　ちょうしは　どうだい？\n"
	.string "へえ　いま　{STR_VAR_2}に　いるのか\p"
	.string "じゃあ　これから　おれと\n"
	.string "しょうぶ　しよう\p"
	.string "まってるよ　じゃあね$"

MatchCall_SameRouteBattleRequestText7::
	.string "···あ　{PLAYER}{KUN}？\n"
	.string "{STR_VAR_1}　だけど···\p"
	.string "へー　いま　{STR_VAR_2}に　いるの？\n"
	.string "じゃあ　しょうぶ　しよう　これから\p"
	.string "おれの　ポケモンを　みせてあげるよ\n"
	.string "じゃあ　まってるよ$"

MatchCall_SameRouteBattleRequestText8::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "げんき　ですか？\n"
	.string "あら　いま　{STR_VAR_2}に　いるのね\p"
	.string "じゃあ　これから\n"
	.string "わたしと　しょうぶ　しない？\p"
	.string "まってるわよ　じゃあね！$"

MatchCall_SameRouteBattleRequestText9::
	.string "あ　{PLAYER}{KUN}　こんにちはー！\n"
	.string "{STR_VAR_1}　です！\p"
	.string "げんきに　してる？\n"
	.string "あら　いま　{STR_VAR_2}に　いるの？\p"
	.string "そっかー　じゃあ　これから\n"
	.string "わたしと　しょうぶ　してみない？\p"
	.string "じゃあね　まってるわよ$"

MatchCall_SameRouteBattleRequestText10::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "げんき　ですか？\n"
	.string "あら　いま　{STR_VAR_2}に　いるのね\p"
	.string "じゃあ　これから\n"
	.string "わたしと　しょうぶ　しない？\p"
	.string "まってるわよ　じゃあね！$"

MatchCall_SameRouteBattleRequestText11::
	.string "ああ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だけど\p"
	.string "ほほう\n"
	.string "いま　{STR_VAR_2}に　いるんだって？\p"
	.string "じゃあ　これから　おじさんと\n"
	.string "ポケモン　しょうぶ　しないかい？\p"
	.string "まってるよ　じゃあね$"

MatchCall_SameRouteBattleRequestText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが\l"
	.string "いま　どこに　いるのかな？\p"
	.string "{STR_VAR_2}　か！　すぐ　ちかく　じゃな\n"
	.string "これから　わしと　しょうぶ　せんか？\p"
	.string "まっておるぞ　じゃあの$"

MatchCall_SameRouteBattleRequestText13::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが　げんきかのう？\p"
	.string "ほうほう　いまは　{STR_VAR_2}に　おるのか\n"
	.string "ちかいから　こっちへ　よって\p"
	.string "いちど　しょうぶ　して　いかんかの？\n"
	.string "まっておるぞ　じゃあの$"

MatchCall_SameRouteBattleRequestText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "あら　いま　{STR_VAR_2}に　いるの？\n"
	.string "すぐちかくに　いるのね\p"
	.string "じゃあ　これから　おばさんと\n"
	.string "ポケモンしょうぶ　してみない？\p"
	.string "まってるわよ　じゃあね$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "あ！　{PLAYER}{KUN}！\n"
	.string "{STR_VAR_1}　です\p"
	.string "これから　ぼくと　しょうぶ　しない？\n"
	.string "{STR_VAR_2}　で　まってるよ！$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "あ！　{PLAYER}{KUN}！\n"
	.string "{STR_VAR_1}　です\p"
	.string "これから　わたしと　しょうぶ　してみない？\n"
	.string "{STR_VAR_2}　で　まってるよ！$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "おーっす　{PLAYER}！\n"
	.string "{STR_VAR_1}　だ！\p"
	.string "あれから　おれの　ポケモンも\n"
	.string "たくましく　なったぞ！\p"
	.string "{PLAYER}の　ポケモンで\n"
	.string "うでだめし　したいから\p"
	.string "しょうぶ　してみないか？\n"
	.string "{STR_VAR_2}　で　まってるぞ$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "ちょうしは　どうだい？\n"
	.string "おれの　ポケモンも\l"
	.string "ずいぶん　つよく　なったよ\p"
	.string "そうだ　また　おれと\n"
	.string "しょうぶ　しないかい？\p"
	.string "じゃあ　{STR_VAR_2}で　あおう$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だけど\p"
	.string "おれの　ポケモン\n"
	.string "けっこう　いいかんじに　そだってきたよ\p"
	.string "きみと　もういちど\n"
	.string "しょうぶ　してみたいなあ\p"
	.string "{STR_VAR_2}　で　まってるよ\n"
	.string "じゃあね$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だけど\l"
	.string "げんきで　やってるかい？\p"
	.string "また　きみと　ポケモンしょうぶを\n"
	.string "してみたいんだけど　どうだい？\p"
	.string "しょうぶ　したくなったら\n"
	.string "{STR_VAR_2}に　きてくれよ\p"
	.string "じゃあ　また$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "あ　{PLAYER}{KUN}？\n"
	.string "{STR_VAR_1}　だけど···\p"
	.string "どう？　ポケモン　そだってる？\n"
	.string "ぼくの　ポケモンも　つよくなったから\l"
	.string "きみに　みせたいなあ\p"
	.string "{STR_VAR_2}で　まってるから\n"
	.string "しょうぶ　しに　きてくれよ\p"
	.string "じゃあ　また$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "ちょうしは　どうですか？\n"
	.string "わたしの　ポケモンは　とても　げんきですよ\p"
	.string "こんど　こちらに　いらしたら\n"
	.string "また　わたしと\l"
	.string "しょうぶ　してくださいね\p"
	.string "{STR_VAR_2}で　まってます\n"
	.string "では　また$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "あ　{PLAYER}{KUN}　こんにちはー！\n"
	.string "{STR_VAR_1}　です！\p"
	.string "ポケモンの　ちょうしは　どうかな？\n"
	.string "わたしの　ポケモンも\p"
	.string "どんどん　つよく　なってるのよ\n"
	.string "{PLAYER}{KUN}にも　みせてあげたいなあ\p"
	.string "{STR_VAR_2}に　いるから\n"
	.string "ちかくに　きたら　しょうぶでも　しようよ\p"
	.string "じゃあ　またね$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "あ　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "どう？　げんきで　やってるかしら？\n"
	.string "あれから　わたしの　ポケモンも\l"
	.string "ずいぶん　つよく　なったのよ\p"
	.string "また　{PLAYER}{KUN}と\n"
	.string "しょうぶ　したいなあ\p"
	.string "{STR_VAR_2}に　いるから\n"
	.string "ちかくに　きたら　あいに　きてね$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "ああ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だけど\l"
	.string "いま　どこに　いるのかな？\p"
	.string "わしの　ポケモンは　とても　げんき　だぞ\n"
	.string "{PLAYER}{KUN}の　ポケモンと　あうのを\l"
	.string "たのしみに　しているみたいだ\p"
	.string "{STR_VAR_2}に　いるから\n"
	.string "ぜひ　あいに　きてくれよ$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃ\p"
	.string "わしの　ポケモンも　あれから\n"
	.string "ずいぶんと　たくましく　なったぞ\p"
	.string "{PLAYER}{KUN}の　ポケモンと\n"
	.string "もういちど　てあわせ　したいのう\p"
	.string "{STR_VAR_2}に　おるから\n"
	.string "いつでも　きてくれたまえ$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃ\p"
	.string "ポケモンは　げんきに　しとるかね？\n"
	.string "わしの　ポケモンも\l"
	.string "まけない　ぐらい　げんきに　しておるよ\p"
	.string "また　しょうぶ　してみたいので\n"
	.string "{STR_VAR_2}の　ちかくに　きたら\p"
	.string "あいに　きてくれんかのう\n"
	.string "では　またの$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "げんきに　してる？\n"
	.string "あ　そうそう\p"
	.string "わたしの　ポケモン\n"
	.string "あれから　けっこう　つよく　なったのよ\p"
	.string "{PLAYER}{KUN}と　もういちど\n"
	.string "しょうぶ　してみたいわねえ\p"
	.string "{STR_VAR_2}で　まってるから\n"
	.string "いつでも　あいに　きてね$"

MatchCall_PersonalizedText1::
	.string "やまを　あいする　{STR_VAR_1}だが\p"
	.string "どうだね　あれから\n"
	.string "すこしは　やまが　すきに　なったか？\l"
	.string "あまり　やまで　きみを　みかけないが⋯⋯\p"
	.string "よし　つぎは　{STR_VAR_2}で\n"
	.string "あおう　じゃないか　またな！$"

MatchCall_PersonalizedText2::
	.string "{STR_VAR_1}です\n"
	.string "こんにちは\p"
	.string "いまね　トレーナーに　なりたてのコに\n"
	.string "あなたの　ことを　きかせて　いたのよ！\l"
	.string "ポケモンを　たいせつに　そだてている\l"
	.string "つよい　トレーナーが　いるのよって⋯⋯\p"
	.string "みんなの　あこがれに　なるような\n"
	.string "すばらしい　トレーナーに　なってね！\l"
	.string "じゃあ　また　あいましょう！$"

MatchCall_PersonalizedText3::
	.string "こんにちは！　{STR_VAR_1}よ\n"
	.string "この　あたりは　ほんとうに\l"
	.string "いいかおりが　して　きもちがいいわ\p"
	.string "だれかが　きのみを　うめて\n"
	.string "はなを　さかせて　くれたのかしら？　うふふ\p"
	.string "それじゃ　またね！$"

MatchCall_PersonalizedText4::
	.string "はいはい！　いせきを　さがして　30ねん\n"
	.string "わたし　{STR_VAR_1}で　ございます\p"
	.string "きみは　せっきょくてきに　あちこちを\n"
	.string "まわって　いるよう　だけど\l"
	.string "なにか　いせきを　みつけたかい？\l"
	.string "みつけたら　おしえて　くれよ！\p"
	.string "では　わたしは\n"
	.string "いせきを　さがすので　これで$"

MatchCall_PersonalizedText5::
	.string "{STR_VAR_1}　でーす\n"
	.string "きょうはね　すなはま　から\l"
	.string "うみを　ながめて　いるんだ！\p"
	.string "はー⋯⋯　キラキラ　なみが　ひかって\n"
	.string "ここから　みる　うみが　いちばん　きれい！\l"
	.string "あー　おなかすいた　じゃあまたね！$"

MatchCall_PersonalizedText6::
	.string "もぐもぐ⋯⋯\n"
	.string "あ　{STR_VAR_1}です\l"
	.string "すなはまで　たべる　おにぎりは　うまいなー\p"
	.string "うーん　ぼくも　ポケモンも\n"
	.string "げんきに　なったぞ！\l"
	.string "じゃ　およいで　くるね！$"

MatchCall_PersonalizedText7::
	.string "やあ　{STR_VAR_1}　だけど⋯⋯\p"
	.string "エリートトレーナー　の　せいかつに\n"
	.string "ちょっと　つかれちゃってね⋯⋯\p"
	.string "みんな　ぼくのことを\n"
	.string "かんぺきな　トレーナーだと　おもうから\l"
	.string "ぼくも　それらしく　しないと　いけない\p"
	.string "でも　それも　エリートトレーナーの\n"
	.string "しゅくめいだと　おもって\l"
	.string "がんばる　ことに　するよ！\p"
	.string "こんな　ことが　いえるのは　キミだけだ\n"
	.string "でも　こんど　あった　ときは\l"
	.string "よわねは　はかないから　あんしんして！\l"
	.string "じゃ！$"

MatchCall_PersonalizedText8::
	.string "ヤッホー　{STR_VAR_1}よ\n"
	.string "こんにちは！\p"
	.string "いま　あなたを　めざして\n"
	.string "ポケモンを　そだてて　いるの！\l"
	.string "こんど　たたかう　ときは\l"
	.string "ぜったい　まけない　つもり！　ふふっ\p"
	.string "トレーナー　なかまが　いるって　いいよね\n"
	.string "また　あいましょう！$"

MatchCall_PersonalizedText9::
	.string "{STR_VAR_1}　ですけど⋯⋯\n"
	.string "いま　あなたの　うしろ⋯⋯\l"
	.string "なにかが　いない⋯⋯？\p"
	.string "ここ　おくりびやまで　ねむっている\n"
	.string "ポケモンたちの　ちからが\l"
	.string "わたしに　おしえて　くれるの⋯⋯\l"
	.string "ふりかえらないで　そのまま\l"
	.string "まっすぐ　あるいたほうが　いいわよ⋯⋯\p"
	.string "フフ⋯⋯\n"
	.string "それじゃあ　さよなら⋯⋯$"

MatchCall_PersonalizedText10::
	.string "わたくし　{STR_VAR_1}ですわ\n"
	.string "ごきげんよう\p"
	.string "はなれていても　こうして\n"
	.string "おはなし　できるなんて　べんりね\p"
	.string "いままでは　あいたい　ひとが　いたら\n"
	.string "パパに　おくってもらって　いたもの⋯⋯\p"
	.string "それではまた⋯⋯\n"
	.string "おはなし　できて　うれしかった　ですわ$"

MatchCall_PersonalizedText11::
	.string "{STR_VAR_1}よ\n"
	.string "ちょっと　はなし　ききなさいよ！\p"
	.string "わたし　サファリゾーンが　すきなんだけど\n"
	.string "あそこに　いくと　かならず　まようのよ！\l"
	.string "くさ　ばっかり　はえてて\l"
	.string "ちょっと　ひろすぎるのよねー！　ぷんぷん！\p"
	.string "あー　おこったら　きが　すんだわ\n"
	.string "ちょっと　サファリゾーンでも　いこっと！\l"
	.string "またね！$"

MatchCall_PersonalizedText12::
	.string "やあ\n"
	.string "おかねもちの　{STR_VAR_1}　だけど\p"
	.string "ボク　あれから　ますます\n"
	.string "おかねもちに　なっちゃったし\l"
	.string "ポケモンも　ますます　つよく　なったよ\p"
	.string "この　せかいって\n"
	.string "ボクの　ために　あるんじゃない　かな？\p"
	.string "ああ　へんじは　しなくて　いいよ\n"
	.string "わかっている　ことだからね！\l"
	.string "おっと　そろそろ　ディナーのじかんだ\l"
	.string "しつれい　するよ！$"

MatchCall_PersonalizedText13::
	.string "うふふふふふふ⋯⋯\n"
	.string "ボ　ボク　{STR_VAR_1}です\p"
	.string "いま　めのまえで\n"
	.string "{STR_VAR_2}　どうしが　たたかってるんだ\l"
	.string "かった　ほうを　つかまえよう　かな？\l"
	.string "うふふふふ⋯⋯\p"
	.string "じ　じゃ　いそがしいから\n"
	.string "ボクは　これで$"

MatchCall_PersonalizedText14::
	.string "あ　{STR_VAR_1}です！\n"
	.string "そろそろ　すてられぶね　にも\l"
	.string "あきて　きちゃった　のよね\p"
	.string "でも　せっかく　だから\n"
	.string "いちどは　キミに　かって　みたいし\l"
	.string "とうぶんは　ここで　さんぽ　してるわ\l"
	.string "きが　むいたら　あいに　きてよね！\p"
	.string "よし　きょうは　ついに\n"
	.string "となりの　へやの　おじさんに\l"
	.string "しょうぶを　いどんで　みようかな？\p"
	.string "ではね！$"

MatchCall_PersonalizedText15::
	.string "うみの　おとこ\n"
	.string "{STR_VAR_1}だぜ！\p"
	.string "やっぱさ！\n"
	.string "でっかい　うみに　いる　トレーナーは\l"
	.string "つよいやつ　ばっかりだぜ！\p"
	.string "おまえも　オレらを　みならって\n"
	.string "うみで　しゅぎょうすりゃ　いいのによ⋯⋯\l"
	.string "⋯⋯と　おおなみが　きそうだ！\p"
	.string "しゅぎょうの　チャンスだぜ！\n"
	.string "わるいけど　またなっ！$"

MatchCall_PersonalizedText16::
	.string "{STR_VAR_1}だ！\n"
	.string "ポケモンに　カラテを　おしえてたら\l"
	.string "ほんとに　おれより　つよくなっちまって\l"
	.string "おれ　まけまくりだ！\p"
	.string "だが　おれは　ポケモンに　まけても\n"
	.string "トレーナー　には　まけん！\l"
	.string "いつか　また　おれと　しょうぶだ！\l"
	.string "うがー！$"

MatchCall_PersonalizedText17::
	.string "{STR_VAR_1}だけど\n"
	.string "そっちの　たびは　どんなカンジ？\p"
	.string "⋯⋯へえー　なるほど　なるほど\n"
	.string "たのしそうじゃん！\l"
	.string "きみの　エピソードで\l"
	.string "1きょく　つくれそうだな！\p"
	.string "⋯⋯おッ　うかんできた\n"
	.string "いい　フレーズ　うかんできたよ！\p"
	.string "じゃ　オレ　いまから\n"
	.string "きょくづくりに　はいるから　またな！$"

MatchCall_PersonalizedText18::
	.string "{STR_VAR_1}だけど⋯⋯\n"
	.string "ボクの　しんきょく　きいてくれ\p"
	.string "ルル　{STR_VAR_2}　{STR_VAR_2}\n"
	.string "どうして　おまえは　{STR_VAR_2}なんだ\l"
	.string "どうして　ボクは　{STR_VAR_2}では　ないんだ\l"
	.string "あー　ルルル　{STR_VAR_2}と{STR_VAR_1}\l"
	.string "{STR_VAR_1}と{STR_VAR_2}　ルル⋯⋯\p"
	.string "フェードアウト⋯⋯$"

MatchCall_PersonalizedText19::
	.string "キャンプの　たつじん\n"
	.string "{STR_VAR_1}　だ！\p"
	.string "ま　こないだ　ぼくが　まけちゃったのは\n"
	.string "ぼくの　せんもんが　キャンプだからね\l"
	.string "しかたが　なかったのさ！\p"
	.string "かっても　まけても\n"
	.string "キャンプで　ポケモンしょうぶ　するの\l"
	.string "ぼく　だいすき　なんだ！\p"
	.string "またこんど　あいてを　たのむよ\n"
	.string "あ　キャンプも　いっしょに　しようぜ！$"

MatchCall_PersonalizedText20::
	.string "おれ　おれ　{STR_VAR_1}！\p"
	.string "いやあ　おれも　ほかの　やまにも\n"
	.string "のぼって　みても　いいんだけどさー\l"
	.string "えんとつやま　みたいに\l"
	.string "きれいな　おねいさん　たちが\l"
	.string "いるか　どうか　わからんもんなー\p"
	.string "きれいな　おねいさんが　いっぱいの\n"
	.string "やまが　あったら　おしえて　くれよ！\l"
	.string "えへへへ　またなあ！$"

MatchCall_PersonalizedText21::
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\l"
	.string "{STR_VAR_1}　です⋯⋯\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\l"
	.string "きょうは　それだけ⋯⋯$"

MatchCall_PersonalizedText22::
	.string "{STR_VAR_1}だよ⋯　きょうは\n"
	.string "きみと　はなす　きが　してたんだ\p"
	.string "きみに　かちたい　きもちは\n"
	.string "ひましに　つよくなる　ばかりだよ\l"
	.string "きみ　にも　そんな　あいてが　いるだろ？\l"
	.string "それが　ぼくなら　いいのにな\p"
	.string "きいて　くれて　ありがと　またな！$"

MatchCall_PersonalizedText23::
	.string "{STR_VAR_1}です\p"
	.string "つよい　トレーナーが　ちかくに　いると\n"
	.string "なんとなく　その　そんざいを\l"
	.string "かんじる　ことが　あるの\p"
	.string "もしかしたら　{PLAYER}{KUN}が\n"
	.string "わたしの　そばを　とおったの　かもね？\p"
	.string "あいに　きて　くれるのを\n"
	.string "まっているわ！　バーイ！$"

MatchCall_PersonalizedText24::
	.string "{STR_VAR_1}です\n"
	.string "{PLAYER}{KUN}は　げんきそう　ですな\p"
	.string "せかい　かっこくを　まわった　わたしですが\n"
	.string "この　ちほうを　たいへん　きにいりました\l"
	.string "とうぶん　いる　つもりですよ\p"
	.string "そういう　わけ　ですから\n"
	.string "また　あえるかも　しれませんね\p"
	.string "あなたの　みごとな　わざ\n"
	.string "わすれては　おりませんよ\l"
	.string "また　おあいてを　おねがいしますね$"

MatchCall_PersonalizedText25::
	.string "グスン　{STR_VAR_1}⋯⋯です\n"
	.string "⋯⋯グスン\p"
	.string "きょう　ツツジさんに\n"
	.string "おこられ　ちゃった\p"
	.string "でも　ツツジさんは\n"
	.string "なんで　ボクが　わるいのか\l"
	.string "ちゃんと　おしえて　くれるから\l"
	.string "うらんだり　しないよ！\p"
	.string "あしたも　また　いくんだ\n"
	.string "トレーナーズ　スクール！　えへ⋯⋯\l"
	.string "じゃ　またね！$"

MatchCall_PersonalizedText26::
	.string "{STR_VAR_1}　です！\p"
	.string "きのう　ツツジさまに\n"
	.string "しょうぶ　してもらったの！\p"
	.string "けっかは　さんざん　だったけど⋯⋯\n"
	.string "ツツジさまが　あたしの　あいてを\l"
	.string "してくれた　って　いうことが\l"
	.string "すごく　うれしいの！\l"
	.string "ますます　あこがれちゃうわ！\p"
	.string "いまから　また　もうべんきょうよ！\n"
	.string "だから　さよなら！$"

MatchCall_PersonalizedText27::
	.string "ミホでーす！\n"
	.string "きょうも　こうはいの　リコと　いっしょだよ\p"
	.string "もうね！　リコも　ポケモンも\n"
	.string "かわいくて　しかたないの\l"
	.string "おとうとや　いもうと　みたいに\l"
	.string "ずーっと　めんどう　みて　あげたいな！\p"
	.string "あ　リコ！\n"
	.string "パン　かってきて　くれた？\p"
	.string "え？　な　なによ\n"
	.string "つかいっぱしり　なんて　させてないわよ！\l"
	.string "ポケモン　しょうぶで　まけたから\l"
	.string "これは　ばつゲームなの！\p"
	.string "かわいい　リコを\n"
	.string "こきつかうわけ　ないでしょ！\l"
	.string "じゃ　これから　おやつだから　バイバイ！$"

MatchCall_PersonalizedText28::
	.string "ポケモン　だいすき！\n"
	.string "だいすきクラブの　{STR_VAR_1}です！\p"
	.string "きっ　きいて　くださいよ！\n"
	.string "わたしの　ポケモンちゃんが　なんと⋯⋯！\l"
	.string "ぐふ　ぐふふふ\l"
	.string "これいじょうは　ひみつ！\l"
	.string "もー　かわいすぎて　くちに　できない！\p"
	.string "ああっ　{STR_VAR_2}ちゃんが\n"
	.string "ポロックを　おねだりしてるー！\l"
	.string "かわいいぞーーーっ！\p"
	.string "わるいけど　きみと\n"
	.string "はなしている　ばあいじゃ　ないぞ！\l"
	.string "また　こんど　つづきを　きいてくれ$"

MatchCall_PersonalizedText29::
	.string "おほほ！\p"
	.string "ポケモンを　じまん　したくて　しかたない\n"
	.string "{STR_VAR_1}　ですわ！\p"
	.string "あなた　おききに　なって\n"
	.string "あたくしの　{STR_VAR_2}ちゃん⋯⋯\l"
	.string "ほかの　ひとに　だっこされると\l"
	.string "ピョンと　にげだして\l"
	.string "あたくしの　むねに　とびこんでくるの！\p"
	.string "もう⋯⋯　もう！\n"
	.string "こんな　しあわせって　ほかに　あるかしら！\p"
	.string "ああ　しあわせだわ\n"
	.string "あなたにも　しあわせを　わけて　あげられて\l"
	.string "よかったわ！\l"
	.string "では　しつれい　するわね$"

MatchCall_PersonalizedText30::
	.string "わたしは⋯⋯　{STR_VAR_1}だ\p"
	.string "ひとは　わたしを　たつじんと　よぶ\n"
	.string "だが　わたしは　わかっている\l"
	.string "わたしだけの　ちから　では\l"
	.string "たつじん　には　なれない　ことを\p"
	.string "ポケモンの　ちからが　あってこそ\n"
	.string "トレーナーは　たつじんに　なれる！\p"
	.string "うむ⋯⋯！　わたしは　いま\n"
	.string "すごく　いいことを　いった　きがする！\l"
	.string "きもちがよい　ままに　わかれよう！$"

MatchCall_PersonalizedText31::
	.string "{STR_VAR_1}　じゃよ\n"
	.string "おんせんに　つかって　ごきげんだからねぇ\l"
	.string "こうして　おはなし　できて　うれしいよ！\p"
	.string "あれから　なんにんか\n"
	.string "わかい　トレーナーさんと　たたかったが\l"
	.string "おまえさんが　いちばん　つよかったよ！\p"
	.string "きっと　としを　とったら\n"
	.string "たつじんに　なるじゃろうな！\l"
	.string "おっほっほっほ⋯⋯$"

MatchCall_PersonalizedText32::
	.string "わーい！　{STR_VAR_1}でーす！\n"
	.string "げんきー？\p"
	.string "ボクが　ポケモン　かてる　ときって\n"
	.string "きのせいかも　しれないけど\l"
	.string "たんパンの　ちょうしが　いいんだ！\p"
	.string "え　どういうこと　かって？\n"
	.string "うーん　うまく　せつめい　できないけど\l"
	.string "なんていう　のかな⋯⋯\l"
	.string "はき　ごこちが　サラっと　してるんだ！\p"
	.string "で　{PLAYER}{KUN}と　しょうぶの　ときは\n"
	.string "だいたい　ベタっと　してるんだよね⋯⋯\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "ボクの　はなし　しんじた？\l"
	.string "えへへへ　じゃあね　バイバーイ！$"

MatchCall_PersonalizedText33::
	.string "うおーい！\n"
	.string "{STR_VAR_1}だぞーっ！\l"
	.string "きょうも　ごうかいに\l"
	.string "つりを　たのしんで　いるぞーっ！\p"
	.string "うみ　か　かわ　いがいに\n"
	.string "つりが　できる　ばしょって　ないかーっ？\l"
	.string "どこでも　つりが　したくって\l"
	.string "うずうずするんだーっ！\p"
	.string "おっと　つりいとが　からまった！\n"
	.string "じゃ　つりが　できるところ\l"
	.string "さがしといてくれーっ！　またなーっ！$"

MatchCall_PersonalizedText34::
	.string "やあ！　{STR_VAR_1}　だけど\n"
	.string "どう　のんびり　やっている　かい？\p"
	.string "ボクはさ　むかしから\n"
	.string "あせったり　いそいだり　するのが\l"
	.string "にがて　なんだよね\l"
	.string "それでも　なぜか　いまは\l"
	.string "トライアスリートを　やっている⋯⋯\p"
	.string "じんせい　なにが　おこるか\n"
	.string "わからないって　ヤツだな！　はは\p"
	.string "キミも　いまは　トレーナーだけど\n"
	.string "しょうらいは　せんせい　とか　えかき　とか\l"
	.string "よそうも　つかない　ことを\l"
	.string "やって　いるの　かもな！\p"
	.string "まー　のんびり　やれよ！\n"
	.string "じゃあなー$"

MatchCall_PersonalizedText35::
	.string "{STR_VAR_1}よ！\n"
	.string "いま　じてんしゃに　のっているわ！\p"
	.string "わたし　すいえいも　はしるのも　すきだけど\n"
	.string "じてんしゃが　いちばん　すきなの！\l"
	.string "だって　からだに　かぜを\l"
	.string "たくさん　かんじる　ことが　できるでしょ？\l"
	.string "そらをとぶ　みたいで　きもちいいのよ！\p"
	.string "よーし　きょうこそ　サイクリングロードで\n"
	.string "しんきろくを　だすわっ！\l"
	.string "あなたも　ちょうせん　しに　きなさいよ！\l"
	.string "じゃあねーっ$"

MatchCall_PersonalizedText36::
	.string "よお！　トライアスロンの　まっさいちゅうの\n"
	.string "{STR_VAR_1}だけど\l"
	.string "さくっと　せけんばなし　でも　どうだい！\p"
	.string "ポケモンと　いっしょに　あせを　ながすと\n"
	.string "すごく　きもちいいぜ！\l"
	.string "ことばに　ださなくったって\l"
	.string "ふたりの　こころが　つうじあうんだ\l"
	.string "あれは　ちょっと　かんどう　するなあ！\p"
	.string "はあはあ⋯　はしりながら　はなしてたら\n"
	.string "たいりょくが　なくなった！\l"
	.string "はあはあ　わるいけど　こんどな！$"

MatchCall_PersonalizedText37::
	.string "こんにちは　{STR_VAR_1}よ\n"
	.string "じきゅうりょく　を　つけるには\l"
	.string "やっぱり　たかい　ところが　いいわね！\p"
	.string "やまの　てっぺん　とかで\n"
	.string "はしり　まわると\l"
	.string "すぐに　いきが　きれるのよ！\p"
	.string "ああ　わたしも　いきが　きれそう\n"
	.string "じゃあ　またね！$"

MatchCall_PersonalizedText38::
	.string "ああ　{STR_VAR_1}　です\n"
	.string "あれから　だいぶ　およいだけど\l"
	.string "サイユウシティには　まだ　つかないのかなあ\p"
	.string "もしかして　おなじ　ところを\n"
	.string "ぐるぐる　まわってるだけ　だったりして\p"
	.string "いや　まさか　そんなこと　ないよな\n"
	.string "わはははは\l"
	.string "じゃあ　また！$"

MatchCall_PersonalizedText39::
	.string "ああ　{STR_VAR_1}　ですけ⋯⋯\p"
	.string "ボチャン\p"
	.string "ブクブクブク⋯⋯⋯\p"
	.string "ザバー\p"
	.string "ブンブン\p"
	.string "⋯⋯ごッ　ごめん！\n"
	.string "いま　オイルを　ぬった　てで\l"
	.string "ポケナビを　もってたら\l"
	.string "うみに　おとして　しまったんだ！\p"
	.string "うみに　おとしても　こわれないなんて\n"
	.string "デボンの　ポケナビって　すげーな！\l"
	.string "じゃ　にっこうよくの　つづきを　するんで\l"
	.string "またこんど　はなそうぜ！$"

MatchCall_PersonalizedText40::
	.string "トライアスロンの　なかでも\n"
	.string "すいえいが　だいすきな　{STR_VAR_1}　です\p"
	.string "でも　あんまり　ながいこと\n"
	.string "うみに　いると\l"
	.string "からだが　ふやけちゃわないかなあ\p"
	.string "やっぱり　トライアスロンは\n"
	.string "かこくな　レースよね！\l"
	.string "じゃ　またね！$"

MatchCall_PersonalizedText41::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だ\p"
	.string "きみの　ポケモンの\n"
	.string "ちょうしは　どうだい？\p"
	.string "ぼくの　ドラゴンポケモンたちも\n"
	.string "ちょうし　よさそうだよ\l"
	.string "じゃあ　また$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1}だ\n"
	.string "おれの　{STR_VAR_2}\l"
	.string "あれから　いちだんと　つよくなったぜ！\p"
	.string "つぎ　キミと　しょうぶ　するときは\n"
	.string "まけない　からな！\p"
	.string "じゃあ　またな！$"

MatchCall_PersonalizedText43::
	.string "{STR_VAR_1}で　ござる\n"
	.string "かくれかたの　けんきゅうを\l"
	.string "つづけて　いるんだけど\p"
	.string "うまく　かくれすぎると\n"
	.string "だれにも　みつけて　もらえないで　ござる\l"
	.string "それは　ちょっと　さびしいで　ござるなあ\p"
	.string "それでは　これにて　どろん！$"

MatchCall_PersonalizedText44::
	.string "{STR_VAR_1}よ\n"
	.string "あれから　しゅぎょうを　かさねて\p"
	.string "わたしの　{STR_VAR_2}も\n"
	.string "けっこう　つよく　なってきたわよ\p"
	.string "やっぱり　すなはまでの　しゅぎょうは\n"
	.string "こうかてき　だわ！\l"
	.string "じゃあ　また！$"

MatchCall_PersonalizedText45::
	.string "こんにちは　{STR_VAR_1}です\n"
	.string "かざんばい　いつになったら\l"
	.string "おさまるの　かしら\p"
	.string "あんまり　つもっちゃうと\n"
	.string "パラソルの　がらが\l"
	.string "みえなく　なっちゃうのに⋯⋯\p"
	.string "それでは　また\n"
	.string "おあい　しましょう$"

MatchCall_PersonalizedText46::
	.string "{STR_VAR_1}　でーす\p"
	.string "ねえねえ！\n"
	.string "うみって　プールと　くらべて\l"
	.string "うかびやすいって　しってた？\p"
	.string "こうやって　からだを　よこに　すれば\l"
	.string "かってに　うくのよ\p"
	.string "でも　あんまり　ながく　うかんでると\n"
	.string "おきに　ながされるから\l"
	.string "きを　つけないと　だめよ\p"
	.string "⋯⋯あれ？　ここ　どこかしら⋯⋯\n"
	.string "じゃ　じゃあ　またね！$"

MatchCall_PersonalizedText47::
	.string "あ　{PLAYER}{KUN}　こんにちは！\n"
	.string "{STR_VAR_1}　です\p"
	.string "ここって　じめんが　でこぼこ　してるから\n"
	.string "テント　はれないのよね⋯⋯\l"
	.string "せっかく　やまに　きたのに⋯⋯\p"
	.string "あ！　いいこと　おもいついた！\n"
	.string "ポケモンで　ここを　たいらに\l"
	.string "できないかしら？\p"
	.string "よーし　がんばっちゃおう！\n"
	.string "じゃあ　またね！$"

MatchCall_PersonalizedText48::
	.string "あ　こんにちは\n"
	.string "{STR_VAR_1}　でーす\p"
	.string "ルミと　いっしょに　がんばって\n"
	.string "ポケモン　そだててるの！\p"
	.string "もっと　がんばったら\n"
	.string "いちばんに　なれるかなあ？\l"
	.string "じゃあ　またねー！$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1}だ！\p"
	.string "オレさまは　ふなのり　だが\n"
	.string "いまは　ふねに　のっていない\p"
	.string "ふねに　のっていない　ふなのりは\n"
	.string "なんと　よべば　いいだろうか！\p"
	.string "うみを　みながら\n"
	.string "そんな　ことを　かんがえて　いるのだ！\l"
	.string "じゃあ　またな！！$"

MatchCall_PersonalizedText50::
	.string "{STR_VAR_1}　だよ\n"
	.string "どう？　ポケモン　ふえた？\p"
	.string "あたらしい　ポケモン　つかまえたら\n"
	.string "また　みせに　きてくれよ\p"
	.string "ちょうだいって　いわないからさ\n"
	.string "まってるよ　じゃあね$"

MatchCall_PersonalizedText51::
	.string "{STR_VAR_1}だ\n"
	.string "ポケモン　ちゃんと　そだててるか？\p"
	.string "ここは　くうきも　きれいだし\n"
	.string "ポケモンを　そだてるには\l"
	.string "ぜっこうの　かんきょう　なんだよな\p"
	.string "きみも　ポケモンを　そだてる　ことに\n"
	.string "せんねん　する　ときは\l"
	.string "{STR_VAR_2}に　くると　いいぞ\l"
	.string "じゃあ　またな$"

MatchCall_PersonalizedText52::
	.string "{STR_VAR_1}です\n"
	.string "わたしの　{STR_VAR_2}に\p"
	.string "ポロック　あげたんですよ\n"
	.string "とても　よろこんでた　みたい\p"
	.string "ポケモンに　よって\n"
	.string "ポロックの　すききらいが　あるみたいなの\p"
	.string "おもしろい　ですよね\n"
	.string "では　ごきげんよう$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1}だ\n"
	.string "ポケモンと　きょうりょく　すれば\l"
	.string "しぜんの　なかでも\l"
	.string "かいてきに　くらせる　ものだよ\p"
	.string "みんな　それに　きが　ついて\n"
	.string "もっと　ポケモンと\l"
	.string "きょうりょく　できるように　なれば\l"
	.string "いいのにな！\p"
	.string "きみは　けっこう　いいセン\n"
	.string "いってると　おもうよ！\l"
	.string "じゃ　またな！$"

MatchCall_PersonalizedText54::
	.string "いつも　ぼうけんの　じゅんびを\n"
	.string "おこたらない　{STR_VAR_1}よ！\p"
	.string "{PLAYER}{KUN}　どうぐは　たりてる？\n"
	.string "ポケモンの　たいちょうは　バッチリ？\p"
	.string "じぶんの　みの　まわりを\n"
	.string "つねに　かんぺきに　しておくことが\l"
	.string "たびを　ながく　つづける　ひけつ　よ！\p"
	.string "わたしも　じぶんの　どうぐを\n"
	.string "かくにん　するわ！　またね！$"

MatchCall_PersonalizedText55::
	.string "{STR_VAR_1}だよ　{STR_VAR_1}だよー！\p"
	.string "{STR_VAR_2}　って\n"
	.string "ひとどおりが　はげしいから\l"
	.string "まいにち　いろんな　ひとに\l"
	.string "しょうぶを　もうしこまれるの！\p"
	.string "きょうはねえ　5にんに　かって\n"
	.string "3にんに　まけたわ！\l"
	.string "あなたのほうは　どうだった？\l"
	.string "こんど　きかせてねっ！　じゃあね$"

MatchCall_PersonalizedText56::
	.string "むしポケモンを　いっぱい　もってて\n"
	.string "にんきものの　{STR_VAR_1}　だけど！\p"
	.string "⋯⋯きょう　がっこうに\n"
	.string "おきにいりの　むしポケモンを\l"
	.string "いっぱい　つれて　いったら\l"
	.string "すきな　おんなのこに　なかれ　ちゃった⋯⋯\l"
	.string "うう　わらいたければ　わらって　くれよ\p"
	.string "ぼくは　むしポケモンの　よさを\n"
	.string "あのコに　わかって　もらえるまで\l"
	.string "がんばるんだ　からね！\p"
	.string "グッスン　じゃーな！$"

MatchCall_PersonalizedText57::
	.string "はっ　ほっ　はっ　ほっ\p"
	.string "やあ！　{STR_VAR_1}です！　はっ　ほっ\p"
	.string "やま⋯⋯のぼり　しながらの　おしゃべりも\n"
	.string "なかなか　どうして⋯⋯　はっ　ほっ\l"
	.string "トレーニングに　なるなあ\p"
	.string "ふっ　くっ⋯⋯\n"
	.string "おっと　のぼりが　きつく　なってきた\l"
	.string "ま　また　こんど⋯⋯　ゆっくり　はなそう！\l"
	.string "はっ　ほっ　はっ⋯⋯$"

MatchCall_PersonalizedText58::
	.string "や　や　どうも！\n"
	.string "いま　ナツと　おたから　さがしててさ！\p"
	.string "おたから　なんて　もしかしたら\n"
	.string "ほんとうは　ないのかも　しれないけど⋯⋯\p"
	.string "ナツと　おたからを　ふたりで　さがす\n"
	.string "って　ことが　だいじ　なんだよね\p"
	.string "⋯⋯て　あれ　ナツ？\n"
	.string "な　なんで　おこってるの？\l"
	.string "ほっといて　ゴメンね\l"
	.string "もちろん　キミが　いちばん　だいじだよぉ\l"
	.string "わかっている　だろう？\p"
	.string "じ　じゃ⋯⋯　{PLAYER}さんさようなら$"

MatchCall_PersonalizedText59::
	.string "じぶんは　{STR_VAR_1}だ！\n"
	.string "しゅぎょうの　ために　また\l"
	.string "ムロの　ポケモンジムに　いってきた！\p"
	.string "ジムリーダーの　トウキは\n"
	.string "あらなみに　もまれ　つよくなった！\l"
	.string "なのに　ちっとも　あせくさく　ないし\l"
	.string "もてもてで　しょうじき　くやしい！\p"
	.string "なかまの　シバ　という　おとこも\n"
	.string "きっと　あせくさく　なくて\l"
	.string "ビッグウェーブ　だとか　ボク　だとか\l"
	.string "さわやかに　いったり　するのだろう！\p"
	.string "⋯⋯やきもちは　みぐるしいな！\n"
	.string "すまん　わすれて　くれ！　オスっ！$"

MatchCall_PersonalizedText60::
	.string "わかい　トレーナーさんと\n"
	.string "おはなし　できて　うれしい　のう\p"
	.string "きみも　もちろん\n"
	.string "なんさいに　なっても　ポケモンを\l"
	.string "がんばる　つもり　じゃろう？\l"
	.string "その　ときには　わしらのように\l"
	.string "だれか　あいてが　いると　いいのう！\p"
	.string "まあ　{PLAYER}{KUN}は　いまだって\n"
	.string "ポケモンに　しんらい　されて\l"
	.string "ずっと　がんばって　おるからのう\p"
	.string "りっぱな　きんこんしきに　なれる\n"
	.string "そしつは　バッチリじゃ！\l"
	.string "はっはっはっ　がんばるのじゃよ！$"

MatchCall_PersonalizedText61::
	.string "{STR_VAR_1}です！\n"
	.string "さっき　ボクたち　めずらしく\l"
	.string "かいパンの　おにいさんに　かったんだ！\l"
	.string "でも　かっこいい　ひとだった　から⋯⋯\p"
	.string "せっかく　かよわい　ところを\n"
	.string "みせようと　したのに！\p"
	.string "って　ねえちゃんに　おこられた⋯⋯\p"
	.string "どーせ　かっても　まけても\n"
	.string "おこられるんだ　ボクは！\l"
	.string "{PLAYER}{KUN}も　こんど\l"
	.string "なんとか　いって　やって！\p"
	.string "じゃ　またねー！$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1}だよ　うん⋯⋯\n"
	.string "きのうは　いせきを　もとめて\l"
	.string "ちがう　うみに　でようと　したら\l"
	.string "みちに　まよってしまったよ\p"
	.string "うみを　めぐり　めぐって\n"
	.string "きがついたら　また　もとの　ばしょさ\p"
	.string "あいかわらず　しょうぶも　よわいし\n"
	.string "もう　わらって　くれよ⋯⋯\p"
	.string "まあ　わしは　あきらめんぞ\n"
	.string "いつのひか　いせきを　みつけたら\l"
	.string "わしの　じだいが　くるだろう　からな！\p"
	.string "そういった　わけで\n"
	.string "きょうは　これで　さらばだ！$"

MatchCall_PersonalizedText63::
	.string "やあー　きみーっ！\n"
	.string "{STR_VAR_1}だー！\l"
	.string "わたしは　いまー\l"
	.string "108ばんすいどうに　きているーっ！\p"
	.string "つまり　いつもと　おなじ　ところだー！\p"
	.string "きょうは　めの　まえを\n"
	.string "ビキニのおねえさんが　とおったからーっ\l"
	.string "おおごえで　おどかして　みたーっ！\p"
	.string "そしたら　いやな　かおを　されたー！\p"
	.string "いじょう　108ばんすいどう　から\n"
	.string "{STR_VAR_1}が　おつたえ　したー！$"

MatchCall_PersonalizedText64::
	.string "{STR_VAR_1}よ！\n"
	.string "いま　いそがしいんだけど\l"
	.string "きょうは　もう\l"
	.string "5にんの　トレーナーを　たおしたから\l"
	.string "あなたにも　いちおう　ほうこく　するわ！\p"
	.string "この　ちょうし　だと\n"
	.string "つぎは　たぶん　あなたに　かてるわね！\l"
	.string "わたしたち　いい　ライバルとして\l"
	.string "やって　いけそうね⋯⋯\l"
	.string "じゃあね　バイ！$"

MatchCall_BattleFrontierStreakText1::
	.string "こんにちは　{STR_VAR_1}　です！\n"
	.string "きいたよ！\p"
	.string "{STR_VAR_2}　で\n"
	.string "すごい　かつやく　したんだって？\p"
	.string "{STR_VAR_3}れんしょう　って　すごいなあ\n"
	.string "じゃあ　またね！$"

MatchCall_BattleFrontierStreakText2::
	.string "こんにちは　{STR_VAR_1}　でーす\n"
	.string "{STR_VAR_2}　で\l"
	.string "{STR_VAR_3}れんしょう　したって　きいたわよ！\p"
	.string "すっごーい！　わたしも　がんばろうっと！\n"
	.string "じゃあ　またね！$"

MatchCall_BattleFrontierStreakText3::
	.string "おう！　{PLAYER}！\n"
	.string "{STR_VAR_1}だぞ！\p"
	.string "{STR_VAR_2}　で\n"
	.string "おおあばれ　したらしいな！\p"
	.string "{STR_VAR_3}れんしょう　って\n"
	.string "すごい　きろく　なんだろ？\p"
	.string "おれも　まけられねーな！\n"
	.string "じゃ　またな！$"

MatchCall_BattleFrontierStreakText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だけど　げんき　かい？\p"
	.string "うわさで　きいたんだけど\n"
	.string "きみ　{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんだって？\p"
	.string "ぼくも　がんばらなきゃな\n"
	.string "じゃあ　また$"

MatchCall_BattleFrontierStreakText5::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したんだってね！\l"
	.string "すごいなあ\p"
	.string "ぼくも　ポケモン　そだてなきゃ\n"
	.string "じゃあ　また$"

MatchCall_BattleFrontierStreakText6::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "こんにちは　{STR_VAR_1}　だ\p"
	.string "そういえば　きみ\n"
	.string "{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんだってね\p"
	.string "おれも　がんばって\n"
	.string "ポケモンを　そだてるよ$"

MatchCall_BattleFrontierStreakText7::
	.string "えーと　あ　{PLAYER}{KUN}？\n"
	.string "{STR_VAR_1}　だ···\p"
	.string "そういえば　{STR_VAR_2}　で\n"
	.string "{STR_VAR_3}れんしょう　したんだってね\p"
	.string "あ！　いま　めずらしい　ポケモンを\n"
	.string "みつけたから　じゃあ　また！$"

MatchCall_BattleFrontierStreakText8::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "ちょうしは　どうですか？\n"
	.string "そういえば　{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいですね！\n"
	.string "つぎも　がんばってね$"

MatchCall_BattleFrontierStreakText9::
	.string "あら　{PLAYER}{KUN}！\n"
	.string "こんにちは　{STR_VAR_1}です！\p"
	.string "きいたわよ！　{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したって！\p"
	.string "すっごいねー\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattleFrontierStreakText10::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいわねえ\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattleFrontierStreakText11::
	.string "やあやあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だ\p"
	.string "{STR_VAR_2}で　だいかつやく　らしいなあ\n"
	.string "{STR_VAR_3}れんしょう　したんだって？\p"
	.string "すげえなあ　おれだったら\n"
	.string "なんれんしょう　できるのかな$"

MatchCall_BattleFrontierStreakText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "ひとづてに　きいたのじゃが\n"
	.string "{STR_VAR_2}　とかいう　ところで\l"
	.string "{STR_VAR_3}れんしょうも　したらしいのう？\p"
	.string "すごい　はなし　だのう\n"
	.string "では　またの$"

MatchCall_BattleFrontierStreakText13::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したそうじゃのう\p"
	.string "げんきで　いいことじゃ\n"
	.string "では　またのう$"

MatchCall_BattleFrontierStreakText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "きいたわよ！\n"
	.string "{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいわねえ　かんしん　しちゃうわ！\n"
	.string "じゃあ　またね$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "こんにちは　{STR_VAR_1}　です！\n"
	.string "きいたよ！\p"
	.string "{STR_VAR_2}　で\n"
	.string "すごい　かつやく　したんだって？\p"
	.string "{STR_VAR_3}れんしょう　って　すごいなあ\n"
	.string "じゃあ　またね！$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "こんにちは　{STR_VAR_1}　でーす\n"
	.string "{STR_VAR_2}　で\l"
	.string "{STR_VAR_3}れんしょう　したって　きいたわよ！\p"
	.string "すっごーい！　わたしも　がんばろうっと！\n"
	.string "じゃあ　またね！$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "おう！　{PLAYER}！\n"
	.string "{STR_VAR_1}だぞ！\p"
	.string "{STR_VAR_2}　で\n"
	.string "おおあばれ　したらしいな！\p"
	.string "{STR_VAR_3}れんしょう　って\n"
	.string "すごい　きろく　なんだろ？\p"
	.string "おれも　まけられねーな！\n"
	.string "じゃ　またな！$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だけど　げんき　かい？\p"
	.string "うわさで　きいたんだけど\n"
	.string "きみ　{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんだって？\p"
	.string "ぼくも　がんばらなきゃな\n"
	.string "じゃあ　また$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したんだってね！\l"
	.string "すごいなあ\p"
	.string "おれ？　おれは　まあ　ぼちぼちかなー\n"
	.string "じゃあ　またね$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "こんにちは　{STR_VAR_1}　だ\p"
	.string "そういえば　きみ\n"
	.string "{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんだってね\p"
	.string "おれも　がんばらなきゃ！\n"
	.string "じゃあ　またね$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "えーと　あ　{PLAYER}{KUN}？\n"
	.string "{STR_VAR_1}　だ···\p"
	.string "そういえば　{STR_VAR_2}　で\n"
	.string "{STR_VAR_3}れんしょう　したんだってね\p"
	.string "あ！　いま　めずらしい　ポケモンを\n"
	.string "みつけたから　じゃあ　また！$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "ちょうしは　どうですか？\n"
	.string "そういえば　{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいですね！　わたしも　がんばって\n"
	.string "ポケモンを　そだてなきゃ$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "あら　{PLAYER}{KUN}！\n"
	.string "こんにちは　{STR_VAR_1}です！\p"
	.string "きいたわよ！　{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したって！\p"
	.string "すっごいねー\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいわねえ\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "やあやあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だ\p"
	.string "{STR_VAR_2}で　だいかつやく　らしいなあ\n"
	.string "{STR_VAR_3}れんしょう　したんだって？\p"
	.string "すげえなあ　おれだったら\n"
	.string "なんれんしょう　できるのかな$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "ひとづてに　きいたのじゃが\n"
	.string "{STR_VAR_2}　とかいう　ところで\l"
	.string "{STR_VAR_3}れんしょうも　したらしいのう？\p"
	.string "すごい　はなし　だのう\n"
	.string "では　またの$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したそうじゃのう\p"
	.string "げんきで　いいことじゃ\n"
	.string "では　またのう$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "きいたわよ！\n"
	.string "{STR_VAR_2}で\l"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいわねえ　かんしん　しちゃうわ！\n"
	.string "じゃあ　またね$"

MatchCall_BattleDomeText1::
	.string "あ！　{PLAYER}？\n"
	.string "こんにちは　{STR_VAR_1}　です！\p"
	.string "きいたよ！\n"
	.string "{STR_VAR_2}　で\p"
	.string "{STR_VAR_3}かい　も\n"
	.string "ゆうしょう　したんだって？\p"
	.string "すごいね！　ぼくも　がんばらなきゃ！\n"
	.string "じゃあ　またね$"

MatchCall_BattleDomeText2::
	.string "こんにちは　{STR_VAR_1}　でーす！\n"
	.string "きいたわよ！\p"
	.string "{STR_VAR_2}　で\n"
	.string "{STR_VAR_3}かい　も\l"
	.string "ゆうしょう　したんですって？\p"
	.string "すごいわねー\n"
	.string "わたしも　ゆうしょう　できるのかな？$"

MatchCall_BattleDomeText3::
	.string "よう　{PLAYER}！\n"
	.string "{STR_VAR_1}だぞ　げんきかー？\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}かいも\n"
	.string "ゆうしょう　したって　きいたぞ\p"
	.string "つぎも　がんばれよなー\n"
	.string "じゃあ　またな$"

MatchCall_BattleDomeText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}かいも\n"
	.string "ゆうしょう　した　らしいね\p"
	.string "がんばってる　みたいだね\n"
	.string "ぼくも　まけないように　しなきゃ$"

MatchCall_BattleDomeText5::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "きいたよ　{STR_VAR_2}で\n"
	.string "{STR_VAR_3}かいも　ゆうしょう　したんだって？\p"
	.string "ぼくも　がんばらなきゃ\n"
	.string "じゃあ　またね$"

MatchCall_BattleDomeText6::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "こんにちは　{STR_VAR_1}　だ\p"
	.string "そういえば　きみ\n"
	.string "{STR_VAR_2}で　{STR_VAR_3}かいも\l"
	.string "ゆうしょう　したんだってね\p"
	.string "おれも　まけないように\n"
	.string "ポケモンを　そだてなきゃな$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}？\n"
	.string "ああ　{STR_VAR_1}　だけど\p"
	.string "{STR_VAR_2}で　ゆうしょうを\n"
	.string "{STR_VAR_3}かいも　したんだって？\p"
	.string "へー　ところで　さいきん\n"
	.string "めずらしい　ポケモン　つかまえた？\p"
	.string "あ　そう\n"
	.string "じゃあ　またね$"

MatchCall_BattleDomeText8::
	.string "こんにちは　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　です\p"
	.string "げんき　ですか？\n"
	.string "{STR_VAR_2}で　{STR_VAR_3}かいも\l"
	.string "ゆうしょう　したんですって？\p"
	.string "すごいですね！\n"
	.string "わたしも　がんばって\p"
	.string "ポケモン　そだてないと！\n"
	.string "じゃあ　またね$"

MatchCall_BattleDomeText9::
	.string "あら　{PLAYER}{KUN}！\n"
	.string "こんにちは　{STR_VAR_1}です！\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}かいも　ゆうしょう　したんだって？\p"
	.string "すっごいねー\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattleDomeText10::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}れんしょうも　したんですって？\p"
	.string "すごいわねえ\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattleDomeText11::
	.string "やあやあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だ\p"
	.string "{STR_VAR_2}で\n"
	.string "だいかつやく　らしいなあ\l"
	.string "{STR_VAR_3}れんしょう　したんだって？\p"
	.string "すげえなあ　おれでも\n"
	.string "ゆうしょう　できるのかな\p"
	.string "···　むりかな？\n"
	.string "じゃあ　またな$"

MatchCall_BattleDomeText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}　とかいう　ところで\n"
	.string "{STR_VAR_3}かい　ゆうしょう　したとな？\p"
	.string "すごい　はなし　だのう\n"
	.string "では　またの$"

MatchCall_BattleDomeText13::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}　で\n"
	.string "{STR_VAR_3}かいも　ゆうしょう　とな？\p"
	.string "げんきで　いいことじゃ\n"
	.string "では　またのう$"

MatchCall_BattleDomeText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "きいたわよ！\n"
	.string "{STR_VAR_2}　で\p"
	.string "{STR_VAR_3}かいも\n"
	.string "ゆうしょう　したんですって？\p"
	.string "すごいわねえ　かんしん　しちゃうわ！\n"
	.string "じゃあ　またね$"

MatchCall_BattlePikeText1::
	.string "あ！　{PLAYER}？\n"
	.string "こんにちは　{STR_VAR_1}　です！\p"
	.string "きいたよ！\n"
	.string "{STR_VAR_2}　で\p"
	.string "{STR_VAR_3}も　へやを\n"
	.string "とっぱ　したんだって？\p"
	.string "すごいなあ\n"
	.string "じゃあ　またね$"

MatchCall_BattlePikeText2::
	.string "こんにちは　{STR_VAR_1}　でーす！\n"
	.string "きいたわよ！\p"
	.string "{STR_VAR_2}　で{STR_VAR_3}へやも\n"
	.string "かちぬいたんですって？\p"
	.string "わたしも　がんばらなきゃ！\n"
	.string "じゃあ　またね$"

MatchCall_BattlePikeText3::
	.string "よう　{PLAYER}！\n"
	.string "{STR_VAR_1}だぞ　げんきかー？\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}へやも\n"
	.string "とっぱ　したって　きいたぞ\p"
	.string "つぎも　がんばれよなー\n"
	.string "じゃあ　またな$"

MatchCall_BattlePikeText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}へやも\n"
	.string "とっぱ　した　らしいね\p"
	.string "おれも　まけないように\n"
	.string "ポケモン　そだてなきゃな$"

MatchCall_BattlePikeText5::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "きいたよ　{STR_VAR_2}で\n"
	.string "{STR_VAR_3}へやも　とっぱ　したんだって？\p"
	.string "ぼくも　がんばらなきゃ\n"
	.string "じゃあ　またね$"

MatchCall_BattlePikeText6::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "こんにちは　{STR_VAR_1}　だ\p"
	.string "そういえば　きみ\n"
	.string "{STR_VAR_2}で　{STR_VAR_3}へやも\l"
	.string "とっぱ　したんだってね\p"
	.string "おれも　まけないように\n"
	.string "ポケモンを　そだてなきゃな$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}？\n"
	.string "ああ　{STR_VAR_1}　だけど\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}へやも\n"
	.string "とっぱ　したんだって？\p"
	.string "すごいねえ\n"
	.string "あ　めずらしいポケモンを　みつけたから\p"
	.string "じゃあ　また$"

MatchCall_BattlePikeText8::
	.string "こんにちは　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　です\p"
	.string "げんき　ですか？\n"
	.string "{STR_VAR_2}で　{STR_VAR_3}へやも\l"
	.string "とっぱ　したんですって？\p"
	.string "すごいですね！\n"
	.string "わたしも　がんばって\p"
	.string "ポケモン　そだてないと！\n"
	.string "じゃあ　またね$"

MatchCall_BattlePikeText9::
	.string "あら　{PLAYER}{KUN}！\n"
	.string "こんにちは　{STR_VAR_1}です！\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}へやも\n"
	.string "とっぱ　したんだって？\p"
	.string "すっごいねー\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattlePikeText10::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}へやも　とっぱ　したんですって？\p"
	.string "すごいわねえ\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattlePikeText11::
	.string "やあやあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だ\p"
	.string "{STR_VAR_2}で\n"
	.string "だいかつやく　らしいなあ\l"
	.string "{STR_VAR_3}へやも　とっぱ　したんだって？\p"
	.string "すげえなあ　おれでも\n"
	.string "ゆうしょう　できるのかな\p"
	.string "···　むりかなあ？\n"
	.string "じゃあ　またな$"

MatchCall_BattlePikeText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}　とかいう　ところで\n"
	.string "{STR_VAR_3}へや　とっぱ　したとな？\p"
	.string "すごい　はなし　だのう\n"
	.string "では　またの$"

MatchCall_BattlePikeText13::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}へやも　とっぱした　とな？\p"
	.string "げんきで　いいことじゃ\n"
	.string "では　またのう$"

MatchCall_BattlePikeText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "きいたわよ！\n"
	.string "{STR_VAR_2}で\p"
	.string "{STR_VAR_3}へやも\n"
	.string "とっぱ　したんですって？\p"
	.string "すごいわねえ　かんしん　しちゃうわ！\n"
	.string "じゃあ　またね$"

MatchCall_BattlePyramidText1::
	.string "あ！　{PLAYER}？\n"
	.string "こんにちは　{STR_VAR_1}　です！\p"
	.string "きいたよ！\n"
	.string "{STR_VAR_2}　で\p"
	.string "{STR_VAR_3}だん　も\n"
	.string "のぼったんだって？\p"
	.string "すごいねー　ぼくも　こんど\n"
	.string "ちょうせん　してみようかなー$"

MatchCall_BattlePyramidText2::
	.string "こんにちは　{STR_VAR_1}　でーす！\n"
	.string "きいたわよ！\p"
	.string "{STR_VAR_2}　で\n"
	.string "{STR_VAR_3}だん　も\l"
	.string "かちぬいたんですって？\p"
	.string "すごーい！　わたしの　ポケモンも\n"
	.string "がんばって　そだてなくちゃ$"

MatchCall_BattlePyramidText3::
	.string "よう　{PLAYER}！\n"
	.string "{STR_VAR_1}だぞ　げんきかー？\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}だんも\n"
	.string "のぼったって　きいたぞ\p"
	.string "つぎも　がんばれよなー\n"
	.string "じゃあ　またな$"

MatchCall_BattlePyramidText4::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　だ\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}だんも\n"
	.string "のぼった　らしいね\p"
	.string "ぼくも　きみに　まけないように\n"
	.string "がんばらなきゃな$"

MatchCall_BattlePyramidText5::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　だよ\p"
	.string "きいたよ　{STR_VAR_2}　で\n"
	.string "{STR_VAR_3}だんも　のぼったんだって？\p"
	.string "ぼくも　がんばらなきゃ\n"
	.string "じゃあ　またね$"

MatchCall_BattlePyramidText6::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "こんにちは　{STR_VAR_1}　だ\p"
	.string "そういえば　きみ\n"
	.string "{STR_VAR_2}で　{STR_VAR_3}だんも\l"
	.string "かちぬいたんだってね\p"
	.string "おれも　まけないように\n"
	.string "ポケモンを　そだてなきゃな$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}？\n"
	.string "ああ　{STR_VAR_1}　だけど\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}だんも\n"
	.string "のぼったんだって？\p"
	.string "へー⋯⋯　そこに\n"
	.string "めずらしい　ポケモン　いなかった？\p"
	.string "そうかー　いないかー\n"
	.string "じゃあ　また$"

MatchCall_BattlePyramidText8::
	.string "こんにちは　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　です\p"
	.string "げんき　ですか？\n"
	.string "{STR_VAR_2}で　{STR_VAR_3}だんも\l"
	.string "かちぬいたんですって？\p"
	.string "すごいですね！\n"
	.string "わたしも　がんばって\p"
	.string "ポケモン　そだてないと！\n"
	.string "じゃあ　またね$"

MatchCall_BattlePyramidText9::
	.string "あら　{PLAYER}{KUN}！\n"
	.string "こんにちは　{STR_VAR_1}です！\p"
	.string "{STR_VAR_2}で　{STR_VAR_3}だんも\n"
	.string "かちぬいたんだって？\p"
	.string "すっごいねー\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattlePyramidText10::
	.string "{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　です\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}だんも　のぼったんですって？\p"
	.string "すごいわねえ\n"
	.string "わたしも　がんばらなくちゃ$"

MatchCall_BattlePyramidText11::
	.string "やあやあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}だ\p"
	.string "{STR_VAR_2}で\n"
	.string "だいかつやく　らしいなあ\l"
	.string "{STR_VAR_3}だんも　のぼったんだって？\p"
	.string "すげえなあ　おれでも\n"
	.string "ゆうしょう　できるのかな\p"
	.string "···　できない？\n"
	.string "じゃあ　またな$"

MatchCall_BattlePyramidText12::
	.string "やあ　{PLAYER}{KUN}\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}　とかいう　ところで\n"
	.string "{STR_VAR_3}だんも　かちぬいたとな？\p"
	.string "すごい　はなし　だのう\n"
	.string "では　またの$"

MatchCall_BattlePyramidText13::
	.string "{PLAYER}{KUN}　かい？\n"
	.string "{STR_VAR_1}　じゃが　げんきかの？\p"
	.string "{STR_VAR_2}で\n"
	.string "{STR_VAR_3}だんも　のぼったとな？\p"
	.string "げんきで　いいことじゃ\n"
	.string "では　またのう$"

MatchCall_BattlePyramidText14::
	.string "あら　{PLAYER}{KUN}　こんにちは\n"
	.string "{STR_VAR_1}　よ\p"
	.string "きいたわよ！\n"
	.string "{STR_VAR_2}で\p"
	.string "{STR_VAR_3}だんも\n"
	.string "かちぬいたんですって？\p"
	.string "すごいわねえ　かんしん　しちゃうわ！\n"
	.string "じゃあ　またね$"

MatchCall_Text_Mom1::
	.string "ママ“パパも　あなたも\n"
	.string "みんな　ポケモンに　むちゅう　なのね\p"
	.string "ポケモンの　みりょく　って\n"
	.string "なんなの　かしら⋯⋯\p"
	.string "わたし？\n"
	.string "わたしは　いえの　ようじを　おてつだい\l"
	.string "してくれる　ポケモンが　すきだわ$"

MatchCall_Text_Mom2::
	.string "ママ“あら　{PLAYER}\n"
	.string "パパなら　まいにち　トウカシティの\l"
	.string "ジムに　こもってるわよ！\p"
	.string "ときどき　うちに　かえってきては\n"
	.string "たくさん　ごはんを　たべて\l"
	.string "また　でかけて　いくの！\p"
	.string "あなたに　まけたのが\n"
	.string "よっぽど　くやしかった　みたいね！$"

MatchCall_Text_Mom3::
	.string "ママ“{PLAYER}⋯⋯\p"
	.string "おうちの　ことなら　きにしなくて　いいから\n"
	.string "ママが　あげた　ランニングシューズ\l"
	.string "ボロボロに　なるまで　はいてちょうだいね！$"

MatchCall_Text_Roxanne_Preparing::
	.string "ツツジ“あら　{PLAYER}さん！\p"
	.string "あれから　また　トレーニングを\n"
	.string "やりなおして　いるところ　なんですよ！\p"
	.string "また　ジムを　さいかい　するためには\n"
	.string "もうすこし　じかんが　かかりますが\p"
	.string "もし　ジムを　さいかい　できたら\n"
	.string "ぜひまた　ちょうせん　してくださいね⋯⋯$"

MatchCall_Text_Roxanne_PreparingPostGame::
	.string "ツツジ“{PLAYER}さん　おめでとう！\n"
	.string "うわさは　ききましたよ！\p"
	.string "こちらは　ジムを　さいかい　するためには\n"
	.string "もうすこし　じかんが　かかりますが\p"
	.string "もし　ジムを　さいかい　できたら\n"
	.string "ぜひまた　ちょうせん　してくださいね⋯⋯$"

MatchCall_Text_Roxanne_RematchReady::
	.string "ツツジ“{PLAYER}さん！\n"
	.string "ジムの　じゅんびが　できました！\p"
	.string "いつでも　カナズミ　シティまで\n"
	.string "きてくださいな！$"

MatchCall_Text_Roxanne_PostRematch::
	.string "ツツジ“{PLAYER}さんと\n"
	.string "しょうぶ　できたことは\l"
	.string "カナズミ　ジムの　ほこりですよ！$"

MatchCall_Text_Brawly_Preparing::
	.string "トウキ“やあ　{PLAYER}{KUN}！\p"
	.string "キミとの　しょうぶでは　いろんなことを\n"
	.string "まなばせて　もらったよ！\p"
	.string "また　しゅぎょう　しなおして\n"
	.string "ジムを　さいかいする　つもりさ！\p"
	.string "ジムの　じゅんびが　できるまでは\n"
	.string "まだ　じかんが　かかりそう　だけど\p"
	.string "もし　ジムを　さいかい　できたら\n"
	.string "ぜひまた　ちょうせん　してくれよ⋯⋯$"

MatchCall_Text_Brawly_PreparingPostGame::
	.string "トウキ“{PLAYER}{KUN}　おめでとう！\p"
	.string "キミの　うわさは　しおかぜに　のって\n"
	.string "このまちにも　とどいて　いるよ！\p"
	.string "ボクのほうは　まだまだ　しゅぎょうを\n"
	.string "やりなおす　ひつようが　ありそうだ\p"
	.string "ジムの　じゅんびが　できるまでは\n"
	.string "まだ　じかんが　かかりそう　だけど\p"
	.string "もし　ジムを　さいかい　できたら\n"
	.string "ぜひまた　ちょうせん　してくれよ⋯⋯$"

MatchCall_Text_Brawly_RematchReady::
	.string "トウキ“{PLAYER}{KUN}！\n"
	.string "ジムの　じゅんびが　できたよ！\p"
	.string "いつでも　ムロ　タウンまで\n"
	.string "ちょうせんしに　きてくれよな！$"

MatchCall_Text_Brawly_PostRematch::
	.string "トウキ“{PLAYER}{KUN}　とは\n"
	.string "なんど　しょうぶ　しても　あきないよ！$"

MatchCall_Text_Wattson_Preparing::
	.string "テッセン“おう　おまえさんか！\p"
	.string "わしは　あれから　また　トレーニングを\n"
	.string "やりなおして　いるところ　じゃよ！\p"
	.string "わしの　ジムを　さいかいするには\n"
	.string "まだ　ちーと　じかんが　かかりそうじゃな！\p"
	.string "それまで　まっていて　おくれ！\n"
	.string "わっはははは！$"

MatchCall_Text_Wattson_PreparingPostGame::
	.string "テッセン“わっははは！\p"
	.string "おまえさん　とうとう　やったな！\n"
	.string "うわさは　わしの　みみにも　とどいとる！\p"
	.string "こちらは　まだまだ　しゅぎょうを\n"
	.string "やりなおす　ひつようが　ありそうじゃ\p"
	.string "わしの　ジムを　さいかいするには\n"
	.string "まだ　ちーと　じかんが　かかりそうじゃな！\p"
	.string "それまで　まっていて　おくれ！\n"
	.string "わっはははは！$"

MatchCall_Text_Wattson_RematchReady::
	.string "テッセン“おう　おまえさんか！\n"
	.string "ジムの　じゅんびが　できたぞい！\p"
	.string "いつでも　キンセツ　シティまで\n"
	.string "くるがいいぞ！　わっははは！$"

MatchCall_Text_Wattson_PostRematch::
	.string "テッセン“わっははは！\p"
	.string "おまえさんとの　ポケモン　しょうぶは\n"
	.string "ビリビリと　しげきてきじゃな！$"

MatchCall_Text_Flannery_Preparing::
	.string "アスナ“{PLAYER}さん⋯⋯\p"
	.string "あなたとの　しょうぶで　じぶんの\n"
	.string "みじゅくさを　おもいしらされた　けど\l"
	.string "わたしは　これで　おわったり　しないよ！\p"
	.string "もういちど　しゅぎょうを　しなおして\n"
	.string "また　ジムを　さいかい　するんだ！\p"
	.string "そのときには　{PLAYER}さん\n"
	.string "ぜったい　ちょうせんしに　きてよね！$"

MatchCall_Text_Flannery_PreparingPostGame::
	.string "アスナ“{PLAYER}さん　おめでとう！\p"
	.string "あなたの　うわさは　かざんの　ねつのように\n"
	.string "わたしにも　つたわって　きてるよ！\p"
	.string "こちらも　じゅんちょうに\n"
	.string "トレーニングが　すすんでるんだ！\p"
	.string "ジムの　じゅんびが　できたら\n"
	.string "エントリーコールの　なまえの　ところに\l"
	.string "しるしが　つくからね！$"

MatchCall_Text_Flannery_RematchReady::
	.string "アスナ“あっ　{PLAYER}さん？\n"
	.string "ジムの　じゅんびは　もうできてます！\p"
	.string "おんせんに　はいる　ついでに\n"
	.string "フエン　タウンまで　きてくださいね！$"

MatchCall_Text_Flannery_PostRematch::
	.string "アスナ“{PLAYER}さん⋯⋯\n"
	.string "ポケモンの　あつかいかたが\l"
	.string "どんどん　うまくなってる　きがするよ！$"

MatchCall_Text_Winona_Preparing::
	.string "ナギ“こんにちは　{PLAYER}さん！\p"
	.string "あなたと　しょうぶを　したおかげで\n"
	.string "じぶんの　じゃくてんが　よくわかったわ！\p"
	.string "いつか　また　ジムを　さいかい　できたら\n"
	.string "そのときは　もう　まけませんよ！$"

MatchCall_Text_Winona_PreparingPostGame::
	.string "ナギ“やりましたね　{PLAYER}さん！\p"
	.string "しんチャンピオン　たんじょうの　うわさは\n"
	.string "ヒワマキにも　とどいて　いますよ！\p"
	.string "でも⋯⋯　つぎに　しょうぶ　するときは\n"
	.string "このまえの　ようには　いきませんからね！$"

MatchCall_Text_Winona_RematchReady::
	.string "ナギ“ええと　{PLAYER}さん？\n"
	.string "ジムの　じゅんびが　できましたよ！\p"
	.string "ヒワマキ　タウンで　まってます！$"

MatchCall_Text_Winona_PostRematch::
	.string "ナギ“{PLAYER}さん⋯⋯\n"
	.string "しょうぶに　まけても　わたしの　つばさは\l"
	.string "けっして　おれることは　ないのです！\p"
	.string "そう　{PLAYER}さんが\n"
	.string "ゆめを　あきらめなかった　ように！$"

MatchCall_Text_TateLiza_Preparing::
	.string "フウ“あっ　あなたは\n"
	.string "ラン“{PLAYER}さん　ですね！\p"
	.string "フウ“ぼくたち　ジムを　さいかい　するため\n"
	.string "ラン“しゅぎょう　しなおして　いるんです！\p"
	.string "フウ“ジムの　じゅんびが　できたら\n"
	.string "ラン“ジムの　じゅんびが　できたら\p"
	.string "フウ“エントリーコールの　なまえに\n"
	.string "ラン“しるしが　つくので　わかるんです！$"

MatchCall_Text_TateLiza_PreparingPostGame::
	.string "フウ“{PLAYER}さん　おめでとう！\n"
	.string "ラン“{PLAYER}さん　おめでとう！\p"
	.string "フウ“ぼくたち　ふたりは\n"
	.string "ラン“まだ　しゅぎょうちゅう！\p"
	.string "フウ“もうすこし　じかんが　かかるけど\n"
	.string "ラン“もし　ジムを　さいかい　できたら\p"
	.string "フウ“エントリーコールの　なまえに\n"
	.string "ラン“しるしが　つくから　わかりますよ！$"

MatchCall_Text_TateLiza_RematchReady::
	.string "フウ“{PLAYER}さん！\n"
	.string "ラン“{PLAYER}さん！\p"
	.string "フウ“ジムの　じゅんびが　できました！\n"
	.string "ラン“ジムの　じゅんびが　できました！\p"
	.string "フウ“いつでも　トクサネ　シティまで\n"
	.string "ラン“きてくださいね！$"

MatchCall_Text_TateLiza_PostRematch::
	.string "フウ“{PLAYER}さんとの　しょうぶは\n"
	.string "ラン“わたしたちの　だいじな　けいけん\p"
	.string "フウ“いつか　また　3にんで\n"
	.string "ラン“しょうぶが　できると　いいですね$"

MatchCall_Text_Juan_Preparing::
	.string "アダン“ほ⋯⋯\n"
	.string "{PLAYER}{KUN}⋯⋯　でしたね\p"
	.string "ユーとの　たたかいは\n"
	.string "はじめて　ミクリと　であったときを\l"
	.string "おもいださせて　くれましたよ\p"
	.string "もしかすると　ユーは\n"
	.string "ミクリを　こえるほどの　ジーニアス！\l"
	.string "すなわち　てんさい　かもしれません$"

MatchCall_Text_Juan_PreparingPostGame::
	.string "アダン“ふ⋯⋯　{PLAYER}{KUN}\n"
	.string "ついに　やりとげた　ようですね\p"
	.string "やはり　わたくしの　ひとを　みるめは\n"
	.string "まちがって　いなかった⋯⋯\p"
	.string "つよさを　きわめた　ユーとは\n"
	.string "ぜひ　また　しょうぶ　したい　ものです$"

MatchCall_Text_Juan_RematchReady::
	.string "アダン“ほっほ⋯⋯　{PLAYER}{KUN}\p"
	.string "わが　ルネシティ　ジムが\n"
	.string "ふたたび　オープン　したのですよ\p"
	.string "わたくしの　すがたを　みたくなったら\n"
	.string "まあ　いつでも　おいでなさい$"

MatchCall_Text_Juan_PostRematch::
	.string "アダン“{PLAYER}{KUN}⋯⋯\p"
	.string "ユーと　かなでる　ポケモン　しょうぶは\n"
	.string "せんれんされた　おんがくにも　にて\l"
	.string "ハートに　ふかく　ひびいて　きます⋯⋯\p"
	.string "めを　とじれば　メロディーに　あわせて\n"
	.string "ゆうがに　まう　ユーの　すがたが⋯⋯$"

MatchCall_Text_Sidney::
	.string "カゲツ“よお　{PLAYER}！\p"
	.string "おれと　ポケモン　しょうぶ　したけりゃ\n"
	.string "いつでも　ポケモン　リーグに　おいで！\p"
	.string "おれは　いつでも　ここに　いるからな\n"
	.string "じゃあ　まってるぜ！$"

MatchCall_Text_Phoebe::
	.string "フヨウ“ハーイ　{PLAYER}！\p"
	.string "あなたと　ポケモンの　きずなが\n"
	.string "どれぐらい　ふかく　なったか\l"
	.string "たまには　ここまで　みせに　きてよね！$"

MatchCall_Text_Glacia::
	.string "プリム“こんにちは　{PLAYER}\p"
	.string "あなたは　その　つよさに\n"
	.string "おぼれたり　していない　でしょうね\p"
	.string "あつい　きもちを　すこしだけ\n"
	.string "ひやしたいと　おもったら\l"
	.string "ポケモン　リーグに　いらっしゃい⋯⋯$"

MatchCall_Text_Drake::
	.string "ゲンジ“そのこえは　{PLAYER}か\n"
	.string "げんきそう　だな⋯⋯\p"
	.string "さいきん　ポケモン　リーグとは　べつに\n"
	.string "トレーナーの　うでを　きそわせる\l"
	.string "バトル　フロンティア　とかいう　しせつが\l"
	.string "あるらしいが⋯⋯\p"
	.string "ほんとうの　しょうぶを　したいのなら\n"
	.string "やはり　ポケモン　リーグだ！\p"
	.string "なあ　{PLAYER}も　そうおもう　だろう？$"

MatchCall_Text_Wallace::
	.string "ミクリ“やあ　{PLAYER}{KUN}\n"
	.string "きみは　ダイゴには　あったかな？\p"
	.string "かれって⋯⋯\n"
	.string "ほんとうは　ものすごく　つよいのに\p"
	.string "あまり　ポケモン　しょうぶを　しないで\n"
	.string "めずらしい　いしを　さがして　ばかりいる\l"
	.string "かわりもの　なんだよ\p"
	.string "どこかの　どうくつか　いわやまに\n"
	.string "もぐってるんじゃ　ないかな\p"
	.string "めずらしい　いし　なんて\n"
	.string "わたしには　いんせき　ぐらいしか\l"
	.string "おもい　うかばないんだけど⋯⋯$"

MatchCall_Text_MayRayquazaCall:
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯　ピッ！\p"
	.string "ハルカ“あっ　{PLAYER}{KUN}！？\p"
	.string "あたしね　さっきまで　キナギ　タウンに\n"
	.string "いってたんだけど\l"
	.string "おおきな　みどりいろの　ポケモンが\l"
	.string "そらを　とんで　いくのを　みたの！\p"
	.string "あたし⋯⋯\n"
	.string "あんな　ポケモン　みたこと　ない！\p"
	.string "なんだろう　もしかしたら　これって\n"
	.string "だいはっけん！？\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯　ツー$"

MatchCall_Text_BrendanRayquazaCall:
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯　ピッ！\p"
	.string "ユウキ“おっ　{PLAYER}！？\p"
	.string "オレ　さっきまで　キナギ　タウンに\n"
	.string "いってたんだけどさ\l"
	.string "でっかい　みどりいろの　ポケモンが\l"
	.string "そらを　とんで　いくのを　みたんだ！\p"
	.string "あんな　すごいの　みたこと　ないよ\n"
	.string "{PLAYER}にも　みせたかったなあ！\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯　ツー$"

MatchCall_Text_May1::
	.string "ハルカ“あっ　{PLAYER}{KUN}！\p"
	.string "ハギろうじんは\n"
	.string "ふなのりを　いんたい　したけど\p"
	.string "ときどき　ピーコちゃんと　いっしょに\n"
	.string "うみに　でてるのを　みかけるよ\p"
	.string "きっと　いまも　うみが　すきなんだね！$"

MatchCall_Text_May2::
	.string "ハルカ“ねえねえ　{PLAYER}{KUN}！\p"
	.string "トウカや　ムロみたいな\n"
	.string "ちいさい　まちに　ジムが　あるのに\p"
	.string "おおきな　みなとまちの　カイナには\n"
	.string "なぜか　ジムが　ないのよね\p"
	.string "いつか　ジムが　できたら　あたし\n"
	.string "ジムリーダーに　りっこうほ　しよっかなー$"

MatchCall_Text_May3::
	.string "ハルカ“あっ　{PLAYER}{KUN}！\p"
	.string "そういえば　カナズミシティに\n"
	.string "いあいぎりオヤジ　っていう　ひとの\l"
	.string "いえが　あったでしょ？\p"
	.string "キンセツシティには\n"
	.string "その　おとうとが　すんでるんだって！\p"
	.string "どんな　なまえだと　おもう？\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\p"
	.string "いわくだきオヤジ　っていうの！$"

MatchCall_Text_May4::
	.string "ハルカ“{PLAYER}{KUN}？\p"
	.string "カナシダトンネル　って\n"
	.string "カナズミと　シダケを　むすぶから\l"
	.string "カナシダトンネル　って　いうのよね！$"

MatchCall_Text_May5::
	.string "ハルカ“{PLAYER}{KUN}　げんきー？\p"
	.string "あたしは　いま\n"
	.string "111ばんどうろに　きているの！\p"
	.string "さばくの　うえのほうに　すんでる\n"
	.string "おばあさんの　ところで\l"
	.string "ひとやすみ　していく　つもりよ！$"

MatchCall_Text_May6::
	.string "ハルカ“あっ　{PLAYER}{KUN}！\p"
	.string "さばくに　げんえいのとう　っていうのが\n"
	.string "たってるの　しってる？\p"
	.string "しんきろう　みたいに\n"
	.string "みえたり　みえなかったり　するんだって！\p"
	.string "あたしも　みてみたいなー$"

MatchCall_Text_May7::
	.string "ハルカ“{PLAYER}{KUN}　やっほー！\p"
	.string "あたしは　いま\n"
	.string "119ばんどうろに　きているの！\p"
	.string "このあたりは　おおきな　かわが　あるし\n"
	.string "あめも　しょっちゅう　ふってるから\l"
	.string "ずぶぬれに　なっちゃったよ！$"

MatchCall_Text_May8::
	.string "ハルカ“{PLAYER}{KUN}！\p"
	.string "おくりびやまには　じゅみょうを　おえた\n"
	.string "ポケモンが　まつられてるの！\p"
	.string "そのせいか　しゅつげんする　ポケモンも\n"
	.string "ゴーストタイプが　おおいのよ！$"

MatchCall_Text_May9::
	.string "ハルカ“ねえねえ　{PLAYER}{KUN}！\p"
	.string "あたし　また　フエンタウンの\n"
	.string "おんせんに　いこうと　おもったんだけど\p"
	.string "デコボコさんどうに\n"
	.string "にんそうの　わるいのが　うろついていて\l"
	.string "なんか　いやーな　かんじ　だったわ！$"

MatchCall_Text_May10::
	.string "ハルカ“あっ　{PLAYER}{KUN}！\p"
	.string "クスノキかんちょうが　せんすいていで\n"
	.string "かいていどうくつを　はっけんした　って\l"
	.string "ニュースで　やってたけど　みた？$"

MatchCall_Text_May11::
	.string "ハルカ“ねえねえ　{PLAYER}{KUN}！\p"
	.string "ふねが　なくても　ポケモンの　わざで\n"
	.string "うみのうえを　わたって　いけるって\l"
	.string "すごいよね！\p"
	.string "でも　それだけじゃなくて\n"
	.string "ポケモンと　いっしょに　うみのそこに\l"
	.string "もぐれちゃう　わざも　あるんだって！$"

MatchCall_Text_May12::
	.string "ハルカ“{PLAYER}{KUN}　おつかれ！\p"
	.string "うみのうえで　みえてるのに　むこうがわへ\n"
	.string "いけない　ところ　なんかは\p"
	.string "どこかから　いったん　もぐって\n"
	.string "かいていの　みちを　とおりぬけて\l"
	.string "むこうの　すいめんに　でれば　いいの！$"

MatchCall_Text_May13::
	.string "ハルカ“はーい　{PLAYER}{KUN}\p"
	.string "どう？　ずかんは　じゅんちょうに\n"
	.string "うまっていってる？\p"
	.string "あのね　うわさで　きいたんだけど\n"
	.string "どこかに　ちょうこだいポケモン　というのが\l"
	.string "3しゅるいも　いるらしいの！\p"
	.string "うーん　1しゅるい　だけでも　いいから\n"
	.string "みてみたいなあ⋯⋯$"

MatchCall_Text_May14::
	.string "ハルカ“{PLAYER}{KUN}！\n"
	.string "うわさは　きいたよ！\p"
	.string "ルネの　ジムリーダーにも　かったって？\n"
	.string "ということは　もうひといき　だね！$"

MatchCall_Text_May15::
	.string "ハルカ“もう　ホウエンちほうで\n"
	.string "{PLAYER}{KUN}を　しらない\l"
	.string "トレーナー　なんて　いないんだよ！\p"
	.string "あたしが　{PLAYER}{KUN}と\n"
	.string "ともだちだ　っていうと\l"
	.string "みんな　ビックリ　するんだから！$"

MatchCall_Text_Brendan1::
	.string "ユウキ“おっ　{PLAYER}！\p"
	.string "ハギろうじんは\n"
	.string "ふなのりを　いんたい　したけど\p"
	.string "ときどき　ピーコちゃんと　いっしょに\n"
	.string "うみに　でてるのを　みかけるんだ\p"
	.string "きっと　いまも　うみが　すきなんだろうな！$"

MatchCall_Text_Brendan2::
	.string "ユウキ“やあ　{PLAYER}！\p"
	.string "トウカや　ムロみたいな\n"
	.string "ちいさい　まちに　ジムが　あるのに\p"
	.string "おおきな　みなとまちの　カイナには\n"
	.string "なぜか　ジムが　ないんだよな\p"
	.string "いつか　ジムが　できたら　オレ\n"
	.string "ジムリーダーに　りっこうほ　しようかな$"

MatchCall_Text_Brendan3::
	.string "ユウキ“おっ　{PLAYER}！\p"
	.string "そういえば　カナズミシティに\n"
	.string "いあいぎりオヤジ　っていう　ひとの\l"
	.string "いえが　あっただろう？\p"
	.string "キンセツシティには\n"
	.string "その　おとうとが　すんでるんだって！\p"
	.string "どんな　なまえだと　おもう？\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\p"
	.string "いわくだきオヤジ　だってさ！$"

MatchCall_Text_Brendan4::
	.string "ユウキ“そのこえは　{PLAYER}？\p"
	.string "カナシダトンネル　って\n"
	.string "カナズミと　シダケを　むすぶから\l"
	.string "カナシダトンネル　なんだよ\p"
	.string "おまえ⋯⋯　しってたか？$"

MatchCall_Text_Brendan5::
	.string "ユウキ“{PLAYER}　げんきか？\p"
	.string "オレは　いま\n"
	.string "111ばんどうろに　きてるんだ！\p"
	.string "さばくの　うえのほうに　すんでる\n"
	.string "ばあさんの　ところで\l"
	.string "ひとやすみ　していく　つもりさ！\p"
	.string "ちかくまで　きたら\n"
	.string "おまえも　よっていくと　いいよ！$"

MatchCall_Text_Brendan6::
	.string "ユウキ“あっ　{PLAYER}！\p"
	.string "さばくに　げんえいのとう　っていうのが\n"
	.string "たってるの　しってるか？\p"
	.string "しんきろう　みたいに\n"
	.string "みえたり　みえなかったり　するんだよ！\p"
	.string "オレも　みてみたいなー$"

MatchCall_Text_Brendan7::
	.string "ユウキ“だれ？　{PLAYER}か？\p"
	.string "オレは　いま\n"
	.string "119ばんどうろに　きてるんだ！\p"
	.string "このへんは　でっかい　かわが　あるし\n"
	.string "いっつも　あめが　ふってるから\l"
	.string "ずぶぬれに　なっちまったよ！$"

MatchCall_Text_Brendan8::
	.string "ユウキ“{PLAYER}！\p"
	.string "おくりびやまには　じゅみょうを　おえた\n"
	.string "ポケモンが　まつられてるんだ！\p"
	.string "そのせいか　しゅつげんする　ポケモンも\n"
	.string "ゴーストタイプが　おおいんだよな！$"

MatchCall_Text_Brendan9::
	.string "ユウキ“なあなあ　{PLAYER}！\p"
	.string "オレ　また　フエンタウンの\n"
	.string "おんせんに　いこうと　おもったんだけど\p"
	.string "デコボコさんどうの　とちゅうに\n"
	.string "にんそうの　わるいのが　いたんだよ！\p"
	.string "あれって　マグマだん⋯⋯　だよな！？$"

MatchCall_Text_Brendan10::
	.string "ユウキ“おっ　{PLAYER}！\p"
	.string "クスノキかんちょうが　せんすいていで\n"
	.string "かいていどうくつを　はっけんした　って\l"
	.string "ニュースで　やってたけど　みたか？$"

MatchCall_Text_Brendan11::
	.string "ユウキ“なあなあ　{PLAYER}！\p"
	.string "ふねが　なくても　ポケモンの　わざで\n"
	.string "うみのうえを　わたって　いけるって\l"
	.string "なんだか　すごくないか！？\p"
	.string "しかも　ポケモンと　いっしょに\n"
	.string "うみのそこに　もぐれる　わざも　あるって！\p"
	.string "ポケモンって　なんでも　できるんだなー！$"

MatchCall_Text_Brendan12::
	.string "ユウキ“{PLAYER}　おつかれ！\p"
	.string "うみのうえで　みえてるのに　むこうがわへ\n"
	.string "いけない　ところ　なんかは\p"
	.string "どこかから　いったん　もぐって\n"
	.string "かいていの　みちを　とおりぬけて\l"
	.string "むこうの　すいめんに　でれば　いいんだ！$"

MatchCall_Text_Brendan13::
	.string "ユウキ“おーす　{PLAYER}！\p"
	.string "どうだ？　ずかんは　じゅんちょうに\n"
	.string "うまっていってるか？\p"
	.string "あのな　うわさで　きいたんだけど\n"
	.string "どこかに　ちょうこだいポケモン　ってのが\l"
	.string "3しゅるいも　いるらしいんだよ！\p"
	.string "うーん　1しゅるい　だけでも　いいから\n"
	.string "つかまえて　みたいよなあ⋯⋯$"

MatchCall_Text_Brendan14::
	.string "ユウキ“{PLAYER}！\n"
	.string "うわさは　きいたよ！\p"
	.string "ルネの　ジムリーダーにも　かったって？\n"
	.string "すげえなあ　もうひといき　だな！$"

MatchCall_Text_Brendan15::
	.string "ユウキ“もう　ホウエンちほうで\n"
	.string "{PLAYER}のこと　しらない\l"
	.string "トレーナー　なんて　いないんだ！\p"
	.string "オレが　{PLAYER}と\n"
	.string "ともだちだ　っていうと\l"
	.string "みんな　うらやましそうに　するよ！$"

MatchCall_Text_Wally1::
	.string "ミツル“あっ　{PLAYER}さん！\p"
	.string "さいきんは　からだの　ぐあいも\n"
	.string "ずいぶん　よくなって　きたし\p"
	.string "ぼくも　はやく　{PLAYER}さん　みたいな\n"
	.string "トレーナーに　なりたいな！$"

MatchCall_Text_Wally2::
	.string "ミツル“{PLAYER}さん　こんにちは！\p"
	.string "カナシダトンネルが　かいつう　したせいで\n"
	.string "ミチルおねえちゃんも\l"
	.string "すっごく　うれしそう　ですよ！$"

MatchCall_Text_Wally3::
	.string "ミツル“あっ　{PLAYER}さん！\p"
	.string "ぼく⋯⋯　シダケの　おじさんに\n"
	.string "なにも　いわずに　でてきちゃった　けど\l"
	.string "おじさん　おこってないかな⋯⋯\p"
	.string "{PLAYER}さん　なら\n"
	.string "ぼくの　きもち　わかって　くれますよね？$"

MatchCall_Text_Wally4::
	.string "ミツル“{PLAYER}さん？\n"
	.string "ぼくです　ミツルです！\p"
	.string "トレーナーの　せかいって　すごいですね！\n"
	.string "ポケモンを　つれて　あるいていると\l"
	.string "みんなが　こえを　かけて　くれるんです！\p"
	.string "まるで　ポケモンを　つうじて\n"
	.string "みんなが　つながっている　みたいに！$"

MatchCall_Text_Wally5::
	.string "ミツル“{PLAYER}さん？　すごいですよ！\n"
	.string "{PLAYER}さんと　いっしょに　つかまえた\l"
	.string "ラルトスが　しんか　したんです！\p"
	.string "ぼくって　さいのう　あるのかなあ⋯⋯\p"
	.string "なーんて　ちょうしに　のったら\n"
	.string "いけませんよね\p"
	.string "えらいのは　ポケモン　ですもん！$"

MatchCall_Text_Wally6::
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\p"
	.string "ミツルは　ポケナビの　よびだしが\n"
	.string "とどかない　ところに　いるようだ⋯⋯$"

MatchCall_Text_Wally7::
	.string "ミツル“あっ　{PLAYER}さん！\p"
	.string "いままで　ほとんど　いえから\n"
	.string "でたことの　ない　ぼくが\p"
	.string "こうして　ポケモンと　いっしょに\n"
	.string "ぼうけんを　している　なんて⋯⋯\p"
	.string "{PLAYER}さん⋯⋯　ありがとう$"

MatchCall_Text_Scott1::
	.string "エニシダ“どーも　どーも　{PLAYER}{KUN}\p"
	.string "やまでも　うみでも　くさむらでも\n"
	.string "どこにだって　ポケモンが　いるように\l"
	.string "トレーナーさん　というのも\l"
	.string "いろんな　ところに　いるもんだねえ\p"
	.string "おかげで　わたしも\n"
	.string "アッチいったり　コッチいったり\l"
	.string "いそがしくて　しょうがないよ！$"

MatchCall_Text_Scott2::
	.string "エニシダ“わたしは　いま\n"
	.string "119ばん　どうろに　きてるんだけど\l"
	.string "たくさんの　トレーナーが　いるねえ！\p"
	.string "でも　このあたりは　せのたかい　くさが\n"
	.string "いっぱい　はえてるから\p"
	.string "はんズボンで　あるきまわると\n"
	.string "あしが　くすぐったくて　こまるよ！$"

MatchCall_Text_Scott3::
	.string "エニシダ“やあやあ　{PLAYER}{KUN}！\p"
	.string "きみは　おくりびやま　って\n"
	.string "のぼったこと　ある？\p"
	.string "あそこは　ポケモンの　たましいが\n"
	.string "まつられている　ばしょ　だからねえ\p"
	.string "トレーナー　ならば　いちど　ぐらいは\n"
	.string "てっぺんまで　のぼって　みないとね！$"

MatchCall_Text_Scott4::
	.string "エニシダ“んー　{PLAYER}{KUN}！\p"
	.string "どうも　ちかごろは\n"
	.string "マグマだん　とか　アクアだん　とか\l"
	.string "おかしな　れんちゅうが　あばれてるね\p"
	.string "かれらの　なかには\n"
	.string "すぐれた　トレーナーも　いるんだろうけど\l"
	.string "でも　わるもの　じゃあなあ⋯⋯$"

MatchCall_Text_Scott5::
	.string "エニシダ“おおー　{PLAYER}{KUN}\p"
	.string "あのね　うみのそこにも　すごうでの\n"
	.string "トレーナーが　いたり　するのかな？\p"
	.string "でも　たしかめに　いこうにも\n"
	.string "わたしは　およげないし\l"
	.string "ポケモンも　もってないし⋯⋯$"

MatchCall_Text_Scott6::
	.string "エニシダ“やあやあ　{PLAYER}{KUN}！\p"
	.string "ぜんぶの　ジムバッジを　あつめたら\n"
	.string "ポケモンリーグに　ちょうせん　できる\l"
	.string "というのは　しってるよね？\p"
	.string "きみほどの　じつりょくが　あるなら\n"
	.string "チャンピオンも　ゆめじゃない　けど⋯⋯\l"
	.string "じつは　もっと　いいところが　あるんだよ\p"
	.string "まあ　いまは　それいじょう\n"
	.string "いわないで　おくよ\p"
	.string "ポケモンリーグを　かちぬいて\n"
	.string "でんどういり　してからの　おたのしみだね！$"

MatchCall_Text_Scott7::
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\p"
	.string "エニシダは　ポケナビの　よびだしが\n"
	.string "とどかない　ところに　いるようだ⋯⋯$"

MatchCall_Text_Norman1::
	.string "パパ“カナズミの　まちには\n"
	.string "いあいぎりおやじ　という\l"
	.string "かわった　なまえの　ひとが　すんでいる！\p"
	.string "ちかくまで　いったら\n"
	.string "おまえも　たずねて　みると　いいぞ！$"

MatchCall_Text_Norman2::
	.string "パパ“ふむ⋯⋯　{PLAYER}は\n"
	.string "すこしずつ　しかし　かくじつに\l"
	.string "つよく　なっているな\p"
	.string "おまえが　つよくなれば　なるほど\n"
	.string "わたしや　ママの　もとから\l"
	.string "とおくへ　はなれて　いってしまう⋯⋯\p"
	.string "なんとも　ふくざつな　きぶんだよ$"

MatchCall_Text_Norman3::
	.string "パパ“そうか⋯⋯\n"
	.string "ジムバッジを　4つ　あつめたのか\p"
	.string "では　やくそく　どおり\n"
	.string "ポケモンしょうぶ　だな⋯⋯\p"
	.string "いつでも　おいで　まってるぞ！$"

MatchCall_Text_Norman4::
	.string "パパ“{PLAYER}！　たまには　ママにも\n"
	.string "あいに　いって　あげるんだぞ！\p"
	.string "わたしは　ここで\n"
	.string "じぶんを　きたえなおす！\p"
	.string "ポケモンしょうぶの　みちは\n"
	.string "おくが　ふかい　からな！$"

MatchCall_Text_Norman5::
	.string "パパ“おお　{PLAYER}！\p"
	.string "なになに？　マグマのしるし⋯⋯？\n"
	.string "なんのことか　わたしには　わからないが\p"
	.string "マグマと　いうぐらい　だから\n"
	.string "なにか　かざんと　かんけい　ありそうだな！$"

MatchCall_Text_Norman_Preparing::
	.string "パパ“せや！　うりゃ！　どりゃー！\p"
	.string "⋯⋯お　{PLAYER}か！\p"
	.string "わたしは　いま　ポケモンと　いっしょに\n"
	.string "トレーニングの　まっさいちゅうだ！$"

MatchCall_Text_Norman_PreparingPostGame::
	.string "パパ“{PLAYER}！\p"
	.string "まさか　おまえが　でんどういりを\n"
	.string "はたして　しまうとは⋯⋯\p"
	.string "よし！\n"
	.string "わたしも　まけては　いられないぞ！$"

MatchCall_Text_Norman_RematchReady::
	.string "パパ“⋯⋯ん？　{PLAYER}か？\n"
	.string "これは　ちょうど　よかった！\p"
	.string "こんどは　パパから　おまえに\n"
	.string "しょうぶを　もうしこんで　やろう\p"
	.string "トウカの　ジムで　まってるから\n"
	.string "いつでも　ちょうせんしに　おいで！$"

MatchCall_Text_Norman_PostRematch::
	.string "パパ“⋯⋯すごいなあ　{PLAYER}\n"
	.string "どこまで　つよく　なっちゃうんだろう　$"

MatchCall_Text_Steven1::
	.string "ダイゴ“やあ　{PLAYER}{KUN}！\p"
	.string "もう　キンセツシティには　いったかな？\p"
	.string "まちの　サイクルショップで\n"
	.string "マッハじてんしゃを　てにいれたら\p"
	.string "もういちど　いしのどうくつの　おくに\n"
	.string "いってみるのも　いいね！\p"
	.string "なにか　あたらしい　はっけんが\n"
	.string "あるかも　しれないよ！$"

MatchCall_Text_Steven2::
	.string "ダイゴ“やあ　{PLAYER}{KUN}！\p"
	.string "ボクは　これまでに　ずいぶん　いろいろな\n"
	.string "トレーナーを　みてきた　けれど\p"
	.string "キミは　だれにも　にていない\n"
	.string "はじめて　みる　タイプの　ひとだよ！$"

MatchCall_Text_Steven3::
	.string "ダイゴ“やあ　{PLAYER}{KUN}！\p"
	.string "キミは　ポケモンと　ぼうけんを　していて\n"
	.string "どんな　きぶんに　なる？\p"
	.string "つよいみかた　だと　おもうかい？\n"
	.string "たのしいなかま　だと　おもうかい？\p"
	.string "キミが　どう　かんじるかに　よって\n"
	.string "その　ぼうけんの　いみは　かわるんだ！$"

MatchCall_Text_Steven4::
	.string "ダイゴ“ああ　{PLAYER}{KUN}　かい？\p"
	.string "ちょっと　いま　うちゅうセンターで\n"
	.string "めんどうな　ことが　おきてるんだ\p"
	.string "わるいけど　また　あとでね！$"

MatchCall_Text_Steven5::
	.string "ダイゴ“あっ　{PLAYER}{KUN}！\p"
	.string "なにも　いわなくて　いいよ！\n"
	.string "とにかく　いまは⋯⋯\p"
	.string "キミが　おもうように　すすむんだ！$"

MatchCall_Text_Steven6::
	.string "⋯⋯　⋯⋯　⋯⋯\p"
	.string "ダイゴには　よびだしが\n"
	.string "つうじていない　ようだ⋯⋯$"

MatchCall_Text_Steven7::
	.string "ダイゴ“{PLAYER}{KUN}⋯⋯\n"
	.string "でんどういり　おめでとう\p"
	.string "⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯\p"
	.string "また　いつか　あえると　いいね！$"

MatchCall_Text_BirchRegisterCall:
	.string "オダマキ“おお　{PLAYER}{KUN}！\n"
	.string "はなしは　すでに　きいて　いるよ！\p"
	.string "きみの　ポケナビに　エントリーコールが\n"
	.string "セットされた　らしいな！\p"
	.string "ならば　わたしも　とうろく　しておこう！\p"
	.string "これで　きみと　はなれていても\n"
	.string "すぐに　ポケモンずかんの　ひょうかを\l"
	.string "してあげられる　からね！\p"
	.string "⋯⋯　⋯⋯　⋯⋯$"

MatchCall_Text_RegisteredBirch:
	.string "オダマキはかせを\n"
	.string "ポケナビに　とうろく　した！$"

MatchCall_Text_UnusedProfBirch:
	.string "オダマキ“ずかんと　ポケナビが　あれば\n"
	.string "ポケモンの　ちょうさも\l"
	.string "より　いっそう　たのしくなるな！$"

MatchCall_Text_MrStone1::
	.string "ツワブキ“おっ！　{PLAYER}{KUN}か？\p"
	.string "こうして　わしを　よびだした　ってことは\n"
	.string "ポケナビの　ちょうしは　よさそうだな！\p"
	.string "わしの　ほかにも　いろんな　ひとが\n"
	.string "とうろく　されて　いくから　どんどん\l"
	.string "よびだして　はなしを　すると　いいぞ！\p"
	.string "けっこう！　けっこう！\n"
	.string "うれしそうに　しとる　ようだな！\p"
	.string "⋯⋯ん？　なんで　わかるのかって？\p"
	.string "それは⋯⋯　しゃちょうしつの　まどから\n"
	.string "きみを　みおろして　いるからだよ！\p"
	.string "わははは！　じゃあ　またな！$"

MatchCall_Text_MrStone2::
	.string "ツワブキ“おっ！　{PLAYER}{KUN}か？\p"
	.string "どうした！　わしが　たのんだ　しごと\n"
	.string "わすれちゃったの　かな？\p"
	.string "まずは　ムロタウンで　ダイゴに\n"
	.string "てがみを　わたしてくれ！\p"
	.string "そのあと　カイナシティの　クスノキくんに\n"
	.string "わがしゃの　にもつを　とどけるんだ！\p"
	.string "な？　おぼえたかな？\n"
	.string "わしは　いそがしい　しゃちょう　だからね\l"
	.string "これで　しつれい　するよ！$"

MatchCall_Text_MrStone3::
	.string "ツワブキ“おっ！　{PLAYER}{KUN}！\p"
	.string "そうか　ダイゴに　あえたのか！\n"
	.string "よーし　おれいに　プレゼントを　やろう！\p"
	.string "カナズミに　くることが　あったら\n"
	.string "わしの　へやに　よっていって　おくれ！\p"
	.string "じゃあな　まっとるぞ！$"

MatchCall_Text_MrStone4::
	.string "ツワブキ“おお！　{PLAYER}{KUN}！\p"
	.string "そうそう　カナシダトンネルは\n"
	.string "わがしゃが　ほって　いたんだけどね\p"
	.string "あの　あたりに　せいそく　している\n"
	.string "ポケモンを　ほご　するために\l"
	.string "こうじは　ちゅうし　したんだよ\p"
	.string "まあ　にんげんの　べんりさ　よりは\n"
	.string "ポケモンが　しずかに　くらせる\l"
	.string "そのほうが　だいじな　ことだからね！$"

MatchCall_Text_MrStone5::
	.string "ツワブキ“やあやあ　{PLAYER}{KUN}！\p"
	.string "トウカシティの　ひとから　きいたんだけど\n"
	.string "きみは　センリさんの　こども　なんだね\p"
	.string "どうりで　たのもしいと　おもったよ！$"

MatchCall_Text_MrStone6::
	.string "ツワブキ“ええっ！\n"
	.string "きみは　じぶんの　おとうさんと\l"
	.string "ポケモンしょうぶを　して　かったのかい？\p"
	.string "こりゃ　びっくりだ！\n"
	.string "わしは　すごい　ひとと　ともだちに\l"
	.string "なっちゃったんだなあ！　わはは！$"

MatchCall_Text_MrStone7::
	.string "もしもし！\n"
	.string "デボンコーポレーションで　ございま⋯⋯\l"
	.string "ああ　{PLAYER}さん　ですね！\p"
	.string "しゃちょうは　さっきまで　いたんですけど\n"
	.string "いまは　るすに　してるんですよ！\p"
	.string "うちの　しゃちょうも　いそがしいけど\n"
	.string "{PLAYER}さんも　いそがしそう　ですね！$"

MatchCall_Text_MrStone8::
	.string "⋯⋯え　⋯⋯なにかね？\p"
	.string "グラ⋯⋯　はい？　⋯⋯ドン？\p"
	.string "なんだか⋯⋯　きこえな⋯⋯\p"
	.string "ザザザザザ⋯⋯　⋯⋯　⋯⋯$"

MatchCall_Text_MrStone9::
	.string "⋯⋯え　⋯⋯なにかね？\p"
	.string "かいて⋯⋯　はい？　⋯⋯どうくつ？\p"
	.string "なんだか⋯⋯　きこえな⋯⋯\p"
	.string "ザザザザザ⋯⋯　⋯⋯　⋯⋯$"

MatchCall_Text_MrStone10::
	.string "ツワブキ“{PLAYER}{KUN}！　わしだ！\p"
	.string "なんだか　いろいろ　あった　らしいが\n"
	.string "いそがしい　わしには\l"
	.string "なんの　ことだか　サッパリ　わからん！\p"
	.string "とにかく　キミは　じぶんの　しんじた\n"
	.string "みちを　あゆんで　いきたまえ！\p"
	.string "わしも　カゲながら　おうえん　しとるぞ！\n"
	.string "じゃあな！$"

MatchCall_Text_MrStone11::
	.string "ツワブキ“⋯⋯　⋯⋯　⋯⋯\n"
	.string "もしかして　{PLAYER}{KUN}　か？\p"
	.string "こえに　じしんが　みなぎっていて\n"
	.string "いっしゅん　ちがうひとかと　おもったぞ！\p"
	.string "うむ！　たまには　わがしゃにも\n"
	.string "あそびに　きておくれ！$"
