@ Only contains the text for the Mauville Man named Giddy. The JP pointer
@ tables remain in their physical data owner.
GiddyText_SoPretty:: @ 0x082593C5
	.string "　きれい　だよねー$"

GiddyText_SoDarling:: @ 0x082593CF
	.string "　かわいい　よねー$"

GiddyText_SoRelaxed:: @ 0x082593D9
	.string "　のんびり　だよねー$"

GiddyText_SoSunny:: @ 0x082593E4
	.string "　ぽっかぽか　だよねー$"

GiddyText_SoDesirable:: @ 0x082593F0
	.string "　あこがれる　よねー$"

GiddyText_SoExciting:: @ 0x082593FB
	.string "　ドキドキ　するよねー$"

GiddyText_SoAmusing:: @ 0x08259407
	.string "　おもしろい　よねー$"

GiddyText_SoMagical:: @ 0x08259412
	.string "　ふしぎ　だよねー$"

GiddyText_Is:: @ 0x0825941C
	.string "って$"

GiddyText_DontYouAgree:: @ 0x0825941F
	.string "\n"
	.string "そう　おもわない？$"

GiddyText_ISoWantToGoOnAVacation:: @ 0x0825942A
	.string "たびに　でたいなー\n"
	.string "どこか　いい　ところ　しらない？$"

GiddyText_IBoughtCrayonsWith120Colors:: @ 0x08259445
	.string "120しょくの　クレヨン　かったんだー\n"
	.string "いいでしょう？$"

GiddyText_WouldntItBeNiceIfWeCouldFloat:: @ 0x08259461
	.string "しゃぼんだまに　のって　とべるように\n"
	.string "ならないかなー$"

GiddyText_WhenYouWriteOnASandyBeach:: @ 0x0825947C
	.string "すなはまに　かいた　もじは\n"
	.string "すぐに　きえちゃうのが　かなしいよねー$"

GiddyText_WhatsTheBottomOfTheSeaLike:: @ 0x0825949E
	.string "うみの　そこって　どうなってるのかなー\n"
	.string "いちどで　いいから　みて　みたいなー$"

GiddyText_WhenYouSeeTheSettingSunDoesIt:: @ 0x082594C5
	.string "ゆうやけを　みると\n"
	.string "ウチに　かえりたく　ならない？$"

GiddyText_LyingBackInTheGreenGrass:: @ 0x082594DF
	.string "みどりの　しばで　ねころがると\n"
	.string "きもちいいよねー$"

GiddyText_SecretBasesAreSoWonderful:: @ 0x082594F8
	.string "ひみつきち　って　いいよね！\n"
	.string "なんか　わくわく　してこない？$"
