gText_ObtainedTheItem::
	.string "{STR_VAR_2}を　てにいれた！$"

gText_TheBagIsFull::
	.string "バッグが　いっぱいだ！$"

gText_PutItemInPocket::
	.string "{PLAYER}は　{STR_VAR_2}を\n"
	.string "{STR_VAR_3}ポケットに　しまった！$"

gText_PlayerFoundOneItem::
	.string "{PLAYER}は　{STR_VAR_2}を\n"
	.string "みつけた！$"

gText_TooBadBagIsFull::
	.string "ざんねん！\n"
	.string "バッグが　いっぱいだ⋯⋯$"

gText_PlayerPutItemInBag::
	.string "{PLAYER}は　{STR_VAR_2}を\n"
	.string "バッグに　しまった！$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2}を　てにいれた！$"

gText_NoRoomLeftForAnother::
	.string "ざんねん！　{STR_VAR_2}を\n"
	.string "いれる　ばしょが　いっぱいだ⋯⋯$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2}は\n"
	.string "パソコンに　てんそうされた！$"
