gText_PkmnTransferredSomeonesPC::
	.string "{B_COPY_VAR_2}は　だれかのパソコンの\n"
	.string "ボックス“{B_COPY_VAR_1}”に\l"
	.string "てんそう　された！$"

gText_PkmnTransferredLanettesPC::
	.string "{B_COPY_VAR_2}は　マユミのパソコンの\n"
	.string "ボックス“{B_COPY_VAR_1}”に\l"
	.string "てんそう　された！$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "だれかのパソコンの\n"
	.string "ボックス“{B_COPY_VAR_3}”が\l"
	.string "いっぱいだ！！\p"
	.string "{B_COPY_VAR_2}は\n"
	.string "ボックス“{B_COPY_VAR_1}”に\l"
	.string "てんそう　された！$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "マユミのパソコンの\n"
	.string "ボックス“{B_COPY_VAR_3}”が\l"
	.string "いっぱいだ！！\p"
	.string "{B_COPY_VAR_2}は\n"
	.string "ボックス“{B_COPY_VAR_1}”に\l"
	.string "てんそう　された！$"

gText_NoMoreRoomForPokemon::
	.string "ポケモンを　もちきれません！\p"
	.string "ボックスも　いっぱいで\n"
	.string "てんそう　できません！$"

gText_NicknameThisPokemon::
	.string "{B_COPY_VAR_1}に\n"
	.string "ニックネームを　つけますか？$"
