gBirchDexRatingText_AreYouCurious:: @ 0x08262DF5
	.string "オダマキ“おお　{PLAYER}{KUN}！\p"
	.string "ポケモンずかんの　ようすを\n"
	.string "みせて　くれるのかい？$"

gBirchDexRatingText_Cancel:: @ 0x08262E1D
	.string "うん？　みせるほど\n"
	.string "ポケモンを　つかまえて　いないのか$"

gBirchDexRatingText_SoYouveSeenAndCaught:: @ 0x08262E39
	.string "ふむふむ⋯⋯\p"
	.string "みつけた　ポケモン　{STR_VAR_1}\n"
	.string "つかまえた　ポケモン　{STR_VAR_2}　か⋯⋯$"

gBirchDexRatingText_LessThan10:: @ 0x08262E5F
	.string "もっと　くさむらに　はいって\n"
	.string "ポケモンを　さがしてみると　いいな！$"

gBirchDexRatingText_LessThan20:: @ 0x08262E81
	.string "ちょうしが　でてきた　みたいだね\n"
	.string "でも　これからが　たいへん　なんだぞ！$"

gBirchDexRatingText_LessThan30:: @ 0x08262EA6
	.string "きまった　ばしょでしか　みつからない\n"
	.string "ポケモンは　しつこく　さがすしか　ないぞ！$"

gBirchDexRatingText_LessThan40:: @ 0x08262ECF
	.string "ボリュームは　まだまだ　だけど\n"
	.string "すこしは　ポケモンずかん　らしく　なったぞ$"

gBirchDexRatingText_LessThan50:: @ 0x08262EF5
	.string "なかなか　いい　かんじ　だな！\n"
	.string "この　ちょうしで　がんばって　くれよ$"

gBirchDexRatingText_LessThan60:: @ 0x08262F18
	.string "つりざおは　つかって　いるかな？\n"
	.string "うみにも　ポケモンは　たくさん　いるからな$"

gBirchDexRatingText_LessThan70:: @ 0x08262F3F
	.string "ポケモンを　つかまえる　だけでなく\n"
	.string "しんか　させるのは　どうだい？$"

gBirchDexRatingText_LessThan80:: @ 0x08262F61
	.string "すばらしい　ポケモンずかんに　なりそうだ\n"
	.string "そんな　よかんが　して　たまらないね！$"

gBirchDexRatingText_LessThan90:: @ 0x08262F8A
	.string "ここまで　あつめるとは⋯⋯\n"
	.string "きみの　さいのうは　たいした　ものだよ！$"

gBirchDexRatingText_LessThan100:: @ 0x08262FAD
	.string "サファリゾーンには　いったかい？\n"
	.string "あそこでしか　つかまえられない\l"
	.string "ポケモンも　いるって　はなし　だぞ！$"

gBirchDexRatingText_LessThan110:: @ 0x08262FE1
	.string "とうとう　100しゅるい　こえたのか！\n"
	.string "ポケモンずかん　として　みごとな　もんだね！$"

gBirchDexRatingText_LessThan120:: @ 0x0826300C
	.string "⋯⋯そういえば　いわくだきを　つかうことで\n"
	.string "みつかる　ポケモンも　いたっけ$"

gBirchDexRatingText_LessThan130:: @ 0x08263032
	.string "ポケモンこうかん　すれば\n"
	.string "もっと　あつまるかも　しれないな$"

gBirchDexRatingText_LessThan140:: @ 0x08263050
	.string "なんでも　なついていると\n"
	.string "しんか　する　ポケモンも　いるそうだよ！$"

gBirchDexRatingText_LessThan150:: @ 0x08263072
	.string "ホウエンちほう　には　こんなにも\n"
	.string "おおくの　ポケモンが　いたのか⋯⋯$"

gBirchDexRatingText_LessThan160:: @ 0x08263095
	.string "ときどき　たいりょうはっせい　する\n"
	.string "ポケモンが　いるらしい\l"
	.string "その　チャンスを　のがさないようにな！$"

gBirchDexRatingText_LessThan170:: @ 0x082630C7
	.string "きみの　ずかんを　みれば\n"
	.string "ホウエンちほうの　ポケモンの\l"
	.string "すべてが　わかるようだ！$"

gBirchDexRatingText_LessThan180:: @ 0x082630F0
	.string "きみは　ポケモンはかせ　としても\n"
	.string "ゆうしゅう　なんだな$"

gBirchDexRatingText_LessThan190:: @ 0x0826310C
	.string "ここまで　ずかんが　できたら\n"
	.string "もはや　プロフェッショナル　だぞ！$"

gBirchDexRatingText_LessThan200:: @ 0x0826312D
	.string "いよいよ　かんせいに　ちかづいた！\n"
	.string "そんな　よかんが　してきたよ！$"

gBirchDexRatingText_DexCompleted:: @ 0x0826314F
	.string "おめでとう！！\n"
	.string "ポケモンずかんの　かんせい　だよ！！$"

gBirchDexRatingText_OnANationwideBasis:: @ 0x0826316A
	.string "ふむふむ　ぜんこくてき　には⋯⋯\p"
	.string "みつけた　ポケモン　{STR_VAR_1}\n"
	.string "つかまえた　ポケモン　{STR_VAR_2}　だね$"
