Questionnaire_Text_FillOut::
	.string "アンケートようの　メモようしが　ある\n"
	.string "アンケートに　なにか　かきますか？$"

Questionnaire_Text_ThankYou::
	.string "アンケートに　ごきょうりょく\n"
	.string "いただき　ありがとう　ございます！\p"
	.string "この　アンケートは　こんごの\n"
	.string "さんこうに　させて　いただきます！$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "⋯⋯　おきゃくさま！\n"
	.string "そのことばを　しってるの　ですか！\p"
	.string "ということは　ふしぎなおくりもの　を\n"
	.string "しって　いらっしゃるの　ですね！\p"
	.string "これからは　あなたにも\n"
	.string "ふしぎなおくりもの　が\l"
	.string "とどくように　なるでしょう！$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "レポートをかくと　ふしぎなおくりもの　が\n"
	.string "つかえるように　なります$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "⋯⋯　おきゃくさま！\n"
	.string "そのことばを　しってるの　ですか！\p"
	.string "ということは　ふしぎなできごと　を\n"
	.string "しって　いらっしゃるの　ですね！$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "レポートをかくと　ふしぎなできごと　が\n"
	.string "つかえるように　なります$"
