SecretBase_Text_Trainer0Intro:
	.string "きみは　もう　ひみつきちを　つくったかい？\p"
	.string "ぼくは　あっち　こっち　まわって\n"
	.string "やっと　この　ばしょに　きめたんだ！\p"
	.string "せっかく　きたんだから\n"
	.string "ポケモン　しょうぶ　しない？$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "それじゃ　いくよ！$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "えっ　いまは　むりなんだ⋯$"

SecretBase_Text_Trainer0Defeated::
	.string "うわっ　きみって　つよいなー\n"
	.string "ぼくが　まけたこと　ひみつに　してね！$"

SecretBase_Text_Trainer0PostBattle:
	.string "ぼくの　ひみつきち　どうかなー\n"
	.string "また　あしたも　あそびに　きてね！$"

SecretBase_Text_Trainer0PreChampion:
	.string "きみは　もう　ひみつきちを　つくったかい？\p"
	.string "ぼくは　あっち　こっち　まわって\n"
	.string "やっと　この　ばしょに　きめたんだ！\p"
	.string "ゆっくり　して　いってね！$"

SecretBase_Text_Trainer5Intro:
	.string "ひみつきちを　つくれる　ばしょは\n"
	.string "ほかにも　たくさん　あるけど\l"
	.string "ここが　いちばん　きにいったの！\p"
	.string "ねっ！　すてきでしょ！\p"
	.string "あっ　もし　よかったら\n"
	.string "ポケモン　しょうぶ　しない？$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "それじゃ　いくわよ！$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "そう　いまは　むりなのね⋯$"

SecretBase_Text_Trainer5Defeated::
	.string "うーん　わたしの　まけね⋯\n"
	.string "わたしが　まけたのは　ないしょの　ひみつね！$"

SecretBase_Text_Trainer5PostBattle:
	.string "このちかくに　くることが　あったら\n"
	.string "また　あそびに　よってね！$"

SecretBase_Text_Trainer5PreChampion:
	.string "ひみつきちを　つくれる　ばしょは\n"
	.string "ほかにも　たくさん　あるけど\l"
	.string "ここが　いちばん　きにいったの！\p"
	.string "ねっ！　すてきでしょ！$"

SecretBase_Text_Trainer1Intro:
	.string "この　ばしょは　にんきが　あるから\n"
	.string "いつも　うまって　いるんだー\p"
	.string "あっ　もしかして\n"
	.string "きみも　ここを　つかいたい？\p"
	.string "うーん　ぼくに　かてたら\n"
	.string "このばしょ　あげても　いいよ！$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "よしっ！　ぼくの　きちを　まもるぞー！$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "えっ　この　ばしょに　きょうみが　ないの？\n"
	.string "そっかー$"

SecretBase_Text_Trainer1Defeated::
	.string "もう　ダメだ！\n"
	.string "こうさーん！$"

SecretBase_Text_Trainer1PostBattle:
	.string "よしっ　ぼくが　いつか　ひっこしたら\n"
	.string "この　ばしょは　きみの　ものさ！$"

SecretBase_Text_Trainer1PreChampion:
	.string "この　ばしょは　にんきが　あるから\n"
	.string "いつも　うまって　いるんだよー\p"
	.string "ぼくは　ずっと　まっていて\n"
	.string "やっと　つかえる　ように　なったんだ！$"

SecretBase_Text_Trainer6Intro:
	.string "わたしの　ポケモン　けんきゅうじょへ\n"
	.string "ようこそ！\p"
	.string "ここで　ポケモン　しょうぶに　ついて\n"
	.string "こっそり　べんきょう　してるのよ\p"
	.string "どう　わたしの　じつりょく　みてみる？$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "ほんきで　いくわよ！$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "それじゃ　また　こんどね！$"

SecretBase_Text_Trainer6Defeated::
	.string "うーん　わたしも　まだまだねー\n"
	.string "もっと　　べんきょう　しないと！$"

SecretBase_Text_Trainer6PostBattle:
	.string "しょうぶ　してくれて　どうも　ありがとう！\n"
	.string "また　あしたも　きてねー$"

SecretBase_Text_Trainer6PreChampion:
	.string "わたしの　ポケモン　けんきゅうじょへ\n"
	.string "ようこそ！\p"
	.string "ここで　ポケモン　しょうぶに　ついて\n"
	.string "こっそり　べんきょう　してるのよ$"

SecretBase_Text_Trainer2Intro:
	.string "おおきな　いえも　いいけど\n"
	.string "ぼくは　こういう　ばしょが　すきなんだ\p"
	.string "だって　いろいろな　ひとが\n"
	.string "あそびに　きてくれる　からねー！\p"
	.string "どう　ポケモン　しょうぶでも　するかい？$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "そう　こなくっちゃ！$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "よういが　できたら\n"
	.string "いつでも　こえを　かけてね！$"

SecretBase_Text_Trainer2Defeated::
	.string "やられたー！\n"
	.string "だけど　ポケモン　しょうぶは　たのしいー！$"

SecretBase_Text_Trainer2PostBattle:
	.string "さてと　グッズでも　かいに　いこうかな\p"
	.string "ぼくの　ひみつきちを\n"
	.string "みんなに　たのしんで　ほしい　からね！$"

SecretBase_Text_Trainer2PreChampion:
	.string "おおきな　いえも　いいけど\n"
	.string "ぼくは　こういう　ばしょが　すきなんだ\p"
	.string "だって　いろいろな　ひとが\n"
	.string "あそびに　きてくれる　からねー！$"

SecretBase_Text_Trainer7Intro:
	.string "わたし　グッズの　おかいものが\n"
	.string "だいすき　です！\p"
	.string "それと　おなじくらい　ポケモンを　そだてるの\n"
	.string "だいすき　です！\p"
	.string "もし　よかったら　わたしの　ポケモンちゃんと\n"
	.string "しょうぶして　くれますか？$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "それでは　おねがいします$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "そう　それは　ざんねん　です⋯$"

SecretBase_Text_Trainer7Defeated::
	.string "まいりました⋯⋯$"

SecretBase_Text_Trainer7PostBattle:
	.string "ああ　たのしかった！\n"
	.string "つぎは　おかいものを　たのしもう　かしら$"

SecretBase_Text_Trainer7PreChampion:
	.string "わたし　グッズの　おかいものが\n"
	.string "だいすき　です\p"
	.string "それと　おなじくらい　ポケモンを　そだてるの\n"
	.string "だいすき　です$"

SecretBase_Text_Trainer3Intro:
	.string "みつかり　にくい　ばしょに\n"
	.string "ひみつきちを　つくる　ひとが　いるけど\l"
	.string "こっそりと　かくれて　いたいのかなぁ⋯⋯\p"
	.string "うん　せっかく　みつけて　くれたんだから\n"
	.string "ポケモン　しょうぶ　しようか？$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "かんたんには　おわらせ　ないよ！$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "もしかして　さがすのに　つかれちゃった？$"

SecretBase_Text_Trainer3Defeated::
	.string "おわっちゃった⋯⋯$"

SecretBase_Text_Trainer3PostBattle:
	.string "きみの　ひみつきちは　どこなんだい！\n"
	.string "こんど　あそびに　いこうかなー$"

SecretBase_Text_Trainer3PreChampion:
	.string "みつかり　にくい　ばしょに\n"
	.string "ひみつきちを　つくる　ひとが　いるけど\l"
	.string "こっそりと　かくれて　いたいのかなぁ$"

SecretBase_Text_Trainer8Intro:
	.string "グッズを　てにいれる　ほうほうは\n"
	.string "いろいろ　あるって　はなしよ\p"
	.string "どっちが　すてきな　グッズを\n"
	.string "てにいれるか　きょうそうね！\p"
	.string "ついでに　ポケモン　しょうぶも　しない？$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "じぶんの　ひみつきちで　まけられないわ！$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "いつでも　しょうぶ　まってるわ！$"

SecretBase_Text_Trainer8Defeated::
	.string "えっ　もしかして　わたしの　まけ？$"

SecretBase_Text_Trainer8PostBattle:
	.string "グッズあつめ　まけないわよ！\n"
	.string "また　あそびに　きてね！$"

SecretBase_Text_Trainer8PreChampion:
	.string "グッズを　てにいれる　ほうほうは\n"
	.string "いろいろ　あるって　はなしよ\p"
	.string "どっちが　すてきな　グッズを\n"
	.string "てにいれるか　きょうそうね！$"

SecretBase_Text_Trainer4Intro:
	.string "すきな　ばしょを　さがして\n"
	.string "すきな　グッズを　おく！\p"
	.string "すきな　ポケモンを　そだてて\n"
	.string "ぼくも　いっしょに　つよくなる\p"
	.string "そんな　ぼくと　しょうぶ　しよう！$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "きみの　じつりょくを　みせてくれ！$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "まぁ　そんな　ときも　あるよね！$"

SecretBase_Text_Trainer4Defeated::
	.string "きみの　じつりょくは　じゅうぶん　わかった！$"

SecretBase_Text_Trainer4PostBattle:
	.string "きみも　ぼくも　もっと　つよく　なれる！\n"
	.string "おたがいに　がんばろうね！$"

SecretBase_Text_Trainer4PreChampion:
	.string "すきな　ばしょを　さがして\n"
	.string "すきな　ものを　おく！\p"
	.string "すきな　ポケモンを　そだてて\n"
	.string "ぼくも　いっしょに　つよくなる\p"
	.string "まいにち　たのしいねー$"

SecretBase_Text_Trainer9Intro:
	.string "グッズの　しゅるいや　おきかたを　みれば\n"
	.string "そのひとが　どんな　センスの　もちぬしか\l"
	.string "よーく　わかるわね！\p"
	.string "わたしの　センスは　どうかしら？\n"
	.string "うふふっ　なにも　いえないって　かんじね！\p"
	.string "しょうぶの　センスも　ためして　みる？$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "おもいっきり　いくわよ！$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "いつでも　わたしの　センスを　みせるわよ！$"

SecretBase_Text_Trainer9Defeated::
	.string "すごい　さいのうね！\n"
	.string "そこしれぬ　つよさを　かんじたわ⋯⋯$"

SecretBase_Text_Trainer9PostBattle:
	.string "わたしの　センス　どうだった？\n"
	.string "もっと　センスを　みがくわよー$"

SecretBase_Text_Trainer9PreChampion:
	.string "グッズの　しゅるいや　おきかたを　みれば\n"
	.string "そのひとが　どんな　センスの　もちぬしか\l"
	.string "よーく　わかるわね！\p"
	.string "わたしの　センスは　どうかしら？\n"
	.string "うふふっ　なにも　いえないって　かんじね！$"
