SecretBase_Text_AllDecorationsWillBeReturned:
	.string "ひみつきちの　グッズは　すべて\n"
	.string "パソコンに　もどります\p"
	.string "それでも　よろしいですか？$"

SecretBase_Text_WantToRegisterSecretBase:
	.string "{STR_VAR_1}の　ひみつきちを\n"
	.string "とうろく　しますか？$"

SecretBase_Text_AlreadyRegisteredDelete:
	.string "すでに　とうろくされています\n"
	.string "とうろくを　かいじょ　しますか？$"

SecretBase_Text_TooManyBasesDeleteSome:
	.string "とうろく　できる　かずは\n"
	.string "10かしょ　まで　です\p"
	.string "どれか　かいじょ　すれば\n"
	.string "とうろく　できます$"

SecretBase_Text_RegistrationCompleted:
	.string "とうろく　しました！$"

SecretBase_Text_DataUnregistered:
	.string "とうろくを　かいじょ　しました！$"

SecretBase_Text_BootUpPC:
	.string "{PLAYER}は\n"
	.string "パソコンの　スイッチを　いれた！$"

SecretBase_Text_WhatWouldYouLikeToDo:
	.string "なにを　しますか？$"

SecretBase_Text_RegistryInfo:
	.string "とうろくした　ひみつきちは\n"
	.string "あいてが　ひっこしを　しないかぎり\l"
	.string "なくなる　ことは　ありません\p"
	.string "とうろく　リストから　さくじょすると\n"
	.string "ほかの　ひみつきちに\l"
	.string "かわることが　あります\p"
	.string "とうろくは　10かしょ　まで　できます$"

SecretBase_Text_BattleTowerShield:
	.string "バトルタワーで　{STR_VAR_1}にん　かちぬいた\n"
	.string "きねんの　{STR_VAR_2}の　たて$"

SecretBase_Text_ToyTV:
	.string "ほんもの　そっくりの　オモチャのテレビ\n"
	.string "しらない　ひとが　みたら　まちがうかも！？$"

SecretBase_Text_SeedotTV:
	.string "タネボー　みたいな　オモチャのテレビ\n"
	.string "なんだか　ころがりだしそう！？$"

SecretBase_Text_SkittyTV:
	.string "エネコ　みたいな　オモチャのテレビ\n"
	.string "なんだか　あるきだしそう！？$"

SecretBase_Text_WouldYouLikeToMoveBases:
	.string "ひみつきちは　ひとつしか　つくれません！\p"
	.string "{STR_VAR_1}　にある\n"
	.string "ひみつきちを　ひっこし　しますか？$"

SecretBase_Text_MovingCompletedUseSecretPower:
	.string "ひっこし　かんりょう！\p"
	.string "ひみつのちからを　つかいますか？$"
