gTrickHouse_Mechadoll_Oddish::
	.string "ナゾノクサ$"

gTrickHouse_Mechadoll_Poochyena::
	.string "ポチエナ$"

gTrickHouse_Mechadoll_Taillow::
	.string "スバメ$"

gTrickHouse_Mechadoll_Azurill::
	.string "ルリリ$"

gTrickHouse_Mechadoll_Lotad::
	.string "ハスボー$"

gTrickHouse_Mechadoll_Wingull::
	.string "キャモメ$"

gTrickHouse_Mechadoll_Dustox::
	.string "ドクケイル$"

gTrickHouse_Mechadoll_Zubat::
	.string "ズバット$"

gTrickHouse_Mechadoll_Nincada::
	.string "ツチニン$"

gTrickHouse_Mechadoll_Ralts::
	.string "ラルトス$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "ジグザグマ$"

gTrickHouse_Mechadoll_Slakoth::
	.string "ナマケロ$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "ポチエナ$"

gTrickHouse_Mechadoll_Shroomish::
	.string "キノココ$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "ジグザグマ$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "ポチエナ$"

gTrickHouse_Mechadoll_Zubat2::
	.string "ズバット$"

gTrickHouse_Mechadoll_Carvanha::
	.string "キバニア$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "やけどなおし$"

gTrickHouse_Mechadoll_HarborMail::
	.string "ハーバーメール$"

gTrickHouse_Mechadoll_SamePrice::
	.string "おなじねだん$"

gTrickHouse_Mechadoll_60Yen::
	.string "60えん$"

gTrickHouse_Mechadoll_55Yen::
	.string "55えん$"

gTrickHouse_Mechadoll_Nothing::
	.string "のこらない$"

gTrickHouse_Mechadoll_CostMore::
	.string "たかくなる$"

gTrickHouse_Mechadoll_CostLess::
	.string "やすくなる$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "おなじねだん$"

gTrickHouse_Mechadoll_Male::
	.string "だんせい$"

gTrickHouse_Mechadoll_Female::
	.string "じょせい$"

gTrickHouse_Mechadoll_Neither::
	.string "どっちでもない$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "おじいさん$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "おばあさん$"

gTrickHouse_Mechadoll_SameNumber::
	.string "おなじかず$"

gTrickHouse_Mechadoll_None::
	.string "いない$"

gTrickHouse_Mechadoll_One::
	.string "ひとり$"

gTrickHouse_Mechadoll_Two::
	.string "ふたり$"

gTrickHouse_Mechadoll_Two2::
	.string "2ひき$"

gTrickHouse_Mechadoll_Three::
	.string "3ひき$"

gTrickHouse_Mechadoll_Four::
	.string "4ひき$"

gTrickHouse_Mechadoll_Six::
	.string "6つ$"

gTrickHouse_Mechadoll_Seven::
	.string "7つ$"

gTrickHouse_Mechadoll_Eight::
	.string "8つ$"

gTrickHouse_Mechadoll_Six2::
	.string "6にん$"

gTrickHouse_Mechadoll_Seven2::
	.string "7にん$"

gTrickHouse_Mechadoll_Eight2::
	.string "8にん$"
