LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "おや？　あなた　ポケモンコンテストに\n"
	.string "さんかして　いましたね！\l"
	.string "その　ポケモンを　みれば　わかりますよ！\p"
	.string "わたくし　ポケモンコンテストに　ついて\n"
	.string "きじを　かいて　いるのですが\p"
	.string "できれば　すこし　かんそうを\n"
	.string "きかせて　くれませんかね？$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "ほんとう　ですか！\n"
	.string "ありがとう　ございます\p"
	.string "それでは　いまの　コンテストの　かんそうを\n"
	.string "ひとことで　おねがいします！$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "うーん　なるほど！\p"
	.string "どんな　コンテストだったか\n"
	.string "よくわかる　ひとこと　ですね！\p"
	.string "⋯⋯さいごに\n"
	.string "ちょっと　おききしたいの　ですが\p"
	.string "あなたが　イメージする　{B_COPY_VAR_2}って\n"
	.string "いったい　どんなもの　ですかね？$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "なるほど！\p"
	.string "それが　あなたの　イメージする\n"
	.string "{B_COPY_VAR_2}　なんですね！\p"
	.string "いろいろ　さんこうに　なりました！\p"
	.string "コンテストに　ついて\n"
	.string "いい　きじが　かけそう　ですよ\p"
	.string "もしかしたら　テレビで　このことが\n"
	.string "ながれるかも　しれないので\l"
	.string "たのしみに　してくださいね！$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "そうですか⋯⋯\p"
	.string "こんど　おもしろいことが　あれば\n"
	.string "きかせて　くださいね$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "こんどの　ポケモンコンテストも\n"
	.string "たのしみに　してますよ！$"

gTVBravoTrainerText00::
	.string "イヤー！\n"
	.string "“ブラボー　トレーナー”の　じかんだ！\p"
	.string "きょうは　{B_COPY_VAR_3}クラスの\n"
	.string "{B_COPY_VAR_2}を　ほこる\l"
	.string "{B_COPY_VAR_1}さんの　ポケモン！$"

gTVBravoTrainerText01::
	.string "{B_COPY_VAR_1}　の　‘{B_COPY_VAR_2}'の\n"
	.string "しょうかいだー！\p"
	.string "‘{B_COPY_VAR_2}'か⋯⋯\p"
	.string "もう　ニックネーム　からして\n"
	.string "{B_COPY_VAR_3}が　にじみ　でているぜ！$"

gTVBravoTrainerText02::
	.string "さーて　この　{B_COPY_VAR_1}さんが\n"
	.string "ポケモンコンテストに　さんか　したとき\p"
	.string "じぶんの　ポケモンに　ついて\n"
	.string "あつく　はなして　くれたぞ！$"

gTVBravoTrainerText03::
	.string "コンテストを　したあとの\n"
	.string "かんそうを　きくと\l"
	.string "すごく　うれしそうに\p"
	.string "‘{B_COPY_VAR_2}'って\n"
	.string "こたえて　くれたぞ！\p"
	.string "まあ　コンテストでは\n"
	.string "{B_COPY_VAR_3}ばん　でした　からねー！\p"
	.string "いまの　{B_COPY_VAR_1}さんには\n"
	.string "ぴったりの　セリフだよ　まったく！$"

gTVBravoTrainerText04::
	.string "コンテストを　したあとの\n"
	.string "かんそうを　きくと\l"
	.string "びみょうに　くやしがり　ながら\p"
	.string "‘{B_COPY_VAR_2}'って\n"
	.string "こたえて　くれたぞ！\p"
	.string "まあ　コンテストでは\n"
	.string "{B_COPY_VAR_3}ばん　でした　からねー！\p"
	.string "この　ことばに　{B_COPY_VAR_1}さんの\n"
	.string "くやしさが　みえかくれ　するねー$"

gTVBravoTrainerText05::
	.string "ところで　{B_COPY_VAR_1}さんの　めざしてる\n"
	.string "{B_COPY_VAR_2}って　いったい　なんだろう？\l"
	.string "きいて　みたいねー！\p"
	.string "もちろん　きいて　きました！\p"
	.string "それは　つぎの　ひとことに\n"
	.string "すべてが　つまって　います！\p"
	.string "それは　‘{B_COPY_VAR_3}！'\p"
	.string "それこそ　{B_COPY_VAR_1}さんの\n"
	.string "{B_COPY_VAR_2}の　すべて　なんです！$"

gTVBravoTrainerText06::
	.string "さいごに　{B_COPY_VAR_1}が\n"
	.string "つかった　{B_COPY_VAR_2}も\l"
	.string "すべて　‘{B_COPY_VAR_3}'　なんです！$"

gTVBravoTrainerText07::
	.string "ブラボー！　{B_COPY_VAR_1}\n"
	.string "ブラボー！！　{B_COPY_VAR_2}\p"
	.string "こんごの　{B_COPY_VAR_1}さんの　かつやくに\n"
	.string "きたい　したいねー！\p"
	.string "それじゃあ　また　じかいの\n"
	.string "ほうそうで　あいましょー！$"

gTVBravoTrainerText08::
	.string "{B_COPY_VAR_1}　の　しょうかいだー！$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "あ！　いま　たたかっていた\n"
	.string "トレーナーの　かたですね！\p"
	.string "わたし　いま　いろんな　トレーナーの\n"
	.string "はなしを　きいて　まわってるんだけど\p"
	.string "たたかいおわった　かんそうを\n"
	.string "すこしだけ　きかせて　もらえませんか？$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "ほんと！？\n"
	.string "ありがとう！\l"
	.string "えっと　それじゃあねぇ⋯⋯\p"
	.string "こんかいの　バトルタワーの\n"
	.string "たいせんは　どうでしたか\p"
	.string "まんぞく　でしたか！\n"
	.string "それとも　ふまん　ですか！？$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "あぁ！\n"
	.string "ごめんなさい\p"
	.string "じゃあ　またこんど　バトルタワーに　きたら\n"
	.string "きかせて　くださいね$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "さっすが！\p"
	.string "その　まんぞくした　かおを　みれば\n"
	.string "どんなに　いいしあいだったか\l"
	.string "わかりますよ！$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "うーん　そうですか⋯⋯\p"
	.string "おもいどおりに　しょうぶを　するのって\n"
	.string "なかなか　むずかしい　ですからね⋯⋯$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "あぁっ　あと\n"
	.string "もう　ひとつだけ　いいですか？\p"
	.string "この　たたかいの　かんそうを\n"
	.string "ひとことで　ビシッと　きかせてください！$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "かっこいー！！\p"
	.string "いい　きめゼリフ　ですね\n"
	.string "つぎの　たたかいも　きたい　してますよ\p"
	.string "それでは　また！$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "そうですか⋯⋯\p"
	.string "でも　なにも　いわないのも\n"
	.string "また　かっこいいですね！\p"
	.string "それじゃあ　またの　きかいに\n"
	.string "かんそうを　きかせて　ください！$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "つぎの　たたかいも\n"
	.string "きたい　してますよ$"
