LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "おや？　あなた　ポケモンコンテストに\n"
	.string "さんかして　いましたね！\l"
	.string "その　ポケモンを　みれば　わかりますよ！\p"
	.string "わたくし　ポケモンコンテストに　ついて\n"
	.string "きじを　かいて　いるのですが\p"
	.string "できれば　すこし　かんそうを\n"
	.string "きかせて　くれませんかね？$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "ほんとう　ですか！\n"
	.string "ありがとう　ございます\p"
	.string "それでは　いまの　コンテストの　かんそうを\n"
	.string "ひとことで　おねがいします！$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "うーん　なるほど！\p"
	.string "どんな　コンテストだったか\n"
	.string "よくわかる　ひとこと　ですね！\p"
	.string "⋯⋯さいごに\n"
	.string "ちょっと　おききしたいの　ですが\p"
	.string "あなたが　イメージする　{B_COPY_VAR_2}って\n"
	.string "いったい　どんなもの　ですかね？$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "なるほど！\p"
	.string "それが　あなたの　イメージする\n"
	.string "{B_COPY_VAR_2}　なんですね！\p"
	.string "いろいろ　さんこうに　なりました！\p"
	.string "コンテストに　ついて\n"
	.string "いい　きじが　かけそう　ですよ\p"
	.string "もしかしたら　テレビで　このことが\n"
	.string "ながれるかも　しれないので\l"
	.string "たのしみに　してくださいね！$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "そうですか⋯⋯\p"
	.string "こんど　おもしろいことが　あれば\n"
	.string "きかせて　くださいね$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "こんどの　ポケモンコンテストも\n"
	.string "たのしみに　してますよ！$"

gTVBravoTrainerText00::
	.string "イヤー！\n"
	.string "“ブラボー　トレーナー”の　じかんだ！\p"
	.string "きょうは　{B_COPY_VAR_3}クラスの\n"
	.string "{B_COPY_VAR_2}を　ほこる\l"
	.string "{B_COPY_VAR_1}さんの　ポケモン！$"

gTVBravoTrainerText01::
	.string "{B_COPY_VAR_1}　の　‘{B_COPY_VAR_2}'の\n"
	.string "しょうかいだー！\p"
	.string "‘{B_COPY_VAR_2}'か⋯⋯\p"
	.string "もう　ニックネーム　からして\n"
	.string "{B_COPY_VAR_3}が　にじみ　でているぜ！$"

gTVBravoTrainerText02::
	.string "さーて　この　{B_COPY_VAR_1}さんが\n"
	.string "ポケモンコンテストに　さんか　したとき\p"
	.string "じぶんの　ポケモンに　ついて\n"
	.string "あつく　はなして　くれたぞ！$"

gTVBravoTrainerText03::
	.string "コンテストを　したあとの\n"
	.string "かんそうを　きくと\l"
	.string "すごく　うれしそうに\p"
	.string "‘{B_COPY_VAR_2}'って\n"
	.string "こたえて　くれたぞ！\p"
	.string "まあ　コンテストでは\n"
	.string "{B_COPY_VAR_3}ばん　でした　からねー！\p"
	.string "いまの　{B_COPY_VAR_1}さんには\n"
	.string "ぴったりの　セリフだよ　まったく！$"

gTVBravoTrainerText04::
	.string "コンテストを　したあとの\n"
	.string "かんそうを　きくと\l"
	.string "びみょうに　くやしがり　ながら\p"
	.string "‘{B_COPY_VAR_2}'って\n"
	.string "こたえて　くれたぞ！\p"
	.string "まあ　コンテストでは\n"
	.string "{B_COPY_VAR_3}ばん　でした　からねー！\p"
	.string "この　ことばに　{B_COPY_VAR_1}さんの\n"
	.string "くやしさが　みえかくれ　するねー$"

gTVBravoTrainerText05::
	.string "ところで　{B_COPY_VAR_1}さんの　めざしてる\n"
	.string "{B_COPY_VAR_2}って　いったい　なんだろう？\l"
	.string "きいて　みたいねー！\p"
	.string "もちろん　きいて　きました！\p"
	.string "それは　つぎの　ひとことに\n"
	.string "すべてが　つまって　います！\p"
	.string "それは　‘{B_COPY_VAR_3}！'\p"
	.string "それこそ　{B_COPY_VAR_1}さんの\n"
	.string "{B_COPY_VAR_2}の　すべて　なんです！$"

gTVBravoTrainerText06::
	.string "さいごに　{B_COPY_VAR_1}が\n"
	.string "つかった　{B_COPY_VAR_2}も\l"
	.string "すべて　‘{B_COPY_VAR_3}'　なんです！$"

gTVBravoTrainerText07::
	.string "ブラボー！　{B_COPY_VAR_1}\n"
	.string "ブラボー！！　{B_COPY_VAR_2}\p"
	.string "こんごの　{B_COPY_VAR_1}さんの　かつやくに\n"
	.string "きたい　したいねー！\p"
	.string "それじゃあ　また　じかいの\n"
	.string "ほうそうで　あいましょー！$"

gTVBravoTrainerText08::
	.string "{B_COPY_VAR_1}　の　しょうかいだー！$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "あ！　いま　たたかっていた\n"
	.string "トレーナーの　かたですね！\p"
	.string "わたし　いま　いろんな　トレーナーの\n"
	.string "はなしを　きいて　まわってるんだけど\p"
	.string "たたかいおわった　かんそうを\n"
	.string "すこしだけ　きかせて　もらえませんか？$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "ほんと！？\n"
	.string "ありがとう！\l"
	.string "えっと　それじゃあねぇ⋯⋯\p"
	.string "こんかいの　バトルタワーの\n"
	.string "たいせんは　どうでしたか\p"
	.string "まんぞく　でしたか！\n"
	.string "それとも　ふまん　ですか！？$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "あぁ！\n"
	.string "ごめんなさい\p"
	.string "じゃあ　またこんど　バトルタワーに　きたら\n"
	.string "きかせて　くださいね$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "さっすが！\p"
	.string "その　まんぞくした　かおを　みれば\n"
	.string "どんなに　いいしあいだったか\l"
	.string "わかりますよ！$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "うーん　そうですか⋯⋯\p"
	.string "おもいどおりに　しょうぶを　するのって\n"
	.string "なかなか　むずかしい　ですからね⋯⋯$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "あぁっ　あと\n"
	.string "もう　ひとつだけ　いいですか？\p"
	.string "この　たたかいの　かんそうを\n"
	.string "ひとことで　ビシッと　きかせてください！$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "かっこいー！！\p"
	.string "いい　きめゼリフ　ですね\n"
	.string "つぎの　たたかいも　きたい　してますよ\p"
	.string "それでは　また！$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "そうですか⋯⋯\p"
	.string "でも　なにも　いわないのも\n"
	.string "また　かっこいいですね！\p"
	.string "それじゃあ　またの　きかいに\n"
	.string "かんそうを　きかせて　ください！$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "つぎの　たたかいも\n"
	.string "きたい　してますよ$"

BravoTrainerBattleTower_Text_Intro::
	.string "イヤー！\n"
	.string "“ブラボー　トレーナー”の　じかんだ！\p"
	.string "きょうは　バトルタワーに　ちょうせんした\n"
	.string "{B_COPY_VAR_1}さんの　しょうかいだー！\p"
	.string "{B_COPY_VAR_1}さんは　{B_COPY_VAR_2}を\n"
	.string "つかった　たたかいをして$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "なんと　{B_COPY_VAR_1}の　へやで\n"
	.string "{B_COPY_VAR_2}れんしょう　という\l"
	.string "きろくを　うちたてたぞ！$"

BravoTrainerBattleTower_Text_Lost::
	.string "おしくも　{B_COPY_VAR_2}にんめで　たたかった\n"
	.string "{B_COPY_VAR_1}さんに　まけて　しまいました\l"
	.string "うーん！　ざんねんだねぇ\p"
	.string "でも　こんなはじめに　{B_COPY_VAR_1}さんに\n"
	.string "あたるとは　うんがないとしか　いえないよ\p"
	.string "さて　その　{B_COPY_VAR_1}さんとの\n"
	.string "しょうぶの　かんそうを　きいたところ$"

BravoTrainerBattleTower_Text_Won::
	.string "さいごには　{B_COPY_VAR_1}さんの\n"
	.string "{B_COPY_VAR_2}を　みごとに　たおして\l"
	.string "しょうり　したんですねぇ\p"
	.string "いや　{B_COPY_VAR_1}さんに　かつなんて\n"
	.string "すごいとしか　いいようがないよ　まったく\p"
	.string "さて　そのしょうりを　つかんだ\n"
	.string "しゅんかんの　かんそうを　きいたところ$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "しかし　さいごに　とうじょうした\n"
	.string "{B_COPY_VAR_1}さんの　{B_COPY_VAR_2}に\l"
	.string "ついに　まけて　しまったんですねぇ\p"
	.string "まあ　‘{B_COPY_VAR_1}の　{B_COPY_VAR_2}'\n"
	.string "といえば　ゆうめいな　コンビ　ですからね\p"
	.string "⋯⋯さて　その　ゆうめいじんとの\n"
	.string "しょうぶの　かんそうを　きいたところ$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "まんぞく　した！！\p"
	.string "と　すがすがしく　こたえてくれたよ\n"
	.string "さすがだぜ！\p"
	.string "まんぞくいく　たたかいが　できるなんて\n"
	.string "ほんと　すごいよねぇ　まったく！\p"
	.string "その　まんぞくかんは　つぎの　ひとことを\n"
	.string "きいたとき　すべて　わかったよ$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "ふまんだった⋯⋯\p"
	.string "と　びみょうに　おちこみながら\n"
	.string "こたえて　くれたよ\p"
	.string "⋯⋯まあ　まんぞくいく　たたかいって\n"
	.string "なかなかできる　もんじゃないからねー\p"
	.string "そのときの　くやしさは\n"
	.string "つぎの　ひとことが　よくあらわしてるよ$"

BravoTrainerBattleTower_Text_None1::
	.string "なし$"

BravoTrainerBattleTower_Text_None2::
	.string "なし$"

BravoTrainerBattleTower_Text_None3::
	.string "なし$"

BravoTrainerBattleTower_Text_None4::
	.string "なし$"

BravoTrainerBattleTower_Text_Response::
	.string "その　ことばは\n"
	.string "‘{B_COPY_VAR_1}！'$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "‘{B_COPY_VAR_1}！'\n"
	.string "うーん　　いい　ことばだねぇ！！\p"
	.string "{B_COPY_VAR_2}さんの　うれしさを\n"
	.string "このことばが　よく　あらわしているよ！\p"
	.string "たしかに　{B_COPY_VAR_3}さんとの　たたかいは\n"
	.string "まさに　‘{B_COPY_VAR_1}'　という\l"
	.string "かんじ　だったからねぇ！$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "‘{B_COPY_VAR_1}！'\n"
	.string "なるほどねぇ\p"
	.string "たしかに　{B_COPY_VAR_3}さんとの　たたかいは\n"
	.string "‘{B_COPY_VAR_1}'　としか　いいようがない\l"
	.string "たたかい　でしたからねぇ\p"
	.string "{B_COPY_VAR_2}さんの　くやしさが\n"
	.string "よく　つたわってくるよ！　くー！$"

BravoTrainerBattleTower_Text_Outro::
	.string "ブラボー！　{B_COPY_VAR_1}\n"
	.string "ブラボー！！　{B_COPY_VAR_2}\p"
	.string "こんごの　{B_COPY_VAR_1}さんの　かつやくに\n"
	.string "きたい　したいねぇ！\p"
	.string "それじゃあ　また　じかいの\n"
	.string "ほうそうで　あいましょー！$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "わあ！\p"
	.string "きみ　その　{B_COPY_VAR_1}を　とても\n"
	.string "だいじに　している　みたいね！\p"
	.string "{B_COPY_VAR_2}　って　いうんだ⋯⋯\p"
	.string "そうだ！\p"
	.string "いま　わたし　テレビの　しゅざいで\n"
	.string "ポケモンの　アンケートを　してるんだけど\p"
	.string "すこしだけ　しつもんに\n"
	.string "こたえて　くれないかな？$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "ありがとう！\p"
	.string "じゃあ　きくね\n"
	.string "ずばり　ひとことで　こたえて！$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "きみが　{B_COPY_VAR_1}と\n"
	.string "であったときって\p"
	.string "なにか　かんじた？\n"
	.string "どう　おもったか　おしえて！$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "きみの　かわいがってる　{B_COPY_VAR_1}！\p"
	.string "もし　なにか　すきなものに　たとえると\n"
	.string "すれば　なんだと　おもう？$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "きみの　かわいがってる　{B_COPY_VAR_1}！\p"
	.string "きみは　{B_COPY_VAR_1}の　どこに\n"
	.string "ひかれたの？$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "うーん　なるほどね\p"
	.string "じゃあ　つぎは　ちょっと\n"
	.string "むずかしい　しつもんを　するね！\p"
	.string "じゃあ⋯⋯\p"
	.string "きみに　とって　ポケモンって\n"
	.string "ひとことで　いうと　なんだと　おもう？$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "なるほどー！\p"
	.string "ふむふむ⋯⋯\p"
	.string "あ！\n"
	.string "きょうりょく　ありがとうね！\p"
	.string "いろいろ　はなしが　きけて\n"
	.string "おもしろ　かったよ\p"
	.string "このはなし　もしかしたら　テレビで\n"
	.string "ながすかも　しれないから　きたい　しててね\p"
	.string "じゃあね\n"
	.string "バイバイ！$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "そっか⋯⋯\p"
	.string "じゃあ　また　ポケモンの　ことを\n"
	.string "はなしたく　なったら　いつでも　きてね$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "ここに　いると　いろんな　ポケモンの\n"
	.string "はなしが　きけるから　おもしろいわ$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "きみの　その　{B_COPY_VAR_1}と\n"
	.string "とても　なかが　よさそうね\p"
	.string "そうだ！　いま　わたし\n"
	.string "テレビの　しゅざいで\p"
	.string "いろんな　ポケモンの　はなしを\n"
	.string "きいて　まわってるんだけど\p"
	.string "よかったら　きみの　{B_COPY_VAR_1}の\n"
	.string "はなしを　きかせて　くれないかな？$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "わあ！\n"
	.string "ありがとう！\p"
	.string "じゃあ　{B_COPY_VAR_1}の　はなし\n"
	.string "なんでも　いいので　きかせてよ！$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "へー⋯⋯\n"
	.string "おもしろい　はなし　だね！\p"
	.string "きみは　ほんとうに　{B_COPY_VAR_1}と\n"
	.string "なかが　いいんだね\p"
	.string "うーん　なんか　このはなしで\n"
	.string "いい　ばんぐみが　できそうな　よかん！\p"
	.string "きっと　おもしろい　ばんぐみに\n"
	.string "するから　たのしみに　まっててね\p"
	.string "じゃあ　ありがとうね\n"
	.string "バイバイ！$"

gTVFanClubOpinionsText00::
	.string "“ぼくたち！\n"
	.string "ポケモン　だいすきクラブ！”\p"
	.string "はい　はじまりました！\p"
	.string "このばんぐみは　みなさんの\n"
	.string "いけんを　このわたしが\l"
	.string "かわりに　さけんで　しまおう！\l"
	.string "という　すごい　ばんぐみ！！\p"
	.string "さて　きょうは　ポケモンだいすきクラブ　に\n"
	.string "いって　いろんな　はなしを　きいてきた\l"
	.string "リポーターからの　じょうほうだ！\p"
	.string "さて　きょうの\n"
	.string "ポケモンだいすき　にんげんは？\p"
	.string "んー⋯⋯\p"
	.string "{B_COPY_VAR_1}さんだー！！\p"
	.string "それでは　ごじぶんの　ポケモン\p"
	.string "{B_COPY_VAR_2}の　‘{B_COPY_VAR_3}'に\n"
	.string "ついての　あつい　きもちを\p"
	.string "かわりに　この　わたくしが　テレビに\n"
	.string "むかって　さけんで　あげましょう！\p"
	.string "うー！！\p"
	.string "レッツ　シャウト！！！$"

gTVFanClubOpinionsText01::
	.string "さて　{B_COPY_VAR_1}さんが　はじめて\n"
	.string "{B_COPY_VAR_2}と　あったとき　ちょっかんてきに\l"
	.string "おもった　ことは⋯⋯\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "んー　いい　さけびだ！\p"
	.string "まるで　そのときの　おもいでが\n"
	.string "よみがえる　ようだー！！$"

gTVFanClubOpinionsText02::
	.string "さて　{B_COPY_VAR_1}さんの　だいすきな\n"
	.string "{B_COPY_VAR_2}を　なにかに　たとえると　したら\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "んー　すごい　はっそうだ！！\p"
	.string "はげしい　{B_COPY_VAR_2}への　おもいこみが\n"
	.string "かんじられるねー！$"

gTVFanClubOpinionsText03::
	.string "さて　{B_COPY_VAR_1}さんが　{B_COPY_VAR_2}に\n"
	.string "ひかれた　りゆうは⋯⋯\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "おー！！　すんばらしい　いけんだー！\p"
	.string "{B_COPY_VAR_2}を　どんなに　すきか\n"
	.string "ビンビン　つたわって　くるねー！$"

gTVFanClubOpinionsText04::
	.string "んー？　まだ　つづきが　ありますねー\n"
	.string "よんで　みましょう！\p"
	.string "えーと⋯⋯\p"
	.string "{B_COPY_VAR_1}さんに　とって　ポケモンを\n"
	.string "ひとことで　たとえると　すれば　それは！\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "ブラボー！！\p"
	.string "いままでの　なかで　いちばん\n"
	.string "いい　さけび　だったー！\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "なんども　さけびたくなる　ことばだねー！\p"
	.string "それでは　いいさけびと　であった　ところで\n"
	.string "また　じかい　おあいしましょう！\p"
	.string "さいごに　もういちど\n"
	.string "みんなで　さけびましょう！\p"
	.string "‘{B_COPY_VAR_3}！！'$"

gTVFanClubText00::
	.string "“ぼくたち！\n"
	.string "ポケモン　だいすきクラブ！”\p"
	.string "はい　はじまりました！\p"
	.string "じゃあ　きょうは　ポケモンアンケートの\n"
	.string "コーナーから！\p"
	.string "かずある　ポケモンと　トレーナーの\n"
	.string "はなしの　なかから\p"
	.string "きょうは　どんな　はなしが\n"
	.string "とびだして　くるのでしょうか！？\l"
	.string "さて　きょうの　はなしは？\p"
	.string "んー⋯⋯\p"
	.string "これだ！\p"
	.string "では　てがみの　しょうかい　から！！\p"
	.string "{B_COPY_VAR_2}の　ことに　ついて\n"
	.string "{B_COPY_VAR_1}さん　からの　おてがみだー\p"
	.string "では　どれだけ　{B_COPY_VAR_2}への\n"
	.string "あつい　いけんが　かいてあるか\l"
	.string "よませて　もらいましょう！\l"
	.string "えーと⋯⋯$"

gTVFanClubText01::
	.string "おー！！\n"
	.string "なんて　すばらしい　てがみなんだ！！$"

gTVFanClubText02::
	.string "きにいったから　もういちど！$"

gTVFanClubText03::
	.string "いい　てがみは\n"
	.string "なんど　きいても　いいねー！！$"

gTVFanClubText04::
	.string "‘{B_COPY_VAR_3}'　っていう　ことばの\n"
	.string "おかげで　グッと　こころに　つたわってくる\l"
	.string "いい　てがみに　なっているねー！！$"

gTVFanClubText05::
	.string "とくに‘{B_COPY_VAR_3}'って　ところ！\p"
	.string "‘{B_COPY_VAR_3}'っていう　ところが\n"
	.string "きにいったぞー！$"

gTVFanClubText06::
	.string "ところで　あんまり　かんけい　ないけど\n"
	.string "‘{B_COPY_VAR_3}'って　いいことば　だよね\p"
	.string "じつは　おれも　‘{B_COPY_VAR_3}'って\n"
	.string "ことば　さいきん　よく　つかうんだよね$"

gTVFanClubText07::
	.string "このてがみ　じぶんてきには\n"
	.string "{B_COPY_VAR_3}てん　ていう　かんじかなー！\p"
	.string "つぎは　もっと　いい　てがみを\n"
	.string "きたい　してるよ！　{B_COPY_VAR_1}さん！！\p"
	.string "おっと　もう　こんなじかんだ！\n"
	.string "それでは　また　じかい\l"
	.string "みなさま　おあい　しましょう！！$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "おや？\n"
	.string "あなたも　ポケモンのことが　おすきで？\p"
	.string "わたくし　テレビきょくの　もので\n"
	.string "さいきん　おきた\p"
	.string "トレーナーと　ポケモンの　できごとを\n"
	.string "きいて　まわって　いるのです\p"
	.string "もし　よければ　なにか\n"
	.string "はなしを　きかせて　くれませんかね？$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "いま　さいきん　おきた\n"
	.string "トレーナーと　ポケモンの　できごとを\l"
	.string "きいて　まわって　いるのですが\p"
	.string "もし　よければ　なにか\n"
	.string "はなしを　きかせて　くれませんかね？$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "おお　きかせて　くれますか！\n"
	.string "ありがとう　ございます\p"
	.string "では　さいきん　おきたこと　なら\n"
	.string "なんでも　よいので\l"
	.string "はなしを　きかせて　ください！$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "そうですか⋯⋯\p"
	.string "では　また　なにか　おもしろい　はなしが\n"
	.string "あったら　きかせて　くださいね$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "⋯⋯おお\n"
	.string "なんて　いいはなしだ！\p"
	.string "このはなし　テレビで\n"
	.string "つかわせて　いただきます！\p"
	.string "いつか　ほうそう　するかも　しれないので\n"
	.string "たのしみに　まっていて　くださいね$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "うーん\n"
	.string "いい　テレビばんぐみが　できそうだ！\p"
	.string "いそいで　まとめないと！$"

gTVRecentHappeningsText00::
	.string "“さいきんの　できごと”\p"
	.string "ポケモントレーナーに　とって\n"
	.string "まいにちが　ものがたりです\l"
	.string "その　ものがたりを　すこしでも\l"
	.string "しょうかい　できたら　うれしいですね\p"
	.string "さて　きょうは　トレーナーの\n"
	.string "{B_COPY_VAR_1}さんの　おはなしです\p"
	.string "{B_COPY_VAR_1}さん　さいきん\n"
	.string "どんなことが　あったんで　しょうか？\l"
	.string "さっそく　みてみることに　しましょう\p"
	.string "えーと⋯⋯$"

gTVRecentHappeningsText01::
	.string "なるほど　{B_COPY_VAR_1}さんの\n"
	.string "まわりで　さいきん　おきている　ことが\l"
	.string "てに　とるように　わかりますね$"

gTVRecentHappeningsText02::
	.string "‘{B_COPY_VAR_3}'という　ことばが\n"
	.string "おはなしに　ストーリーを　かんじさせますね$"

gTVRecentHappeningsText03::
	.string "‘{B_COPY_VAR_3}'という　ことばの\n"
	.string "おかげで　まるで　じょうけいが\l"
	.string "うかんで　くるようですね$"

gTVRecentHappeningsText04::
	.string "このおはなしは　‘{B_COPY_VAR_3}'という\n"
	.string "ぶぶんが　とても　いんしょうてき　ですね$"

gTVRecentHappeningsText05::
	.string "{B_COPY_VAR_1}さんは　とても　いい\n"
	.string "おはなしを　きかせて　くれましたね\p"
	.string "これで　あなたの　こころにも\n"
	.string "{B_COPY_VAR_1}さん　という　ストーリーが\l"
	.string "きざみ　こまれましたよ\p"
	.string "それでは　また　じかいの\n"
	.string "ほうそうで　おあいしましょう$"

gTVMassOutbreakText00::
	.string "こんにちは\n"
	.string "“ポケモン　ニュース”の　じかんです\p"
	.string "たいへん　めずらしい　ニュースが\n"
	.string "はいって　きました\p"
	.string "{B_COPY_VAR_1}で\n"
	.string "{B_COPY_VAR_2}が　たいりょうはっせい　した\l"
	.string "という　ほうこくが　ありました！\p"
	.string "{B_COPY_VAR_2}と　いえば\n"
	.string "なかなか　みつけることが　むずかしい\l"
	.string "ポケモンとしても　ゆうめい　ですね\p"
	.string "あなたも　このしんぴてきな\n"
	.string "{B_COPY_VAR_2}の　たいりょうはっせいを\l"
	.string "みにいっては　いかが　でしょうか？\p"
	.string "いじょう\n"
	.string "“ポケモン　ニュース”でした$"

gTV3CheersForPokeblocksText00::
	.string "しかい“ごきげん　いかがですか？\n"
	.string "“ポロック　バンザイ！”の　おじかんです\p"
	.string "きょうの　ポロックは\n"
	.string "{B_COPY_VAR_1}さんと　その　おなかまが\l"
	.string "ブレンドした　ポロックです\p"
	.string "さっそく　わたしの　グルメな　ポケモン\n"
	.string "ゴクリンちゃんに　たべさせて　みましょう！\p"
	.string "⋯⋯　⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯　⋯⋯$"

gTV3CheersForPokeblocksText01::
	.string "ゴクリン“グビィ！　グビィ！\p"
	.string "しかい“おお！　とっても　{B_COPY_VAR_1}くて\n"
	.string "‘{B_COPY_VAR_2}！'と　いってますね\p"
	.string "きっと　これは　{B_COPY_VAR_3}さんが\n"
	.string "がんばって　まわした　おかげですね！\p"
	.string "{B_COPY_VAR_3}さん！\n"
	.string "ごちそうさま　でした！$"

gTV3CheersForPokeblocksText02::
	.string "こんかい　いまいち　だった\n"
	.string "{B_COPY_VAR_1}さんが\l"
	.string "もっと　じょうずに　まわすことが　できれば\l"
	.string "さらに　おいしく　なるかも　しれませんよ！$"

gTV3CheersForPokeblocksText03::
	.string "ゴクリン“グビィ！　グビィ！\p"
	.string "しかい“うーん⋯⋯　ちょっと　{B_COPY_VAR_1}すぎて\n"
	.string "‘{B_COPY_VAR_2}！'と　いってますね⋯⋯\p"
	.string "やっぱり　{B_COPY_VAR_3}さんの　しっぱいが\n"
	.string "いたかった　ですね⋯⋯$"

gTV3CheersForPokeblocksText04::
	.string "こんかい　いちばん　がんばっていた\n"
	.string "{B_COPY_VAR_1}さんが　かわいそうです⋯⋯\p"
	.string "⋯⋯{B_COPY_VAR_2}さん！\n"
	.string "つぎは　がんばって　ください！$"

gTV3CheersForPokeblocksText05::
	.string "では　また　おあいしましょう！\n"
	.string "あいことばは　“ポロック　バンザイ！”$"
