@ OldaleTown_House1 scripts (JP map g2 m0 @ 0x081F28D3)

OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 0x081F28D4
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 0x081F28DD
	.string "ポケモンしょうぶの　とき\n"
	.string "ポケモンの　リストの　ひだりに　いる\l"
	.string "ポケモンが　とびだして　たたかうの\p"
	.string "だから　つれあるく　ポケモンが　ふえてきたら\n"
	.string "ポケモンの　じゅんばんを　かえると\l"
	.string "しょうぶが　ゆうりに　なるかも！$"
