Common_Movement_ExclamationMark: @ 0x0824361B
	emote_exclamation_mark
	step_end

Common_Movement_Delay48: @ 0x0824361D
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer: @ 0x08243621
	face_player
	step_end

Common_Movement_FaceAwayPlayer: @ 0x08243623
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection: @ 0x08243625
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFasterLeft: @ 0x08243627
	walk_in_place_faster_left
	step_end

Common_Movement_WalkInPlaceFasterUp: @ 0x08243629
	walk_in_place_faster_up
	step_end

Common_Movement_WalkInPlaceFasterRight: @ 0x0824362B
	walk_in_place_faster_right
	step_end

Common_Movement_WalkInPlaceFasterDown: @ 0x0824362D
	walk_in_place_faster_down
	step_end

Common_Movement_FaceRight:: @ 0x0824362F
	face_right
	step_end

Common_Movement_FaceLeft:: @ 0x08243631
	face_left
	step_end

Common_Movement_FaceDown:: @ 0x08243633
	face_down
	step_end

Common_Movement_FaceUp:: @ 0x08243635
	face_up
	step_end

Common_Movement_WalkInPlaceDown:: @ 0x08243637
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceLeft:: @ 0x08243639
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceRight:: @ 0x0824363B
	walk_in_place_right
	step_end

Common_Movement_WalkUp6:: @ 0x0824363D
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:: @ 0x08243644
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32:: @ 0x08243649
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp:: @ 0x0824364C
	walk_up
	step_end

@ Unused
Common_Movement_WalkUp2:: @ 0x0824364E
	walk_up
	walk_up
	step_end
