	lockall 
	loadword 0x0, 0x82568A2
	callstd 0x4
	releaseall 
	end 
	.string "{LIGHT_RED}{LIGHT_RED}{LIGHT_GREEN}{SE_PIN}{LIGHT_RED}と{SE_WARP_IN}たてて\n"
	.string "みず{SE_SAVE}ながれ{LIGHT_RED}ち{MUS_RG_CAUGHT_INTRO}る！$"
	.string "{LIGHT_RED}{LIGHT_RED}{LIGHT_GREEN}{SE_PIN}た{LIGHT_GREEN}だ！\n"
	.string "⋯⋯た{LIGHT_GREEN}のぼり{SE_WARP_IN}つ{MUS_RG_POKE_TOWER}ま{DYNAMIC_COLOR4}{GREEN}？$"
	.string "{B_COPY_VAR_1}{TRANSPARENT}{SE_I}た{LIGHT_GREEN}のぼり{SE_WARP_IN}つ{GREEN}った！$"
