	lockall 
	dofieldeffect 0x2
	waitstate 
	goto 0x825661D
	end 
	.string "ぽ{DYNAMIC_COLOR6}ィわニゆ{BLUE}{SE_THUNDERSTORM}{TRANSPARENT}ウ{DYNAMIC_COLOR6}ィヒ{DARK_GRAY}サ\n"
	.string "{SE_BALL_OPEN}ヒニゆ{BLUE}{LIGHT_BLUE}{RED}ヒ{DARK_GRAY}ネヒ{DARK_GRAY}⋯⋯{DYNAMIC_COLOR1}の{LIGHT_GREEN}{SE_I}なんだ{GREEN}\n"
	.string "{LIGHT_GREEN}れ{DYNAMIC_COLOR6}{LIGHT_GRAY}だ！\p"
	.string "{SE_RG_HELP_CLOSE}{DARK_GRAY}ぎり{SE_NOTE_B}{LIGHT_GREEN}りま{DYNAMIC_COLOR4}{GREEN}？$"
	.string "{B_COPY_VAR_1}{TRANSPARENT}は\n"
	.string "{B_COPY_VAR_2}{SE_WARP_IN}つ{GREEN}った！$"
	.string "{DYNAMIC_COLOR1}の{LIGHT_GREEN}{SE_I}なんだ{GREEN}\n"
	.string "{LIGHT_GREEN}れ{DYNAMIC_COLOR6}{LIGHT_GRAY}だ！$"
	.incbin "baserom_jp.gba", 0x25667c, 0x4a
