	.incbin "baserom_jp.gba", 0x256935, 0x6b
	.globl gJPText_002569A0
gJPText_002569A0: @ 0x082569A0
	.string "ふかい　うみだ！\n"
	.string "ダイビングを　つかいますか？$"

	.globl gJPText_002569B8
gJPText_002569B8: @ 0x082569B8
	.string "{B_COPY_VAR_1}　は　ダイビングを　つかった！$"

	.incbin "baserom_jp.gba", 0x2569ca, 0x28
	.globl gJPText_002569F2
gJPText_002569F2: @ 0x082569F2
	.string "うえから　ひかりが　さしこんでいる！\n"
	.string "ダイビングを　つかいますか？$"

