	loadword 0x0, 0x81EFD5A
	callstd 0x3
	end
	.incbin "baserom_jp.gba", 0x2585d8, 0x1d6
BerryBlender_Text_LetsGetBlendingAlready: @ 0x082587AE
	.incbin "baserom_jp.gba", 0x2587ae, 0xc
BerryBlender_Text_WhatKindOfPokeblockWillIGet: @ 0x082587BA
	.incbin "baserom_jp.gba", 0x2587ba, 0x5b4
	.globl BerryBlender_EventScript_BerryBlender1
BerryBlender_EventScript_BerryBlender1: @ 0x08258D6E
	.incbin "baserom_jp.gba", 0x258d6e, 0x10f
	.globl BerryBlender_EventScript_BerryBlender2
BerryBlender_EventScript_BerryBlender2: @ 0x08258E7D
	.incbin "baserom_jp.gba", 0x258e7d, 0xd1
	.globl BerryBlender_EventScript_BerryBlender3
BerryBlender_EventScript_BerryBlender3: @ 0x08258F4E
	.incbin "baserom_jp.gba", 0x258f4e, 0x184
	.globl BerryBlender_EventScript_Blender2Man
BerryBlender_EventScript_Blender2Man: @ 0x082590D2
	.incbin "baserom_jp.gba", 0x2590d2, 0x9
	.globl BerryBlender_EventScript_Blender3PokefanF
BerryBlender_EventScript_Blender3PokefanF: @ 0x082590DB
	.incbin "baserom_jp.gba", 0x2590db, 0x9
	.globl BerryBlender_EventScript_Blender2Twin
BerryBlender_EventScript_Blender2Twin: @ 0x082590E4
	.incbin "baserom_jp.gba", 0x2590e4, 0x9
	.globl BerryBlender_EventScript_Blender1ExpertM
BerryBlender_EventScript_Blender1ExpertM: @ 0x082590ED
	.incbin "baserom_jp.gba", 0x2590ed, 0x98
	.globl BerryBlender_EventScript_BerryBlenderLink
BerryBlender_EventScript_BerryBlenderLink: @ 0x08259185
	.incbin "baserom_jp.gba", 0x259185, 0x297
