	return 
	goto 0x2081032
	nop 
	returnram 
	returnram 
	gotostd 0xA
	end 
	.byte 0x19
	pokemartdecoration 0x2004C000
	.byte 0x19
	pokemartdecoration 0x1804C000
	.byte 0x19
	pokemartdecoration 0x1004C000
	.byte 0x19
	pokemartdecoration 0x804C000
	.byte 0x19
	pokemartdecoration 0x804C000
	.byte 0x19
	pokemartdecoration 0x804C000
	.byte 0x19
	pokemartdecoration 0x804C000
	.byte 0x19
	pokemartdecoration 0x804C000
	.byte 0x19
	pokemartdecoration 0xB05C000
	end 
	.byte 0x0D
	.byte 0x04
	.byte 0x01
	.byte 0x08
