	nop 
	dofieldeffect 0x1427
	copylocal 0x17, 0x19
	setwildbattle 0xC000, 0x10, 0x7
	nop 
	return 
	.string "ルヲた{BLUE}{SE_ARENA_TIMEUP2}{SE_M_STRING_SHOT2}{DYNAMIC_COLOR5}ぬzら{BLUE}{LIGHT_GRAY}オぱ{DYNAMIC_COLOR4}{BLUE}{LIGHT_RED}{SE_RG_POKE_JUMP_SUCCESS}{SE_RG_SS_ANNE_HORN}{MUS_DUMMY}{TRANSPARENT}{SE_FLEE}{SE_USE_ITEM}{DYNAMIC_COLOR5}ぬzら{BLUE}{DYNAMIC_COLOR5}ぬzら{BLUE}{DYNAMIC_COLOR5}ぬzら{BLUE}た{LIGHT_GREEN}$"
	.incbin "baserom_jp.gba", 0x27edcf, 0x1
	.string "まドゴな{BLUE}{LIGHT_GREEN}{SE_M_BUBBLE_BEAM2}F$"
	.incbin "baserom_jp.gba", 0x27edda, 0x8a
