	.incbin "baserom_jp.gba", 0x2436cd, 0x2aa
	.globl gJPText_00243977
gJPText_00243977: @ 0x08243977
	.string "ざんねん！\n"
	.string "バッグが　いっぱいだ⋯⋯$"

	.incbin "baserom_jp.gba", 0x24398a, 0xf6
	.globl gJPText_00243A80
gJPText_00243A80: @ 0x08243A80
	.string "バッグに　いれてある　どうぐを\n"
	.string "べんりボタンに　とうろく　できます$"

	.incbin "baserom_jp.gba", 0x243aa2, 0xdd
	.globl gJPText_00243B7F
gJPText_00243B7F: @ 0x08243B7F
	.string "{B_COPY_VAR_1}の　{B_COPY_VAR_2}を\n"
	.string "ポケナビに　とうろく　した！$"

	.incbin "baserom_jp.gba", 0x243b96, 0xf5
	.globl gJPText_00243C8B
gJPText_00243C8B: @ 0x08243C8B
	.string "みずは　ふかい　あおに　そまっている⋯⋯\n"
	.string "なみのりを　つかいますか？$"

	.globl gJPText_00243CAE
gJPText_00243CAE: @ 0x08243CAE
	.string "{B_COPY_VAR_1}は\n"
	.string "なみのりを　つかった！$"

	.incbin "baserom_jp.gba", 0x243cbe, 0x230
	.globl gJPText_00243EEE
gJPText_00243EEE: @ 0x08243EEE
	.string "アンケートようの　メモようしが　ある\n"
	.string "アンケートに　なにか　かきますか？$"

	.incbin "baserom_jp.gba", 0x243f13, 0x1a9
	.globl gJPText_002440BC
gJPText_002440BC: @ 0x082440BC
	.string "おおあめは　おさまったようだ⋯⋯$"

	.globl gJPText_002440CD
gJPText_002440CD: @ 0x082440CD
	.string "ひでりは　おさまったようだ⋯⋯$"

