	.incbin "baserom_jp.gba", 0x26240a, 0x48
	.globl gJPText_00262452
gJPText_00262452: @ 0x08262452
	.string "サファリゾーンを\n"
	.string "このまま　しゅうりょう　しますか？$"

	.globl gJPText_0026246D
gJPText_0026246D: @ 0x0826246D
	.string "ピンポーン！　じかん　でーす！\n"
	.string "サファリゲームを　しゅうりょう　します$"

	.globl gJPText_00262491
gJPText_00262491: @ 0x08262491
	.string "サファリボールを　つかいきったので\n"
	.string "サファリゲームを　しゅうりょう　します$"

	.globl gJPText_002624B7
gJPText_002624B7: @ 0x082624B7
	.string "ポロックおきばに　ポロックを　おきますか？$"

	.incbin "baserom_jp.gba", 0x2624cd, 0x826
