// Auto-generated by tools/generate_battle_tower_partner_texts.py; do not edit.

#define PARTNER_TEXTS(name) \
    BattleFrontier_BattleTowerMultiPartnerRoom_Text_##name##Intro, \
    BattleFrontier_BattleTowerMultiPartnerRoom_Text_##name##Mon1, \
    BattleFrontier_BattleTowerMultiPartnerRoom_Text_##name##Mon2Ask, \
    BattleFrontier_BattleTowerMultiPartnerRoom_Text_##name##Accept, \
    BattleFrontier_BattleTowerMultiPartnerRoom_Text_##name##Reject

static const u8 *const sPartnerApprenticeTexts1[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice1)
};

static const u8 *const sPartnerApprenticeTexts2[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice2)
};

static const u8 *const sPartnerApprenticeTexts3[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice3)
};

static const u8 *const sPartnerApprenticeTexts4[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice4)
};

static const u8 *const sPartnerApprenticeTexts5[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice5)
};

static const u8 *const sPartnerApprenticeTexts6[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice6)
};

static const u8 *const sPartnerApprenticeTexts7[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice7)
};

static const u8 *const sPartnerApprenticeTexts8[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice8)
};

static const u8 *const sPartnerApprenticeTexts9[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice9)
};

static const u8 *const sPartnerApprenticeTexts10[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice10)
};

static const u8 *const sPartnerApprenticeTexts11[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice11)
};

static const u8 *const sPartnerApprenticeTexts12[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice12)
};

static const u8 *const sPartnerApprenticeTexts13[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice13)
};

static const u8 *const sPartnerApprenticeTexts14[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice14)
};

static const u8 *const sPartnerApprenticeTexts15[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice15)
};

static const u8 *const sPartnerApprenticeTexts16[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Apprentice16)
};

static const u8 *const sPartnerTextsLass[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Lass)
};

static const u8 *const sPartnerTextsYoungster[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Youngster)
};

static const u8 *const sPartnerTextsHiker[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Hiker)
};

static const u8 *const sPartnerTextsBeauty[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Beauty)
};

static const u8 *const sPartnerTextsFisherman[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Fisherman)
};

static const u8 *const sPartnerTextsLady[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Lady)
};

static const u8 *const sPartnerTextsCyclingTriathleteF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(CyclingTriathleteF)
};

static const u8 *const sPartnerTextsBugCatcher[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(BugCatcher)
};

static const u8 *const sPartnerTextsSchoolKidM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(SchoolKidM)
};

static const u8 *const sPartnerTextsRichBoy[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(RichBoy)
};

static const u8 *const sPartnerTextsBlackBelt[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(BlackBelt)
};

static const u8 *const sPartnerTextsTuberF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(TuberF)
};

static const u8 *const sPartnerTextsHexManiac[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(HexManiac)
};

static const u8 *const sPartnerTextsPkmnBreederM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PkmnBreederM)
};

static const u8 *const sPartnerTextsRunningTriathleteF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(RunningTriathleteF)
};

static const u8 *const sPartnerTextsRunningTriathleteM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(RunningTriathleteM)
};

static const u8 *const sPartnerTextsBattleGirl[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(BattleGirl)
};

static const u8 *const sPartnerTextsCyclingTriathleteM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(CyclingTriathleteM)
};

static const u8 *const sPartnerTextsTuberM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(TuberM)
};

static const u8 *const sPartnerTextsGuitarist[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Guitarist)
};

static const u8 *const sPartnerTextsGentleman[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Gentleman)
};

static const u8 *const sPartnerTextsPokefanM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PokefanM)
};

static const u8 *const sPartnerTextsExpertM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(ExpertM)
};

static const u8 *const sPartnerTextsExpertF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(ExpertF)
};

static const u8 *const sPartnerTextsDragonTamer[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(DragonTamer)
};

static const u8 *const sPartnerTextsBirdKeeper[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(BirdKeeper)
};

static const u8 *const sPartnerTextsNinjaBoy[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(NinjaBoy)
};

static const u8 *const sPartnerTextsParasolLady[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(ParasolLady)
};

static const u8 *const sPartnerTextsBugManiac[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(BugManiac)
};

static const u8 *const sPartnerTextsSailor[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Sailor)
};

static const u8 *const sPartnerTextsCollector[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Collector)
};

static const u8 *const sPartnerTextsPkmnRangerM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PkmnRangerM)
};

static const u8 *const sPartnerTextsPkmnRangerF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PkmnRangerF)
};

static const u8 *const sPartnerTextsAromaLady[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(AromaLady)
};

static const u8 *const sPartnerTextsRuinManiac[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(RuinManiac)
};

static const u8 *const sPartnerTextsCoolTrainerM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(CoolTrainerM)
};

static const u8 *const sPartnerTextsCoolTrainerF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(CoolTrainerF)
};

static const u8 *const sPartnerTextsPokemaniac[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Pokemaniac)
};

static const u8 *const sPartnerTextsKindler[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Kindler)
};

static const u8 *const sPartnerTextsCamper[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Camper)
};

static const u8 *const sPartnerTextsPicnicker[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(Picnicker)
};

static const u8 *const sPartnerTextsPsychicM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PsychicM)
};

static const u8 *const sPartnerTextsPsychicF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PsychicF)
};

static const u8 *const sPartnerTextsSchoolKidF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(SchoolKidF)
};

static const u8 *const sPartnerTextsPkmnBreederF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PkmnBreederF)
};

static const u8 *const sPartnerTextsPokefanF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(PokefanF)
};

static const u8 *const sPartnerTextsSwimmerF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(SwimmerF)
};

static const u8 *const sPartnerTextsSwimmingTriathleteM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(SwimmingTriathleteM)
};

static const u8 *const sPartnerTextsSwimmingTriathleteF[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(SwimmingTriathleteF)
};

static const u8 *const sPartnerTextsSwimmerM[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    PARTNER_TEXTS(SwimmerM)
};

struct PartnerTrainerTextTable
{
    u32 facilityClass;
    const u8 *const *strings;
};

static const struct PartnerTrainerTextTable sPartnerTrainerTextTables[] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    {FACILITY_CLASS_LASS, sPartnerTextsLass},
    {FACILITY_CLASS_YOUNGSTER, sPartnerTextsYoungster},
    {FACILITY_CLASS_HIKER, sPartnerTextsHiker},
    {FACILITY_CLASS_BEAUTY, sPartnerTextsBeauty},
    {FACILITY_CLASS_FISHERMAN, sPartnerTextsFisherman},
    {FACILITY_CLASS_LADY, sPartnerTextsLady},
    {FACILITY_CLASS_CYCLING_TRIATHLETE_F, sPartnerTextsCyclingTriathleteF},
    {FACILITY_CLASS_BUG_CATCHER, sPartnerTextsBugCatcher},
    {FACILITY_CLASS_SCHOOL_KID_M, sPartnerTextsSchoolKidM},
    {FACILITY_CLASS_RICH_BOY, sPartnerTextsRichBoy},
    {FACILITY_CLASS_BLACK_BELT, sPartnerTextsBlackBelt},
    {FACILITY_CLASS_TUBER_F, sPartnerTextsTuberF},
    {FACILITY_CLASS_HEX_MANIAC, sPartnerTextsHexManiac},
    {FACILITY_CLASS_PKMN_BREEDER_M, sPartnerTextsPkmnBreederM},
    {FACILITY_CLASS_RUNNING_TRIATHLETE_F, sPartnerTextsRunningTriathleteF},
    {FACILITY_CLASS_RUNNING_TRIATHLETE_M, sPartnerTextsRunningTriathleteM},
    {FACILITY_CLASS_BATTLE_GIRL, sPartnerTextsBattleGirl},
    {FACILITY_CLASS_CYCLING_TRIATHLETE_M, sPartnerTextsCyclingTriathleteM},
    {FACILITY_CLASS_TUBER_M, sPartnerTextsTuberM},
    {FACILITY_CLASS_GUITARIST, sPartnerTextsGuitarist},
    {FACILITY_CLASS_GENTLEMAN, sPartnerTextsGentleman},
    {FACILITY_CLASS_POKEFAN_M, sPartnerTextsPokefanM},
    {FACILITY_CLASS_EXPERT_M, sPartnerTextsExpertM},
    {FACILITY_CLASS_EXPERT_F, sPartnerTextsExpertF},
    {FACILITY_CLASS_DRAGON_TAMER, sPartnerTextsDragonTamer},
    {FACILITY_CLASS_BIRD_KEEPER, sPartnerTextsBirdKeeper},
    {FACILITY_CLASS_NINJA_BOY, sPartnerTextsNinjaBoy},
    {FACILITY_CLASS_PARASOL_LADY, sPartnerTextsParasolLady},
    {FACILITY_CLASS_BUG_MANIAC, sPartnerTextsBugManiac},
    {FACILITY_CLASS_SAILOR, sPartnerTextsSailor},
    {FACILITY_CLASS_COLLECTOR, sPartnerTextsCollector},
    {FACILITY_CLASS_PKMN_RANGER_M, sPartnerTextsPkmnRangerM},
    {FACILITY_CLASS_PKMN_RANGER_F, sPartnerTextsPkmnRangerF},
    {FACILITY_CLASS_AROMA_LADY, sPartnerTextsAromaLady},
    {FACILITY_CLASS_RUIN_MANIAC, sPartnerTextsRuinManiac},
    {FACILITY_CLASS_COOLTRAINER_M, sPartnerTextsCoolTrainerM},
    {FACILITY_CLASS_COOLTRAINER_F, sPartnerTextsCoolTrainerF},
    {FACILITY_CLASS_POKEMANIAC, sPartnerTextsPokemaniac},
    {FACILITY_CLASS_KINDLER, sPartnerTextsKindler},
    {FACILITY_CLASS_CAMPER, sPartnerTextsCamper},
    {FACILITY_CLASS_PICNICKER, sPartnerTextsPicnicker},
    {FACILITY_CLASS_PSYCHIC_M, sPartnerTextsPsychicM},
    {FACILITY_CLASS_PSYCHIC_F, sPartnerTextsPsychicF},
    {FACILITY_CLASS_SCHOOL_KID_F, sPartnerTextsSchoolKidF},
    {FACILITY_CLASS_PKMN_BREEDER_F, sPartnerTextsPkmnBreederF},
    {FACILITY_CLASS_POKEFAN_F, sPartnerTextsPokefanF},
    {FACILITY_CLASS_SWIMMER_F, sPartnerTextsSwimmerF},
    {FACILITY_CLASS_SWIMMING_TRIATHLETE_M, sPartnerTextsSwimmingTriathleteM},
    {FACILITY_CLASS_SWIMMING_TRIATHLETE_F, sPartnerTextsSwimmingTriathleteF},
    {FACILITY_CLASS_SWIMMER_M, sPartnerTextsSwimmerM},
};

static const u8 *const *const sPartnerApprenticeTextTables[NUM_APPRENTICES] BATTLE_TOWER_PARTNER_TEXT_DATA =
{
    sPartnerApprenticeTexts1,
    sPartnerApprenticeTexts2,
    sPartnerApprenticeTexts3,
    sPartnerApprenticeTexts4,
    sPartnerApprenticeTexts5,
    sPartnerApprenticeTexts6,
    sPartnerApprenticeTexts7,
    sPartnerApprenticeTexts8,
    sPartnerApprenticeTexts9,
    sPartnerApprenticeTexts10,
    sPartnerApprenticeTexts11,
    sPartnerApprenticeTexts12,
    sPartnerApprenticeTexts13,
    sPartnerApprenticeTexts14,
    sPartnerApprenticeTexts15,
    sPartnerApprenticeTexts16,
};

#undef PARTNER_TEXTS
