// Generated by tools/generate_pokedex_data.py from the verified JP ROM manifest.
// Keep this include in src/pokedex.c so its final owner follows pokeemerald.

#define POKEDEX_TEXT_DATA __attribute__((section(".rodata.pokedex_text"), aligned(1)))

// 0x08539C50 is the byte-exact empty description used before gDummyPokedexText.
const u8 gText_EmptyPokedexDescription[] POKEDEX_TEXT_DATA = _("");

// 0x539C51
const u8 gDummyPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたらしく　はっけんされたポケモン\n"
    "げんざい　ちょうさちゅう");

// 0x539C70
const u8 gBulbasaurPokedexText[] POKEDEX_TEXT_DATA = _(
    "ひなたで　ひるねを　する　すがたを　みかける。\n"
    "たいようの　ひかりを　いっぱい　あびることで\n"
    "せなかの　タネが　おおきく　そだつのだ。");

// 0x539CB4
const u8 gIvysaurPokedexText[] POKEDEX_TEXT_DATA = _(
    "つぼみを　ささえるため　あしこしが　つよくなる。\n"
    "ひなたで　じっとする　じかんが　ながくなれば\n"
    "いよいよ　たいりんの　はなが　さくころだ。");

// 0x539CFA
const u8 gVenusaurPokedexText[] POKEDEX_TEXT_DATA = _(
    "じゅうぶんな　えいようと　たいようの　ひかりが\n"
    "はなの　いろを　あざやかに　すると　いわれる。\n"
    "はなの　かおりは　ひとの　こころを　いやす。");

// 0x539D41
const u8 gCharmanderPokedexText[] POKEDEX_TEXT_DATA = _(
    "しっぽの　ほのおは　きぶんを　ひょうげん。\n"
    "たのしい　ときには　ゆらゆら　ほのおが　ゆれて\n"
    "おこった　ときには　めらめら　さかんに　もえる。");

// 0x539D88
const u8 gCharmeleonPokedexText[] POKEDEX_TEXT_DATA = _(
    "するどい　ツメで　ようしゃなく　たたきのめす。\n"
    "きょうてきと　むかいあうと　きぶんが　たかぶり\n"
    "しっぽの　ほのおが　あおじろく　もえあがる。");

// 0x539DCF
const u8 gCharizardPokedexText[] POKEDEX_TEXT_DATA = _(
    "つよい　あいてを　もとめて　そらを　とびまわる。\n"
    "なんでも　とかして　しまう　こうねつの　ほのおを\n"
    "じぶんより　よわいものに　むけることは　しない。");

// 0x539E1A
const u8 gSquirtlePokedexText[] POKEDEX_TEXT_DATA = _(
    "こうらの　やくめは　みを　まもる　だけではない。\n"
    "まるい　かたちと　ひょうめんの　みぞが　みずの\n"
    "ていこうを　へらすので　はやく　およげるのだ。");

// 0x539E63
const u8 gWartortlePokedexText[] POKEDEX_TEXT_DATA = _(
    "ふさふさの　けで　おおわれた　おおきな　しっぽは\n"
    "ながいき　するほど　ふかい　いろあいに　かわる。\n"
    "こうらの　キズは　つわものの　あかし。");

// 0x539EA9
const u8 gBlastoisePokedexText[] POKEDEX_TEXT_DATA = _(
    "こうらの　ふんしゃこうの　ねらいは　せいかく。\n"
    "みずの　だんがんを　50メートル　はなれた\n"
    "あきかんに　めいちゅうさせる　ことが　できるぞ。");

// 0x539EF0
const u8 gCaterpiePokedexText[] POKEDEX_TEXT_DATA = _(
    "からだ　よりも　おおきな　はっぱを　みるみる\n"
    "たべつくして　しまうほどの　しょくよくを　もつ。\n"
    "しょっかくから　きょうれつな　においを　だすぞ。");

// 0x539F39
const u8 gMetapodPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだの　カラは　てっぱんの　ように　かたい。\n"
    "あまり　うごかないのは　カラのなかで　やわらかい\n"
    "なかみが　しんかの　じゅんびを　しているからだ。");

// 0x539F83
const u8 gButterfreePokedexText[] POKEDEX_TEXT_DATA = _(
    "おいしい　はなの　ミツを　さがす　のうりょくに\n"
    "すぐれ　すみかから　10キロはなれた　ばしょに\n"
    "さく　はなから　ミツを　あつめて　はこんでいる。");

// 0x539FCC
const u8 gWeedlePokedexText[] POKEDEX_TEXT_DATA = _(
    "とても　するどい　きゅうかくを　もっている。\n"
    "こうぶつの　はっぱか　きらいな　はっぱか\n"
    "おおきな　あかい　はなで　かぎわける。");

// 0x53A00C
const u8 gKakunaPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほとんど　うごかず　きに　つかまっているが\n"
    "なかでは　しんかの　じゅんびで　おおいそがし。\n"
    "その　しょうこに　からだが　あつくなっているぞ。");

// 0x53A053
const u8 gBeedrillPokedexText[] POKEDEX_TEXT_DATA = _(
    "なわばりいしきが　とても　つよいので　スピアーの\n"
    "すみかには　ちかづかない　ほうが　みの　ためだ。\n"
    "おこると　しゅうだんで　おそって　くるぞ。");

// 0x53A09B
const u8 gPidgeyPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほうこう　かんかくに　とても　すぐれているので\n"
    "どんなに　はなれた　ばしょからでも　まよわずに\n"
    "じぶんの　す　まで　かえる　ことが　できる。");

// 0x53A0E2
const u8 gPidgeottoPokedexText[] POKEDEX_TEXT_DATA = _(
    "ひろい　なわばりを　とんで　みまわりを　する。\n"
    "なわばりを　あらす　あいては　ようしゃ　しない。\n"
    "するどい　ツメで　てっていてきに　こらしめるぞ。");

// 0x53A12C
const u8 gPidgeotPokedexText[] POKEDEX_TEXT_DATA = _(
    "うつくしい　こうたくの　はねを　もつ　ポケモン。\n"
    "あたまの　はねの　うつくしさに　こころ　うばわれ\n"
    "ピジョットを　そだてる　トレーナーも　おおい。");

// 0x53A176
const u8 gRattataPokedexText[] POKEDEX_TEXT_DATA = _(
    "けいかいしんが　とても　つよく　ねている　ときも\n"
    "みみを　うごかし　まわりの　おとを　きいている。\n"
    "どこにでも　すみつき　す　を　つくる。");

// 0x53A1BC
const u8 gRaticatePokedexText[] POKEDEX_TEXT_DATA = _(
    "じょうぶな　キバは　どんどん　のびるので\n"
    "いわや　たいぼくを　かじって　けずっている。\n"
    "いえの　カベを　かじられる　ことも　あるよ。");

// 0x53A1FF
const u8 gSpearowPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　なきごえは　1キロ　さきまで　とどく。\n"
    "あちこちで　カンだかい　こえが　きこえる　ときは\n"
    "なかまたちに　きけんを　しらせている　あいずだ。");

// 0x53A24A
const u8 gFearowPokedexText[] POKEDEX_TEXT_DATA = _(
    "ながい　くびと　くちばしは　つちや　みずの\n"
    "なかに　いる　エサを　つかまえるのに　べんり。\n"
    "ほそながい　くちばしで　きように　つまむぞ。");

// 0x53A28F
const u8 gEkansPokedexText[] POKEDEX_TEXT_DATA = _(
    "ぐるぐる　からだを　まいて　やすんでいるのは\n"
    "どの　ほうこうから　てきが　おそってきても\n"
    "とっさに　あたまを　むけて　いかくできるからだ。");

// 0x53A2D5
const u8 gArbokPokedexText[] POKEDEX_TEXT_DATA = _(
    "しめつける　ちからは　とても　きょうりょく。\n"
    "ドラムかんも　ぺしゃんこに　してしまうぞ。\n"
    "まきつかれたら　にげだす　ことは　ふかのうだ。");

// 0x53A31A
const u8 gPikachuPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほっぺたの　でんきぶくろに　でんきを　ためる。\n"
    "おもいっきり　ほうでんすると　かみなりに\n"
    "ひってきする　でんきを　はなつ　ことが　できる。");

// 0x53A360
const u8 gRaichuPokedexText[] POKEDEX_TEXT_DATA = _(
    "でんきが　たまりすぎると　こうげきてきな\n"
    "せいかくに　かわるため　たまに　ほうでんして\n"
    "きもちを　おちつける　こうどうを　とる。");

// 0x53A3A1
const u8 gSandshrewPokedexText[] POKEDEX_TEXT_DATA = _(
    "まるくなると　どんな　こうげきでも　はねかえす。\n"
    "さばくで　せいかつしている　うちに　からだの\n"
    "ひょうめんが　カチカチに　かたく　へんかした。");

// 0x53A3E9
const u8 gSandslashPokedexText[] POKEDEX_TEXT_DATA = _(
    "てきの　こうげきを　ふせぐときだけでなく\n"
    "きおんが　きゅうじょうしょうする　にっちゅうは\n"
    "にっしゃびょうを　ふせぐために　まるくなる。");

// 0x53A42D
const u8 gNidoranFPokedexText[] POKEDEX_TEXT_DATA = _(
    "ちいさい　からだを　まもるため　きょうりょくな\n"
    "どくばりが　はったつしたと　かんがえられている。\n"
    "おこると　ツノの　さきから　もうどくを　だす。");

// 0x53A476
const u8 gNidorinaPokedexText[] POKEDEX_TEXT_DATA = _(
    "なかまや　かぞくと　いっしょの　ときは　おたがい\n"
    "きずつかないように　トゲが　ひっこんでいる。\n"
    "なかまから　はなれると　ふあんに　なるらしい。");

// 0x53A4BE
const u8 gNidoqueenPokedexText[] POKEDEX_TEXT_DATA = _(
    "かたい　ウロコで　おおわれた　からだを　ぶつけて\n"
    "あいてを　はじきとばす　こうげきが　とくいだ。\n"
    "こどもを　まもる　ときが　いちばん　つよい。");

// 0x53A506
const u8 gNidoranMPokedexText[] POKEDEX_TEXT_DATA = _(
    "みみを　うごかす　きんにくが　はったつしていて\n"
    "どんな　むきにも　じざいに　みみを　うごかせる。\n"
    "かすかな　ものおとも　ききもらさない　ポケモン。");

// 0x53A550
const u8 gNidorinoPokedexText[] POKEDEX_TEXT_DATA = _(
    "ダイヤモンドよりも　かたい　ツノを　もつ。\n"
    "てきの　けはいを　かんじると　せなかの　トゲが\n"
    "いっせいに　さかだち　ぜんりょくで　たちむかう。");

// 0x53A597
const u8 gNidokingPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふとい　しっぽの　ひとふりは　がんじょうな\n"
    "てっとうも　へしおる　すさまじい　はかいりょく。\n"
    "いちど　あばれだすと　てが　つけられない。");

// 0x53A5DC
const u8 gClefairyPokedexText[] POKEDEX_TEXT_DATA = _(
    "まんげつの　よるは　げんき　いっぱいに　あそぶ。\n"
    "あけがた　つかれた　ピッピたちは　しずかな\n"
    "やまおくで　なかまたちと　よりそって　ねむる。");

// 0x53A623
const u8 gClefablePokedexText[] POKEDEX_TEXT_DATA = _(
    "つばさを　つかって　とぶように　スキップ。\n"
    "すいめんを　あるく　ことだって　できるのだ。\n"
    "しずかな　つきよに　みずうみを　あるく。");

// 0x53A665
const u8 gVulpixPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほのおを　あやつり　ひとだまの　ように　とばす。\n"
    "しんかする　ちょくぜんに　なると　6ぽんの\n"
    "しっぽが　もえたように　ねつを　おびる。");

// 0x53A6A9
const u8 gNinetalesPokedexText[] POKEDEX_TEXT_DATA = _(
    "9ほんの　しっぽには　それぞれ　ふしぎな\n"
    "ちからが　やどっていると　いいつたえられる。\n"
    "ながいきの　キュウコンは　たいもうが　きんいろ。");

// 0x53A6EE
const u8 gJigglypuffPokedexText[] POKEDEX_TEXT_DATA = _(
    "プリンの　うたで　ねむらない　ものは　いない。\n"
    "うたごえの　おとの　なみは　じゅくすいしている\n"
    "ときの　のうはと　おなじ　かたちを　している。");

// 0x53A736
const u8 gWigglytuffPokedexText[] POKEDEX_TEXT_DATA = _(
    "ごくじょうの　けなみを　もつ　ポケモン。\n"
    "プクリンと　そいねすると　さいこうの　ねごこち。\n"
    "いきを　すうと　からだが　どんどん　ふくらむ。");

// 0x53A77C
const u8 gZubatPokedexText[] POKEDEX_TEXT_DATA = _(
    "まっくらな　どうくつで　せいかつしている　うちに\n"
    "りょうめが　ふさがり　みえなくなってしまった。\n"
    "ちょうおんぱで　しょうがいぶつを　たんちする。");

// 0x53A7C5
const u8 gGolbatPokedexText[] POKEDEX_TEXT_DATA = _(
    "かたい　ひふでも　らくらく　つらぬく　キバ。\n"
    "ひとや　ポケモンの　けつえきが　だいこうぶつ。\n"
    "くらやみを　とびまわり　はいごから　おそう。");

// 0x53A80B
const u8 gOddishPokedexText[] POKEDEX_TEXT_DATA = _(
    "つきあかりを　あびて　せいちょうする　ポケモン。\n"
    "ひるまは　はっぱだけを　だして　じめんに\n"
    "うまっているので　てきから　みつかりにくいのだ。");

// 0x53A852
const u8 gGloomPokedexText[] POKEDEX_TEXT_DATA = _(
    "くちから　たれている　みつの　においを　かぐと\n"
    "あまりの　くささに　きおくが　なくなる　らしい。\n"
    "むしろ　この　においを　このむ　マニアも　いる。");

// 0x53A89C
const u8 gVileplumePokedexText[] POKEDEX_TEXT_DATA = _(
    "かふんの　ふえる　きせつは　ラフレシアが\n"
    "あるくと　まわりの　くうきが　きいろく　なる。\n"
    "かふんは　からだを　しびれさせる　もうどく。");

// 0x53A8E0
const u8 gParasPokedexText[] POKEDEX_TEXT_DATA = _(
    "パラスから　ようぶんを　すいとって　おおきくなる\n"
    "キノコは　とうちゅうかそう　と　よばれている。\n"
    "ちょうじゅの　くすりになる　きちょうな　キノコ。");

// 0x53A92A
const u8 gParasectPokedexText[] POKEDEX_TEXT_DATA = _(
    "パラセクトは　しゅうだんで　たいぼくの　ねもとに\n"
    "くっついて　えいようを　すいとってしまう。\n"
    "かれると　いっせいに　べつの　きに　いどうする。");

// 0x53A972
const u8 gVenonatPokedexText[] POKEDEX_TEXT_DATA = _(
    "みを　まもるために　ほそく　かたい　たいもうが\n"
    "ぜんしんを　おおうように　なったと　いわれる。\n"
    "ちいさな　えものも　みのがさない　めを　もつ。");

// 0x53A9BA
const u8 gVenomothPokedexText[] POKEDEX_TEXT_DATA = _(
    "やこうせいで　よるに　かつどうを　はじめる。\n"
    "がいとうの　あかりに　さそわれ　あつまった\n"
    "ちいさな　むしを　このんで　たべる。");

// 0x53A9FA
const u8 gDiglettPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほとんどの　のうかは　ディグダを　そだてている。\n"
    "ディグダが　あなを　ほった　とちは　ほどよく\n"
    "たがやされ　おいしい　やさいが　つくれるからだ。");

// 0x53AA43
const u8 gDugtrioPokedexText[] POKEDEX_TEXT_DATA = _(
    "もともと　ひとつの　からだから　3つごに\n"
    "なったので　みんな　かんがえることは　おなじ。\n"
    "ちからを　あわせ　どこまでも　ほりすすむ。");

// 0x53AA86
const u8 gMeowthPokedexText[] POKEDEX_TEXT_DATA = _(
    "するどい　ツメを　ひっこめて　ぬきあし　さしあし\n"
    "あしおとを　たてずに　あるくことが　できる。\n"
    "キラキラ　ひかる　コインが　なぜか　だいすきだ。");

// 0x53AACF
const u8 gPersianPokedexText[] POKEDEX_TEXT_DATA = _(
    "たくましい　6ぽんの　ヒゲは　くうきの　うごきで\n"
    "まわりの　ようすを　キャッチする　やくわり。\n"
    "ヒゲを　つかまれると　おとなしくなって　しまう。");

// 0x53AB18
const u8 gPsyduckPokedexText[] POKEDEX_TEXT_DATA = _(
    "ずつうが　はげしくなると　ふしぎな　ちからを\n"
    "つかいだすが　そのときの　きおくは　のこらない。\n"
    "おもいだせないので　くびを　かしげているのだ。");

// 0x53AB60
const u8 gGolduckPokedexText[] POKEDEX_TEXT_DATA = _(
    "およぎが　とくいな　ゴルダックは　すいえい\n"
    "せんしゅの　とっくんに　つきあう　ことも　ある。\n"
    "ひたいが　かがやくとき　じんつうりきを　つかう。");

// 0x53ABA8
const u8 gMankeyPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだが　ふるえ　はないきが　あらくなれば\n"
    "おこりだす　まえぶれ　なのだが　あっというまに\n"
    "はげしく　おこるので　にげだす　ひまは　ない。");

// 0x53ABEE
const u8 gPrimeapePokedexText[] POKEDEX_TEXT_DATA = _(
    "はげしく　おこる　ことで　けっこうが　よくなり\n"
    "きんにくの　ちからを　つよくするのだ。\n"
    "ただし　あたまの　かいてんは　おそくなるぞ。");

// 0x53AC31
const u8 gGrowlithePokedexText[] POKEDEX_TEXT_DATA = _(
    "きゅうかくに　すぐれ　いちど　かいだ　においは\n"
    "なにが　あっても　ぜったいに　わすれない。\n"
    "あいての　きもちを　においで　さっちする。");

// 0x53AC75
const u8 gArcaninePokedexText[] POKEDEX_TEXT_DATA = _(
    "10000キロの　きょりを　いっちゅうやで\n"
    "はしると　いわれている　かいそくの　ポケモン。\n"
    "たいないで　もえさかる　ほのおが　パワーとなる。");

// 0x53ACBC
const u8 gPoliwagPokedexText[] POKEDEX_TEXT_DATA = _(
    "うずまき　もようの　ないぞうが　すけてしまうほど\n"
    "うすい　ひふだが　するどい　キバを　はねかえす\n"
    "だんりょくを　もっているのだ。");

// 0x53ACFD
const u8 gPoliwhirlPokedexText[] POKEDEX_TEXT_DATA = _(
    "いつも　からだの　ひょうめんが　えきたいで\n"
    "ぬるぬる　ぬれているため　てきに　つかまっても\n"
    "ぬるりと　すりぬけ　にげる　ことが　できるぞ。");

// 0x53AD43
const u8 gPoliwrathPokedexText[] POKEDEX_TEXT_DATA = _(
    "はったつした　きょうじんな　きんにくは　どんなに\n"
    "うんどうしても　つかれる　ことは　ない。\n"
    "たいへいようも　かるく　おうだん　できるほどだ。");

// 0x53AD8A
const u8 gAbraPokedexText[] POKEDEX_TEXT_DATA = _(
    "1にち　18じかん　ねむる　ポケモン。\n"
    "かんさつの　けっか　1じかんごとに　テレポートで\n"
    "ばしょを　いどうしている　ことが　わかった。");

// 0x53ADCE
const u8 gKadabraPokedexText[] POKEDEX_TEXT_DATA = _(
    "ちょうのうりょくの　けんきゅうを　てつだっていた\n"
    "エスパーしょうねんが　あるとき　とつぜん\n"
    "ユンゲラーに　なったと　うわさ　されているのだ。");

// 0x53AE15
const u8 gAlakazamPokedexText[] POKEDEX_TEXT_DATA = _(
    "つよい　ちょうのうりょくと　たかい　ちのうを\n"
    "もっているが　きんりょくは　とても　よわい。\n"
    "ちょうのうりょくで　からだを　うごかしている。");

// 0x53AE5B
const u8 gMachopPokedexText[] POKEDEX_TEXT_DATA = _(
    "あらゆる　かくとうぎを　マスターする　ために\n"
    "きびしい　トレーニングを　つづけている。\n"
    "ちからもちで　すもうとりも　らくらく　かつぐ。");

// 0x53AE9F
const u8 gMachokePokedexText[] POKEDEX_TEXT_DATA = _(
    "こしに　まいた　ベルトは　ゴーリキーの\n"
    "ありあまる　パワーを　せいぎょする　ため。\n"
    "きけんなので　だれも　はずした　ことが　ない。");

// 0x53AEE1
const u8 gMachampPokedexText[] POKEDEX_TEXT_DATA = _(
    "4ほんの　うでから　くりだされる　パンチや\n"
    "チョップを　ふせぐ　ことは　ふかのうだ。\n"
    "きょうてきに　であうと　とうしを　もやす。");

// 0x53AF22
const u8 gBellsproutPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほそく　しなやかな　からだは　どんな　つよい\n"
    "こうげきでも　しなって　よける　ことが　できる。\n"
    "くちから　てつも　とかしてしまう　えきを　だす。");

// 0x53AF6B
const u8 gWeepinbellPokedexText[] POKEDEX_TEXT_DATA = _(
    "よるに　なると　おしりの　フックを　きの　えだに\n"
    "ひっかけて　ぶらさがり　ねむりに　つく。\n"
    "ねぞうが　わるいと　あさ　おっこちているよ。");

// 0x53AFB0
const u8 gVictreebelPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたまに　ついている　ながい　つるを　ちいさな\n"
    "いきものに　みえる　うごきで　えものを　さそい\n"
    "ちかづいてきた　ところを　ぱくりと　ひとのみ。");

// 0x53AFF8
const u8 gTentacoolPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだの　ほとんどが　すいぶんで　できている。\n"
    "2ほんの　ながい　しょくしゅを　てきに　からませ\n"
    "せんたんに　ついている　どくばりを　つきさすぞ。");

// 0x53B042
const u8 gTentacruelPokedexText[] POKEDEX_TEXT_DATA = _(
    "いりくんだ　かいていの　いわばに　せいそく。\n"
    "80ぽんの　しょくしゅで　えものを　とらえる。\n"
    "こうふんすると　あかい　たまが　はっこうする。");

// 0x53B089
const u8 gGeodudePokedexText[] POKEDEX_TEXT_DATA = _(
    "りょううでの　ちからだけで　やまみちを　のぼる。\n"
    "みちばたの　いしと　そっくりなので　とざんしゃが\n"
    "きづかずに　ふみつけてしまう　ことが　ある。");

// 0x53B0D2
const u8 gGravelerPokedexText[] POKEDEX_TEXT_DATA = _(
    "きゅうしゃめんを　ころがり　やまを　おりていく。\n"
    "ゆくてを　ふさぐ　たいぼくや　おおいわは\n"
    "たいあたりで　なぎたおしてしまう　あらあらしさ。");

// 0x53B119
const u8 gGolemPokedexText[] POKEDEX_TEXT_DATA = _(
    "さんちょうの　かこうに　すみかが　あるという。\n"
    "1ねんに　1かい　だっぴして　おおきくなる。\n"
    "だっぴした　カラは　くずれて　つちに　かえる。");

// 0x53B160
const u8 gPonytaPokedexText[] POKEDEX_TEXT_DATA = _(
    "うまれて　すぐは　たちあがるのも　やっとだが\n"
    "ころびながら　おやの　あとを　おいかけている\n"
    "うちに　じょうぶな　あしこしに　そだつのだ。");

// 0x53B1A5
const u8 gRapidashPokedexText[] POKEDEX_TEXT_DATA = _(
    "いつもは　のんびり　のはらを　かけまわっているが\n"
    "ひとたび　ほんきを　だすと　たてがみの　ほのおが\n"
    "もえあがり　じそく240キロで　はしりだす。");

// 0x53B1EE
const u8 gSlowpokePokedexText[] POKEDEX_TEXT_DATA = _(
    "しっぽを　かわに　いれて　エサを　つっているが\n"
    "そのうち　なにを　しているのか　わすれてしまい\n"
    "かわべりに　ねそべったまま　1にちを　おえる。");

// 0x53B236
const u8 gSlowbroPokedexText[] POKEDEX_TEXT_DATA = _(
    "シェルダーが　かみついて　いるので　しっぽで\n"
    "エサを　つれなくなった　ヤドランは　しぶしぶ\n"
    "すいちゅうを　およいで　エサを　つかまえている。");

// 0x53B27D
const u8 gMagnemitePokedexText[] POKEDEX_TEXT_DATA = _(
    "さゆうの　ユニットは　きょうりょくな　じしゃく。\n"
    "はんけい　100メートル　いないの　てつを\n"
    "ひきよせるほどの　つよい　じりょくを　だす。");

// 0x53B2C3
const u8 gMagnetonPokedexText[] POKEDEX_TEXT_DATA = _(
    "3ひきの　コイルが　じりょくで　つながっている。\n"
    "つよい　でんぱを　だしているため　はんけい\n"
    "1キロの　はんいでは　きおんが　2ど　あがる。");

// 0x53B30A
const u8 gFarfetchdPokedexText[] POKEDEX_TEXT_DATA = _(
    "もっている　しょくぶつの　クキにも　よいものと\n"
    "そうでない　ものが　あるらしく　カモネギどうしが\n"
    "クキを　めぐって　たたかう　ことが　ある。");

// 0x53B351
const u8 gDoduoPokedexText[] POKEDEX_TEXT_DATA = _(
    "しょくじの　ときも　ねている　ときも　どちらかの\n"
    "あたまが　つねに　まわりを　けいかいしている。\n"
    "きけんになると　じそく100キロで　にげる。");

// 0x53B399
const u8 gDodrioPokedexText[] POKEDEX_TEXT_DATA = _(
    "3つの　あたまを　もつ　ちんしゅの　ポケモン。\n"
    "あめの　ふらない　かんそうした　きせつでも\n"
    "げんきに　そうげんを　はしりまわる。");

// 0x53B3DA
const u8 gSeelPokedexText[] POKEDEX_TEXT_DATA = _(
    "こおりに　おおわれた　うみで　エサを　とる。\n"
    "いきつぎを　するときは　あたまの　でっぱりで\n"
    "こおりを　わって　うみから　かおを　だす。");

// 0x53B41E
const u8 gDewgongPokedexText[] POKEDEX_TEXT_DATA = _(
    "つめたい　こおりの　うえで　ねるのが　だいすき。\n"
    "むかし　ひょうざんで　ねむる　すがたを　みた\n"
    "ふなのりが　にんぎょと　まちがえた。");

// 0x53B461
const u8 gGrimerPokedexText[] POKEDEX_TEXT_DATA = _(
    "おせんされた　うみの　ヘドロから　うまれた\n"
    "ベトベターは　きたない　ものが　だいこうぶつ。\n"
    "こうじょうから　でる　はいえきが　しょくりょう。");

// 0x53B4A8
const u8 gMukPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたたかく　しっけの　おおい　とちを　このむ。\n"
    "なつばは　たいないの　どくそが　さらに　つよまり\n"
    "なまごみが　くさったような　においを　だす。");

// 0x53B4F0
const u8 gShellderPokedexText[] POKEDEX_TEXT_DATA = _(
    "よるに　なると　おおきな　ベロで　かいていの\n"
    "すなに　あなを　ほり　そのなかで　ねむる。\n"
    "カラを　とじて　ねむるが　ベロは　だしたまま。");

// 0x53B535
const u8 gCloysterPokedexText[] POKEDEX_TEXT_DATA = _(
    "のみこんだ　かいすいを　うしろへ　いきおい　よく\n"
    "ふんしゃする　ことで　うみの　なかを　およぐ。\n"
    "トゲを　はっしゃする　しくみも　おなじ。");

// 0x53B57B
const u8 gGastlyPokedexText[] POKEDEX_TEXT_DATA = _(
    "きょうふうを　うけると　ガスじょうの　からだは\n"
    "みるみる　ふきとばされ　ちいさくなって　しまう。\n"
    "かぜを　さけた　ゴースが　のきしたに　あつまる。");

// 0x53B5C5
const u8 gHaunterPokedexText[] POKEDEX_TEXT_DATA = _(
    "やみに　うかぶ　ゴーストが　てまねきしても\n"
    "ぜったいに　ちかよっては　いけないよ。\n"
    "ペロリと　なめられ　いのちを　すわれてしまうぞ。");

// 0x53B608
const u8 gGengarPokedexText[] POKEDEX_TEXT_DATA = _(
    "まよなか　がいとうの　あかりで　できた　かげが\n"
    "じぶんを　おいこして　いくのは　ゲンガーが\n"
    "かげに　なりすまして　はしって　いくからだ。");

// 0x53B64D
const u8 gOnixPokedexText[] POKEDEX_TEXT_DATA = _(
    "のうみそに　じしゃくが　あるので　つちの　なかを\n"
    "ほり　すすんでいても　ほうこうを　まちがえない。\n"
    "としを　とるほど　からだは　まるみを　おびる。");

// 0x53B697
const u8 gDrowzeePokedexText[] POKEDEX_TEXT_DATA = _(
    "ねむっているとき　キミの　はなが　ムズムズしたら\n"
    "まくらもとに　たった　スリープが　はなの\n"
    "あなから　ゆめを　たべようとしている　あいず。");

// 0x53B6DD
const u8 gHypnoPokedexText[] POKEDEX_TEXT_DATA = _(
    "てに　もっている　ふりこの　うごきと　かがやきが\n"
    "あいてを　ふかい　さいみんじょうたいに　おとす。\n"
    "えものを　さがしながら　ふりこを　みがいている。");

// 0x53B728
const u8 gKrabbyPokedexText[] POKEDEX_TEXT_DATA = _(
    "すなはまに　あなを　ほり　そこで　くらしている。\n"
    "エサの　すくない　すなはまでは　ばしょとりをする\n"
    "クラブたちの　あらそいを　みる　ことが　できる。");

// 0x53B773
const u8 gKinglerPokedexText[] POKEDEX_TEXT_DATA = _(
    "キングラーは　きょだいな　ハサミを　ふって\n"
    "なかまどうしで　あいずを　おくりあっているが\n"
    "ハサミが　おもすぎて　すぐに　つかれてしまう。");

// 0x53B7B8
const u8 gVoltorbPokedexText[] POKEDEX_TEXT_DATA = _(
    "なぜか　モンスターボールに　すがたが　にている。\n"
    "すこしの　しげきで　だいばくはつ　してしまうため\n"
    "ベテラン　トレーナーも　あつかいは　しんちょう。");

// 0x53B803
const u8 gElectrodePokedexText[] POKEDEX_TEXT_DATA = _(
    "はつでんしょに　たいりょうはっせいする。\n"
    "でんきを　たべてしまうため　ちかくの　まちでは\n"
    "だいていでんが　おこり　おおさわぎに　なる。");

// 0x53B847
const u8 gExeggcutePokedexText[] POKEDEX_TEXT_DATA = _(
    "なかまおもいの　6この　たまごは　おたがいに\n"
    "ひきつけあい　くるくる　かいてんしている。\n"
    "カラの　ヒビが　ふえると　しんかは　まぢかだ。");

// 0x53B88C
const u8 gExeggutorPokedexText[] POKEDEX_TEXT_DATA = _(
    "なんごく　うまれの　ナッシーの　あたまは　つよい\n"
    "ひざしを　いっぱい　あびて　どんどん　そだち\n"
    "じめんに　おちると　タマタマに　なると　いう。");

// 0x53B8D4
const u8 gCubonePokedexText[] POKEDEX_TEXT_DATA = _(
    "2どと　あえない　ははおやの　おもかげを\n"
    "まんげつに　みつけて　なきごえを　あげる。\n"
    "かぶっている　ホネの　しみは　なみだの　あと。");

// 0x53B917
const u8 gMarowakPokedexText[] POKEDEX_TEXT_DATA = _(
    "ははおやに　あえない　かなしみを　のりこえた\n"
    "カラカラが　たくましく　しんかした　すがた。\n"
    "きたえられた　こころは　かんたんに　くじけない。");

// 0x53B95E
const u8 gHitmonleePokedexText[] POKEDEX_TEXT_DATA = _(
    "じざいに　のびちぢみする　あしで　きょうれつな\n"
    "キックを　はなち　あいてを　けりたおす。\n"
    "たたかいの　あと　つかれた　あしを　もみほぐす。");

// 0x53B9A4
const u8 gHitmonchanPokedexText[] POKEDEX_TEXT_DATA = _(
    "せかいチャンピオンを　めざしていた　ボクサーの\n"
    "たましいが　やどったと　いわれる　エビワラーは\n"
    "ふくつの　せいしんで　ぜったいに　へこたれない。");

// 0x53B9ED
const u8 gLickitungPokedexText[] POKEDEX_TEXT_DATA = _(
    "はじめて　めに　する　ものは　かならず　ペロリ。\n"
    "したざわりと　あじで　きおくしているのだ。\n"
    "でも　すっぱい　ものは　ちょっと　にがて。");

// 0x53BA32
const u8 gKoffingPokedexText[] POKEDEX_TEXT_DATA = _(
    "ドガースに　ちかづくと　うすい　ひふを　とおして\n"
    "どくガスの　うずまく　ようすを　かんさつできる。\n"
    "すこしの　しげきで　だいばくはつを　おこす。");

// 0x53BA7B
const u8 gWeezingPokedexText[] POKEDEX_TEXT_DATA = _(
    "どくガスを　とくしゅな　ほうほうで　うすめると\n"
    "さいこうきゅうの　こうすいが　できあがる。\n"
    "ゴミから　でる　ガスが　さいこうの　ごちそう。");

// 0x53BAC1
const u8 gRhyhornPokedexText[] POKEDEX_TEXT_DATA = _(
    "いちど　はしりだしたら　とまらない。\n"
    "のうみそが　ちいさいので　はしっている　りゆうを\n"
    "わすれてしまうほど　あたまが　わるいのだ。");

// 0x53BB03
const u8 gRhydonPokedexText[] POKEDEX_TEXT_DATA = _(
    "ドリルの　ように　かいてんする　ツノは\n"
    "ひとつきで　こうそうビルを　はかいする。\n"
    "うしろあしで　たちあがり　のうが　はったつした。");

// 0x53BB45
const u8 gChanseyPokedexText[] POKEDEX_TEXT_DATA = _(
    "えいよう　まんてんの　タマゴを　まいにち　うむ。\n"
    "しょくよくを　なくした　ひとでも　ペロリと\n"
    "たべてしまうほど　おいしい　タマゴだ。");

// 0x53BB88
const u8 gTangelaPokedexText[] POKEDEX_TEXT_DATA = _(
    "てきに　つかまれると　ツルは　ぷちっと　きれる。\n"
    "ぜんぜん　いたくないので　その　スキに　にげる。\n"
    "よくじつには　あたらしい　ツルが　はえそろうぞ。");

// 0x53BBD3
const u8 gKangaskhanPokedexText[] POKEDEX_TEXT_DATA = _(
    "ガルーラの　こどもが　1ぴきで　あそんでいても\n"
    "ぜったいに　つかまえたりしては　いけないよ。\n"
    "ちかくに　いる　おやが　はげしく　おこりだすぞ。");

// 0x53BC1B
const u8 gHorseaPokedexText[] POKEDEX_TEXT_DATA = _(
    "せなかの　ヒレを　きように　うごかして\n"
    "まえを　むいたまま　ぜんごさゆうに　いどうする。\n"
    "きけんを　かんじると　スミを　はいて　にげる。");

// 0x53BC60
const u8 gSeadraPokedexText[] POKEDEX_TEXT_DATA = _(
    "ぜんしんを　おおう　もうどくの　トゲは\n"
    "かんぽうやくの　ざいりょうになり　きちょう。\n"
    "すみかに　ちかづく　てきには　ようしゃ　しない。");

// 0x53BCA4
const u8 gGoldeenPokedexText[] POKEDEX_TEXT_DATA = _(
    "はるになると　トサキントの　しゅうだんが\n"
    "たきを　のぼって　じょうりゅうへ　むかう。\n"
    "いっぽんヅノの　こうげきは　きょうれつ。");

// 0x53BCE4
const u8 gSeakingPokedexText[] POKEDEX_TEXT_DATA = _(
    "かわぞこの　いわに　ツノで　あなを　あける。\n"
    "タマゴが　きゅうりゅうに　ながされたり　てきに\n"
    "おそわれない　ための　かしこい　くふう。");

// 0x53BD28
const u8 gStaryuPokedexText[] POKEDEX_TEXT_DATA = _(
    "よぞらの　ほしの　またたきに　あわせて\n"
    "しゅうだんで　あかい　コアを　てんめつさせる。\n"
    "からだの　いちぶが　ちぎれても　さいせいする。");

// 0x53BD6C
const u8 gStarmiePokedexText[] POKEDEX_TEXT_DATA = _(
    "おだやかな　うみに　うつった　よぞらの　ほしが\n"
    "すがたを　かえて　スターミーに　なったと\n"
    "おおむかしの　ひとは　くうそうしていた。");

// 0x53BDAE
const u8 gMrMimePokedexText[] POKEDEX_TEXT_DATA = _(
    "めに　みえない　ものを　みぶりで　そこに　あると\n"
    "しんじこませる　パントマイムの　たつじん。\n"
    "しんじさせた　ものは　ほんとうに　あらわれる。");

// 0x53BDF5
const u8 gScytherPokedexText[] POKEDEX_TEXT_DATA = _(
    "めにも　とまらぬ　スピードが　りょううでの\n"
    "カマの　きれあじを　さらに　するどく　するのだ。\n"
    "ひとふり　すれば　たいぼくも　まっぷたつだ。");

// 0x53BE3B
const u8 gJynxPokedexText[] POKEDEX_TEXT_DATA = _(
    "おどるような　こしつきで　リズミカルに　あるく。\n"
    "その　うごきは　みている　ひとも　おもわず\n"
    "こしを　ふってしまうほど　かろやかなのだ。");

// 0x53BE80
const u8 gElectabuzzPokedexText[] POKEDEX_TEXT_DATA = _(
    "あらしが　くると　きの　うえ　など　カミナリの\n"
    "おちそうな　たかい　ばしょへ　きそって　のぼる。\n"
    "ひらいしん　がわりに　する　まちも　ある。");

// 0x53BEC7
const u8 gMagmarPokedexText[] POKEDEX_TEXT_DATA = _(
    "たたかいに　なると　からだから　しゃくねつの\n"
    "ほのおを　ふきあげ　あいてを　いかくする。\n"
    "その　ねっぷうで　まわりの　くさきも　もやすぞ。");

// 0x53BF0D
const u8 gPinsirPokedexText[] POKEDEX_TEXT_DATA = _(
    "ツノは　たいぼくも　へしおる　いりょく。\n"
    "カイロスは　さむさが　にがてな　ポケモン。\n"
    "ひえこむ　よるは　つちの　なかで　ねむる。");

// 0x53BF4E
const u8 gTaurosPokedexText[] POKEDEX_TEXT_DATA = _(
    "いつも　あばれて　いないと　きが　すまない。\n"
    "たたかう　あいてが　いない　ときは　たいぼくに\n"
    "ぶちあたり　なぎたおす　ことで　きを　しずめる。");

// 0x53BF96
const u8 gMagikarpPokedexText[] POKEDEX_TEXT_DATA = _(
    "およぐ　ちからが　よわいため　ながされてしまう。\n"
    "ながれの　よどんだ　ばしょを　のぞいてみれば\n"
    "ながされてきた　コイキングが　たまっているぞ。");

// 0x53BFDE
const u8 gGyaradosPokedexText[] POKEDEX_TEXT_DATA = _(
    "にんげんが　あらそいを　はじめると　あらわれて\n"
    "しゃくねつの　ほのおで　すべてを　やきつくす。\n"
    "ひじょうに　きょうぼうな　ポケモン。");

// 0x53C021
const u8 gLaprasPokedexText[] POKEDEX_TEXT_DATA = _(
    "ひとが　ぜつめつの　ききに　おいこんでしまった。\n"
    "ゆうぐれどきになると　すくなくなった　なかまを\n"
    "さがして　かなしそうな　こえで　うたうと　いう。");

// 0x53C06B
const u8 gDittoPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだの　さいぼうを　くみかえて　へんしんする。\n"
    "おもいだしながら　いぜん　みた　ものに　かわると\n"
    "ちょっと　ちがう　かたちに　なってしまうのだ。");

// 0x53C0B5
const u8 gEeveePokedexText[] POKEDEX_TEXT_DATA = _(
    "くらしている　かんきょうで　とつぜんへんい　する\n"
    "ふあんていな　いでんしを　もつ　ポケモン。\n"
    "いしの　ほうしゃせんが　しんかを　ひきおこす。");

// 0x53C0FC
const u8 gVaporeonPokedexText[] POKEDEX_TEXT_DATA = _(
    "とつぜんへんいに　より　すいちゅうで　せいかつ\n"
    "できる　ように　ヒレと　エラが　はえてきた。\n"
    "みずを　じざいに　あやつる　ちからを　もつ。");

// 0x53C142
const u8 gJolteonPokedexText[] POKEDEX_TEXT_DATA = _(
    "さいぼうの　だす　よわい　でんきを　たいもうの\n"
    "せいでんきで　ぞうふくさせ　カミナリを　おとす。\n"
    "さかだった　たいもうは　でんきを　おびた　はり。");

// 0x53C18C
const u8 gFlareonPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふさふさの　たいもうは　あがりすぎた　たいおんを\n"
    "くうきに　ほうねつして　さげる　きのうを　もつ。\n"
    "たいおんは　さいこう　900ど　まで　あがるぞ。");

// 0x53C1D7
const u8 gPorygonPokedexText[] POKEDEX_TEXT_DATA = _(
    "ぜんしんを　プログラム　データに　もどして\n"
    "でんし　くうかんに　はいる　ことが　できる。\n"
    "コピーガードされて　いるので　コピー　できない。");

// 0x53C21D
const u8 gOmanytePokedexText[] POKEDEX_TEXT_DATA = _(
    "おおむかしに　ぜつめつしたが　にんげんの　てで\n"
    "かせきから　ふっかつさせた　ポケモンの　ひとつ。\n"
    "てきに　おそわれると　かたい　カラに　かくれる。");

// 0x53C267
const u8 gOmastarPokedexText[] POKEDEX_TEXT_DATA = _(
    "しょくしゅを　あやつり　えものを　つかまえる。\n"
    "カラが　おおきく　なりすぎた　ことで　うごきが\n"
    "にぶくなり　ぜつめつしたと　かんがえられている。");

// 0x53C2B0
const u8 gKabutoPokedexText[] POKEDEX_TEXT_DATA = _(
    "かせきから　ふっかつした　ポケモンだが　まれに\n"
    "いきつづけている　カブトを　はっけん　できる。\n"
    "その　すがたは　3おくねん　かわっていない。");

// 0x53C2F7
const u8 gKabutopsPokedexText[] POKEDEX_TEXT_DATA = _(
    "すいちゅうを　およぎ　えものを　とらえていた。\n"
    "みずの　せいかつから　ちじょうで　くらせるように\n"
    "エラや　あし　などが　へんかを　はじめていた。");

// 0x53C340
const u8 gAerodactylPokedexText[] POKEDEX_TEXT_DATA = _(
    "コハクから　とりだした　いでんしを　さいせいして\n"
    "ふっかつした　きょうりゅう　じだいの　ポケモン。\n"
    "そらの　おうじゃだったと　そうぞうされている。");

// 0x53C38A
const u8 gSnorlaxPokedexText[] POKEDEX_TEXT_DATA = _(
    "たべて　ねての　くりかえしで　1にちが　おわる。\n"
    "おおきな　おなかの　うえを　あそびばに　している\n"
    "こどもたちも　いるほど　おとなしい　ポケモンだ。");

// 0x53C3D5
const u8 gArticunoPokedexText[] POKEDEX_TEXT_DATA = _(
    "こおりを　あやつる　でんせつの　とりポケモン。\n"
    "はばたく　ことで　くうきを　つめたく　ひやすので\n"
    "フリーザーが　とぶと　ゆきが　ふると　いわれる。");

// 0x53C41F
const u8 gZapdosPokedexText[] POKEDEX_TEXT_DATA = _(
    "でんきを　あやつる　でんせつの　とりポケモン。\n"
    "ふだんは　カミナリぐもの　なかで　くらしている。\n"
    "カミナリに　うたれると　ちからが　わいてくる。");

// 0x53C468
const u8 gMoltresPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほのおを　あやつる　でんせつの　とりポケモン。\n"
    "からだが　きずつくと　かこうの　マグマに　はいり\n"
    "ぜんしんを　もやして　きずを　いやすと　いう。");

// 0x53C4B1
const u8 gDratiniPokedexText[] POKEDEX_TEXT_DATA = _(
    "ミニリュウが　だっぴを　くりかえして　いるのは\n"
    "からだの　なかで　せいめいの　エネルギーが\n"
    "どんどん　ふくらみ　おさえきれなく　なるからだ。");

// 0x53C4F8
const u8 gDragonairPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　エネルギーを　からだに　ためている。\n"
    "くびと　しっぽの　すいしょうから　エネルギーを\n"
    "ときはなち　あたりの　てんきを　かえると　いう。");

// 0x53C541
const u8 gDragonitePokedexText[] POKEDEX_TEXT_DATA = _(
    "16じかんで　ちきゅうを　1しゅうできる。\n"
    "あらしで　なんぱしかけた　ふねを　みつけると\n"
    "りくちまで　ゆうどうする　やさしい　ポケモン。");

// 0x53C586
const u8 gMewtwoPokedexText[] POKEDEX_TEXT_DATA = _(
    "いでんしそうさに　よって　つくられた　ポケモン。\n"
    "にんげんの　かがくりょくで　からだは　つくれても\n"
    "やさしい　こころを　つくることは　できなかった。");

// 0x53C5D1
const u8 gMewPokedexText[] POKEDEX_TEXT_DATA = _(
    "すべての　ポケモンの　いでんしを　もつと　いう。\n"
    "じゆうじざいに　すがたを　けすことが　できるので\n"
    "ひとに　ちかづいても　まったく　きづかれない。");

// 0x53C61B
const u8 gChikoritaPokedexText[] POKEDEX_TEXT_DATA = _(
    "はっぱを　ふりまわして　あいてを　いかくするが\n"
    "はっぱから　あまい　かおりが　ただようので\n"
    "おたがいに　なごやかな　ふんいきに　なるよ。");

// 0x53C660
const u8 gBayleefPokedexText[] POKEDEX_TEXT_DATA = _(
    "くびの　まわりの　くるりと　まいた　はっぱの\n"
    "なかには　ちいさな　きのめが　1こ　なっている。\n"
    "その　かおりは　ひとを　げんきに　させるぞ。");

// 0x53C6A7
const u8 gMeganiumPokedexText[] POKEDEX_TEXT_DATA = _(
    "はなの　かおりは　きもちを　おだやかにする。\n"
    "たたかいの　ときは　かおりを　はっさんさせて\n"
    "あいての　たたかう　きもちを　にぶらせるのだ。");

// 0x53C6ED
const u8 gCyndaquilPokedexText[] POKEDEX_TEXT_DATA = _(
    "せなかから　ほのおを　ふきあげて　みを　まもる。\n"
    "おこった　ときの　ほのおは　いきおいが　いいが\n"
    "つかれている　ときは　ふかんぜんねんしょうする。");

// 0x53C737
const u8 gQuilavaPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほのおの　いきおいと　ねっぷうで　いかくする。\n"
    "すばやい　みのこなしで　あいての　こうげきを\n"
    "かわしながら　どうじに　ほのおで　もやす。");

// 0x53C77C
const u8 gTyphlosionPokedexText[] POKEDEX_TEXT_DATA = _(
    "しゃくねつの　ほのおで　まわりに　かげろうを\n"
    "つくりだして　すがたを　かくす　ことが　できる。\n"
    "もえあがる　ばくふうは　すべてを　やきつくすぞ。");

// 0x53C7C5
const u8 gTotodilePokedexText[] POKEDEX_TEXT_DATA = _(
    "ちいさな　からだでも　アゴの　ちからは　つよい。\n"
    "ワニノコじしんは　あまがみ　している　つもりでも\n"
    "おおけがを　してしまう　ほどの　ちからが　ある。");

// 0x53C810
const u8 gCroconawPokedexText[] POKEDEX_TEXT_DATA = _(
    "いちど　かみついたら　ぜったいに　はなさない。\n"
    "キバの　さきが　つりばり　みたいに　そりかえって\n"
    "いるので　いちど　ささると　ぬけなく　なるのだ。");

// 0x53C85A
const u8 gFeraligatrPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　くちを　あけて　あいてを　いかくする。\n"
    "きょうじんな　うしろあしで　じめんを　けって\n"
    "ものすごい　スピードで　とっしん　してくるぞ。");

// 0x53C8A2
const u8 gSentretPokedexText[] POKEDEX_TEXT_DATA = _(
    "ねむる　ときには　こうたいで　みはりをする。\n"
    "きけんを　さっちすると　なかまを　おこすのだ。\n"
    "むれから　はぐれると　こわくて　ねむれなくなる。");

// 0x53C8EA
const u8 gFurretPokedexText[] POKEDEX_TEXT_DATA = _(
    "てきに　おそわれても　ほそい　すきまに\n"
    "するりと　もぐりこんで　にげる　ことが　できる。\n"
    "てあしは　みじかいが　とても　すばしっこい。");

// 0x53C92E
const u8 gHoothootPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだの　なかには　ちきゅうの　じてんを\n"
    "かんじとる　きかんを　もっているので　まいにち\n"
    "おなじ　じかんに　なると　なきごえを　あげる。");

// 0x53C973
const u8 gNoctowlPokedexText[] POKEDEX_TEXT_DATA = _(
    "わずかな　ひかりでも　みえる　すぐれた　めと\n"
    "はおとを　たてない　やわらかい　はねの　おかげで\n"
    "くらやみでは　えものを　ぜったいに　にがさない。");

// 0x53C9BC
const u8 gLedybaPokedexText[] POKEDEX_TEXT_DATA = _(
    "あしの　つけねから　だす　えきたいの　においで\n"
    "なかまと　コミュニケーションを　とっている。\n"
    "においの　ちがいで　きもちを　つたえるという。");

// 0x53CA03
const u8 gLedianPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほしが　たくさん　みえる　くうきの　きれいな\n"
    "とちには　レディアンが　たくさん　すむと　いう。\n"
    "ほしあかりを　エネルギーに　しているからだ。");

// 0x53CA4A
const u8 gSpinarakPokedexText[] POKEDEX_TEXT_DATA = _(
    "いとで　つくった　ワナは　だい2の　しんけい。\n"
    "いとを　つたわる　わずかな　しんどう　だけで\n"
    "えものの　しゅるいが　わかると　いわれている。");

// 0x53CA91
const u8 gAriadosPokedexText[] POKEDEX_TEXT_DATA = _(
    "あしの　せんたんには　ちいさな　カギヅメが　あり\n"
    "てんじょうや　すいちょくの　かべも　あるける。\n"
    "ほそく　じょうぶな　いとで　てきを　しめあげる。");

// 0x53CADB
const u8 gCrobatPokedexText[] POKEDEX_TEXT_DATA = _(
    "うしろあしが　はったつして　ハネに　かわった。\n"
    "てあしの　ハネを　こうごに　やすませながら\n"
    "はばたけば　1にちじゅう　やすまず　とべる。");

// 0x53CB20
const u8 gChinchouPokedexText[] POKEDEX_TEXT_DATA = _(
    "きけんを　さっちすると　2ほんの　しょくしゅから\n"
    "プラスと　マイナスの　でんきを　ながす。\n"
    "ひかりの　とどかない　かいていで　くらす。");

// 0x53CB64
const u8 gLanturnPokedexText[] POKEDEX_TEXT_DATA = _(
    "つよい　ひかりを　だす　まるい　ぶぶんは\n"
    "せびれの　いちぶが　へんかして　できたもの。\n"
    "しんかいの　やみを　てらす　ポケモン。");

// 0x53CBA4
const u8 gPichuPokedexText[] POKEDEX_TEXT_DATA = _(
    "でんきを　ためておく　ことが　まだ　ヘタ。\n"
    "びっくりすると　おもわず　ほうでんしてしまう。\n"
    "せいちょうすると　じょうずに　なっていく。");

// 0x53CBE8
const u8 gCleffaPokedexText[] POKEDEX_TEXT_DATA = _(
    "ながれぼしの　おおい　よるは　わ　に　なって\n"
    "おどる　ピィの　すがたを　みることが　できる。\n"
    "ひのでまで　おどり　よつゆで　のどを　うるおす。");

// 0x53CC30
const u8 gIgglybuffPokedexText[] POKEDEX_TEXT_DATA = _(
    "やわらかい　からだは　とても　よく　はずむ。\n"
    "いっしょうけんめい　うたいつづけると\n"
    "ぜんしんが　こい　ピンクいろに　そまっていく。");

// 0x53CC72
const u8 gTogepiPokedexText[] POKEDEX_TEXT_DATA = _(
    "ひとや　ポケモンが　はっしている　やさしさや\n"
    "たのしい　きもちを　エネルギーに　している。\n"
    "カラの　なかに　ためた　しあわせを　わけている。");

// 0x53CCB9
const u8 gTogeticPokedexText[] POKEDEX_TEXT_DATA = _(
    "こううんを　もたらす　ポケモンと　いわれている。\n"
    "じゅんすいな　こころの　もちぬしを　みつけると\n"
    "すがたを　あらわし　しあわせを　わけあたえる。");

// 0x53CD02
const u8 gNatuPokedexText[] POKEDEX_TEXT_DATA = _(
    "サバンナに　はえている　せたけの　ひくい　きを\n"
    "かけのぼり　あたらしい　きのめを　ついばむ。\n"
    "なにかを　かんさつしている　みたいな　ひとみ。");

// 0x53CD49
const u8 gXatuPokedexText[] POKEDEX_TEXT_DATA = _(
    "みらいを　よちする　ふしぎな　ちからを　もつ。\n"
    "かみさまが　つかわせた　ポケモンだと　むかしから\n"
    "しんじている　ひとびとが　がいこくには　いる。");

// 0x53CD92
const u8 gMareepPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいもうが　こすれて　せいでんきが　たまる。\n"
    "でんりょくが　たくさん　たまるほど　しっぽの\n"
    "さきに　ついた　でんきゅうが　あかるく　ひかる。");

// 0x53CDD9
const u8 gFlaaffyPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいもうの　せいしつが　へんかするので　すくない\n"
    "りょうでも　たくさんの　でんきを　つくりだせる。\n"
    "でんきを　さえぎる　つるつるの　はだを　もつ。");

// 0x53CE23
const u8 gAmpharosPokedexText[] POKEDEX_TEXT_DATA = _(
    "デンリュウの　あかりは　うちゅうからも　みえる。\n"
    "むかしの　ひとは　デンリュウの　あかりを　つかい\n"
    "とおくの　なかまと　あいずを　おくりあっていた。");

// 0x53CE6E
const u8 gBellossomPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいようを　あびて　はなびらが　いろづく。\n"
    "くもりが　つづいた　ときに　おどる　ダンスは\n"
    "たいようを　よぶ　ぎしきと　かんがえられている。");

// 0x53CEB4
const u8 gMarillPokedexText[] POKEDEX_TEXT_DATA = _(
    "みずを　はじく　たいもうに　おおわれているので\n"
    "すいちゅうで　みずの　ていこうを　うけずに\n"
    "はやい　スピードで　およぐ　ことが　できる。");

// 0x53CEF9
const u8 gAzumarillPokedexText[] POKEDEX_TEXT_DATA = _(
    "1にちの　ほとんどを　みずの　なかで　くらす。\n"
    "からだの　いろと　もようは　すいちゅうで\n"
    "てきに　みつかり　にくくする　カムフラージュ。");

// 0x53CF3E
const u8 gSudowoodoPokedexText[] POKEDEX_TEXT_DATA = _(
    "てきに　おそわれない　ように　きの　ふりをする。\n"
    "りょうては　1ねんじゅう　みどりいろなので\n"
    "ふゆは　にせものだと　すぐに　ばれてしまう。");

// 0x53CF84
const u8 gPolitoedPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたまの　まきげは　おうじゃの　あかしだ。\n"
    "ながく　きれいに　まいている　ニョロトノほど\n"
    "なかまの　そんけいを　あつめると　いわれている。");

// 0x53CFCA
const u8 gHoppipPokedexText[] POKEDEX_TEXT_DATA = _(
    "かぜに　のって　ふわふわ　ただよう　ポケモン。\n"
    "きょうふうの　けはいを　かんじると　なかまどうし\n"
    "はっぱを　からめ　とばされない　じゅんびをする。");

// 0x53D014
const u8 gSkiploomPokedexText[] POKEDEX_TEXT_DATA = _(
    "きおんが　18どを　こえると　はなが　ひらく。\n"
    "おんどに　より　はなの　ひらきかたが　かわるので\n"
    "おんどけいの　かわりに　することも　ある。");

// 0x53D05B
const u8 gJumpluffPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたたかい　みなみかぜに　のって　うみを　こえ\n"
    "がいこくまで　とんでいってしまう　ポケモン。\n"
    "つめたい　くうきに　ふれると　じめんに　おりる。");

// 0x53D0A3
const u8 gAipomPokedexText[] POKEDEX_TEXT_DATA = _(
    "きように　うごく　しっぽの　さきを　てのひらの\n"
    "かわりに　つかっていたら　はんたいに　りょうてが\n"
    "ぶきように　なってしまった　ポケモンだ。");

// 0x53D0E9
const u8 gSunkernPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだに　ためた　えいようは　しんかの　ときまで\n"
    "とっておくため　ほとんど　うごこうとしない。\n"
    "なにも　たべずに　あさつゆ　だけを　のんでいる。");

// 0x53D132
const u8 gSunfloraPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいようエネルギーから　えいようを　つくりだす。\n"
    "きおんの　たかい　にっちゅう　かっぱつに　うごき\n"
    "たいようが　しずむと　ぱったり　うごかなくなる。");

// 0x53D17D
const u8 gYanmaPokedexText[] POKEDEX_TEXT_DATA = _(
    "めだまを　うごかさずに　360ど　みわたせる。\n"
    "きゅうブレーキや　ほうこうてんかんが　とくい。\n"
    "ねらった　えものを　すばやく　おいつめていく。");

// 0x53D1C5
const u8 gWooperPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふだんは　みずの　なかで　くらしているが　エサを\n"
    "さがすときなど　たまに　ちじょうに　でてくる。\n"
    "りくでは　どくの　ねんえきで　からだを　おおう。");

// 0x53D20F
const u8 gQuagsirePokedexText[] POKEDEX_TEXT_DATA = _(
    "みずの　なかで　くちを　あけて　エサが　ぐうぜん\n"
    "とびこんで　くるのを　ただただ　まっている。\n"
    "うごかないので　あまり　おなかが　すかないのだ。");

// 0x53D258
const u8 gEspeonPokedexText[] POKEDEX_TEXT_DATA = _(
    "みとめた　トレーナーには　きわめて　ちゅうじつ。\n"
    "トレーナーを　きけんから　まもる　ために\n"
    "よちのうりょくが　はったつしたと　いわれている。");

// 0x53D29F
const u8 gUmbreonPokedexText[] POKEDEX_TEXT_DATA = _(
    "つきの　はどうを　うけて　しんかした　ポケモン。\n"
    "くらやみに　じっと　ひそみ　あいてを　うかがう。\n"
    "おそいかかる　とき　からだの　わっかが　ひかる。");

// 0x53D2EA
const u8 gMurkrowPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふこうを　はこぶと　いわれ　おそれられていた。\n"
    "キラキラ　ひかる　ものに　きょうみを　しめし\n"
    "じょせいの　ゆびわを　とっていこうとする。");

// 0x53D32F
const u8 gSlowkingPokedexText[] POKEDEX_TEXT_DATA = _(
    "せかいの　ふしぎを　かいめい　するため　まいにち\n"
    "けんきゅう　しているが　あたまの　シェルダーが\n"
    "はずれると　ぜんぶ　わすれてしまう　らしい。");

// 0x53D377
const u8 gMisdreavusPokedexText[] POKEDEX_TEXT_DATA = _(
    "すすりなく　ような　なきごえで　こわがらせる。\n"
    "あいての　こわがる　こころを　あかい　たまで\n"
    "きゅうしゅうして　えいように　している　らしい。");

// 0x53D3BF
const u8 gUnownPokedexText[] POKEDEX_TEXT_DATA = _(
    "こだいの　もじに　にた　すがたの　ポケモン。\n"
    "さきに　うまれたのは　もじか　アンノーンなのか。\n"
    "けんきゅうちゅうだが　いまだに　なぞである。");

// 0x53D406
const u8 gWobbuffetPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふだんは　おとなしいが　くろい　しっぽを\n"
    "こうげきされると　もうれつに　はんげきする。\n"
    "どうくつの　すみかで　ひぐれを　まつ。");

// 0x53D446
const u8 gGirafarigPokedexText[] POKEDEX_TEXT_DATA = _(
    "くさや　きのめを　たべる　そうしょくせい。\n"
    "キリンリキが　くさを　たべている　ときは\n"
    "シッポも　もぐもぐ　なにかを　たべる　しぐさ。");

// 0x53D489
const u8 gPinecoPokedexText[] POKEDEX_TEXT_DATA = _(
    "きの　えだに　ぶらさがり　えものを　まっている。\n"
    "きを　ゆらされて　しょくじの　じゃまを　されると\n"
    "じめんに　おちてから　いきなり　ばくはつするぞ。");

// 0x53D4D4
const u8 gForretressPokedexText[] POKEDEX_TEXT_DATA = _(
    "こうてつの　カラの　なかに　ほんたいが　いる。\n"
    "えものを　つかまえる　ときに　カラが　ひらくが\n"
    "あまりの　はやさに　なかみは　みえないのだ。");

// 0x53D51B
const u8 gDunsparcePokedexText[] POKEDEX_TEXT_DATA = _(
    "ドリルの　シッポを　つかって　うしろむきに\n"
    "じめんを　ほりすすみ　ふくざつな　かたちの\n"
    "すあなを　ちちゅう　ふかくに　つくる　ポケモン。");

// 0x53D560
const u8 gGligarPokedexText[] POKEDEX_TEXT_DATA = _(
    "おとを　たてず　すべる　ように　かっくうする。\n"
    "りょううでの　おおきな　ツメと　あしの　ツメで\n"
    "えものの　かおに　しがみつき　どくばりを　さす。");

// 0x53D5A9
const u8 gSteelixPokedexText[] POKEDEX_TEXT_DATA = _(
    "イワークよりも　ふかい　ちちゅうに　すんでいる。\n"
    "ちきゅうの　ちゅうしんに　むかって　ほりすすみ\n"
    "ふかさ　1キロに　たっする　ことも　ある。");

// 0x53D5F0
const u8 gSnubbullPokedexText[] POKEDEX_TEXT_DATA = _(
    "キバを　むきだして　こわい　かおを　すれば\n"
    "ちいさな　ポケモンなら　おびえて　にげだす。\n"
    "にげられた　ブルーは　ちょっと　さみしそう。");

// 0x53D634
const u8 gGranbullPokedexText[] POKEDEX_TEXT_DATA = _(
    "したアゴが　とても　はったつした　ポケモン。\n"
    "キバが　おもたいので　くびを　かしげている。\n"
    "おどろかさなければ　むやみに　かみつかない。");

// 0x53D679
const u8 gQwilfishPokedexText[] POKEDEX_TEXT_DATA = _(
    "のみこんだ　みずの　ちからを　りようして\n"
    "ぜんしんの　どくばりを　いっせいに　うちだす。\n"
    "およぐのは　ちょっと　にがてな　ポケモンだ。");

// 0x53D6BD
const u8 gScizorPokedexText[] POKEDEX_TEXT_DATA = _(
    "はがねの　かたさを　もつ　からだは　ちょっとや\n"
    "そっとの　こうげきでは　びくとも　しないぞ。\n"
    "ハネを　はばたかせ　たいおんを　ちょうせつする。");

// 0x53D705
const u8 gShucklePokedexText[] POKEDEX_TEXT_DATA = _(
    "いわの　したで　こうらの　なかに　たくわえた\n"
    "きのみを　たべながら　みを　ひそめている。\n"
    "たいえきと　まざり　きのみは　ジュースに　なる。");

// 0x53D74B
const u8 gHeracrossPokedexText[] POKEDEX_TEXT_DATA = _(
    "あまい　じゅえきを　もとめて　もりに　あつまる。\n"
    "てつの　ように　かたい　ひふに　おおわれている。\n"
    "じまんの　ツノで　あいてを　なげとばす。");

// 0x53D792
const u8 gSneaselPokedexText[] POKEDEX_TEXT_DATA = _(
    "てあしの　カギヅメを　つきたてて　きを　のぼる。\n"
    "おやの　いない　すきを　ねらって　きの　うえに\n"
    "ある　す　から　タマゴを　ぬすんで　たべる。");

// 0x53D7DA
const u8 gTeddiursaPokedexText[] POKEDEX_TEXT_DATA = _(
    "ハチミツの　しみこんだ　てのひらを　なめている。\n"
    "ヒメグマの　ハチミツは　くだものと　スピアーの\n"
    "あつめた　かふんが　ブレンドされて　つくられる。");

// 0x53D824
const u8 gUrsaringPokedexText[] POKEDEX_TEXT_DATA = _(
    "もりの　なかには　リングマが　エサあつめを　する\n"
    "たいぼくや　おがわが　あちこちに　あると　いう。\n"
    "まいにち　エサを　あつめて　もりを　あるく。");

// 0x53D86D
const u8 gSlugmaPokedexText[] POKEDEX_TEXT_DATA = _(
    "かざんちたいで　くらす　ポケモンの　いっしゅ。\n"
    "からだが　ひえると　ひふが　かたまってしまい\n"
    "うごけなくなるため　マグマの　そばで　ねむる。");

// 0x53D8B4
const u8 gMagcargoPokedexText[] POKEDEX_TEXT_DATA = _(
    "せなかの　カラは　マグマが　かたまって　できた。\n"
    "なんまんねんもの　あいだ　かざんの　かこうで\n"
    "くらす　うちに　からだが　マグマに　なった。");

// 0x53D8FB
const u8 gSwinubPokedexText[] POKEDEX_TEXT_DATA = _(
    "じめんに　はなを　こすりつけて　エサを　さがす。\n"
    "かれくさの　したに　はえた　キノコが　こうぶつ。\n"
    "たまに　おんせんを　ほりあてる　ことが　あるよ。");

// 0x53D946
const u8 gPiloswinePokedexText[] POKEDEX_TEXT_DATA = _(
    "こごえる　さむさにも　たえられる　ように\n"
    "あつくて　ながい　けがわに　おおわれている。\n"
    "こおりに　うまった　エサを　キバで　ほりだす。");

// 0x53D98A
const u8 gCorsolaPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたたかい　みなみの　うみに　せいそくする。\n"
    "うみが　よごれると　うつくしい　サンゴのえだは\n"
    "いろが　くすみ　ボロボロに　なってしまう。");

// 0x53D9CF
const u8 gRemoraidPokedexText[] POKEDEX_TEXT_DATA = _(
    "のんだ　みずを　ふっきんを　つかい　いきおいよく\n"
    "ふきだして　そらを　とぶ　えものを　しとめる。\n"
    "しんかが　ちかづくと　かわを　くだっていく。");

// 0x53DA17
const u8 gOctilleryPokedexText[] POKEDEX_TEXT_DATA = _(
    "きゅうばんの　うでで　あいてに　からみつく。\n"
    "うごけなくなった　ところを　しとめるのだ。\n"
    "かなわない　ときは　スミを　はいて　にげる。");

// 0x53DA5B
const u8 gDelibirdPokedexText[] POKEDEX_TEXT_DATA = _(
    "しっぽで　エサを　つつみ　もちはこぶ　ポケモン。\n"
    "デリバードに　エサを　わけてもらった　おかげで\n"
    "エベレストを　のぼりきれた　ぼうけんかが　いた。");

// 0x53DAA5
const u8 gMantinePokedexText[] POKEDEX_TEXT_DATA = _(
    "はれた　ひには　うみの　うえを　ゆうがに　はねる\n"
    "マンタインの　むれを　みることが　できるよ。\n"
    "テッポウオが　くっついていても　きにしない。");

// 0x53DAEC
const u8 gSkarmoryPokedexText[] POKEDEX_TEXT_DATA = _(
    "はがねの　からだと　ハネを　もつ　ポケモン。\n"
    "むかしの　ひとは　ぬけおちた　ハネを　つかって\n"
    "かたなや　ほうちょうを　つくっていた。");

// 0x53DB2F
const u8 gHoundourPokedexText[] POKEDEX_TEXT_DATA = _(
    "さまざまな　なきごえを　つかいわけ　なかまと\n"
    "れんらくを　とりあい　えものを　おいこんでいく。\n"
    "チームワークの　みごとさは　ポケモンずいいち。");

// 0x53DB77
const u8 gHoundoomPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたまの　ツノが　おおきく　そりかえって　いる\n"
    "ヘルガーが　グループの　リーダーてき　そんざい。\n"
    "なかま　どうしで　あらそい　リーダーが　きまる。");

// 0x53DBC1
const u8 gKingdraPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふかい　かいていで　しずかに　ねむる。\n"
    "すいめんへ　あがってくるとき　ふねを　のみこむ\n"
    "ほど　おおきな　うずしおが　はっせいする。");

// 0x53DC03
const u8 gPhanpyPokedexText[] POKEDEX_TEXT_DATA = _(
    "ゴマゾウの　おおきな　みみは　うちわの　かわり。\n"
    "あつくなると　ぱたぱた　あおいで　すずむ。\n"
    "こどもでも　ちからは　とても　つよい。");

// 0x53DC46
const u8 gDonphanPokedexText[] POKEDEX_TEXT_DATA = _(
    "ダンプカーを　らくらく　ひっぱる　ちからもち。\n"
    "いわの　ように　かたくなった　ひふは\n"
    "すこしの　こうげきでは　キズも　つかない。");

// 0x53DC87
const u8 gPorygon2PokedexText[] POKEDEX_TEXT_DATA = _(
    "にんげんが　かがくの　ちからで　つくりだした。\n"
    "じんこう　ちのうを　もたせたので　あたらしい\n"
    "しぐさや　かんじょうを　ひとりで　おぼえていく。");

// 0x53DCCF
const u8 gStantlerPokedexText[] POKEDEX_TEXT_DATA = _(
    "みごとな　かたちの　ツノは　びじゅつひん　として\n"
    "たかく　うれた　ために　ぜつめつ　すんぜんまで\n"
    "らんかくされた　ことのある　ポケモン。");

// 0x53DD14
const u8 gSmearglePokedexText[] POKEDEX_TEXT_DATA = _(
    "しっぽの　さきから　にじみでる　たいえきで\n"
    "なわばりの　まわりに　じぶんの　マークを　かく。\n"
    "5000　しゅるいの　マークが　みつかっている。");

// 0x53DD5C
const u8 gTyroguePokedexText[] POKEDEX_TEXT_DATA = _(
    "まいにち　トレーニング　しないと　ストレスが\n"
    "たまってしまうので　トレーナーは　そだてる　とき\n"
    "スケジュールかんりに　くふうが　ひつようだ。");

// 0x53DDA3
const u8 gHitmontopPokedexText[] POKEDEX_TEXT_DATA = _(
    "こうそく　かいてんしながら　はなつ　キックは\n"
    "こうげきと　ぼうぎょを　かねた　みごとな　わざ。\n"
    "あるく　よりも　かいてんした　ほうが　はやい。");

// 0x53DDEB
const u8 gSmoochumPokedexText[] POKEDEX_TEXT_DATA = _(
    "げんき　いっぱい　うごきまわるが　よく　ころぶ。\n"
    "むっくり　おきあがると　みずうみの　すいめんに\n"
    "かおを　うつして　よごれていないか　しらべる。");

// 0x53DE34
const u8 gElekidPokedexText[] POKEDEX_TEXT_DATA = _(
    "きんぞくに　さわって　からだに　ためた　でんきが\n"
    "ほうでん　してしまうと　りょううでを　ぐるぐる\n"
    "まわして　ふたたび　でんきを　ためる。");

// 0x53DE79
const u8 gMagbyPokedexText[] POKEDEX_TEXT_DATA = _(
    "きいろい　ほのおを　くちから　ふいている　ときは\n"
    "けんこうな　しょうこだが　つかれていると　くろい\n"
    "けむりが　まざる　ように　なるぞ。");

// 0x53DEBD
const u8 gMiltankPokedexText[] POKEDEX_TEXT_DATA = _(
    "まいにち　20リットルの　ミルクを　だす。\n"
    "あまい　ミルクは　おとなも　こどもも　だいすき。\n"
    "にがてな　ひとは　ヨーグルトにして　たべている。");

// 0x53DF05
const u8 gBlisseyPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふわふわの　たいもうで　かなしんでいる　こころを\n"
    "キャッチすると　どんなに　とおくでも　かけつけて\n"
    "えがおに　なる　しあわせタマゴを　わけてあげる。");

// 0x53DF50
const u8 gRaikouPokedexText[] POKEDEX_TEXT_DATA = _(
    "かみなりの　スピードを　やどした　ポケモン。\n"
    "その　とおぼえは　かみなりが　おちた　ときの\n"
    "ように　くうきを　ふるわせ　だいちを　ゆるがす。");

// 0x53DF97
const u8 gEnteiPokedexText[] POKEDEX_TEXT_DATA = _(
    "マグマの　じょうねつを　やどした　ポケモン。\n"
    "かざんの　ふんかから　うまれたと　かんがえられ\n"
    "すべてを　やきつくす　ほのおを　ふきあげる。");

// 0x53DFDD
const u8 gSuicunePokedexText[] POKEDEX_TEXT_DATA = _(
    "わきみずの　やさしさを　やどした　ポケモン。\n"
    "すべる　ような　みのこなしで　だいちを　はしり\n"
    "にごった　みずを　きよめる　ちからを　もつ。");

// 0x53E023
const u8 gLarvitarPokedexText[] POKEDEX_TEXT_DATA = _(
    "ちちゅう　ふかくで　うまれる　ヨーギラスは\n"
    "つちを　たべつくして　ちじょうへ　でないと\n"
    "おやの　かおを　みる　ことが　できないのだ。");

// 0x53E066
const u8 gPupitarPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいないで　つくりだした　ガスを　あっしゅくして\n"
    "いきおいよく　ふんしゃする　ことで　とんでいく。\n"
    "こうてつに　ぶつかっても　へいきな　ボディだ。");

// 0x53E0B0
const u8 gTyranitarPokedexText[] POKEDEX_TEXT_DATA = _(
    "じぶんの　すみかを　つくる　ために　やま　ひとつ\n"
    "くずしてしまう　ほどの　つよい　パワーを　もつ。\n"
    "たたかう　あいてを　もとめて　やまを　さまよう。");

// 0x53E0FB
const u8 gLugiaPokedexText[] POKEDEX_TEXT_DATA = _(
    "つばさを　かるく　はばたかせた　だけで　みんかを\n"
    "ふきとばす　はかいりょくを　もっている　ために\n"
    "かいていで　ひとしれず　くらす　ように　なった。");

// 0x53E145
const u8 gHoOhPokedexText[] POKEDEX_TEXT_DATA = _(
    "ひかりの　あたる　かくどに　よって　なないろに\n"
    "かがやく　ハネは　しあわせを　もたらすと　いう。\n"
    "にじの　ふもとに　すむと　いわれている。");

// 0x53E18B
const u8 gCelebiPokedexText[] POKEDEX_TEXT_DATA = _(
    "ときを　こえ　みらいから　やってきた　ポケモン。\n"
    "セレビィが　すがたを　あらわす　かぎり　あかるい\n"
    "みらいが　まっていると　かんがえられている。");

// 0x53E1D4
const u8 gTreeckoPokedexText[] POKEDEX_TEXT_DATA = _(
    "もりの　たいぼくに　すを　つくり　くらす。\n"
    "なわばりに　ちかづく　てきを　はげしく　いかく。\n"
    "もりの　きを　まもる　ポケモンと　いわれている。");

// 0x53E21C
const u8 gGrovylePokedexText[] POKEDEX_TEXT_DATA = _(
    "うっそうと　おいしげった　もりの　なかでは\n"
    "からだから　はえた　はっぱが　てきの　めから\n"
    "ジュプトルの　すがたを　かくしてくれるのだ。");

// 0x53E260
const u8 gSceptilePokedexText[] POKEDEX_TEXT_DATA = _(
    "ジャングルの　なかでは　てきなしの　つよさ。\n"
    "くさきを　だいじに　そだてる　ポケモン。\n"
    "ひなたぼっこをして　たいおんを　ちょうせつする。");

// 0x53E2A5
const u8 gTorchicPokedexText[] POKEDEX_TEXT_DATA = _(
    "てきに　おそわれると　おなかで　つくりだした\n"
    "ほのおの　たまを　くちから　とばして　こうげき。\n"
    "まわりが　みえなくなる　くらやみは　にがて。");

// 0x53E2EC
const u8 gCombuskenPokedexText[] POKEDEX_TEXT_DATA = _(
    "1びょうかんに　10ぱつの　キックを　くりだす。\n"
    "あいてが　ギブアップするまで　たたかい　つづける\n"
    "つよい　とうそうほんのうを　もつ　ポケモンだ。");

// 0x53E336
const u8 gBlazikenPokedexText[] POKEDEX_TEXT_DATA = _(
    "パンチや　キックの　かくとうわざを　みにつける。\n"
    "すうねんごとに　ふるくなった　はねが　もえて\n"
    "あたらしく　しなやかな　はねに　はえかわるのだ。");

// 0x53E37F
const u8 gMudkipPokedexText[] POKEDEX_TEXT_DATA = _(
    "りくじょうでは　4ほんの　あしを　ふんばって\n"
    "おおきな　いわを　もちあげる　パワーを　はっき。\n"
    "みずべの　どろに　からだを　うめて　ねむる。");

// 0x53E3C6
const u8 gMarshtompPokedexText[] POKEDEX_TEXT_DATA = _(
    "あしこしが　きたえられて　2ほんあしに　なった。\n"
    "ひふが　かんそうすると　よわってしまうため\n"
    "どろあそびを　して　すいぶんを　ほきゅうする。");

// 0x53E40D
const u8 gSwampertPokedexText[] POKEDEX_TEXT_DATA = _(
    "あらしが　ちかづき　つなみを　よかんすると\n"
    "いわを　つみあげて　うみぞいの　すを　まもる。\n"
    "ジェットスキーと　ごかくの　スピードで　およぐ。");

// 0x53E454
const u8 gPoochyenaPokedexText[] POKEDEX_TEXT_DATA = _(
    "キバを　むいて　はげしく　いかくする。\n"
    "にげる　あいては　しつこく　おいかけまわすぞ。\n"
    "はんげき　されると　しっぽを　まいて　にげだす。");

// 0x53E499
const u8 gMightyenaPokedexText[] POKEDEX_TEXT_DATA = _(
    "やせいの　グラエナは　むれで　こうどうする。\n"
    "リーダーの　めいれいには　ぜったいに　さからわず\n"
    "いっしみだれぬ　チームワークで　てきを　たおす。");

// 0x53E4E2
const u8 gZigzagoonPokedexText[] POKEDEX_TEXT_DATA = _(
    "はなを　じめんに　こすりつけ　あっち　こっちに\n"
    "いったり　きたり　いつも　なにかを　さがしてる。\n"
    "ジグザグ　すすむ　あしあとが　とくちょうだ。");

// 0x53E52A
const u8 gLinoonePokedexText[] POKEDEX_TEXT_DATA = _(
    "まっすぐ　はしるだけなら　とても　はやい。\n"
    "いけに　すむ　えものを　すいめんから　みつけると\n"
    "すばやく　とびこみ　するどい　ツメで　とらえる。");

// 0x53E572
const u8 gWurmplePokedexText[] POKEDEX_TEXT_DATA = _(
    "きの　えだに　くっついて　はっぱを　たべる。\n"
    "くちから　だす　いとは　くうきに　ふれると\n"
    "ネバネバになり　てきの　うごきを　にぶらせる。");

// 0x53E5B7
const u8 gSilcoonPokedexText[] POKEDEX_TEXT_DATA = _(
    "ケムッソの　ときに　たくわえた　エネルギーを\n"
    "つかって　しんかの　じゅんびを　している。\n"
    "2つの　めで　まわりの　ようすを　うかがう。");

// 0x53E5FB
const u8 gBeautiflyPokedexText[] POKEDEX_TEXT_DATA = _(
    "カラフルな　はねの　もようが　とくちょう。\n"
    "かふんを　あつめに　はなばたけに　あつまる。\n"
    "おこった　ときの　こうげきは　とても　はげしい。");

// 0x53E641
const u8 gCascoonPokedexText[] POKEDEX_TEXT_DATA = _(
    "てきに　みつからない　ように　おおきな　はっぱの\n"
    "うらがわや　えだの　すきまで　じっとしている。\n"
    "かれはを　からだに　くっつけて　カムフラージュ。");

// 0x53E68B
const u8 gDustoxPokedexText[] POKEDEX_TEXT_DATA = _(
    "まよなか　がいとうの　あかりに　さそわれて\n"
    "のやまから　とんでくる　やこうせいの　ポケモン。\n"
    "もうどくの　こなを　はねから　ふりまく。");

// 0x53E6CF
const u8 gLotadPokedexText[] POKEDEX_TEXT_DATA = _(
    "みずの　きれいな　いけで　くらす　ポケモン。\n"
    "あたまの　はっぱに　のった　ちいさな　ポケモンを\n"
    "むこうぎしまで　はこんであげる　ことが　あるよ。");

// 0x53E718
const u8 gLombrePokedexText[] POKEDEX_TEXT_DATA = _(
    "ゆうぐれどき　かわの　なかから　ひょっこりと\n"
    "あらわれては　ひとを　おどろかせて　よろこぶ。\n"
    "かわぞこの　いしに　ついた　みずごけを　たべる。");

// 0x53E760
const u8 gLudicoloPokedexText[] POKEDEX_TEXT_DATA = _(
    "たのしい　おんがくを　きくと　からだじゅうの\n"
    "さいぼうが　うずき　リズムを　とりはじめるぞ。\n"
    "きょうてきを　あいてにしても　ひるまない。");

// 0x53E7A5
const u8 gSeedotPokedexText[] POKEDEX_TEXT_DATA = _(
    "えだに　ぶらさがり　えいようを　きゅうしゅう。\n"
    "しょくじを　おえて　からだの　おもくなった\n"
    "タネボーは　ぽとりぽとりと　じめんに　おちる。");

// 0x53E7EB
const u8 gNuzleafPokedexText[] POKEDEX_TEXT_DATA = _(
    "きのぼりが　とくいな　もりに　すむ　ポケモン。\n"
    "とがった　ながい　はなが　じゃくてん。\n"
    "にぎられると　からだの　ちからが　ぬけてしまう。");

// 0x53E830
const u8 gShiftryPokedexText[] POKEDEX_TEXT_DATA = _(
    "こがらしに　のって　あらわれると　いわれている。\n"
    "むかしから　もりの　かみさまと　おそれられ\n"
    "ひとの　おとずれない　みつりんで　くらす。");

// 0x53E875
const u8 gTaillowPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだは　ちいさいが　とても　ゆうかん。\n"
    "おおきな　エアームドと　ごかくに　たたかうが\n"
    "おなかが　すくと　よわきに　なってしまう。");

// 0x53E8B7
const u8 gSwellowPokedexText[] POKEDEX_TEXT_DATA = _(
    "はるか　じょうくうから　きゅうこうか。\n"
    "ねらった　えものは　ぜったいに　にがさない。\n"
    "あたたかい　とちを　さがして　いどうする。");

// 0x53E8F8
const u8 gWingullPokedexText[] POKEDEX_TEXT_DATA = _(
    "うみべの　だんがいぜっぺきに　すを　つくる。\n"
    "ながい　じかん　はばたく　ことは　にがて。\n"
    "じょうしょうきりゅうを　りようして　とぶ。");

// 0x53E93B
const u8 gPelipperPokedexText[] POKEDEX_TEXT_DATA = _(
    "かいめん　すれすれを　とび　エサを　みつけると\n"
    "おおきな　クチバシで　かいすいごと　すくいとる。\n"
    "クチバシの　なかに　タマゴを　いれて　まもる。");

// 0x53E984
const u8 gRaltsPokedexText[] POKEDEX_TEXT_DATA = _(
    "ひとや　ポケモンの　かんじょうを　あたまの\n"
    "ツノで　キャッチする　ちからを　もつ　ポケモン。\n"
    "てきいを　かんじとると　かくれてしまう。");

// 0x53E9C8
const u8 gKirliaPokedexText[] POKEDEX_TEXT_DATA = _(
    "サイコパワーで　できた　くうかんの　さけめから\n"
    "みらいの　できごとを　みる　ちからを　もつ。\n"
    "はれた　あさは　きぶんよく　おどると　いわれる。");

// 0x53EA10
const u8 gGardevoirPokedexText[] POKEDEX_TEXT_DATA = _(
    "サイコパワーで　からだを　ささえているため\n"
    "じゅうりょくを　かんじていない　らしい。\n"
    "トレーナーを　まもる　ために　いのちを　かける。");

// 0x53EA54
const u8 gSurskitPokedexText[] POKEDEX_TEXT_DATA = _(
    "ゆうだちの　あと　みずたまりに　あつまってくる。\n"
    "みずの　ひょうめんを　すべる　ように　あるき\n"
    "あたまから　あまい　においの　みつを　だす。");

// 0x53EA9B
const u8 gMasquerainPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　めだま　もようで　てきを　いかくする。\n"
    "あめに　ぬれると　とべなくなって　しまうため\n"
    "たいぼくの　したや　のきしたで　あまやどり。");

// 0x53EAE2
const u8 gShroomishPokedexText[] POKEDEX_TEXT_DATA = _(
    "もりの　しめった　ふようどが　だいこうぶつ。\n"
    "ながあめの　あと　もりに　はいると　キノココが\n"
    "たくさん　あつまって　ふようどを　たべているよ。");

// 0x53EB2A
const u8 gBreloomPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたまの　かさの　あなから　ほうしを　ばらまく。\n"
    "あたたかく　しめった　きこうが　だいすき。\n"
    "そうげんや　しんりんの　くさきを　たべる。");

// 0x53EB6F
const u8 gSlakothPokedexText[] POKEDEX_TEXT_DATA = _(
    "1にちの　うち　ほとんどの　じかん　ねている。\n"
    "いっしょう　すみかを　かえないが　たまに\n"
    "かわを　およいで　ながい　きょりを　いどうする。");

// 0x53EBB5
const u8 gVigorothPokedexText[] POKEDEX_TEXT_DATA = _(
    "ぜんしんの　ちが　たぎり　じっとしていられない。\n"
    "1にちじゅう　のやまを　かけまわり　こうふんを\n"
    "しずめないと　よる　ねむれなくなってしまうのだ。");

// 0x53EBFF
const u8 gSlakingPokedexText[] POKEDEX_TEXT_DATA = _(
    "くだものが　みのる　きせつに　なると　じゅもくの\n"
    "まわりに　ケッキングが　たくさん　あつまる。\n"
    "じゅくして　おちてくるのを　まっているのだ。");

// 0x53EC46
const u8 gNincadaPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいぼくの　ねもとに　すみかを　つくる。\n"
    "まっくらな　ちちゅうの　ようすを\n"
    "ヒゲの　ような　しょっかくで　さぐる。");

// 0x53EC80
const u8 gNinjaskPokedexText[] POKEDEX_TEXT_DATA = _(
    "こうそくで　はげしく　うごきまわっているため\n"
    "すがたを　とらえる　ことは　とても　むずかしい。\n"
    "なきごえを　ききつづけると　ずつうが　してくる。");

// 0x53ECC9
const u8 gShedinjaPokedexText[] POKEDEX_TEXT_DATA = _(
    "ハネを　まったく　うごかして　いないのに\n"
    "くうちゅうに　うかんでいる　ふしぎな　ポケモン。\n"
    "からだの　なかは　くうどうで　まっくら。");

// 0x53ED0C
const u8 gWhismurPokedexText[] POKEDEX_TEXT_DATA = _(
    "なきごえは　ジェットき　なみの　おんりょうだ。\n"
    "みみの　あなから　いきを　すいこむ　しくみ。\n"
    "いきぎれしないで　なきつづける　ことが　できる。");

// 0x53ED54
const u8 gLoudredPokedexText[] POKEDEX_TEXT_DATA = _(
    "あたまの　まるい　スピーカーを　うごかして\n"
    "おおごえの　ちょうおんぱを　てきに　ぶつける。\n"
    "あしを　ふみならして　パワーを　ためるぞ。");

// 0x53ED98
const u8 gExploudPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだじゅうに　おとを　だす　きかんを　もつ。\n"
    "おとの　たかさや　おおきさを　つかいわけて\n"
    "なかまと　コミュニケーションを　とっている。");

// 0x53EDDD
const u8 gMakuhitaPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだを　きたえる　ことが　なによりも　すき。\n"
    "どうくつで　じひびきが　きこえたら　それは\n"
    "マクノシタが　けいこしている　おとだ。");

// 0x53EE1F
const u8 gHariyamaPokedexText[] POKEDEX_TEXT_DATA = _(
    "すぐに　ちからくらべを　いどむ　しゅうせい。\n"
    "せんろに　たちふさがり　はしってくる　れっしゃを\n"
    "つっぱりで　おしとどめた　ことが　あるぞ。");

// 0x53EE65
const u8 gAzurillPokedexText[] POKEDEX_TEXT_DATA = _(
    "えいようが　たっぷり　つまった　しっぽは\n"
    "ゴムボール　みたいに　よく　はずむ。\n"
    "はれた　ひは　みずべに　あつまり　みずあそび。");

// 0x53EEA5
const u8 gNosepassPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだから　はっする　きょうりょくな　じりょくで\n"
    "ひきよせた　えものを　しょくりょうに　する。\n"
    "さむい　きせつの　ほうが　じりょくが　つよい。");

// 0x53EEED
const u8 gSkittyPokedexText[] POKEDEX_TEXT_DATA = _(
    "あいきょう　たっぷりの　しぐさで　だいにんき。\n"
    "たたかう　ときは　しっぽを　けばだたせる。\n"
    "するどい　うなりごえを　あげて　てきを　いかく。");

// 0x53EF34
const u8 gDelcattyPokedexText[] POKEDEX_TEXT_DATA = _(
    "きまった　すみかを　もたずに　いごこちの　よい\n"
    "ばしょを　さがし　ねどこを　かえる　しゅうせい。\n"
    "やこうせいで　ひぐれから　こうどうを　はじめる。");

// 0x53EF7E
const u8 gSableyePokedexText[] POKEDEX_TEXT_DATA = _(
    "するどい　ツメで　どうくつに　よこあなを　ほり\n"
    "ほうせきの　げんせきを　さがしだして　たべる。\n"
    "やみに　ひそみ　めったに　すがたを　みせない。");

// 0x53EFC6
const u8 gMawilePokedexText[] POKEDEX_TEXT_DATA = _(
    "おおあごは　はがねの　ツノが　へんけいしたもの。\n"
    "あいきょう　たっぷりの　しぐさに　ゆだんした\n"
    "あいてを　おおあごで　がぶりと　かみつく。");

// 0x53F00C
const u8 gAronPokedexText[] POKEDEX_TEXT_DATA = _(
    "こうてつの　よろいに　みを　つつむ　ポケモン。\n"
    "しんかの　ときに　あたらしい　よろいが　できる。\n"
    "とれた　よろいは　てつせいひんの　ざいりょう。");

// 0x53F055
const u8 gLaironPokedexText[] POKEDEX_TEXT_DATA = _(
    "コドラ　どうしが　であうと　はがねの　からだを\n"
    "ぶつけあって　なわばり　あらそいを　する。\n"
    "ぶつかりあう　おとは　すうキロさきにも　とどく。");

// 0x53F09C
const u8 gAggronPokedexText[] POKEDEX_TEXT_DATA = _(
    "すこしずつ　てつの　ツノは　ながく　なるので\n"
    "ながさで　ボスゴドラの　ねんれいが　わかる。\n"
    "よろいの　キズは　たたかいの　くんしょうだ。");

// 0x53F0E1
const u8 gMedititePokedexText[] POKEDEX_TEXT_DATA = _(
    "まいにち　なんじかんも　めいそうを　つづけ\n"
    "きたえられた　せいしんりょくで　そらを　とぶ。\n"
    "ヨガの　しゅぎょうを　つづけてきた　せいかだ。");

// 0x53F127
const u8 gMedichamPokedexText[] POKEDEX_TEXT_DATA = _(
    "かこくな　ヨガの　しゅぎょうで　あいての\n"
    "うごきを　さきよみする　ちからを　みにつけた。\n"
    "おどる　ような　ゆうがな　うごきで　たたかう。");

// 0x53F16C
const u8 gElectrikePokedexText[] POKEDEX_TEXT_DATA = _(
    "くうきとの　まさつで　でんきを　つくりだす。\n"
    "とくに　くうきの　かんそうした　きせつは\n"
    "ぜんしんから　ひばなを　はげしく　ちらしている。");

// 0x53F1B1
const u8 gManectricPokedexText[] POKEDEX_TEXT_DATA = _(
    "ライボルトの　ちかくに　かみなりが　おちるため\n"
    "かみなりから　うまれたと　かんがえられていた。\n"
    "たたかいになると　かみなりぐもを　つくりだす。");

// 0x53F1F9
const u8 gPluslePokedexText[] POKEDEX_TEXT_DATA = _(
    "なかまの　ポケモンを　おうえんする　しゅうせい。\n"
    "りょうてから　はっした　でんきを　ショートさせて\n"
    "ひばなの　ボンボンを　つくる　ことが　できる。");

// 0x53F243
const u8 gMinunPokedexText[] POKEDEX_TEXT_DATA = _(
    "プラスルと　マイナンの　でんきを　どうじに\n"
    "あびると　けっこうが　よくなり　げんきに\n"
    "なると　ポケモンがっかいで　はっぴょうされた。");

// 0x53F286
const u8 gVolbeatPokedexText[] POKEDEX_TEXT_DATA = _(
    "しっぽの　あかりを　ともしながら　しゅうだんで\n"
    "よぞらに　きかがくてきな　もようを　えがく。\n"
    "いけの　みずが　よごれると　すみかを　うつす。");

// 0x53F2CD
const u8 gIllumisePokedexText[] POKEDEX_TEXT_DATA = _(
    "ひぐれから　こうどうを　はじめる　やこうせい。\n"
    "バルビートを　ゆうどうして　えがく　もようは\n"
    "200しゅるい　いじょう　かくにんされている。");

// 0x53F314
const u8 gRoseliaPokedexText[] POKEDEX_TEXT_DATA = _(
    "えいよう　まんてんの　わきみずを　のませた\n"
    "ロゼリアは　うつくしい　はなを　さかせる。\n"
    "はなの　かおりは　てきを　ゆだんさせる　こうか。");

// 0x53F359
const u8 gGulpinPokedexText[] POKEDEX_TEXT_DATA = _(
    "てつくずも　しょうかしてしまう　いえきを　もつ。\n"
    "じぶんの　からだと　おなじ　おおきさの　ものも\n"
    "ひとくちで　のみこむ　ことが　できる。");

// 0x53F39E
const u8 gSwalotPokedexText[] POKEDEX_TEXT_DATA = _(
    "きょうりょくな　いさんで　なんでも　しょうか。\n"
    "しょうか　できない　ものは　よのなかで　ひとつ。\n"
    "マルノームの　いぶくろ　だけと　いわれている。");

// 0x53F3E7
const u8 gCarvanhaPokedexText[] POKEDEX_TEXT_DATA = _(
    "しゅうだんで　ふねを　おそい　しずめてしまう。\n"
    "とても　きょうぼうな　ポケモンと　いわれているが\n"
    "1ぴきに　なると　とたんに　にげだしていく。");

// 0x53F42F
const u8 gSharpedoPokedexText[] POKEDEX_TEXT_DATA = _(
    "きょうぼうで　ずるがしこい　うみのギャング。\n"
    "みずの　ていこうを　へらす　とくしゅな　ひふ。\n"
    "さいこう　そくどは　じそく120キロを　こえる。");

// 0x53F477
const u8 gWailmerPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふだんは　うみで　くらす　ポケモンだが　すこしの\n"
    "じかんなら　ちじょうでも　せいかつ　できる。\n"
    "からだが　かわくと　げんきが　なくなってしまう。");

// 0x53F4C0
const u8 gWailordPokedexText[] POKEDEX_TEXT_DATA = _(
    "かいめんから　だした　はなのあなで　こきゅう。\n"
    "おもいきり　くうきを　すいこめば\n"
    "3000メートルの　しんかいまで　もぐれる。");

// 0x53F500
const u8 gNumelPokedexText[] POKEDEX_TEXT_DATA = _(
    "せなかの　コブに　にえたぎる　マグマを　ためる。\n"
    "100キロの　にもつを　はこぶ　ちからもち。\n"
    "むかしから　ひとの　しごとを　てつだっている。");

// 0x53F548
const u8 gCameruptPokedexText[] POKEDEX_TEXT_DATA = _(
    "かざんの　かこうで　くらしている　ポケモン。\n"
    "10ねんごとに　せなかの　かざんが　だいふんか。\n"
    "げんいんの　けんきゅうが　すすめられている。");

// 0x53F58F
const u8 gTorkoalPokedexText[] POKEDEX_TEXT_DATA = _(
    "せきたんを　もやす　エネルギーで　たたかう。\n"
    "はなのあなから　けむりを　ふきだすときに\n"
    "きかんしゃの　けいてきに　にた　おとを　だす。");

// 0x53F5D3
const u8 gSpoinkPokedexText[] POKEDEX_TEXT_DATA = _(
    "サイコパワーを　じざいに　あやつる　ポケモン。\n"
    "ねむっている　ときも　とびはねている。\n"
    "ちちゅうに　はえる　キノコが　だいこうぶつ。");

// 0x53F616
const u8 gGrumpigPokedexText[] POKEDEX_TEXT_DATA = _(
    "おでこの　くろしんじゅに　パワーを　ためる。\n"
    "サイコパワーを　つかうときに　おどる　ステップが\n"
    "むかし　がいこくで　だいりゅうこうした。");

// 0x53F65B
const u8 gSpindaPokedexText[] POKEDEX_TEXT_DATA = _(
    "1ぴきずつ　ちがう　ブチもようが　とくちょう。\n"
    "フラフラと　おぼつかない　あしどりは\n"
    "あいての　ねらいを　はずす　こうかが　ある。");

// 0x53F69D
const u8 gTrapinchPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　アゴは　おおいわを　かみくだく。\n"
    "あたまが　おおきいので　ひっくりかえると\n"
    "なかなか　おきあがる　ことが　できない。");

// 0x53F6DD
const u8 gVibravaPokedexText[] POKEDEX_TEXT_DATA = _(
    "ハネを　こすって　ちょうおんぱを　はなつ。\n"
    "ビブラーバの　ハネは　せいちょう　とちゅうなので\n"
    "ながい　きょりを　とぶ　ことは　できない。");

// 0x53F722
const u8 gFlygonPokedexText[] POKEDEX_TEXT_DATA = _(
    "はばたく　おとが　うたごえの　ように　きこえる。\n"
    "てきに　みつからないように　さばくの　すなを\n"
    "はばたきで　まいあげて　すがたを　かくす。");

// 0x53F768
const u8 gCacneaPokedexText[] POKEDEX_TEXT_DATA = _(
    "あめが　ほとんど　ふらない　さばくに　せいそく。\n"
    "ふとい　トゲの　うでを　ふりまわして　たたかう。\n"
    "1ねんに　1ど　きいろの　はなが　さく。");

// 0x53F7AF
const u8 gCacturnePokedexText[] POKEDEX_TEXT_DATA = _(
    "なんぜんねんも　かこくな　さばくで　くらすうちに\n"
    "けつえきが　すなと　おなじ　せいぶんに　なった。\n"
    "よるに　なると　えものを　さがす　やこうせい。");

// 0x53F7F9
const u8 gSwabluPokedexText[] POKEDEX_TEXT_DATA = _(
    "わたぐもの　ような　つばさを　もつ　ポケモン。\n"
    "エサの　すくない　ふゆを　こした　チルットたちは\n"
    "はるに　なると　まちの　ちかくまで　やってくる。");

// 0x53F843
const u8 gAltariaPokedexText[] POKEDEX_TEXT_DATA = _(
    "うつくしい　ソプラノの　なきごえで　ハミング。\n"
    "あおぞらと　しろい　くもに　まぎれて　とぶ。\n"
    "しゃくねつの　ひのたまを　くちから　はきだす。");

// 0x53F88A
const u8 gZangoosePokedexText[] POKEDEX_TEXT_DATA = _(
    "たたかう　ときは　うしろあしで　たちあがり\n"
    "まえあしの　するどい　ツメで　こうげきする。\n"
    "ハブネークに　であうと　たいもうが　さかだつ。");

// 0x53F8CF
const u8 gSeviperPokedexText[] POKEDEX_TEXT_DATA = _(
    "ザングースとは　えいえんの　ライバルだ。\n"
    "もうどくの　しみだす　しっぽの　かたなで\n"
    "うごきの　すばやい　ザングースに　たいこうする。");

// 0x53F912
const u8 gLunatonePokedexText[] POKEDEX_TEXT_DATA = _(
    "まんげつの　よるは　かっぱつに　うごきだす。\n"
    "40ねんまえ　いんせきの　おちた　げんばで\n"
    "はじめて　はっけんされた　ポケモン。");

// 0x53F952
const u8 gSolrockPokedexText[] POKEDEX_TEXT_DATA = _(
    "たいようエネルギーが　パワーの　みなもと。\n"
    "はれた　ひは　たいように　むかって　ならんだ\n"
    "ソルロックが　ひかりを　きゅうしゅうする。");

// 0x53F995
const u8 gBarboachPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだを　おおう　ヌルヌルの　ねんまくは\n"
    "どろみずに　いる　バイキンが　からだの　なかに\n"
    "はいるのを　ふせぐ　はたらきを　している。");

// 0x53F9D8
const u8 gWhiscashPokedexText[] POKEDEX_TEXT_DATA = _(
    "じしんを　よちする　ふしぎな　ちからを　もつ。\n"
    "ひるまは　ぬまぞこの　どろの　なかで　ねむり\n"
    "おきると　ひとばんじゅう　エサを　たべつづける。");

// 0x53FA20
const u8 gCorphishPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　ハサミで　いちど　つかまえた　えものは\n"
    "なにが　あっても　ぜったいに　はなさない。\n"
    "どんな　ばしょでも　げんきに　せいかつ　できる。");

// 0x53FA68
const u8 gCrawdauntPokedexText[] POKEDEX_TEXT_DATA = _(
    "たたかいを　このむ　あらあらしい　ポケモン。\n"
    "ひゃくせんれんまの　シザリガーは　キズあとが\n"
    "いくつも　のこる　きょだいな　ハサミを　もつ。");

// 0x53FAAE
const u8 gBaltoyPokedexText[] POKEDEX_TEXT_DATA = _(
    "いっぽんあしで　かいてんしながら　いどうする。\n"
    "きげんぜんに　さかえた　こだいとしの　へきがに\n"
    "ヤジロンの　すがたが　えがかれている。");

// 0x53FAF2
const u8 gClaydolPokedexText[] POKEDEX_TEXT_DATA = _(
    "くうちゅうに　うかんだまま　ねむる。\n"
    "からだから　はなれている　りょううでを\n"
    "サイコパワーで　あやつり　とばしている。");

// 0x53FB2E
const u8 gLileepPokedexText[] POKEDEX_TEXT_DATA = _(
    "しょくしゅを　ゆらして　かいそうに　みせかける。\n"
    "だまされて　ちかよってきた　えものを　ひとのみ。\n"
    "1おくねんまえに　ぜつめつした　ポケモン。");

// 0x53FB76
const u8 gCradilyPokedexText[] POKEDEX_TEXT_DATA = _(
    "おもい　からだを　ひきずり　かいていを　いどう。\n"
    "あたたかい　うみの　あさせを　すみかにする。\n"
    "しおが　ひくと　すなはまに　すがたを　みせる。");

// 0x53FBBE
const u8 gAnorithPokedexText[] POKEDEX_TEXT_DATA = _(
    "かがくの　ちからで　かせきから　よみがえった。\n"
    "さゆう　8まいの　はねを　くねらせて　およぐ。\n"
    "うみで　くらすうちに　あしが　ハネに　かわった。");

// 0x53FC07
const u8 gArmaldoPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふだんは　ちじょうで　くらす　アーマルドだが\n"
    "えものを　とる　ときには　うみに　もぐり\n"
    "2まいの　おおきな　はねを　つかって　およぐ。");

// 0x53FC4B
const u8 gFeebasPokedexText[] POKEDEX_TEXT_DATA = _(
    "みずくさの　おおい　いけに　せいそくする。\n"
    "あまりにも　みすぼらしい　すがたを　しているため\n"
    "そだてる　トレーナーが　すくないらしい。");

// 0x53FC8F
const u8 gMiloticPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　みずうみの　そこに　いると　いわれる。\n"
    "もっとも　うつくしい　ポケモンと　いわれていて\n"
    "かいがや　ちょうこくの　モデルと　なっている。");

// 0x53FCD8
const u8 gCastformPokedexText[] POKEDEX_TEXT_DATA = _(
    "てんきに　よって　すがたを　へんかさせる。\n"
    "きおんや　しつどなど　てんこうの　へんかが\n"
    "さいぼうに　えいきょうを　あたえるらしい。");

// 0x53FD1A
const u8 gKecleonPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだの　いろを　まわりの　けしきに　あわせて\n"
    "へんかさせる　のうりょくを　もつ　ポケモン。\n"
    "おどろくと　もとの　いろに　もどってしまう。");

// 0x53FD60
const u8 gShuppetPokedexText[] POKEDEX_TEXT_DATA = _(
    "うしみつどきに　なると　うらみや　ねたみの\n"
    "かんじょうを　もとめて　さまよう　ポケモン。\n"
    "あさひが　のぼると　すみかに　もどっていく。");

// 0x53FDA4
const u8 gBanettePokedexText[] POKEDEX_TEXT_DATA = _(
    "すてられた　ぬいぐるみが　ポケモンに　なった。\n"
    "ゴミすてばを　すみかにして　すてた　こどもを\n"
    "さがして　あるきまわると　いわれている。");

// 0x53FDE8
const u8 gDuskullPokedexText[] POKEDEX_TEXT_DATA = _(
    "まっかな　ひとつめに　にらまれると　くっきょうな\n"
    "おとなでも　からだが　すくんで　うごけなくなる。\n"
    "やみに　まぎれて　あるきまわる　やこうせい。");

// 0x53FE31
const u8 gDusclopsPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだの　なかは　からっぽで　ひとだまが\n"
    "ひとつだけ　もえていると　かんがえられているが\n"
    "まだ　だれも　たしかめた　ことは　ない。");

// 0x53FE73
const u8 gTropiusPokedexText[] POKEDEX_TEXT_DATA = _(
    "おおきな　はっぱを　はばたかせて　そらを　とぶ。\n"
    "くびに　なる　フサは　あまくて　おいしい。\n"
    "はるに　なると　くびから　かふんを　ばらまく。");

// 0x53FEBA
const u8 gChimechoPokedexText[] POKEDEX_TEXT_DATA = _(
    "あつい　きせつに　なると　げんきに　とびまわる。\n"
    "7しゅるいの　なきごえを　つかいわけて\n"
    "なかまと　コミュニケーションを　とっている。");

// 0x53FEFE
const u8 gAbsolPokedexText[] POKEDEX_TEXT_DATA = _(
    "そらや　だいちの　へんかを　びんかんに　かんじ\n"
    "さいがいを　さっちする　のうりょくを　もつ。\n"
    "100ねん　いきる　ちょうじゅの　ポケモン。");

// 0x53FF44
const u8 gWynautPokedexText[] POKEDEX_TEXT_DATA = _(
    "あまい　くだものが　だいこうぶつ。\n"
    "みみの　ような　うでで　きように　つみとる。\n"
    "かおりに　さそわれて　かじゅえんに　あつまる。");

// 0x53FF85
const u8 gSnoruntPokedexText[] POKEDEX_TEXT_DATA = _(
    "5ひき　ぐらいの　グループで　こうどうする。\n"
    "ゆきぐにでは　まよなか　ユキワラシが　すがたを\n"
    "みせると　あさ　ゆきが　つもると　いわれている。");

// 0x53FFCD
const u8 gGlaliePokedexText[] POKEDEX_TEXT_DATA = _(
    "くうきちゅうの　すいぶんを　しゅんかんてきに\n"
    "こおらせる　ちからを　もつため　オニゴーリの\n"
    "まわりには　ダイヤモンドダストが　はっせいする。");

// 0x540014
const u8 gSphealPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふかふかの　けがわで　おおわれているので\n"
    "りゅうひょうの　うえを　ころがったり\n"
    "うみに　もぐっても　ぜんぜん　つめたくない。");

// 0x540053
const u8 gSealeoPokedexText[] POKEDEX_TEXT_DATA = _(
    "むれを　つくり　りゅうひょうの　うえで　くらす。\n"
    "まえあしの　ちからが　つよく　こおりを　くだく。\n"
    "1にち　5かい　うみに　もぐり　えものを　とる。");

// 0x54009E
const u8 gWalreinPokedexText[] POKEDEX_TEXT_DATA = _(
    "むれを　まもる　リーダーは　なわばりに\n"
    "はいってきた　あいてを　いのちがけで　たおす。\n"
    "たたかいで　キバが　おれる　ことも　ある。");

// 0x5400E0
const u8 gClamperlPokedexText[] POKEDEX_TEXT_DATA = _(
    "カラを　つかって　えものを　はさみ　にがさない。\n"
    "しんかする　ときに　つくられる　しんじゅは\n"
    "ふしぎな　ちからを　やどしていると　いわれる。");

// 0x540127
const u8 gHuntailPokedexText[] POKEDEX_TEXT_DATA = _(
    "しんかいの　つよい　すいあつに　たえられるように\n"
    "とても　ふとく　がんじょうな　せぼねを　もつ。\n"
    "こざかなに　にた　しっぽの　めが　ひかる。");

// 0x54016E
const u8 gGorebyssPokedexText[] POKEDEX_TEXT_DATA = _(
    "ほそい　くちで　えものの　たいえきを　すする。\n"
    "うすい　ピンクいろの　からだは　エサを\n"
    "たべおえると　さらに　あざやかに　いろづく。");

// 0x5401B1
const u8 gRelicanthPokedexText[] POKEDEX_TEXT_DATA = _(
    "ぜつめつしたと　かんがえられていた　ポケモン。\n"
    "1おくねんの　あいだ　すがたが　かわっていない。\n"
    "むなびれを　つかって　かいていを　あるく。");

// 0x5401F8
const u8 gLuvdiscPokedexText[] POKEDEX_TEXT_DATA = _(
    "サニーゴの　えだを　ねどこに　している。\n"
    "すきな　あいてに　おもいを　つたえる　ときに\n"
    "ラブカスを　おくる　ふうしゅうが　のこっている。");

// 0x54023D
const u8 gBagonPokedexText[] POKEDEX_TEXT_DATA = _(
    "からだは　ちいさいが　ぜんしんが　きんにくの\n"
    "かたまりで　とても　ちからづよい　ポケモン。\n"
    "てつの　ような　あたまで　ずつきを　くりだす。");

// 0x540283
const u8 gShelgonPokedexText[] POKEDEX_TEXT_DATA = _(
    "エサを　ほとんど　たべずに　しんかを　まつ。\n"
    "くうふくに　たえる　ことで　つよくなる。\n"
    "しんかの　しゅんかん　カラが　はがれおちる。");

// 0x5402C6
const u8 gSalamencePokedexText[] POKEDEX_TEXT_DATA = _(
    "ながい　ねんげつを　かけて　からだの　さいぼうが\n"
    "とつぜんへんいを　おこして　つばさが　はえた。\n"
    "おこると　われを　わすれて　あばれまわる。");

// 0x54030D
const u8 gBeldumPokedexText[] POKEDEX_TEXT_DATA = _(
    "むれに　なった　ダンバルたちは　まるで　1ぴきの\n"
    "ポケモンの　ように　いっしみだれぬ　うごき。\n"
    "のうはで　きもちを　こうしんしているのだ。");

// 0x540353
const u8 gMetangPokedexText[] POKEDEX_TEXT_DATA = _(
    "りょうての　ツメは　ぶあつい　てっぱんを\n"
    "まるで　きぬの　ように　ひきさく　はかいりょく。\n"
    "じそく　100キロの　はやさで　そらを　とぶ。");

// 0x540399
const u8 gMetagrossPokedexText[] POKEDEX_TEXT_DATA = _(
    "ふくざつな　しんけい　ネットワークで　むすばれた\n"
    "4つの　のうみそを　もつ　メタグロスは\n"
    "スーパーコンピュータよりも　あたまが　いい。");

// 0x5403DD
const u8 gRegirockPokedexText[] POKEDEX_TEXT_DATA = _(
    "ぜんしんが　いわと　いしで　できた　ポケモン。\n"
    "たたかいで　からだの　いちぶが　けずれてしまうが\n"
    "じぶんで　あたらしい　いわを　つけて　なおす。");

// 0x540426
const u8 gRegicePokedexText[] POKEDEX_TEXT_DATA = _(
    "ぜんしんが　なんきょくの　こおりで　できている。\n"
    "けんきゅうしゃが　ちょうさした　けっか\n"
    "ひょうがきに　つくられた　こおり　らしい。");

// 0x540469
const u8 gRegisteelPokedexText[] POKEDEX_TEXT_DATA = _(
    "あらゆる　きんぞく　よりも　かたい　からだ。\n"
    "からだの　きんぞくは　かたい　だけでは　なく\n"
    "のびちぢみする　しょうたい　ふめいの　ぶっしつ。");

// 0x5404B0
const u8 gLatiasPokedexText[] POKEDEX_TEXT_DATA = _(
    "すうひきで　むれを　つくって　こうどうしていて\n"
    "めったに　ひとや　ポケモンと　せっしょくしない。\n"
    "てきの　けはいを　さっちすると　すがたを　けす。");

// 0x5404FA
const u8 gLatiosPokedexText[] POKEDEX_TEXT_DATA = _(
    "すがたを　けしていても　テレパシーが　あるので\n"
    "なかまの　いる　ばしょや　きもちが　わかる。\n"
    "ひとの　ことばを　りかいする　ちのうを　もつ。");

// 0x540541
const u8 gKyogrePokedexText[] POKEDEX_TEXT_DATA = _(
    "うみを　つくったとして　しんわに　とうじょう。\n"
    "ながねんに　わたり　グラードンと　たたかったのち\n"
    "かいていの　そこで　ねむりに　ついた。");

// 0x540586
const u8 gGroudonPokedexText[] POKEDEX_TEXT_DATA = _(
    "りくちを　つくったとして　しんわに　とうじょう。\n"
    "ちていの　マグマの　なかで　ねむっていて\n"
    "おきると　かざんが　ふんかすると　いわれている。");

// 0x5405CD
const u8 gRayquazaPokedexText[] POKEDEX_TEXT_DATA = _(
    "オゾンそうを　とびつづけている　ポケモン。\n"
    "カイオーガと　グラードンが　たたかうと\n"
    "ちじょうに　おりてくると　いわれている。");

// 0x54060C
const u8 gJirachiPokedexText[] POKEDEX_TEXT_DATA = _(
    "ねがいごとを　かなえる　ちからを　もつという。\n"
    "ねむっている　とき　かたい　けっしょうたいが\n"
    "からだを　つつみこみ　てきから　みを　まもる。");

// 0x540653
const u8 gDeoxysPokedexText[] POKEDEX_TEXT_DATA = _(
    "うちゅうウィルスが　レーザーを　あびたとき\n"
    "とつぜんへんいを　おこして　ポケモンに　なった。\n"
    "すばやい　うごきに　すぐれた　からだの　かたち。");

#undef POKEDEX_TEXT_DATA
