@ AbandonedShip_Rooms2_B1F scripts (JP map g24 m59 @ 0x0821ADC7)

AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper:: @ 0x0821ADC8
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring: @ 0x0821ADD1
	.string "たんけんに　ぴったりの　ばしょだから\n"
	.string "なんだか　わくわく　してくるよ！\l"
	.string "きっと　すっごい　たからものが　あるぜ！$"
