LavaridgeTown_PokemonCenter_1F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, LavaridgeTown_PokemonCenter_1F_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0

LavaridgeTown_PokemonCenter_1F_OnTransition:
	setrespawn HEAL_LOCATION_LAVARIDGE_TOWN
	call Common_EventScript_UpdateBrineyLocation
	end

LavaridgeTown_PokemonCenter_1F_EventScript_Nurse::
	setvar VAR_0x800B, LOCALID_LAVARIDGE_NURSE
	call Common_EventScript_PkmnCenterNurse
	waitmessage
	waitbuttonpress
	release
	end

LavaridgeTown_PokemonCenter_1F_EventScript_Youngster::
	msgbox LavaridgeTown_PokemonCenter_1F_Text_HotSpringCanInvigorate, MSGBOX_NPC
	end

LavaridgeTown_PokemonCenter_1F_EventScript_Woman::
	msgbox LavaridgeTown_PokemonCenter_1F_Text_TrainersPokemonSpendTimeTogether, MSGBOX_NPC
	end

LavaridgeTown_PokemonCenter_1F_EventScript_Gentleman::
	msgbox LavaridgeTown_PokemonCenter_1F_Text_TrainersShouldRestToo, MSGBOX_NPC
	end

LavaridgeTown_PokemonCenter_1F_Text_TrainersPokemonSpendTimeTogether:
	.string "ポケモンと　いっしょに　あるいていると\n"
	.string "なんだか　ポケモンが　なついてくれるような\l"
	.string "そんな　きが　するのよね$"

LavaridgeTown_PokemonCenter_1F_Text_HotSpringCanInvigorate:
	.string "おんせんに　はいる　だけで\n"
	.string "げんきに　なるなんて　ふしぎだなー！\l"
	.string "ポケモンも　いれて　あげたいなー$"

LavaridgeTown_PokemonCenter_1F_Text_TrainersShouldRestToo:
	.string "ほっほっほ！　おわかいの\n"
	.string "ここから　おんせんに　いけますぞ！\p"
	.string "ポケモンが　ここで　やすむのなら\n"
	.string "ひとも　おんせんで　ゆっくり　しませんと！$"
