#include "global.h"
#include "constants/songs.h"
#include "start_menu.h"

enum
{
    MENU_ACTION_POKEDEX,
    MENU_ACTION_POKEMON,
    MENU_ACTION_BAG,
    MENU_ACTION_POKENAV,
    MENU_ACTION_PLAYER,
    MENU_ACTION_SAVE,
    MENU_ACTION_OPTION,
    MENU_ACTION_EXIT,
    MENU_ACTION_RETIRE_SAFARI,
    MENU_ACTION_PLAYER_LINK,
    MENU_ACTION_REST_FRONTIER,
    MENU_ACTION_RETIRE_FRONTIER,
    MENU_ACTION_PYRAMID_BAG
};

// Save status
enum
{
    SAVE_IN_PROGRESS,
    SAVE_SUCCESS,
    SAVE_CANCELED,
    SAVE_ERROR
};

__attribute__((naked)) void SetDexPokemonPokenavFlags(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809ED10\n\t"
        "	bl FlagSet\n\t"
        "	movs r0, #0x86\n\t"
        "	lsls r0, r0, #4\n\t"
        "	bl FlagSet\n\t"
        "	ldr r0, _0809ED14\n\t"
        "	bl FlagSet\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809ED10: .4byte 0x00000861\n\t"
        "_0809ED14: .4byte 0x00000862\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildStartMenuActions(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809ED30\n\t"
        "	movs r1, #0\n\t"
        "	strb r1, [r0]\n\t"
        "	bl IsUpdateLinkStateCBActive\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809ED34\n\t"
        "	bl BuildLinkModeStartMenu\n\t"
        "	b _0809ED84\n\t"
        "	.align 2, 0\n\t"
        "_0809ED30: .4byte gUnknown_20372AF\n\t"
        "_0809ED34:\n\t"
        "	bl InUnionRoom\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809ED42\n\t"
        "	bl BuildUnionRoomStartMenu\n\t"
        "	b _0809ED84\n\t"
        "_0809ED42:\n\t"
        "	bl GetSafariZoneFlag\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809ED50\n\t"
        "	bl BuildSafariZoneStartMenu\n\t"
        "	b _0809ED84\n\t"
        "_0809ED50:\n\t"
        "	bl InBattlePike\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809ED60\n\t"
        "	bl BuildBattlePikeStartMenu\n\t"
        "	b _0809ED84\n\t"
        "_0809ED60:\n\t"
        "	bl CurrentBattlePyramidLocation\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809ED70\n\t"
        "	bl BuildBattlePyramidStartMenu\n\t"
        "	b _0809ED84\n\t"
        "_0809ED70:\n\t"
        "	bl InMultiBattleRoom\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809ED80\n\t"
        "	bl BuildMultiPartnerRoomStartMenu\n\t"
        "	b _0809ED84\n\t"
        "_0809ED80:\n\t"
        "	bl BuildNormalStartMenu\n\t"
        "_0809ED84:\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void AddStartMenuAction(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	adds r2, r0, #0\n\t"
        "	lsls r2, r2, #0x18\n\t"
        "	lsrs r2, r2, #0x18\n\t"
        "	ldr r0, _0809ED9C\n\t"
        "	ldr r1, _0809EDA0\n\t"
        "	bl AppendToList\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809ED9C: .4byte gUnknown_20372B0\n\t"
        "_0809EDA0: .4byte gUnknown_20372AF\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildNormalStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809EE08\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809EDBA\n\t"
        "	movs r0, #0\n\t"
        "	bl AddStartMenuAction\n\t"
        "_0809EDBA:\n\t"
        "	movs r0, #0x86\n\t"
        "	lsls r0, r0, #4\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809EDD0\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "_0809EDD0:\n\t"
        "	movs r0, #2\n\t"
        "	bl AddStartMenuAction\n\t"
        "	ldr r0, _0809EE0C\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809EDEA\n\t"
        "	movs r0, #3\n\t"
        "	bl AddStartMenuAction\n\t"
        "_0809EDEA:\n\t"
        "	movs r0, #4\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #5\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809EE08: .4byte 0x00000861\n\t"
        "_0809EE0C: .4byte 0x00000862\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildSafariZoneStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #8\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #0\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #2\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #4\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildLinkModeStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #2\n\t"
        "	bl AddStartMenuAction\n\t"
        "	ldr r0, _0809EE78\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809EE62\n\t"
        "	movs r0, #3\n\t"
        "	bl AddStartMenuAction\n\t"
        "_0809EE62:\n\t"
        "	movs r0, #9\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809EE78: .4byte 0x00000862\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildUnionRoomStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #2\n\t"
        "	bl AddStartMenuAction\n\t"
        "	ldr r0, _0809EEB4\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809EE9E\n\t"
        "	movs r0, #3\n\t"
        "	bl AddStartMenuAction\n\t"
        "_0809EE9E:\n\t"
        "	movs r0, #4\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809EEB4: .4byte 0x00000862\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildBattlePikeStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #0\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #4\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BuildBattlePyramidStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #0xc\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #4\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #0xa\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #0xb\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        ".syntax divided\n\t"
    );
}
__attribute__((naked)) void BuildMultiPartnerRoomStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #1\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #4\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #6\n\t"
        "	bl AddStartMenuAction\n\t"
        "	movs r0, #7\n\t"
        "	bl AddStartMenuAction\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}



__attribute__((naked)) void ShowSafariBallsWindow(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, lr}\n\t"
        "	sub sp, #0xc\n\t"
        "	ldr r4, _0809EF88\n\t"
        "	ldr r0, _0809EF8C\n\t"
        "	bl AddWindow\n\t"
        "	strb r0, [r4]\n\t"
        "	ldrb r0, [r4]\n\t"
        "	bl PutWindowTilemap\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #0\n\t"
        "	bl DrawStdWindowFrame\n\t"
        "	ldr r0, _0809EF90\n\t"
        "	ldr r1, _0809EF94\n\t"
        "	ldrb r1, [r1]\n\t"
        "	movs r2, #1\n\t"
        "	movs r3, #2\n\t"
        "	bl ConvertIntToDecimalStringN\n\t"
        "	ldr r5, _0809EF98\n\t"
        "	ldr r1, _0809EF9C\n\t"
        "	adds r0, r5, #0\n\t"
        "	bl StringExpandPlaceholders\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #2\n\t"
        "	str r1, [sp]\n\t"
        "	movs r1, #0xff\n\t"
        "	str r1, [sp, #4]\n\t"
        "	movs r1, #0\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #2\n\t"
        "	bl CopyWindowToVram\n\t"
        "	add sp, #0xc\n\t"
        "	pop {r4, r5}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809EF88: .4byte gUnknown_20372AC\n\t"
        "_0809EF8C: .4byte gUnknown_84E8B94\n\t"
        "_0809EF90: .4byte gStringVar1\n\t"
        "_0809EF94: .4byte gNumSafariBalls\n\t"
        "_0809EF98: .4byte gStringVar4\n\t"
        "_0809EF9C: .4byte gUnknown_84E8B5C + 0x28\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void ShowPyramidFloorWindow(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, lr}\n\t"
        "	sub sp, #0xc\n\t"
        "	ldr r0, _0809EFB8\n\t"
        "	ldr r0, [r0]\n\t"
        "	ldr r1, _0809EFBC\n\t"
        "	adds r0, r0, r1\n\t"
        "	ldrh r0, [r0]\n\t"
        "	cmp r0, #7\n\t"
        "	bne _0809EFC8\n\t"
        "	ldr r4, _0809EFC0\n\t"
        "	ldr r0, _0809EFC4\n\t"
        "	b _0809EFCC\n\t"
        "	.align 2, 0\n\t"
        "_0809EFB8: .4byte gSaveBlock2Ptr\n\t"
        "_0809EFBC: .4byte 0x00000CB2\n\t"
        "_0809EFC0: .4byte gUnknown_20372AD\n\t"
        "_0809EFC4: .4byte gUnknown_84E8C24\n\t"
        "_0809EFC8:\n\t"
        "	ldr r4, _0809F02C\n\t"
        "	ldr r0, _0809F030\n\t"
        "_0809EFCC:\n\t"
        "	bl AddWindow\n\t"
        "	strb r0, [r4]\n\t"
        "	ldr r4, _0809F02C\n\t"
        "	ldrb r0, [r4]\n\t"
        "	bl PutWindowTilemap\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #0\n\t"
        "	bl DrawStdWindowFrame\n\t"
        "	ldr r0, _0809F034\n\t"
        "	ldr r2, _0809F038\n\t"
        "	ldr r1, _0809F03C\n\t"
        "	ldr r1, [r1]\n\t"
        "	ldr r3, _0809F040\n\t"
        "	adds r1, r1, r3\n\t"
        "	ldrh r1, [r1]\n\t"
        "	lsls r1, r1, #2\n\t"
        "	adds r1, r1, r2\n\t"
        "	ldr r1, [r1]\n\t"
        "	bl StringCopy\n\t"
        "	ldr r5, _0809F044\n\t"
        "	ldr r1, _0809F048\n\t"
        "	adds r0, r5, #0\n\t"
        "	bl StringExpandPlaceholders\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #2\n\t"
        "	str r1, [sp]\n\t"
        "	movs r1, #0xff\n\t"
        "	str r1, [sp, #4]\n\t"
        "	movs r1, #0\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #2\n\t"
        "	bl CopyWindowToVram\n\t"
        "	add sp, #0xc\n\t"
        "	pop {r4, r5}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F02C: .4byte gUnknown_20372AD\n\t"
        "_0809F030: .4byte gUnknown_84E8C1C\n\t"
        "_0809F034: .4byte gStringVar1\n\t"
        "_0809F038: .4byte gUnknown_84E8BFC\n\t"
        "_0809F03C: .4byte gSaveBlock2Ptr\n\t"
        "_0809F040: .4byte 0x00000CB2\n\t"
        "_0809F044: .4byte gStringVar4\n\t"
        "_0809F048: .4byte gUnknown_84E8B9C\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void RemoveExtraStartMenuWindows(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	bl GetSafariZoneFlag\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F06E\n\t"
        "	ldr r4, _0809F090\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearStdWindowAndFrameToTransparent\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #2\n\t"
        "	bl CopyWindowToVram\n\t"
        "	ldrb r0, [r4]\n\t"
        "	bl RemoveWindow\n\t"
        "_0809F06E:\n\t"
        "	bl CurrentBattlePyramidLocation\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F088\n\t"
        "	ldr r4, _0809F094\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearStdWindowAndFrameToTransparent\n\t"
        "	ldrb r0, [r4]\n\t"
        "	bl RemoveWindow\n\t"
        "_0809F088:\n\t"
        "	pop {r4}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F090: .4byte gUnknown_20372AC\n\t"
        "_0809F094: .4byte gUnknown_20372AD\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void PrintStartMenuActions(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, r6, r7, lr}\n\t"
        "	mov r7, sl\n\t"
        "	mov r6, sb\n\t"
        "	mov r5, r8\n\t"
        "	push {r5, r6, r7}\n\t"
        "	sub sp, #0xc\n\t"
        "	mov r8, r0\n\t"
        "	adds r6, r1, #0\n\t"
        "	ldrb r2, [r0]\n\t"
        "	ldr r0, _0809F0F0\n\t"
        "	mov sb, r0\n\t"
        "	ldr r1, _0809F0F4\n\t"
        "	mov sl, r1\n\t"
        "_0809F0B2:\n\t"
        "	ldr r0, _0809F0F8\n\t"
        "	lsls r2, r2, #0x18\n\t"
        "	asrs r4, r2, #0x18\n\t"
        "	adds r5, r4, r0\n\t"
        "	ldrb r0, [r5]\n\t"
        "	lsls r3, r0, #3\n\t"
        "	mov r0, sb\n\t"
        "	adds r0, #4\n\t"
        "	adds r0, r3, r0\n\t"
        "	ldr r1, [r0]\n\t"
        "	ldr r0, _0809F0FC\n\t"
        "	adds r7, r2, #0\n\t"
        "	cmp r1, r0\n\t"
        "	bne _0809F100\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	ldrb r1, [r5]\n\t"
        "	lsls r1, r1, #3\n\t"
        "	add r1, sb\n\t"
        "	ldr r1, [r1]\n\t"
        "	lsls r3, r4, #4\n\t"
        "	adds r3, #0xa\n\t"
        "	lsls r3, r3, #0x10\n\t"
        "	lsrs r3, r3, #0x10\n\t"
        "	movs r2, #8\n\t"
        "	bl PrintPlayerNameOnWindow\n\t"
        "	b _0809F130\n\t"
        "	.align 2, 0\n\t"
        "_0809F0F0: .4byte gUnknown_84E8C2C\n\t"
        "_0809F0F4: .4byte gStringVar4\n\t"
        "_0809F0F8: .4byte gUnknown_20372B0\n\t"
        "_0809F0FC: .4byte StartMenuPlayerNameCallback + 1\n\t"
        "_0809F100:\n\t"
        "	mov r1, sb\n\t"
        "	adds r0, r3, r1\n\t"
        "	ldr r1, [r0]\n\t"
        "	mov r0, sl\n\t"
        "	bl StringExpandPlaceholders\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	lsls r1, r4, #4\n\t"
        "	adds r1, #0xa\n\t"
        "	lsls r1, r1, #0x18\n\t"
        "	lsrs r1, r1, #0x18\n\t"
        "	str r1, [sp]\n\t"
        "	movs r1, #0xff\n\t"
        "	str r1, [sp, #4]\n\t"
        "	movs r1, #0\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	mov r2, sl\n\t"
        "	movs r3, #8\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "_0809F130:\n\t"
        "	movs r0, #0x80\n\t"
        "	lsls r0, r0, #0x11\n\t"
        "	adds r1, r7, r0\n\t"
        "	lsrs r2, r1, #0x18\n\t"
        "	asrs r1, r1, #0x18\n\t"
        "	ldr r0, _0809F150\n\t"
        "	ldrb r0, [r0]\n\t"
        "	cmp r1, r0\n\t"
        "	bge _0809F154\n\t"
        "	subs r6, #1\n\t"
        "	cmp r6, #0\n\t"
        "	bne _0809F0B2\n\t"
        "	mov r1, r8\n\t"
        "	strb r2, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F15A\n\t"
        "	.align 2, 0\n\t"
        "_0809F150: .4byte gUnknown_20372AF\n\t"
        "_0809F154:\n\t"
        "	mov r0, r8\n\t"
        "	strb r2, [r0]\n\t"
        "	movs r0, #1\n\t"
        "_0809F15A:\n\t"
        "	add sp, #0xc\n\t"
        "	pop {r3, r4, r5}\n\t"
        "	mov r8, r3\n\t"
        "	mov sb, r4\n\t"
        "	mov sl, r5\n\t"
        "	pop {r4, r5, r6, r7}\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void InitStartMenuStep(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	sub sp, #0xc\n\t"
        "	ldr r0, _0809F188\n\t"
        "	movs r1, #0\n\t"
        "	ldrsb r1, [r0, r1]\n\t"
        "	adds r2, r0, #0\n\t"
        "	cmp r1, #5\n\t"
        "	bhi _0809F264\n\t"
        "	lsls r0, r1, #2\n\t"
        "	ldr r1, _0809F18C\n\t"
        "	adds r0, r0, r1\n\t"
        "	ldr r0, [r0]\n\t"
        "	mov pc, r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F188: .4byte gUnknown_20372B9\n\t"
        "_0809F18C: .4byte _0809F190\n\t"
        "_0809F190:\n\t"
        "	.4byte _0809F1A8\n\t"
        "	.4byte _0809F1B0\n\t"
        "	.4byte _0809F1BC\n\t"
        "	.4byte _0809F1E4\n\t"
        "	.4byte _0809F208\n\t"
        "	.4byte _0809F224\n\t"
        "_0809F1A8:\n\t"
        "	ldrb r0, [r2]\n\t"
        "	adds r0, #1\n\t"
        "	strb r0, [r2]\n\t"
        "	b _0809F264\n\t"
        "_0809F1B0:\n\t"
        "	bl BuildStartMenuActions\n\t"
        "	ldr r1, _0809F1B8\n\t"
        "	b _0809F218\n\t"
        "	.align 2, 0\n\t"
        "_0809F1B8: .4byte gUnknown_20372B9\n\t"
        "_0809F1BC:\n\t"
        "	bl LoadMessageBoxAndBorderGfx\n\t"
        "	ldr r0, _0809F1DC\n\t"
        "	ldrb r0, [r0]\n\t"
        "	bl sub_081977C8\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	movs r1, #0\n\t"
        "	bl DrawStdWindowFrame\n\t"
        "	ldr r1, _0809F1E0\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1, #1]\n\t"
        "	b _0809F218\n\t"
        "	.align 2, 0\n\t"
        "_0809F1DC: .4byte gUnknown_20372AF\n\t"
        "_0809F1E0: .4byte gUnknown_20372B9\n\t"
        "_0809F1E4:\n\t"
        "	bl GetSafariZoneFlag\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F1F0\n\t"
        "	bl ShowSafariBallsWindow\n\t"
        "_0809F1F0:\n\t"
        "	bl CurrentBattlePyramidLocation\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F1FE\n\t"
        "	bl ShowPyramidFloorWindow\n\t"
        "_0809F1FE:\n\t"
        "	ldr r1, _0809F204\n\t"
        "	b _0809F218\n\t"
        "	.align 2, 0\n\t"
        "_0809F204: .4byte gUnknown_20372B9\n\t"
        "_0809F208:\n\t"
        "	ldr r4, _0809F220\n\t"
        "	adds r0, r4, #0\n\t"
        "	movs r1, #2\n\t"
        "	bl PrintStartMenuActions\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F264\n\t"
        "	subs r1, r4, #1\n\t"
        "_0809F218:\n\t"
        "	ldrb r0, [r1]\n\t"
        "	adds r0, #1\n\t"
        "	strb r0, [r1]\n\t"
        "	b _0809F264\n\t"
        "	.align 2, 0\n\t"
        "_0809F220: .4byte gUnknown_20372BA\n\t"
        "_0809F224:\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	movs r1, #0x10\n\t"
        "	str r1, [sp]\n\t"
        "	ldr r1, _0809F25C\n\t"
        "	ldrb r1, [r1]\n\t"
        "	str r1, [sp, #4]\n\t"
        "	ldr r4, _0809F260\n\t"
        "	ldrb r1, [r4]\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	movs r2, #0\n\t"
        "	movs r3, #0xa\n\t"
        "	bl sub_081984B0\n\t"
        "	strb r0, [r4]\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	movs r1, #1\n\t"
        "	bl CopyWindowToVram\n\t"
        "	movs r0, #1\n\t"
        "	b _0809F266\n\t"
        "	.align 2, 0\n\t"
        "_0809F25C: .4byte gUnknown_20372AF\n\t"
        "_0809F260: .4byte gUnknown_20372AE\n\t"
        "_0809F264:\n\t"
        "	movs r0, #0\n\t"
        "_0809F266:\n\t"
        "	add sp, #0xc\n\t"
        "	pop {r4}\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void InitStartMenu(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r1, _0809F288\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	strb r0, [r1, #1]\n\t"
        "_0809F27A:\n\t"
        "	bl InitStartMenuStep\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F27A\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F288: .4byte gUnknown_20372B9\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuTask(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r4, r0, #0x18\n\t"
        "	bl InitStartMenuStep\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809F2A0\n\t"
        "	adds r0, r4, #0\n\t"
        "	bl SwitchTaskToFollowupFunc\n\t"
        "_0809F2A0:\n\t"
        "	pop {r4}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void CreateStartMenuTask(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, lr}\n\t"
        "	adds r5, r0, #0\n\t"
        "	ldr r1, _0809F2D0\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	strb r0, [r1, #1]\n\t"
        "	ldr r4, _0809F2D4\n\t"
        "	adds r0, r4, #0\n\t"
        "	movs r1, #0x50\n\t"
        "	bl CreateTask\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	adds r1, r4, #0\n\t"
        "	adds r2, r5, #0\n\t"
        "	bl SetTaskFuncWithFollowupFunc\n\t"
        "	pop {r4, r5}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F2D0: .4byte gUnknown_20372B9\n\t"
        "_0809F2D4: .4byte StartMenuTask + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809F2D8(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl InitStartMenuStep\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F2EA\n\t"
        "	bl ReturnToFieldOpenStartMenu\n\t"
        "	movs r0, #1\n\t"
        "	b _0809F2EC\n\t"
        "_0809F2EA:\n\t"
        "	movs r0, #0\n\t"
        "_0809F2EC:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void ShowReturnToFieldStartMenu()
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	ldr r1, _0809F300\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	strb r0, [r1, #1]\n\t"
        "	ldr r1, _0809F304\n\t"
        "	ldr r0, _0809F308\n\t"
        "	str r0, [r1]\n\t"
        "	bx lr\n\t"
        "	.align 2, 0\n\t"
        "_0809F300: .4byte gUnknown_20372B9\n\t"
        "_0809F304: .4byte gFieldCallback2\n\t"
        "_0809F308: .4byte sub_0809F2D8 + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void Task_ShowStartMenu(u8 taskId)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, lr}\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r5, r0, #0x18\n\t"
        "	lsls r0, r5, #2\n\t"
        "	adds r0, r0, r5\n\t"
        "	lsls r0, r0, #3\n\t"
        "	ldr r1, _0809F32C\n\t"
        "	adds r4, r0, r1\n\t"
        "	movs r1, #8\n\t"
        "	ldrsh r0, [r4, r1]\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F330\n\t"
        "	cmp r0, #1\n\t"
        "	beq _0809F354\n\t"
        "	b _0809F36A\n\t"
        "	.align 2, 0\n\t"
        "_0809F32C: .4byte gTasks\n\t"
        "_0809F330:\n\t"
        "	bl InUnionRoom\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809F33C\n\t"
        "	bl var_800D_set_xB\n\t"
        "_0809F33C:\n\t"
        "	ldr r1, _0809F34C\n\t"
        "	ldr r0, _0809F350\n\t"
        "	str r0, [r1]\n\t"
        "	ldrh r0, [r4, #8]\n\t"
        "	adds r0, #1\n\t"
        "	strh r0, [r4, #8]\n\t"
        "	b _0809F36A\n\t"
        "	.align 2, 0\n\t"
        "_0809F34C: .4byte gUnknown_3005B54\n\t"
        "_0809F350: .4byte HandleStartMenuInput + 1\n\t"
        "_0809F354:\n\t"
        "	ldr r0, _0809F370\n\t"
        "	ldr r0, [r0]\n\t"
        "	bl _call_via_r0\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809F36A\n\t"
        "	adds r0, r5, #0\n\t"
        "	bl DestroyTask\n\t"
        "_0809F36A:\n\t"
        "	pop {r4, r5}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F370: .4byte gUnknown_3005B54\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void ShowStartMenu()
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl IsUpdateLinkStateCBActive\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809F38A\n\t"
        "	bl FreezeObjectEvents\n\t"
        "	bl sub_0808B1C8\n\t"
        "	bl sub_0808B658\n\t"
        "_0809F38A:\n\t"
        "	ldr r0, _0809F398\n\t"
        "	bl CreateStartMenuTask\n\t"
        "	bl LockPlayerFieldControls\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F398: .4byte Task_ShowStartMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void HandleStartMenuInput(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	ldr r4, _0809F448\n\t"
        "	ldrh r1, [r4, #0x2e]\n\t"
        "	movs r0, #0x40\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F3BC\n\t"
        "	movs r0, #5\n\t"
        "	bl PlaySE\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	bl Menu_MoveCursor\n\t"
        "	ldr r1, _0809F44C\n\t"
        "	strb r0, [r1]\n\t"
        "_0809F3BC:\n\t"
        "	ldrh r1, [r4, #0x2e]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F3D6\n\t"
        "	movs r0, #5\n\t"
        "	bl PlaySE\n\t"
        "	movs r0, #1\n\t"
        "	bl Menu_MoveCursor\n\t"
        "	ldr r1, _0809F44C\n\t"
        "	strb r0, [r1]\n\t"
        "_0809F3D6:\n\t"
        "	ldrh r1, [r4, #0x2e]\n\t"
        "	movs r0, #1\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F470\n\t"
        "	movs r0, #5\n\t"
        "	bl PlaySE\n\t"
        "	ldr r1, _0809F450\n\t"
        "	ldr r2, _0809F454\n\t"
        "	ldr r0, _0809F44C\n\t"
        "	ldrb r0, [r0]\n\t"
        "	adds r0, r0, r2\n\t"
        "	ldrb r0, [r0]\n\t"
        "	lsls r0, r0, #3\n\t"
        "	adds r1, #4\n\t"
        "	adds r0, r0, r1\n\t"
        "	ldr r1, [r0]\n\t"
        "	ldr r0, _0809F458\n\t"
        "	cmp r1, r0\n\t"
        "	bne _0809F40C\n\t"
        "	movs r0, #0\n\t"
        "	bl GetNationalPokedexCount\n\t"
        "	lsls r0, r0, #0x10\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F478\n\t"
        "_0809F40C:\n\t"
        "	ldr r3, _0809F45C\n\t"
        "	ldr r1, _0809F450\n\t"
        "	ldr r2, _0809F454\n\t"
        "	ldr r0, _0809F44C\n\t"
        "	ldrb r0, [r0]\n\t"
        "	adds r0, r0, r2\n\t"
        "	ldrb r0, [r0]\n\t"
        "	lsls r0, r0, #3\n\t"
        "	adds r1, #4\n\t"
        "	adds r0, r0, r1\n\t"
        "	ldr r1, [r0]\n\t"
        "	str r1, [r3]\n\t"
        "	ldr r0, _0809F460\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809F478\n\t"
        "	ldr r0, _0809F464\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809F478\n\t"
        "	ldr r0, _0809F468\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809F478\n\t"
        "	ldr r0, _0809F46C\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809F478\n\t"
        "	movs r0, #1\n\t"
        "	movs r1, #0\n\t"
        "	bl FadeScreen\n\t"
        "	b _0809F478\n\t"
        "	.align 2, 0\n\t"
        "_0809F448: .4byte gMain\n\t"
        "_0809F44C: .4byte gUnknown_20372AE\n\t"
        "_0809F450: .4byte gUnknown_84E8C2C\n\t"
        "_0809F454: .4byte gUnknown_20372B0\n\t"
        "_0809F458: .4byte StartMenuPokedexCallback + 1\n\t"
        "_0809F45C: .4byte gUnknown_3005B54\n\t"
        "_0809F460: .4byte StartMenuSaveCallback + 1\n\t"
        "_0809F464: .4byte StartMenuExitCallback + 1\n\t"
        "_0809F468: .4byte StartMenuSafariZoneRetireCallback + 1\n\t"
        "_0809F46C: .4byte StartMenuBattlePyramidRetireCallback + 1\n\t"
        "_0809F470:\n\t"
        "	movs r0, #0xa\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809F47C\n\t"
        "_0809F478:\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F486\n\t"
        "_0809F47C:\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl HideStartMenu\n\t"
        "	movs r0, #1\n\t"
        "_0809F486:\n\t"
        "	pop {r4}\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuPokedexCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F4A0\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F4A4\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F4BE\n\t"
        "	.align 2, 0\n\t"
        "_0809F4A0: .4byte gPaletteFade\n\t"
        "_0809F4A4:\n\t"
        "	movs r0, #0x29\n\t"
        "	bl IncrementGameStat\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F4C4\n\t"
        "	bl SetMainCallback2\n\t"
        "	movs r0, #1\n\t"
        "_0809F4BE:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F4C4: .4byte CB2_Pokedex + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuPokemonCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F4DC\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F4E0\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F4F4\n\t"
        "	.align 2, 0\n\t"
        "_0809F4DC: .4byte gPaletteFade\n\t"
        "_0809F4E0:\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F4F8\n\t"
        "	bl SetMainCallback2\n\t"
        "	movs r0, #1\n\t"
        "_0809F4F4:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F4F8: .4byte CB2_PartyMenuFromStartMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuBagCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F510\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F514\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F528\n\t"
        "	.align 2, 0\n\t"
        "_0809F510: .4byte gPaletteFade\n\t"
        "_0809F514:\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F52C\n\t"
        "	bl SetMainCallback2\n\t"
        "	movs r0, #1\n\t"
        "_0809F528:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F52C: .4byte CB2_BagMenuFromStartMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuPokeNavCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F544\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F548\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F55C\n\t"
        "	.align 2, 0\n\t"
        "_0809F544: .4byte gPaletteFade\n\t"
        "_0809F548:\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F560\n\t"
        "	bl SetMainCallback2\n\t"
        "	movs r0, #1\n\t"
        "_0809F55C:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F560: .4byte CB2_InitPokeNav + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuPlayerNameCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F598\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809F5CC\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	bl IsUpdateLinkStateCBActive\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809F58E\n\t"
        "	bl InUnionRoom\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F5A0\n\t"
        "_0809F58E:\n\t"
        "	ldr r0, _0809F59C\n\t"
        "	bl ShowPlayerTrainerCard\n\t"
        "	b _0809F5C2\n\t"
        "	.align 2, 0\n\t"
        "_0809F598: .4byte gPaletteFade\n\t"
        "_0809F59C: .4byte CB2_ReturnToFieldWithOpenMenu + 1\n\t"
        "_0809F5A0:\n\t"
        "	ldr r0, _0809F5B4\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F5BC\n\t"
        "	ldr r0, _0809F5B8\n\t"
        "	bl ShowFrontierPass\n\t"
        "	b _0809F5C2\n\t"
        "	.align 2, 0\n\t"
        "_0809F5B4: .4byte 0x000008D2\n\t"
        "_0809F5B8: .4byte CB2_ReturnToFieldWithOpenMenu + 1\n\t"
        "_0809F5BC:\n\t"
        "	ldr r0, _0809F5C8\n\t"
        "	bl ShowPlayerTrainerCard\n\t"
        "_0809F5C2:\n\t"
        "	movs r0, #1\n\t"
        "	b _0809F5CE\n\t"
        "	.align 2, 0\n\t"
        "_0809F5C8: .4byte CB2_ReturnToFieldWithOpenMenu + 1\n\t"
        "_0809F5CC:\n\t"
        "	movs r0, #0\n\t"
        "_0809F5CE:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuSaveCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl CurrentBattlePyramidLocation\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F5E4\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "_0809F5E4:\n\t"
        "	ldr r1, _0809F5F0\n\t"
        "	ldr r0, _0809F5F4\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F5F0: .4byte gUnknown_3005B54\n\t"
        "_0809F5F4: .4byte SaveStartCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuOptionCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F60C\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F610\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F62A\n\t"
        "	.align 2, 0\n\t"
        "_0809F60C: .4byte gPaletteFade\n\t"
        "_0809F610:\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F630\n\t"
        "	bl SetMainCallback2\n\t"
        "	ldr r1, _0809F634\n\t"
        "	ldr r0, _0809F638\n\t"
        "	str r0, [r1, #8]\n\t"
        "	movs r0, #1\n\t"
        "_0809F62A:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F630: .4byte CB2_InitOptionMenu + 1\n\t"
        "_0809F634: .4byte gMain\n\t"
        "_0809F638: .4byte CB2_ReturnToFieldWithOpenMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuExitCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl HideStartMenu\n\t"
        "	movs r0, #1\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuSafariZoneRetireCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl HideStartMenu\n\t"
        "	bl SafariZoneRetirePrompt\n\t"
        "	movs r0, #1\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuLinkModePlayerNameCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F674\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F678\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F68C\n\t"
        "	.align 2, 0\n\t"
        "_0809F674: .4byte gPaletteFade\n\t"
        "_0809F678:\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F690\n\t"
        "	ldrb r0, [r0]\n\t"
        "	ldr r1, _0809F694\n\t"
        "	bl ShowTrainerCardInLink\n\t"
        "	movs r0, #1\n\t"
        "_0809F68C:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F690: .4byte gLocalLinkPlayerId\n\t"
        "_0809F694: .4byte CB2_ReturnToFieldWithOpenMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuBattlePyramidRetireCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	ldr r1, _0809F6A4\n\t"
        "	ldr r0, _0809F6A8\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	bx lr\n\t"
        "	.align 2, 0\n\t"
        "_0809F6A4: .4byte gUnknown_3005B54\n\t"
        "_0809F6A8: .4byte BattlePyramidRetireStartCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809F6AC(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearDialogWindowAndFrameToTransparent\n\t"
        "	bl ScriptUnfreezeObjectEvents\n\t"
        "	ldr r0, _0809F6C8\n\t"
        "	bl CreateStartMenuTask\n\t"
        "	bl LockPlayerFieldControls\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F6C8: .4byte Task_ShowStartMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void StartMenuBattlePyramidBagCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809F6E0\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F6E4\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F6F8\n\t"
        "	.align 2, 0\n\t"
        "_0809F6E0: .4byte gPaletteFade\n\t"
        "_0809F6E4:\n\t"
        "	bl PlayRainStoppingSoundEffect\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	bl CleanupOverworldWindowsAndTilemaps\n\t"
        "	ldr r0, _0809F6FC\n\t"
        "	bl SetMainCallback2\n\t"
        "	movs r0, #1\n\t"
        "_0809F6F8:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F6FC: .4byte CB2_PyramidBagMenuFromStartMenu + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveStartCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl InitSave\n\t"
        "	ldr r1, _0809F714\n\t"
        "	ldr r0, _0809F718\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F714: .4byte gUnknown_3005B54\n\t"
        "_0809F718: .4byte SaveCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RunSaveCallback\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	beq _0809F754\n\t"
        "	cmp r0, #1\n\t"
        "	ble _0809F76C\n\t"
        "	cmp r0, #2\n\t"
        "	beq _0809F738\n\t"
        "	cmp r0, #3\n\t"
        "	beq _0809F754\n\t"
        "	b _0809F76C\n\t"
        "_0809F738:\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearDialogWindowAndFrameToTransparent\n\t"
        "	bl InitStartMenu\n\t"
        "	ldr r1, _0809F74C\n\t"
        "	ldr r0, _0809F750\n\t"
        "	str r0, [r1]\n\t"
        "	b _0809F76C\n\t"
        "	.align 2, 0\n\t"
        "_0809F74C: .4byte gUnknown_3005B54\n\t"
        "_0809F750: .4byte HandleStartMenuInput + 1\n\t"
        "_0809F754:\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #1\n\t"
        "	bl ClearDialogWindowAndFrameToTransparent\n\t"
        "	bl ScriptUnfreezeObjectEvents\n\t"
        "	bl UnlockPlayerFieldControls\n\t"
        "	bl SoftResetInBattlePyramid\n\t"
        "	movs r0, #1\n\t"
        "	b _0809F76E\n\t"
        "_0809F76C:\n\t"
        "	movs r0, #0\n\t"
        "_0809F76E:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BattlePyramidRetireStartCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl InitBattlePyramidRetire\n\t"
        "	ldr r1, _0809F788\n\t"
        "	ldr r0, _0809F78C\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F788: .4byte gUnknown_3005B54\n\t"
        "_0809F78C: .4byte BattlePyramidRetireCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BattlePyramidRetireReturnCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl InitStartMenu\n\t"
        "	ldr r1, _0809F7A4\n\t"
        "	ldr r0, _0809F7A8\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F7A4: .4byte gUnknown_3005B54\n\t"
        "_0809F7A8: .4byte HandleStartMenuInput + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BattlePyramidRetireCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RunSaveCallback\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	beq _0809F7C4\n\t"
        "	cmp r0, #1\n\t"
        "	ble _0809F7F8\n\t"
        "	cmp r0, #2\n\t"
        "	beq _0809F7D8\n\t"
        "	b _0809F7F8\n\t"
        "_0809F7C4:\n\t"
        "	bl RemoveExtraStartMenuWindows\n\t"
        "	ldr r1, _0809F7D0\n\t"
        "	ldr r0, _0809F7D4\n\t"
        "	str r0, [r1]\n\t"
        "	b _0809F7F8\n\t"
        "	.align 2, 0\n\t"
        "_0809F7D0: .4byte gUnknown_3005B54\n\t"
        "_0809F7D4: .4byte BattlePyramidRetireReturnCallback + 1\n\t"
        "_0809F7D8:\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #1\n\t"
        "	bl ClearDialogWindowAndFrameToTransparent\n\t"
        "	bl ScriptUnfreezeObjectEvents\n\t"
        "	bl UnlockPlayerFieldControls\n\t"
        "	ldr r0, _0809F7F4\n\t"
        "	bl ScriptContext_SetupScript\n\t"
        "	movs r0, #1\n\t"
        "	b _0809F7FA\n\t"
        "	.align 2, 0\n\t"
        "_0809F7F4: .4byte 0x0822D751\n\t"
        "_0809F7F8:\n\t"
        "	movs r0, #0\n\t"
        "_0809F7FA:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void InitSave(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl save_serialize_map\n\t"
        "	ldr r1, _0809F818\n\t"
        "	ldr r0, _0809F81C\n\t"
        "	str r0, [r1]\n\t"
        "	ldr r1, _0809F820\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F818: .4byte gUnknown_20372BC\n\t"
        "_0809F81C: .4byte SaveConfirmSaveCallback + 1\n\t"
        "_0809F820: .4byte gUnknown_20372C1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void RunSaveCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RunTextPrintersAndIsPrinter0Active\n\t"
        "	lsls r0, r0, #0x10\n\t"
        "	lsrs r0, r0, #0x10\n\t"
        "	cmp r0, #1\n\t"
        "	beq _0809F850\n\t"
        "	ldr r1, _0809F848\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	ldr r0, _0809F84C\n\t"
        "	ldr r0, [r0]\n\t"
        "	bl _call_via_r0\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	b _0809F852\n\t"
        "	.align 2, 0\n\t"
        "_0809F848: .4byte gUnknown_20372C1\n\t"
        "_0809F84C: .4byte gUnknown_20372BC\n\t"
        "_0809F850:\n\t"
        "	movs r0, #0\n\t"
        "_0809F852:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveGame()
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl InitSave\n\t"
        "	ldr r0, _0809F86C\n\t"
        "	movs r1, #0x50\n\t"
        "	bl CreateTask\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F86C: .4byte SaveGameTask + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void ShowSaveMessage(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	adds r2, r0, #0\n\t"
        "	adds r4, r1, #0\n\t"
        "	ldr r0, _0809F89C\n\t"
        "	adds r1, r2, #0\n\t"
        "	bl StringExpandPlaceholders\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #1\n\t"
        "	bl sub_08197650\n\t"
        "	movs r0, #1\n\t"
        "	bl AddTextPrinterForMessage_2\n\t"
        "	ldr r1, _0809F8A0\n\t"
        "	movs r0, #1\n\t"
        "	strb r0, [r1]\n\t"
        "	ldr r0, _0809F8A4\n\t"
        "	str r4, [r0]\n\t"
        "	pop {r4}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F89C: .4byte gStringVar4\n\t"
        "_0809F8A0: .4byte gUnknown_20372C1\n\t"
        "_0809F8A4: .4byte gUnknown_20372BC\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveGameTask(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r4, r0, #0x18\n\t"
        "	bl RunSaveCallback\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r1, r0, #0x18\n\t"
        "	cmp r1, #1\n\t"
        "	beq _0809F8D4\n\t"
        "	cmp r1, #1\n\t"
        "	bgt _0809F8C4\n\t"
        "	cmp r1, #0\n\t"
        "	beq _0809F8E2\n\t"
        "	b _0809F8D8\n\t"
        "_0809F8C4:\n\t"
        "	cmp r1, #3\n\t"
        "	bgt _0809F8D8\n\t"
        "	ldr r1, _0809F8D0\n\t"
        "	movs r0, #0\n\t"
        "	strh r0, [r1]\n\t"
        "	b _0809F8D8\n\t"
        "	.align 2, 0\n\t"
        "_0809F8D0: .4byte gSpecialVar_Result\n\t"
        "_0809F8D4:\n\t"
        "	ldr r0, _0809F8E8\n\t"
        "	strh r1, [r0]\n\t"
        "_0809F8D8:\n\t"
        "	adds r0, r4, #0\n\t"
        "	bl DestroyTask\n\t"
        "	bl ScriptContext_Enable\n\t"
        "_0809F8E2:\n\t"
        "	pop {r4}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809F8E8: .4byte gSpecialVar_Result\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809F8EC(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #1\n\t"
        "	bl ClearDialogWindowAndFrame\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void HideSaveInfoWindow(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RemoveSaveInfoWindow\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveStartTimer(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	ldr r1, _0809F910\n\t"
        "	movs r0, #0x3c\n\t"
        "	strb r0, [r1]\n\t"
        "	bx lr\n\t"
        "	.align 2, 0\n\t"
        "_0809F910: .4byte gUnknown_20372C0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveSuccesTimer(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r1, _0809F934\n\t"
        "	ldrb r0, [r1]\n\t"
        "	subs r2, r0, #1\n\t"
        "	strb r2, [r1]\n\t"
        "	ldr r0, _0809F938\n\t"
        "	ldrh r1, [r0, #0x2c]\n\t"
        "	movs r0, #1\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809F93C\n\t"
        "	lsls r0, r2, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F942\n\t"
        "	movs r0, #0\n\t"
        "	b _0809F944\n\t"
        "	.align 2, 0\n\t"
        "_0809F934: .4byte gUnknown_20372C0\n\t"
        "_0809F938: .4byte gMain\n\t"
        "_0809F93C:\n\t"
        "	movs r0, #5\n\t"
        "	bl PlaySE\n\t"
        "_0809F942:\n\t"
        "	movs r0, #1\n\t"
        "_0809F944:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveErrorTimer(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r1, _0809F964\n\t"
        "	ldrb r0, [r1]\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809F96C\n\t"
        "	ldr r0, _0809F968\n\t"
        "	ldrh r1, [r0, #0x2c]\n\t"
        "	movs r0, #1\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F970\n\t"
        "	movs r0, #1\n\t"
        "	b _0809F972\n\t"
        "	.align 2, 0\n\t"
        "_0809F964: .4byte gUnknown_20372C0\n\t"
        "_0809F968: .4byte gMain\n\t"
        "_0809F96C:\n\t"
        "	subs r0, #1\n\t"
        "	strb r0, [r1]\n\t"
        "_0809F970:\n\t"
        "	movs r0, #0\n\t"
        "_0809F972:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveConfirmSaveCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearStdWindowAndFrame\n\t"
        "	bl RemoveMapNamePopUpWindow\n\t"
        "	bl ShowSaveInfoWindow\n\t"
        "	bl CurrentBattlePyramidLocation\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809F9AC\n\t"
        "	ldr r0, _0809F9A4\n\t"
        "	ldr r1, _0809F9A8\n\t"
        "	bl ShowSaveMessage\n\t"
        "	b _0809F9B4\n\t"
        "	.align 2, 0\n\t"
        "_0809F9A4: .4byte 0x0822D762\n\t"
        "_0809F9A8: .4byte SaveConfirmOverwriteCallback + 1\n\t"
        "_0809F9AC:\n\t"
        "	ldr r0, _0809F9BC\n\t"
        "	ldr r1, _0809F9C0\n\t"
        "	bl ShowSaveMessage\n\t"
        "_0809F9B4:\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F9BC: .4byte gUnknown_8276F58\n\t"
        "_0809F9C0: .4byte SaveConfirmOverwriteCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveConfirmOverwriteCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl DisplayYesNoMenuDefaultYes\n\t"
        "	ldr r1, _0809F9D8\n\t"
        "	ldr r0, _0809F9DC\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809F9D8: .4byte gUnknown_20372BC\n\t"
        "_0809F9DC: .4byte SaveConfirmInputCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveConfirmInputCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl Menu_ProcessInputNoWrapClearOnChoose\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	asrs r1, r0, #0x18\n\t"
        "	cmp r1, #0\n\t"
        "	beq _0809FA02\n\t"
        "	cmp r1, #0\n\t"
        "	bgt _0809F9FC\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809FA40\n\t"
        "	b _0809FA4C\n\t"
        "_0809F9FC:\n\t"
        "	cmp r1, #1\n\t"
        "	beq _0809FA40\n\t"
        "	b _0809FA4C\n\t"
        "_0809FA02:\n\t"
        "	ldr r0, _0809FA20\n\t"
        "	ldrh r0, [r0]\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FA0E\n\t"
        "	cmp r0, #2\n\t"
        "	bne _0809FA16\n\t"
        "_0809FA0E:\n\t"
        "	ldr r0, _0809FA24\n\t"
        "	ldrb r0, [r0]\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FA30\n\t"
        "_0809FA16:\n\t"
        "	ldr r1, _0809FA28\n\t"
        "	ldr r0, _0809FA2C\n\t"
        "	str r0, [r1]\n\t"
        "	b _0809FA4C\n\t"
        "	.align 2, 0\n\t"
        "_0809FA20: .4byte gSaveFileStatus\n\t"
        "_0809FA24: .4byte gDifferentSaveFile\n\t"
        "_0809FA28: .4byte gUnknown_20372BC\n\t"
        "_0809FA2C: .4byte SaveFileExistsCallback + 1\n\t"
        "_0809FA30:\n\t"
        "	ldr r1, _0809FA38\n\t"
        "	ldr r0, _0809FA3C\n\t"
        "	str r0, [r1]\n\t"
        "	b _0809FA4C\n\t"
        "	.align 2, 0\n\t"
        "_0809FA38: .4byte gUnknown_20372BC\n\t"
        "_0809FA3C: .4byte SaveSavingMessageCallback + 1\n\t"
        "_0809FA40:\n\t"
        "	bl HideSaveInfoWindow\n\t"
        "	bl sub_0809F8EC\n\t"
        "	movs r0, #2\n\t"
        "	b _0809FA4E\n\t"
        "_0809FA4C:\n\t"
        "	movs r0, #0\n\t"
        "_0809FA4E:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveFileExistsCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809FA68\n\t"
        "	ldrb r0, [r0]\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809FA74\n\t"
        "	ldr r0, _0809FA6C\n\t"
        "	ldr r1, _0809FA70\n\t"
        "	bl ShowSaveMessage\n\t"
        "	b _0809FA7C\n\t"
        "	.align 2, 0\n\t"
        "_0809FA68: .4byte gDifferentSaveFile\n\t"
        "_0809FA6C: .4byte gUnknown_8276FD3\n\t"
        "_0809FA70: .4byte BattlePyramidRetireYesNoCallback + 1\n\t"
        "_0809FA74:\n\t"
        "	ldr r0, _0809FA84\n\t"
        "	ldr r1, _0809FA88\n\t"
        "	bl ShowSaveMessage\n\t"
        "_0809FA7C:\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FA84: .4byte gUnknown_8276F77\n\t"
        "_0809FA88: .4byte SaveYesNoCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BattlePyramidRetireYesNoCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #1\n\t"
        "	bl DisplayYesNoMenuWithDefault\n\t"
        "	ldr r1, _0809FAA0\n\t"
        "	ldr r0, _0809FAA4\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FAA0: .4byte gUnknown_20372BC\n\t"
        "_0809FAA4: .4byte SaveOverwriteInputCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveYesNoCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl DisplayYesNoMenuDefaultYes\n\t"
        "	ldr r1, _0809FABC\n\t"
        "	ldr r0, _0809FAC0\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FABC: .4byte gUnknown_20372BC\n\t"
        "_0809FAC0: .4byte SaveOverwriteInputCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveOverwriteInputCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl Menu_ProcessInputNoWrapClearOnChoose\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	asrs r1, r0, #0x18\n\t"
        "	cmp r1, #0\n\t"
        "	beq _0809FAE6\n\t"
        "	cmp r1, #0\n\t"
        "	bgt _0809FAE0\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809FAF8\n\t"
        "	b _0809FB04\n\t"
        "_0809FAE0:\n\t"
        "	cmp r1, #1\n\t"
        "	beq _0809FAF8\n\t"
        "	b _0809FB04\n\t"
        "_0809FAE6:\n\t"
        "	ldr r1, _0809FAF0\n\t"
        "	ldr r0, _0809FAF4\n\t"
        "	str r0, [r1]\n\t"
        "	b _0809FB04\n\t"
        "	.align 2, 0\n\t"
        "_0809FAF0: .4byte gUnknown_20372BC\n\t"
        "_0809FAF4: .4byte SaveSavingMessageCallback + 1\n\t"
        "_0809FAF8:\n\t"
        "	bl HideSaveInfoWindow\n\t"
        "	bl sub_0809F8EC\n\t"
        "	movs r0, #2\n\t"
        "	b _0809FB06\n\t"
        "_0809FB04:\n\t"
        "	movs r0, #0\n\t"
        "_0809FB06:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveSavingMessageCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809FB1C\n\t"
        "	ldr r1, _0809FB20\n\t"
        "	bl ShowSaveMessage\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FB1C: .4byte gUnknown_8276F97\n\t"
        "_0809FB20: .4byte SaveDoSaveCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveDoSaveCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	movs r0, #0\n\t"
        "	bl IncrementGameStat\n\t"
        "	bl sub_081A9C08\n\t"
        "	ldr r4, _0809FB48\n\t"
        "	ldrb r0, [r4]\n\t"
        "	cmp r0, #1\n\t"
        "	bne _0809FB4C\n\t"
        "	movs r0, #4\n\t"
        "	bl TrySavingData\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r1, r0, #0x18\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r4]\n\t"
        "	b _0809FB56\n\t"
        "	.align 2, 0\n\t"
        "_0809FB48: .4byte gDifferentSaveFile\n\t"
        "_0809FB4C:\n\t"
        "	movs r0, #0\n\t"
        "	bl TrySavingData\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r1, r0, #0x18\n\t"
        "_0809FB56:\n\t"
        "	cmp r1, #1\n\t"
        "	bne _0809FB6C\n\t"
        "	ldr r0, _0809FB64\n\t"
        "	ldr r1, _0809FB68\n\t"
        "	bl ShowSaveMessage\n\t"
        "	b _0809FB74\n\t"
        "	.align 2, 0\n\t"
        "_0809FB64: .4byte gUnknown_8276FBB\n\t"
        "_0809FB68: .4byte SaveSuccessCallback + 1\n\t"
        "_0809FB6C:\n\t"
        "	ldr r0, _0809FB80\n\t"
        "	ldr r1, _0809FB84\n\t"
        "	bl ShowSaveMessage\n\t"
        "_0809FB74:\n\t"
        "	bl SaveStartTimer\n\t"
        "	movs r0, #0\n\t"
        "	pop {r4}\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FB80: .4byte gUnknown_8277048\n\t"
        "_0809FB84: .4byte SaveErrorCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveSuccessCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #0\n\t"
        "	bl IsTextPrinterActive\n\t"
        "	lsls r0, r0, #0x10\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FBA2\n\t"
        "	movs r0, #0x37\n\t"
        "	bl PlaySE\n\t"
        "	ldr r1, _0809FBA8\n\t"
        "	ldr r0, _0809FBAC\n\t"
        "	str r0, [r1]\n\t"
        "_0809FBA2:\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FBA8: .4byte gUnknown_20372BC\n\t"
        "_0809FBAC: .4byte SaveReturnSuccessCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveReturnSuccessCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl IsSEPlaying\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FBCE\n\t"
        "	bl SaveSuccesTimer\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FBCE\n\t"
        "	bl HideSaveInfoWindow\n\t"
        "	movs r0, #1\n\t"
        "	b _0809FBD0\n\t"
        "_0809FBCE:\n\t"
        "	movs r0, #0\n\t"
        "_0809FBD0:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveErrorCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #0\n\t"
        "	bl IsTextPrinterActive\n\t"
        "	lsls r0, r0, #0x10\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FBEE\n\t"
        "	movs r0, #0x16\n\t"
        "	bl PlaySE\n\t"
        "	ldr r1, _0809FBF4\n\t"
        "	ldr r0, _0809FBF8\n\t"
        "	str r0, [r1]\n\t"
        "_0809FBEE:\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FBF4: .4byte gUnknown_20372BC\n\t"
        "_0809FBF8: .4byte SaveReturnErrorCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}
__attribute__((naked)) void SaveReturnErrorCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl SaveErrorTimer\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FC10\n\t"
        "	bl HideSaveInfoWindow\n\t"
        "	movs r0, #3\n\t"
        "	b _0809FC12\n\t"
        "_0809FC10:\n\t"
        "	movs r0, #0\n\t"
        "_0809FC12:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}



__attribute__((naked)) void InitBattlePyramidRetire(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	ldr r1, _0809FC28\n\t"
        "	ldr r0, _0809FC2C\n\t"
        "	str r0, [r1]\n\t"
        "	ldr r1, _0809FC30\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	bx lr\n\t"
        "	.align 2, 0\n\t"
        "_0809FC28: .4byte gUnknown_20372BC\n\t"
        "_0809FC2C: .4byte BattlePyramidConfirmRetireCallback + 1\n\t"
        "_0809FC30: .4byte gUnknown_20372C1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BattlePyramidConfirmRetireCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearStdWindowAndFrame\n\t"
        "	bl RemoveMapNamePopUpWindow\n\t"
        "	ldr r0, _0809FC58\n\t"
        "	ldr r1, _0809FC5C\n\t"
        "	bl ShowSaveMessage\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FC58: .4byte 0x0822D78F\n\t"
        "_0809FC5C: .4byte SaveConfirmOverwriteDefaultNoCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void SaveConfirmOverwriteDefaultNoCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	movs r0, #1\n\t"
        "	bl DisplayYesNoMenuWithDefault\n\t"
        "	ldr r1, _0809FC74\n\t"
        "	ldr r0, _0809FC78\n\t"
        "	str r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        "_0809FC74: .4byte gUnknown_20372BC\n\t"
        "_0809FC78: .4byte BattlePyramidRetireInputCallback + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void BattlePyramidRetireInputCallback(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl Menu_ProcessInputNoWrapClearOnChoose\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	asrs r1, r0, #0x18\n\t"
        "	cmp r1, #0\n\t"
        "	beq _0809FC9E\n\t"
        "	cmp r1, #0\n\t"
        "	bgt _0809FC98\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	cmp r1, r0\n\t"
        "	beq _0809FCA2\n\t"
        "	b _0809FCAA\n\t"
        "_0809FC98:\n\t"
        "	cmp r1, #1\n\t"
        "	beq _0809FCA2\n\t"
        "	b _0809FCAA\n\t"
        "_0809FC9E:\n\t"
        "	movs r0, #2\n\t"
        "	b _0809FCAC\n\t"
        "_0809FCA2:\n\t"
        "	bl sub_0809F8EC\n\t"
        "	movs r0, #1\n\t"
        "	b _0809FCAC\n\t"
        "_0809FCAA:\n\t"
        "	movs r0, #0\n\t"
        "_0809FCAC:\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809FCB0(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl TransferPlttBuffer\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809FCBC(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, r6, r7, lr}\n\t"
        "	mov r7, r8\n\t"
        "	push {r7}\n\t"
        "	sub sp, #4\n\t"
        "	mov r8, r0\n\t"
        "	ldrb r0, [r0]\n\t"
        "	cmp r0, #4\n\t"
        "	bls _0809FCCE\n\t"
        "	b _0809FDD4\n\t"
        "_0809FCCE:\n\t"
        "	lsls r0, r0, #2\n\t"
        "	ldr r1, _0809FCD8\n\t"
        "	adds r0, r0, r1\n\t"
        "	ldr r0, [r0]\n\t"
        "	mov pc, r0\n\t"
        "	.align 2, 0\n\t"
        "_0809FCD8: .4byte _0809FCDC\n\t"
        "_0809FCDC:\n\t"
        "	.4byte _0809FCF0\n\t"
        "	.4byte _0809FD68\n\t"
        "	.4byte _0809FD7A\n\t"
        "	.4byte _0809FDAC\n\t"
        "	.4byte _0809FDD0\n\t"
        "_0809FCF0:\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #0\n\t"
        "	bl SetGpuReg\n\t"
        "	movs r0, #0\n\t"
        "	bl SetVBlankCallback\n\t"
        "	bl ScanlineEffect_Stop\n\t"
        "	movs r2, #0xa0\n\t"
        "	lsls r2, r2, #0x13\n\t"
        "	mov r1, sp\n\t"
        "	movs r0, #0\n\t"
        "	strh r0, [r1]\n\t"
        "	ldr r1, _0809FD5C\n\t"
        "	mov r0, sp\n\t"
        "	str r0, [r1]\n\t"
        "	str r2, [r1, #4]\n\t"
        "	ldr r0, _0809FD60\n\t"
        "	str r0, [r1, #8]\n\t"
        "	ldr r0, [r1, #8]\n\t"
        "	movs r2, #0xc0\n\t"
        "	lsls r2, r2, #0x13\n\t"
        "	movs r3, #0xc0\n\t"
        "	lsls r3, r3, #9\n\t"
        "	mov r4, sp\n\t"
        "	movs r6, #0\n\t"
        "	movs r5, #0x80\n\t"
        "	lsls r5, r5, #5\n\t"
        "	ldr r7, _0809FD64\n\t"
        "	movs r0, #0x81\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	mov ip, r0\n\t"
        "_0809FD32:\n\t"
        "	strh r6, [r4]\n\t"
        "	mov r0, sp\n\t"
        "	str r0, [r1]\n\t"
        "	str r2, [r1, #4]\n\t"
        "	str r7, [r1, #8]\n\t"
        "	ldr r0, [r1, #8]\n\t"
        "	adds r2, r2, r5\n\t"
        "	subs r3, r3, r5\n\t"
        "	cmp r3, r5\n\t"
        "	bhi _0809FD32\n\t"
        "	strh r6, [r4]\n\t"
        "	mov r0, sp\n\t"
        "	str r0, [r1]\n\t"
        "	str r2, [r1, #4]\n\t"
        "	lsrs r0, r3, #1\n\t"
        "	mov r2, ip\n\t"
        "	orrs r0, r2\n\t"
        "	str r0, [r1, #8]\n\t"
        "	ldr r0, [r1, #8]\n\t"
        "	b _0809FDD4\n\t"
        "	.align 2, 0\n\t"
        "_0809FD5C: .4byte 0x040000D4\n\t"
        "_0809FD60: .4byte 0x81000200\n\t"
        "_0809FD64: .4byte 0x81000800\n\t"
        "_0809FD68:\n\t"
        "	bl ResetSpriteData\n\t"
        "	bl ResetTasks\n\t"
        "	bl ResetPaletteFade\n\t"
        "	bl ScanlineEffect_Clear\n\t"
        "	b _0809FDD4\n\t"
        "_0809FD7A:\n\t"
        "	movs r0, #0\n\t"
        "	bl ResetBgsAndClearDma3BusyFlags\n\t"
        "	ldr r1, _0809FDA4\n\t"
        "	movs r0, #0\n\t"
        "	movs r2, #1\n\t"
        "	bl InitBgsFromTemplates\n\t"
        "	ldr r0, _0809FDA8\n\t"
        "	bl InitWindows\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #8\n\t"
        "	movs r2, #0xe0\n\t"
        "	bl LoadUserWindowBorderGfx_\n\t"
        "	movs r0, #0xf0\n\t"
        "	bl Menu_LoadStdPalAt\n\t"
        "	b _0809FDD4\n\t"
        "	.align 2, 0\n\t"
        "_0809FDA4: .4byte gUnknown_84E8C94\n\t"
        "_0809FDA8: .4byte gUnknown_84E8C98\n\t"
        "_0809FDAC:\n\t"
        "	movs r0, #0\n\t"
        "	bl ShowBg\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	movs r1, #0x10\n\t"
        "	movs r2, #0\n\t"
        "	bl BlendPalettes\n\t"
        "	ldr r0, _0809FDCC\n\t"
        "	bl SetVBlankCallback\n\t"
        "	movs r0, #1\n\t"
        "	bl EnableInterrupts\n\t"
        "	b _0809FDD4\n\t"
        "	.align 2, 0\n\t"
        "_0809FDCC: .4byte sub_0809FCB0 + 1\n\t"
        "_0809FDD0:\n\t"
        "	movs r0, #1\n\t"
        "	b _0809FDDE\n\t"
        "_0809FDD4:\n\t"
        "	mov r1, r8\n\t"
        "	ldrb r0, [r1]\n\t"
        "	adds r0, #1\n\t"
        "	strb r0, [r1]\n\t"
        "	movs r0, #0\n\t"
        "_0809FDDE:\n\t"
        "	add sp, #4\n\t"
        "	pop {r3}\n\t"
        "	mov r8, r3\n\t"
        "	pop {r4, r5, r6, r7}\n\t"
        "	pop {r1}\n\t"
        "	bx r1\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809FDEC(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	ldr r0, _0809FE0C\n\t"
        "	bl sub_0809FCBC\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FE06\n\t"
        "	ldr r0, _0809FE10\n\t"
        "	movs r1, #0x50\n\t"
        "	bl CreateTask\n\t"
        "	ldr r0, _0809FE14\n\t"
        "	bl SetMainCallback2\n\t"
        "_0809FE06:\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809FE0C: .4byte gUnknown_3002798\n\t"
        "_0809FE10: .4byte sub_0809FE28 + 1\n\t"
        "_0809FE14: .4byte sub_0809FE18 + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809FE18(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl RunTasks\n\t"
        "	bl UpdatePaletteFade\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_0809FE28(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, r6, lr}\n\t"
        "	sub sp, #0x10\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r4, r0, #0x18\n\t"
        "	lsls r0, r4, #2\n\t"
        "	adds r0, r0, r4\n\t"
        "	lsls r0, r0, #3\n\t"
        "	ldr r1, _0809FE5C\n\t"
        "	adds r5, r0, r1\n\t"
        "	ldr r0, _0809FE60\n\t"
        "	ldrb r1, [r0, #7]\n\t"
        "	movs r0, #0x80\n\t"
        "	ands r0, r1\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FE48\n\t"
        "	b _0809FF80\n\t"
        "_0809FE48:\n\t"
        "	movs r1, #0\n\t"
        "	ldrsh r0, [r5, r1]\n\t"
        "	cmp r0, #6\n\t"
        "	bls _0809FE52\n\t"
        "	b _0809FF80\n\t"
        "_0809FE52:\n\t"
        "	lsls r0, r0, #2\n\t"
        "	ldr r1, _0809FE64\n\t"
        "	adds r0, r0, r1\n\t"
        "	ldr r0, [r0]\n\t"
        "	mov pc, r0\n\t"
        "	.align 2, 0\n\t"
        "_0809FE5C: .4byte gUnknown_3005B68\n\t"
        "_0809FE60: .4byte gPaletteFade\n\t"
        "_0809FE64: .4byte _0809FE68\n\t"
        "_0809FE68:\n\t"
        "	.4byte _0809FE84\n\t"
        "	.4byte _0809FF08\n\t"
        "	.4byte _0809FF14\n\t"
        "	.4byte _0809FF34\n\t"
        "	.4byte _0809FF48\n\t"
        "	.4byte _0809FF60\n\t"
        "	.4byte _0809FF70\n\t"
        "_0809FE84:\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #0x11\n\t"
        "	bl FillWindowPixelBuffer\n\t"
        "	ldr r2, _0809FEEC\n\t"
        "	movs r4, #0\n\t"
        "	str r4, [sp]\n\t"
        "	movs r0, #2\n\t"
        "	str r0, [sp, #4]\n\t"
        "	movs r6, #1\n\t"
        "	str r6, [sp, #8]\n\t"
        "	movs r0, #3\n\t"
        "	str r0, [sp, #0xc]\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #1\n\t"
        "	movs r3, #0xff\n\t"
        "	bl AddTextPrinterParameterized2\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #8\n\t"
        "	movs r2, #0xe\n\t"
        "	bl DrawTextBorderOuter\n\t"
        "	movs r0, #0\n\t"
        "	bl PutWindowTilemap\n\t"
        "	movs r0, #0\n\t"
        "	movs r1, #3\n\t"
        "	bl CopyWindowToVram\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	str r4, [sp]\n\t"
        "	movs r1, #0\n\t"
        "	movs r2, #0x10\n\t"
        "	movs r3, #0\n\t"
        "	bl BeginNormalPaletteFade\n\t"
        "	ldr r0, _0809FEF0\n\t"
        "	ldrb r0, [r0]\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FEF8\n\t"
        "	bl InUnionRoom\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FEF8\n\t"
        "	bl sub_08009C40\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FEF4\n\t"
        "	strh r6, [r5]\n\t"
        "	b _0809FF80\n\t"
        "	.align 2, 0\n\t"
        "_0809FEEC: .4byte gText_SavingDontTurnOffPower\n\t"
        "_0809FEF0: .4byte gWirelessCommType\n\t"
        "_0809FEF4:\n\t"
        "	movs r0, #5\n\t"
        "	b _0809FF7E\n\t"
        "_0809FEF8:\n\t"
        "	ldr r0, _0809FF04\n\t"
        "	movs r1, #1\n\t"
        "	strb r1, [r0]\n\t"
        "	movs r0, #1\n\t"
        "	b _0809FF7E\n\t"
        "	.align 2, 0\n\t"
        "_0809FF04: .4byte gSoftResetDisabled\n\t"
        "_0809FF08:\n\t"
        "	bl SetContinueGameWarpStatusToDynamicWarp\n\t"
        "	bl FullSaveGame\n\t"
        "	movs r0, #2\n\t"
        "	b _0809FF7E\n\t"
        "_0809FF14:\n\t"
        "	bl CheckSaveFile\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	beq _0809FF80\n\t"
        "	bl ClearContinueGameWarpStatus\n\t"
        "	movs r0, #3\n\t"
        "	strh r0, [r5]\n\t"
        "	ldr r1, _0809FF30\n\t"
        "	movs r0, #0\n\t"
        "	strb r0, [r1]\n\t"
        "	b _0809FF80\n\t"
        "	.align 2, 0\n\t"
        "_0809FF30: .4byte gSoftResetDisabled\n\t"
        "_0809FF34:\n\t"
        "	movs r0, #1\n\t"
        "	rsbs r0, r0, #0\n\t"
        "	movs r1, #0\n\t"
        "	str r1, [sp]\n\t"
        "	movs r2, #0\n\t"
        "	movs r3, #0x10\n\t"
        "	bl BeginNormalPaletteFade\n\t"
        "	movs r0, #4\n\t"
        "	b _0809FF7E\n\t"
        "_0809FF48:\n\t"
        "	bl FreeAllWindowBuffers\n\t"
        "	ldr r0, _0809FF5C\n\t"
        "	ldr r0, [r0, #8]\n\t"
        "	bl SetMainCallback2\n\t"
        "	adds r0, r4, #0\n\t"
        "	bl DestroyTask\n\t"
        "	b _0809FF80\n\t"
        "	.align 2, 0\n\t"
        "_0809FF5C: .4byte gMain\n\t"
        "_0809FF60:\n\t"
        "	ldr r0, _0809FF6C\n\t"
        "	movs r1, #5\n\t"
        "	bl CreateTask\n\t"
        "	movs r0, #6\n\t"
        "	b _0809FF7E\n\t"
        "	.align 2, 0\n\t"
        "_0809FF6C: .4byte Task_LinkFullSave + 1\n\t"
        "_0809FF70:\n\t"
        "	ldr r0, _0809FF88\n\t"
        "	bl FuncIsActiveTask\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FF80\n\t"
        "	movs r0, #3\n\t"
        "_0809FF7E:\n\t"
        "	strh r0, [r5]\n\t"
        "_0809FF80:\n\t"
        "	add sp, #0x10\n\t"
        "	pop {r4, r5, r6}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_0809FF88: .4byte Task_LinkFullSave + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void ShowSaveInfoWindow(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, r6, r7, lr}\n\t"
        "	mov r7, sl\n\t"
        "	mov r6, sb\n\t"
        "	mov r5, r8\n\t"
        "	push {r5, r6, r7}\n\t"
        "	sub sp, #0x14\n\t"
        "	ldr r0, _080A00F4\n\t"
        "	ldr r1, [r0, #4]\n\t"
        "	ldr r0, [r0]\n\t"
        "	str r0, [sp, #0xc]\n\t"
        "	str r1, [sp, #0x10]\n\t"
        "	ldr r0, _080A00F8\n\t"
        "	mov sl, r0\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FFC4\n\t"
        "	add r0, sp, #0xc\n\t"
        "	ldrb r1, [r0, #4]\n\t"
        "	subs r1, #2\n\t"
        "	lsls r1, r1, #0x18\n\t"
        "	lsrs r1, r1, #0x18\n\t"
        "	ldr r2, _080A00FC\n\t"
        "	ldr r0, [sp, #0x10]\n\t"
        "	ands r0, r2\n\t"
        "	orrs r0, r1\n\t"
        "	str r0, [sp, #0x10]\n\t"
        "_0809FFC4:\n\t"
        "	ldr r6, _080A0100\n\t"
        "	add r0, sp, #0xc\n\t"
        "	bl AddWindow\n\t"
        "	strb r0, [r6]\n\t"
        "	ldrb r0, [r6]\n\t"
        "	movs r1, #0\n\t"
        "	bl DrawStdWindowFrame\n\t"
        "	ldr r1, _080A0104\n\t"
        "	ldr r0, [r1]\n\t"
        "	ldrb r0, [r0, #8]\n\t"
        "	movs r1, #4\n\t"
        "	mov sb, r1\n\t"
        "	cmp r0, #0\n\t"
        "	bne _0809FFE8\n\t"
        "	movs r0, #8\n\t"
        "	mov sb, r0\n\t"
        "_0809FFE8:\n\t"
        "	movs r4, #2\n\t"
        "	ldr r5, _080A0108\n\t"
        "	movs r0, #3\n\t"
        "	adds r1, r5, #0\n\t"
        "	movs r2, #6\n\t"
        "	bl sub_08199FDC\n\t"
        "	ldrb r0, [r6]\n\t"
        "	str r4, [sp]\n\t"
        "	movs r7, #0xff\n\t"
        "	str r7, [sp, #4]\n\t"
        "	movs r1, #0\n\t"
        "	mov r8, r1\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r4, #0x10\n\t"
        "	ldrb r0, [r6]\n\t"
        "	ldr r2, _080A010C\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r0, #0\n\t"
        "	adds r1, r5, #0\n\t"
        "	mov r2, sb\n\t"
        "	bl sub_08199FDC\n\t"
        "	movs r0, #0xff\n\t"
        "	strb r0, [r5, #0xb]\n\t"
        "	ldrb r0, [r6]\n\t"
        "	adds r1, r5, #0\n\t"
        "	movs r2, #0x48\n\t"
        "	movs r3, #0x10\n\t"
        "	bl PrintPlayerNameOnWindow\n\t"
        "	movs r4, #0x1e\n\t"
        "	ldrb r0, [r6]\n\t"
        "	ldr r2, _080A0110\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r0, #4\n\t"
        "	adds r1, r5, #0\n\t"
        "	mov r2, sb\n\t"
        "	bl sub_08199FDC\n\t"
        "	ldrb r0, [r6]\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0x48\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r4, #0x2c\n\t"
        "	mov r0, sl\n\t"
        "	bl FlagGet\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	cmp r0, #1\n\t"
        "	bne _080A00B6\n\t"
        "	ldrb r0, [r6]\n\t"
        "	ldr r2, _080A0114\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r0, #1\n\t"
        "	adds r1, r5, #0\n\t"
        "	mov r2, sb\n\t"
        "	bl sub_08199FDC\n\t"
        "	ldrb r0, [r6]\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0x48\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r4, #0x3a\n\t"
        "_080A00B6:\n\t"
        "	ldrb r0, [r6]\n\t"
        "	ldr r2, _080A0118\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	movs r3, #0\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	movs r0, #2\n\t"
        "	adds r1, r5, #0\n\t"
        "	mov r2, sb\n\t"
        "	bl sub_08199FDC\n\t"
        "	ldr r1, _080A0104\n\t"
        "	ldr r0, [r1]\n\t"
        "	ldrh r0, [r0, #0xe]\n\t"
        "	cmp r0, #0x63\n\t"
        "	bls _080A011C\n\t"
        "	ldrb r0, [r6]\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0x40\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "	b _080A0130\n\t"
        "	.align 2, 0\n\t"
        "_080A00F4: .4byte gUnknown_84E8CA8\n\t"
        "_080A00F8: .4byte 0x00000861\n\t"
        "_080A00FC: .4byte 0xFFFFFF00\n\t"
        "_080A0100: .4byte gUnknown_20372C2\n\t"
        "_080A0104: .4byte gSaveBlock2Ptr\n\t"
        "_080A0108: .4byte gStringVar4\n\t"
        "_080A010C: .4byte gUnknown_84E8CA8 + 0x8\n\t"
        "_080A0110: .4byte gUnknown_84E8CA8 + 0xF\n\t"
        "_080A0114: .4byte gUnknown_84E8CA8 + 0x18\n\t"
        "_080A0118: .4byte gUnknown_84E8CC8\n\t"
        "_080A011C:\n\t"
        "	ldrb r0, [r6]\n\t"
        "	str r4, [sp]\n\t"
        "	str r7, [sp, #4]\n\t"
        "	mov r1, r8\n\t"
        "	str r1, [sp, #8]\n\t"
        "	movs r1, #1\n\t"
        "	adds r2, r5, #0\n\t"
        "	movs r3, #0x48\n\t"
        "	bl AddTextPrinterParameterized\n\t"
        "_080A0130:\n\t"
        "	ldr r0, _080A014C\n\t"
        "	ldrb r0, [r0]\n\t"
        "	movs r1, #2\n\t"
        "	bl CopyWindowToVram\n\t"
        "	add sp, #0x14\n\t"
        "	pop {r3, r4, r5}\n\t"
        "	mov r8, r3\n\t"
        "	mov sb, r4\n\t"
        "	mov sl, r5\n\t"
        "	pop {r4, r5, r6, r7}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_080A014C: .4byte gUnknown_20372C2\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void RemoveSaveInfoWindow(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	ldr r4, _080A0168\n\t"
        "	ldrb r0, [r4]\n\t"
        "	movs r1, #0\n\t"
        "	bl ClearStdWindowAndFrame\n\t"
        "	ldrb r0, [r4]\n\t"
        "	bl RemoveWindow\n\t"
        "	pop {r4}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_080A0168: .4byte gUnknown_20372C2\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_080A016C(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, lr}\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r4, r0, #0x18\n\t"
        "	ldr r0, _080A0190\n\t"
        "	bl FuncIsActiveTask\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	cmp r0, #0\n\t"
        "	bne _080A0188\n\t"
        "	adds r0, r4, #0\n\t"
        "	bl DestroyTask\n\t"
        "	bl ScriptContext_Enable\n\t"
        "_080A0188:\n\t"
        "	pop {r4}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_080A0190: .4byte Task_LinkFullSave + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void sub_080A0194(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {r4, r5, lr}\n\t"
        "	ldr r0, _080A01D0\n\t"
        "	movs r1, #5\n\t"
        "	bl CreateTask\n\t"
        "	adds r4, r0, #0\n\t"
        "	lsls r4, r4, #0x18\n\t"
        "	lsrs r4, r4, #0x18\n\t"
        "	ldr r5, _080A01D4\n\t"
        "	lsls r0, r4, #2\n\t"
        "	adds r0, r0, r4\n\t"
        "	lsls r0, r0, #3\n\t"
        "	adds r0, r0, r5\n\t"
        "	movs r1, #1\n\t"
        "	strh r1, [r0, #0xc]\n\t"
        "	ldr r0, _080A01D8\n\t"
        "	movs r1, #6\n\t"
        "	bl CreateTask\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	lsls r1, r0, #2\n\t"
        "	adds r1, r1, r0\n\t"
        "	lsls r1, r1, #3\n\t"
        "	adds r1, r1, r5\n\t"
        "	strh r4, [r1, #0xa]\n\t"
        "	pop {r4, r5}\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        "	.align 2, 0\n\t"
        "_080A01D0: .4byte Task_LinkFullSave + 1\n\t"
        "_080A01D4: .4byte gTasks\n\t"
        "_080A01D8: .4byte sub_080A016C + 1\n\t"
        ".syntax divided\n\t"
    );
}

__attribute__((naked)) void HideStartMenuWindow(void)
{
    __asm__(".syntax unified\n\t"
        ".code 16\n\t"
        "	push {lr}\n\t"
        "	bl GetStartMenuWindowId\n\t"
        "	lsls r0, r0, #0x18\n\t"
        "	lsrs r0, r0, #0x18\n\t"
        "	movs r1, #1\n\t"
        "	bl ClearStdWindowAndFrame\n\t"
        "	bl RemoveMapNamePopUpWindow\n\t"
        "	bl ScriptUnfreezeObjectEvents\n\t"
        "	bl UnlockPlayerFieldControls\n\t"
        "	pop {r0}\n\t"
        "	bx r0\n\t"
        ".syntax divided\n\t"
    );
}


void HideStartMenu(void)
{
    PlaySE(SE_SELECT);
    HideStartMenuWindow();
}



void AppendToList(u8 *list, u8 *pos, u8 newEntry)
{
    list[*pos] = newEntry;
    (*pos)++;
}
