	.globl gTileset_General
gTileset_General: @ 0x083B7B24
	.byte 0x01, 0x00, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTilesetTiles_General  @ tiles
	.4byte gTilesetPalettes_General  @ palettes
	.4byte gTileset_General_Metatiles  @ metatiles
	.4byte gTileset_General_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A03E9  @ callback
	.globl gTileset_Petalburg
gTileset_Petalburg: @ 0x083B7B3C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Petalburg_Tiles  @ tiles
	.4byte gTileset_Petalburg_Palettes  @ palettes
	.4byte gTileset_Petalburg_Metatiles  @ metatiles
	.4byte gTileset_Petalburg_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0535  @ callback
	.globl gTileset_Rustboro
gTileset_Rustboro: @ 0x083B7B54
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Rustboro_Tiles  @ tiles
	.4byte gTileset_Rustboro_Palettes  @ palettes
	.4byte gTileset_Rustboro_Metatiles  @ metatiles
	.4byte gTileset_Rustboro_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A055D  @ callback
	.globl gTileset_Dewford
gTileset_Dewford: @ 0x083B7B6C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Dewford_Tiles  @ tiles
	.4byte gTileset_Dewford_Palettes  @ palettes
	.4byte gTileset_Dewford_Metatiles  @ metatiles
	.4byte gTileset_Dewford_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0589  @ callback
	.globl gTileset_Slateport
gTileset_Slateport: @ 0x083B7B84
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Slateport_Tiles  @ tiles
	.4byte gTileset_Slateport_Palettes  @ palettes
	.4byte gTileset_Slateport_Metatiles  @ metatiles
	.4byte gTileset_Slateport_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A05B5  @ callback
	.globl gTileset_Mauville
gTileset_Mauville: @ 0x083B7B9C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Mauville_Tiles  @ tiles
	.4byte gTileset_Mauville_Palettes  @ palettes
	.4byte gTileset_Mauville_Metatiles  @ metatiles
	.4byte gTileset_Mauville_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A05E1  @ callback
	.globl gTileset_Lavaridge
gTileset_Lavaridge: @ 0x083B7BB4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Lavaridge_Tiles  @ tiles
	.4byte gTileset_Lavaridge_Palettes  @ palettes
	.4byte gTileset_Lavaridge_Metatiles  @ metatiles
	.4byte gTileset_Lavaridge_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0611  @ callback
	.globl gTileset_Fallarbor
gTileset_Fallarbor: @ 0x083B7BCC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Fallarbor_Tiles  @ tiles
	.4byte gTileset_Fallarbor_Palettes  @ palettes
	.4byte gTileset_Fallarbor_Metatiles  @ metatiles
	.4byte gTileset_Fallarbor_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A063D  @ callback
	.globl gTileset_Fortree
gTileset_Fortree: @ 0x083B7BE4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Fortree_Tiles  @ tiles
	.4byte gTileset_Fortree_Palettes  @ palettes
	.4byte gTileset_Fortree_Metatiles  @ metatiles
	.4byte gTileset_Fortree_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0665  @ callback
	.globl gTileset_Lilycove
gTileset_Lilycove: @ 0x083B7BFC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Lilycove_Tiles  @ tiles
	.4byte gTileset_Lilycove_Palettes  @ palettes
	.4byte gTileset_Lilycove_Metatiles  @ metatiles
	.4byte gTileset_Lilycove_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A068D  @ callback
	.globl gTileset_Mossdeep
gTileset_Mossdeep: @ 0x083B7C14
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Mossdeep_Tiles  @ tiles
	.4byte gTileset_Mossdeep_Palettes  @ palettes
	.4byte gTileset_Mossdeep_Metatiles  @ metatiles
	.4byte gTileset_Mossdeep_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A06B5  @ callback
	.globl gTileset_EverGrande
gTileset_EverGrande: @ 0x083B7C2C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_EverGrande_Tiles  @ tiles
	.4byte gTileset_EverGrande_Palettes  @ palettes
	.4byte gTileset_EverGrande_Metatiles  @ metatiles
	.4byte gTileset_EverGrande_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A06DD  @ callback
	.globl gTileset_Pacifidlog
gTileset_Pacifidlog: @ 0x083B7C44
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Pacifidlog_Tiles  @ tiles
	.4byte gTileset_Pacifidlog_Palettes  @ palettes
	.4byte gTileset_Pacifidlog_Metatiles  @ metatiles
	.4byte gTileset_Pacifidlog_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0709  @ callback
	.globl gTileset_Sootopolis
gTileset_Sootopolis: @ 0x083B7C5C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Sootopolis_Tiles  @ tiles
	.4byte gTileset_Sootopolis_Palettes  @ palettes
	.4byte gTileset_Sootopolis_Metatiles  @ metatiles
	.4byte gTileset_Sootopolis_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0739  @ callback
	.globl gTileset_BattleFrontierOutsideWest
gTileset_BattleFrontierOutsideWest: @ 0x083B7C74
	.incbin "baserom_jp.gba", 0x3B7C74, 0x18
	.globl gTileset_BattleFrontierOutsideEast
gTileset_BattleFrontierOutsideEast: @ 0x083B7C8C
	.incbin "baserom_jp.gba", 0x3B7C8C, 0x18
	.globl gTileset_Building
gTileset_Building: @ 0x083B7CA4
	.byte 0x01, 0x00, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Building_Tiles  @ tiles
	.4byte gTileset_Building_Palettes  @ palettes
	.4byte gTileset_Building_Metatiles  @ metatiles
	.4byte gTileset_Building_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0411  @ callback
	.globl gTileset_Shop
gTileset_Shop: @ 0x083B7CBC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Shop_Tiles  @ tiles
	.4byte gTileset_Shop_Palettes  @ palettes
	.4byte gTileset_Shop_Metatiles  @ metatiles
	.4byte gTileset_Shop_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_PokemonCenter
gTileset_PokemonCenter: @ 0x083B7CD4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_PokemonCenter_Tiles  @ tiles
	.4byte gTileset_PokemonCenter_Palettes  @ palettes
	.4byte gTileset_PokemonCenter_Metatiles  @ metatiles
	.4byte gTileset_PokemonCenter_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_Cave
gTileset_Cave: @ 0x083B7CEC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Cave_Tiles  @ tiles
	.4byte gTileset_Cave_Palettes  @ palettes
	.4byte gTileset_Cave_Metatiles  @ metatiles
	.4byte gTileset_Cave_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0805  @ callback
	.globl gTileset_PokemonSchool
gTileset_PokemonSchool: @ 0x083B7D04
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_PokemonSchool_Tiles  @ tiles
	.4byte gTileset_PokemonSchool_Palettes  @ palettes
	.4byte gTileset_PokemonSchool_Metatiles  @ metatiles
	.4byte gTileset_PokemonSchool_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_PokemonFanClub
gTileset_PokemonFanClub: @ 0x083B7D1C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_PokemonFanClub_Tiles  @ tiles
	.4byte gTileset_PokemonFanClub_Palettes  @ palettes
	.4byte gTileset_PokemonFanClub_Metatiles  @ metatiles
	.4byte gTileset_PokemonFanClub_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_Unused1
gTileset_Unused1: @ 0x083B7D34
	.incbin "baserom_jp.gba", 0x3B7D34, 0x18
	.globl gTileset_MeteorFalls
gTileset_MeteorFalls: @ 0x083B7D4C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_MeteorFalls_Tiles  @ tiles
	.4byte gTileset_MeteorFalls_Palettes  @ palettes
	.4byte gTileset_MeteorFalls_Metatiles  @ metatiles
	.4byte gTileset_MeteorFalls_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_OceanicMuseum
gTileset_OceanicMuseum: @ 0x083B7D64
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_OceanicMuseum_Tiles  @ tiles
	.4byte gTileset_OceanicMuseum_Palettes  @ palettes
	.4byte gTileset_OceanicMuseum_Metatiles  @ metatiles
	.4byte gTileset_OceanicMuseum_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_CableClub
gTileset_CableClub: @ 0x083B7D7C
	.byte 0x00, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_CableClub_Tiles  @ tiles
	.4byte gTileset_CableClub_Palettes  @ palettes
	.4byte gTileset_CableClub_Metatiles  @ metatiles
	.4byte gTileset_CableClub_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_SeashoreHouse
gTileset_SeashoreHouse: @ 0x083B7D94
	.incbin "baserom_jp.gba", 0x3B7D94, 0x18
	.globl gTileset_PrettyPetalFlowerShop
gTileset_PrettyPetalFlowerShop: @ 0x083B7DAC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_PrettyPetalFlowerShop_Tiles  @ tiles
	.4byte gTileset_PrettyPetalFlowerShop_Palettes  @ palettes
	.4byte gTileset_PrettyPetalFlowerShop_Metatiles  @ metatiles
	.4byte gTileset_PrettyPetalFlowerShop_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_PokemonDayCare
gTileset_PokemonDayCare: @ 0x083B7DC4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_PokemonDayCare_Tiles  @ tiles
	.4byte gTileset_PokemonDayCare_Palettes  @ palettes
	.4byte gTileset_PokemonDayCare_Metatiles  @ metatiles
	.4byte gTileset_PokemonDayCare_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_Facility
gTileset_Facility: @ 0x083B7DDC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Facility_Tiles  @ tiles
	.4byte gTileset_Facility_Palettes  @ palettes
	.4byte gTileset_Facility_Metatiles  @ metatiles
	.4byte gTileset_Facility_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_BikeShop
gTileset_BikeShop: @ 0x083B7DF4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_BikeShop_Tiles  @ tiles
	.4byte gTileset_BikeShop_Palettes  @ palettes
	.4byte gTileset_BikeShop_Metatiles  @ metatiles
	.4byte gTileset_BikeShop_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0881  @ callback
	.globl gTileset_RusturfTunnel
gTileset_RusturfTunnel: @ 0x083B7E0C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_RusturfTunnel_Tiles  @ tiles
	.4byte gTileset_RusturfTunnel_Palettes  @ palettes
	.4byte gTileset_RusturfTunnel_Metatiles  @ metatiles
	.4byte gTileset_RusturfTunnel_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_SecretBaseBrownCave
gTileset_SecretBaseBrownCave: @ 0x083B7E24
	.incbin "baserom_jp.gba", 0x3B7E24, 0x18
	.globl gTileset_SecretBaseTree
gTileset_SecretBaseTree: @ 0x083B7E3C
	.incbin "baserom_jp.gba", 0x3B7E3C, 0x18
	.globl gTileset_SecretBaseShrub
gTileset_SecretBaseShrub: @ 0x083B7E54
	.incbin "baserom_jp.gba", 0x3B7E54, 0x18
	.globl gTileset_SecretBaseBlueCave
gTileset_SecretBaseBlueCave: @ 0x083B7E6C
	.incbin "baserom_jp.gba", 0x3B7E6C, 0x18
	.globl gTileset_SecretBaseYellowCave
gTileset_SecretBaseYellowCave: @ 0x083B7E84
	.incbin "baserom_jp.gba", 0x3B7E84, 0x18
	.globl gTileset_SecretBaseRedCave
gTileset_SecretBaseRedCave: @ 0x083B7E9C
	.incbin "baserom_jp.gba", 0x3B7E9C, 0x18
	.globl gTileset_InsideOfTruck
gTileset_InsideOfTruck: @ 0x083B7EB4
	.incbin "baserom_jp.gba", 0x3B7EB4, 0x18
	.globl gTileset_Unused2
gTileset_Unused2: @ 0x083B7ECC
	.incbin "baserom_jp.gba", 0x3B7ECC, 0x18
	.globl gTileset_Contest
gTileset_Contest: @ 0x083B7EE4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Contest_Tiles  @ tiles
	.4byte gTileset_Contest_Palettes  @ palettes
	.4byte gTileset_Contest_Metatiles  @ metatiles
	.4byte gTileset_Contest_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_LilycoveMuseum
gTileset_LilycoveMuseum: @ 0x083B7EFC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_LilycoveMuseum_Tiles  @ tiles
	.4byte gTileset_LilycoveMuseum_Palettes  @ palettes
	.4byte gTileset_LilycoveMuseum_Metatiles  @ metatiles
	.4byte gTileset_LilycoveMuseum_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_BrendansMaysHouse
gTileset_BrendansMaysHouse: @ 0x083B7F14
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_BrendansMaysHouse_Tiles  @ tiles
	.4byte gTileset_BrendansMaysHouse_Palettes  @ palettes
	.4byte gTileset_BrendansMaysHouse_Metatiles  @ metatiles
	.4byte gTileset_BrendansMaysHouse_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_Lab
gTileset_Lab: @ 0x083B7F2C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Lab_Tiles  @ tiles
	.4byte gTileset_Lab_Palettes  @ palettes
	.4byte gTileset_Lab_Metatiles  @ metatiles
	.4byte gTileset_Lab_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_Underwater
gTileset_Underwater: @ 0x083B7F44
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_Underwater_Tiles  @ tiles
	.4byte gTileset_Underwater_Palettes  @ palettes
	.4byte gTileset_Underwater_Metatiles  @ metatiles
	.4byte gTileset_Underwater_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A07BD  @ callback
	.globl gTileset_PetalburgGym
gTileset_PetalburgGym: @ 0x083B7F5C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_PetalburgGym_Tiles  @ tiles
	.4byte gTileset_PetalburgGym_Palettes  @ palettes
	.4byte gTileset_PetalburgGym_Metatiles  @ metatiles
	.4byte gTileset_PetalburgGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_SootopolisGym
gTileset_SootopolisGym: @ 0x083B7F74
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_SootopolisGym_Tiles  @ tiles
	.4byte gTileset_SootopolisGym_Palettes  @ palettes
	.4byte gTileset_SootopolisGym_Metatiles  @ metatiles
	.4byte gTileset_SootopolisGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A07E1  @ callback
	.globl gTileset_GenericBuilding
gTileset_GenericBuilding: @ 0x083B7F8C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_GenericBuilding_Tiles  @ tiles
	.4byte gTileset_GenericBuilding_Palettes  @ palettes
	.4byte gTileset_GenericBuilding_Metatiles  @ metatiles
	.4byte gTileset_GenericBuilding_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_MauvilleGameCorner
gTileset_MauvilleGameCorner: @ 0x083B7FA4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_MauvilleGameCorner_Tiles  @ tiles
	.4byte gTileset_MauvilleGameCorner_Palettes  @ palettes
	.4byte gTileset_MauvilleGameCorner_Metatiles  @ metatiles
	.4byte gTileset_MauvilleGameCorner_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_RustboroGym
gTileset_RustboroGym: @ 0x083B7FBC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_RustboroGym_Tiles  @ tiles
	.4byte gTileset_RustboroGym_Palettes  @ palettes
	.4byte gTileset_RustboroGym_Metatiles  @ metatiles
	.4byte gTileset_RustboroGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_DewfordGym
gTileset_DewfordGym: @ 0x083B7FD4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_DewfordGym_Tiles  @ tiles
	.4byte gTileset_DewfordGym_Palettes  @ palettes
	.4byte gTileset_DewfordGym_Metatiles  @ metatiles
	.4byte gTileset_DewfordGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_MauvilleGym
gTileset_MauvilleGym: @ 0x083B7FEC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_MauvilleGym_Tiles  @ tiles
	.4byte gTileset_MauvilleGym_Palettes  @ palettes
	.4byte gTileset_MauvilleGym_Metatiles  @ metatiles
	.4byte gTileset_MauvilleGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0855  @ callback
	.globl gTileset_LavaridgeGym
gTileset_LavaridgeGym: @ 0x083B8004
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_LavaridgeGym_Tiles  @ tiles
	.4byte gTileset_LavaridgeGym_Palettes  @ palettes
	.4byte gTileset_LavaridgeGym_Metatiles  @ metatiles
	.4byte gTileset_LavaridgeGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_TrickHousePuzzle
gTileset_TrickHousePuzzle: @ 0x083B801C
	.incbin "baserom_jp.gba", 0x3B801C, 0x18
	.globl gTileset_FortreeGym
gTileset_FortreeGym: @ 0x083B8034
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_FortreeGym_Tiles  @ tiles
	.4byte gTileset_FortreeGym_Palettes  @ palettes
	.4byte gTileset_FortreeGym_Metatiles  @ metatiles
	.4byte gTileset_FortreeGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_MossdeepGym
gTileset_MossdeepGym: @ 0x083B804C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_MossdeepGym_Tiles  @ tiles
	.4byte gTileset_MossdeepGym_Palettes  @ palettes
	.4byte gTileset_MossdeepGym_Metatiles  @ metatiles
	.4byte gTileset_MossdeepGym_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_InsideShip
gTileset_InsideShip: @ 0x083B8064
	.incbin "baserom_jp.gba", 0x3B8064, 0x18
	.globl gTileset_SecretBase
gTileset_SecretBase: @ 0x083B807C
	.incbin "baserom_jp.gba", 0x3B807C, 0x18

	.globl gTilesetPointer_SecretBase
gTilesetPointer_SecretBase: @ 0x83B8094
	.incbin "baserom_jp.gba", 0x3b8094, 0x4

	.globl gTilesetPointer_SecretBaseRedCave
gTilesetPointer_SecretBaseRedCave: @ 0x083B8098
	.incbin "baserom_jp.gba", 0x3B8098, 0x4
	.globl gTileset_EliteFour
gTileset_EliteFour: @ 0x083B809C
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_EliteFour_Tiles  @ tiles
	.4byte gTileset_EliteFour_Palettes  @ palettes
	.4byte gTileset_EliteFour_Metatiles  @ metatiles
	.4byte gTileset_EliteFour_MetatileAttributes  @ metatileAttributes
	.4byte 0x080A0831  @ callback
	.globl gTileset_BattleFrontier
gTileset_BattleFrontier: @ 0x083B80B4
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_BattleFrontier_Tiles  @ tiles
	.4byte gTileset_BattleFrontier_Palettes  @ palettes
	.4byte gTileset_BattleFrontier_Metatiles  @ metatiles
	.4byte gTileset_BattleFrontier_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_BattlePalace
gTileset_BattlePalace: @ 0x083B80CC
	.incbin "baserom_jp.gba", 0x3B80CC, 0x18
	.globl gTileset_BattleDome
gTileset_BattleDome: @ 0x083B80E4
	.incbin "baserom_jp.gba", 0x3B80E4, 0x18
	.globl gTileset_BattleFactory
gTileset_BattleFactory: @ 0x083B80FC
	.incbin "baserom_jp.gba", 0x3B80FC, 0x18
	.globl gTileset_BattlePike
gTileset_BattlePike: @ 0x083B8114
	.incbin "baserom_jp.gba", 0x3B8114, 0x18
	.globl gTileset_BattleArena
gTileset_BattleArena: @ 0x083B812C
	.incbin "baserom_jp.gba", 0x3B812C, 0x18
	.globl gTileset_BattlePyramid
gTileset_BattlePyramid: @ 0x083B8144
	.incbin "baserom_jp.gba", 0x3B8144, 0x18
	.globl gTileset_MirageTower
gTileset_MirageTower: @ 0x083B815C
	.incbin "baserom_jp.gba", 0x3B815C, 0x18
	.globl gTileset_MossdeepGameCorner
gTileset_MossdeepGameCorner: @ 0x083B8174
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_MossdeepGameCorner_Tiles  @ tiles
	.4byte gTileset_MossdeepGameCorner_Palettes  @ palettes
	.4byte gTileset_MossdeepGameCorner_Metatiles  @ metatiles
	.4byte gTileset_MossdeepGameCorner_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_IslandHarbor
gTileset_IslandHarbor: @ 0x083B818C
	.incbin "baserom_jp.gba", 0x3B818C, 0x18
	.globl gTileset_TrainerHill
gTileset_TrainerHill: @ 0x083B81A4
	.incbin "baserom_jp.gba", 0x3B81A4, 0x18
	.globl gTileset_NavelRock
gTileset_NavelRock: @ 0x083B81BC
	.incbin "baserom_jp.gba", 0x3B81BC, 0x18
	.globl gTileset_BattleFrontierRankingHall
gTileset_BattleFrontierRankingHall: @ 0x083B81D4
	.incbin "baserom_jp.gba", 0x3B81D4, 0x18
	.globl gTileset_BattleTent
gTileset_BattleTent: @ 0x083B81EC
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_BattleTent_Tiles  @ tiles
	.4byte gTileset_BattleTent_Palettes  @ palettes
	.4byte gTileset_BattleTent_Metatiles  @ metatiles
	.4byte gTileset_BattleTent_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_MysteryEventsHouse
gTileset_MysteryEventsHouse: @ 0x083B8204
	.byte 0x01, 0x01, 0x00, 0x00  @ isCompressed, isSecondary
	.4byte gTileset_MysteryEventsHouse_Tiles  @ tiles
	.4byte gTileset_MysteryEventsHouse_Palettes  @ palettes
	.4byte gTileset_MysteryEventsHouse_Metatiles  @ metatiles
	.4byte gTileset_MysteryEventsHouse_MetatileAttributes  @ metatileAttributes
	.4byte 0x00000000  @ callback
	.globl gTileset_UnionRoom
gTileset_UnionRoom: @ 0x083B821C
	.incbin "baserom_jp.gba", 0x3B821C, 0x18
