gTVPokemonNewsBattleFrontierText00::
	.string "こんにちは！\n"
	.string "“ポケモン　ニュース”の　じかんです\p"
	.string "バトルフロンティアから\n"
	.string "うれしい　ニュースが　はいって　きました！$"

gTVPokemonNewsBattleFrontierText01::
	.string "バトルタワー　シングル　バトルルームに\n"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText02::
	.string "バトルタワー　ダブル　バトルルームに\n"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText03::
	.string "バトルタワー　マルチ　バトルルームに\n"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText04::
	.string "バトルタワー\n"
	.string "つうしん　マルチ　バトルルームに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText05::
	.string "バトルドーム\n"
	.string "シングル　バトルトーナメントに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんぱで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText06::
	.string "バトルドーム\n"
	.string "ダブル　バトルトーナメントに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんぱで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText07::
	.string "バトルファクトリー\n"
	.string "バトルトレード　シングルに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText08::
	.string "バトルファクトリー\n"
	.string "バトルトレード　ダブルに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText09::
	.string "バトルチューブで\n"
	.string "バトルゲームに　ちょうせんした\l"
	.string "{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　へや　とっぱで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText10::
	.string "バトルアリーナで\n"
	.string "かちぬきチームバトルに　ちょうせんした\l"
	.string "{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　にんぬきで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText11::
	.string "バトルパレス\n"
	.string "シングル　バトルホールに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText12::
	.string "バトルパレス\n"
	.string "ダブル　バトルホールに\l"
	.string "ちょうせんした　{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　れんしょうで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText13::
	.string "バトルピラミッドで\n"
	.string "バトルアドベンチャーに　ちょうせんした\l"
	.string "{STR_VAR_1}さんが\l"
	.string "{STR_VAR_2}　だん　せいはで\l"
	.string "きろくを　こうしん　しました！\p"
	.string "⋯⋯{STR_VAR_1}さん！$"

gTVPokemonNewsBattleFrontierText14::
	.string "{STR_VAR_1}と　{STR_VAR_2}と\n"
	.string "{STR_VAR_3}の　3ひきの　ポケモンたち！\p"
	.string "きろく　こうしん\n"
	.string "おめでとう　ございました！！$"

gTVPokemonNewsBattleFrontierText15::
	.string "{STR_VAR_1}と　{STR_VAR_2}の\n"
	.string "2ひきの　ポケモンたち！\p"
	.string "きろく　こうしん\n"
	.string "おめでとう　ございました！！$"

gTVPokemonNewsBattleFrontierText16::
	.string "{STR_VAR_1}！\p"
	.string "{STR_VAR_2}！\p"
	.string "{STR_VAR_3}！$"

gTVPokemonNewsBattleFrontierText17::
	.string "そして　{STR_VAR_1}の\n"
	.string "4ひきの　ポケモンたち！\p"
	.string "きろく　こうしん\n"
	.string "おめでとう　ございました！！$"

gTVPokemonNewsBattleFrontierText18::
	.string "{STR_VAR_1}さんと　ポケモンたちの\n"
	.string "つぎの　チャレンジに　きたい　しましょう！\p"
	.string "いじょう\n"
	.string "“ポケモン　ニュース”　でした！$"
