BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "あ！　いま　たたかっていた\n"
	.string "トレーナーの　かたですね！\p"
	.string "わたし　いま　いろんな　トレーナーの\n"
	.string "はなしを　きいて　まわってるんだけど\p"
	.string "たたかいおわった　かんそうを\n"
	.string "すこしだけ　きかせて　もらえませんか？$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "ほんと！？\n"
	.string "ありがとう！\l"
	.string "えっと　それじゃあねぇ⋯⋯\p"
	.string "こんかいの　バトルタワーの\n"
	.string "たいせんは　どうでしたか\p"
	.string "まんぞく　でしたか！\n"
	.string "それとも　ふまん　ですか！？$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "あぁ！\n"
	.string "ごめんなさい\p"
	.string "じゃあ　またこんど　バトルタワーに　きたら\n"
	.string "きかせて　くださいね$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "さっすが！\p"
	.string "その　まんぞくした　かおを　みれば\n"
	.string "どんなに　いいしあいだったか\l"
	.string "わかりますよ！$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "うーん　そうですか⋯⋯\p"
	.string "おもいどおりに　しょうぶを　するのって\n"
	.string "なかなか　むずかしい　ですからね⋯⋯$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "あぁっ　あと\n"
	.string "もう　ひとつだけ　いいですか？\p"
	.string "この　たたかいの　かんそうを\n"
	.string "ひとことで　ビシッと　きかせてください！$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "かっこいー！！\p"
	.string "いい　きめゼリフ　ですね\n"
	.string "つぎの　たたかいも　きたい　してますよ\p"
	.string "それでは　また！$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "そうですか⋯⋯\p"
	.string "でも　なにも　いわないのも\n"
	.string "また　かっこいいですね！\p"
	.string "それじゃあ　またの　きかいに\n"
	.string "かんそうを　きかせて　ください！$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "つぎの　たたかいも\n"
	.string "きたい　してますよ$"

BravoTrainerBattleTower_Text_Intro::
	.string "イヤー！\n"
	.string "“ブラボー　トレーナー”の　じかんだ！\p"
	.string "きょうは　バトルタワーに　ちょうせんした\n"
	.string "{B_COPY_VAR_1}さんの　しょうかいだー！\p"
	.string "{B_COPY_VAR_1}さんは　{B_COPY_VAR_2}を\n"
	.string "つかった　たたかいをして$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "なんと　{B_COPY_VAR_1}の　へやで\n"
	.string "{B_COPY_VAR_2}れんしょう　という\l"
	.string "きろくを　うちたてたぞ！$"

BravoTrainerBattleTower_Text_Lost::
	.string "おしくも　{B_COPY_VAR_2}にんめで　たたかった\n"
	.string "{B_COPY_VAR_1}さんに　まけて　しまいました\l"
	.string "うーん！　ざんねんだねぇ\p"
	.string "でも　こんなはじめに　{B_COPY_VAR_1}さんに\n"
	.string "あたるとは　うんがないとしか　いえないよ\p"
	.string "さて　その　{B_COPY_VAR_1}さんとの\n"
	.string "しょうぶの　かんそうを　きいたところ$"

BravoTrainerBattleTower_Text_Won::
	.string "さいごには　{B_COPY_VAR_1}さんの\n"
	.string "{B_COPY_VAR_2}を　みごとに　たおして\l"
	.string "しょうり　したんですねぇ\p"
	.string "いや　{B_COPY_VAR_1}さんに　かつなんて\n"
	.string "すごいとしか　いいようがないよ　まったく\p"
	.string "さて　そのしょうりを　つかんだ\n"
	.string "しゅんかんの　かんそうを　きいたところ$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "しかし　さいごに　とうじょうした\n"
	.string "{B_COPY_VAR_1}さんの　{B_COPY_VAR_2}に\l"
	.string "ついに　まけて　しまったんですねぇ\p"
	.string "まあ　‘{B_COPY_VAR_1}の　{B_COPY_VAR_2}'\n"
	.string "といえば　ゆうめいな　コンビ　ですからね\p"
	.string "⋯⋯さて　その　ゆうめいじんとの\n"
	.string "しょうぶの　かんそうを　きいたところ$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "まんぞく　した！！\p"
	.string "と　すがすがしく　こたえてくれたよ\n"
	.string "さすがだぜ！\p"
	.string "まんぞくいく　たたかいが　できるなんて\n"
	.string "ほんと　すごいよねぇ　まったく！\p"
	.string "その　まんぞくかんは　つぎの　ひとことを\n"
	.string "きいたとき　すべて　わかったよ$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "ふまんだった⋯⋯\p"
	.string "と　びみょうに　おちこみながら\n"
	.string "こたえて　くれたよ\p"
	.string "⋯⋯まあ　まんぞくいく　たたかいって\n"
	.string "なかなかできる　もんじゃないからねー\p"
	.string "そのときの　くやしさは\n"
	.string "つぎの　ひとことが　よくあらわしてるよ$"

BravoTrainerBattleTower_Text_None1::
	.string "なし$"

BravoTrainerBattleTower_Text_None2::
	.string "なし$"

BravoTrainerBattleTower_Text_None3::
	.string "なし$"

BravoTrainerBattleTower_Text_None4::
	.string "なし$"

BravoTrainerBattleTower_Text_Response::
	.string "その　ことばは\n"
	.string "‘{B_COPY_VAR_1}！'$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "‘{B_COPY_VAR_1}！'\n"
	.string "うーん　　いい　ことばだねぇ！！\p"
	.string "{B_COPY_VAR_2}さんの　うれしさを\n"
	.string "このことばが　よく　あらわしているよ！\p"
	.string "たしかに　{B_COPY_VAR_3}さんとの　たたかいは\n"
	.string "まさに　‘{B_COPY_VAR_1}'　という\l"
	.string "かんじ　だったからねぇ！$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "‘{B_COPY_VAR_1}！'\n"
	.string "なるほどねぇ\p"
	.string "たしかに　{B_COPY_VAR_3}さんとの　たたかいは\n"
	.string "‘{B_COPY_VAR_1}'　としか　いいようがない\l"
	.string "たたかい　でしたからねぇ\p"
	.string "{B_COPY_VAR_2}さんの　くやしさが\n"
	.string "よく　つたわってくるよ！　くー！$"

BravoTrainerBattleTower_Text_Outro::
	.string "ブラボー！　{B_COPY_VAR_1}\n"
	.string "ブラボー！！　{B_COPY_VAR_2}\p"
	.string "こんごの　{B_COPY_VAR_1}さんの　かつやくに\n"
	.string "きたい　したいねぇ！\p"
	.string "それじゃあ　また　じかいの\n"
	.string "ほうそうで　あいましょー！$"
