gTVBreakingNewsText00::
	.string "⋯⋯きんきゅう　スペシャル　テレビ！！$"

gTVBreakingNewsText01::
	.string "“{STR_VAR_1}さん　レア　{STR_VAR_2}を\n"
	.string "　つかまえるーーー！！”\p"
	.string "⋯⋯はい！\n"
	.string "こちら　{STR_VAR_3}　です！\p"
	.string "さきほど　{STR_VAR_1}さんが\n"
	.string "レア　{STR_VAR_2}を　つかまえる　ことに\l"
	.string "せいこう　しました！$"

gTVBreakingNewsText02::
	.string "レア　{STR_VAR_2}に　であった\n"
	.string "{STR_VAR_1}さんは\l"
	.string "{STR_VAR_3}で　たたかいを　いどみました！\p"
	.string "そして⋯⋯$"

gTVBreakingNewsText03::
	.string "ボールを　{STR_VAR_1}かい　なげて\n"
	.string "みごと　{STR_VAR_2}の　なかに\l"
	.string "つかまえた　のです！$"

gTVBreakingNewsText04::
	.string "その　しゅんかん　{STR_VAR_2}には\n"
	.string "{STR_VAR_1}さんの　よろこびの　おたけびが\l"
	.string "ひびき　わたった　そうです！\p"
	.string "いやー　{STR_VAR_1}さん！\n"
	.string "うらやましいです！\l"
	.string "わたしも　いっしょに　さけびたいです！\p"
	.string "⋯⋯いじょう\n"
	.string "よろこび　いっぱいの　げんばより\l"
	.string "おつたえ　しました！$"

gTVBreakingNewsText05::
	.string "“{STR_VAR_1}さん　レア　{STR_VAR_2}を\n"
	.string "　とりにがすーーー！！”\p"
	.string "⋯⋯はい！\n"
	.string "こちら　{STR_VAR_3}です！\p"
	.string "さきほど　{STR_VAR_1}さんが\n"
	.string "レア　{STR_VAR_2}を　つかまえることに\l"
	.string "しっぱい　しました！$"

gTVBreakingNewsText06::
	.string "レア　{STR_VAR_2}に　であった\n"
	.string "{STR_VAR_1}さんは\l"
	.string "{STR_VAR_3}で　たたかいを　いどみました$"

gTVBreakingNewsText07::
	.string "そして⋯⋯\p"
	.string "{STR_VAR_2}に　{STR_VAR_1}　などを\n"
	.string "めいれい　している　うちに\l"
	.string "きが　つくと　たおしていた　のです⋯⋯$"

gTVBreakingNewsText12::
	.string "しかし⋯⋯\p"
	.string "レア　{STR_VAR_2}に　おどろいて\n"
	.string "こんらんした　{STR_VAR_1}さんは\l"
	.string "わけも　わからないまま\l"
	.string "{STR_VAR_3}に　めいれいを　してしまい\l"
	.string "きが　つくと　たおしていた　のです⋯⋯$"

gTVBreakingNewsText08::
	.string "その　しゅんかん　{STR_VAR_2}には\n"
	.string "{STR_VAR_1}さんの　かなしみの　さけびが\l"
	.string "ひびき　わたった　そうです⋯⋯$"

gTVBreakingNewsText09::
	.string "しかし⋯⋯\p"
	.string "ボールが　なかったのか　このあと\n"
	.string "{STR_VAR_2}から　にげてしまった　のです\p"
	.string "その　しゅんかん　{STR_VAR_3}には\n"
	.string "{STR_VAR_1}さんの　かなしみの　さけびが\l"
	.string "ひびき　わたった　そうです⋯⋯$"

gTVBreakingNewsText10::
	.string "しかし⋯⋯\p"
	.string "{STR_VAR_2}は　あっというまに\n"
	.string "にげてしまった　のです\p"
	.string "その　しゅんかん　{STR_VAR_3}には\n"
	.string "{STR_VAR_1}さんの　かなしみの　さけびが\l"
	.string "ひびき　わたった　そうです⋯⋯$"

gTVBreakingNewsText11::
	.string "いやー　{STR_VAR_1}さん！\n"
	.string "ざんねん　でした⋯⋯\l"
	.string "わたしも　いっしょに　さけびたいです\p"
	.string "⋯⋯いじょう\n"
	.string "かなしみ　いっぱいの　げんばより\l"
	.string "おつたえ　しました⋯⋯！$"
