ContestLiveUpdates_Text_Intro::
	.string "“ポケモン　コンテスト\n"
	.string "　けっか　そくほう！”\p"
	.string "しかい“⋯⋯はい！\n"
	.string "こちら　さきほど　おわりました\l"
	.string "{STR_VAR_1}　コンテストの　かいじょうです\p"
	.string "かいじょうには　まだ　たくさんの\n"
	.string "おきゃくさんが　のこっています\p"
	.string "かんきゃく“{STR_VAR_2}ーーー！\p"
	.string "かんきゃく“{STR_VAR_3}ーーー！\p"
	.string "しかい“⋯⋯と　みなさんが　おっしゃる\n"
	.string "とおりに　ゆうしょう　ポケモンは\l"
	.string "{STR_VAR_3}さんの　{STR_VAR_2}　でした！\p"
	.string "かんきゃく“{STR_VAR_2}！　さいこー！\p"
	.string "かんきゃく“{STR_VAR_3}！　えらいー！\p"
	.string "しかい“それでは⋯⋯　おきゃくさんに\n"
	.string "ちょっと　かんそうを　きいて　みましょう！$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "かんきゃく“1じ　しんさも　2じ　しんさも\n"
	.string "だんとつで　1ばん　でしたー！\l"
	.string "{STR_VAR_2}　つぎも　ゆうしょうだー！$"

ContestLiveUpdates_Text_BetterRound2::
	.string "かんきゃく“1じ　しんさが　だめ　だったのに\n"
	.string "2じ　しんさで　だいぎゃくてん！\l"
	.string "ミラクル　{STR_VAR_2}　ばんざいーー！$"

ContestLiveUpdates_Text_EqualRounds::
	.string "かんきゃく“1じ　しんさも　2じ　しんさも\n"
	.string "あんてい　しておったのう⋯⋯\p"
	.string "{STR_VAR_2}に　{STR_VAR_3}さん！\n"
	.string "あんたら　ただものでは　ないのう⋯⋯$"

ContestLiveUpdates_Text_BetterRound1::
	.string "かんきゃく“{STR_VAR_2}の\n"
	.string "あの　{STR_VAR_1}は　ケタちがい　でしたね！\l"
	.string "つぎは　もっと　アピールを　がんばってー！$"

ContestLiveUpdates_Text_GotNervous::
	.string "かんきゃく“{STR_VAR_2}が\n"
	.string "きんちょう　したとき　おもわず\l"
	.string "がんばれー　って　さけんじゃいました\p"
	.string "{STR_VAR_2}　よかったね　おめでとう！$"

ContestLiveUpdates_Text_StartledFoes::
	.string "かんきゃく“{STR_VAR_2}の　アピールで\n"
	.string "おもわず　ボクも　おどろいちゃった！\p"
	.string "{STR_VAR_2}！　きみは　スゴイ！$"

ContestLiveUpdates_Text_UsedCombo::
	.string "かんきゃく“{STR_VAR_2}の\n"
	.string "あの　コンボでの　アピール！\l"
	.string "ああ　もう　ウットリ⋯⋯$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "かんきゃく“{STR_VAR_2}の　アピールに\n"
	.string "もう　もえあがっちゃいました！$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}！\n"
	.string "かっこよかった　よー！$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}\n"
	.string "うつくしかった　よー！$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}\n"
	.string "かわいかった　よー！$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}！\n"
	.string "かしこかった　よー！$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}！\n"
	.string "たくましかった　よー！$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "かんきゃく“{STR_VAR_2}の　アピールに\n"
	.string "もう　もえつきちゃい　ました！$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}！\n"
	.string "さいこうに　かっこいいー！$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}！\n"
	.string "さいこうに　うつくしいー！$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}！\n"
	.string "さいこうに　かわいいー！$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}！\n"
	.string "さいこうに　かしこいー！$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}！\n"
	.string "さいこうに　たくましいー！$"

ContestLiveUpdates_Text_TookBreak::
	.string "かんきゃく“{STR_VAR_2}が　とちゅうで\n"
	.string "アピールを　やすんだ　ときも⋯⋯\l"
	.string "ずーっと　{STR_VAR_2}だけ　みてました！\p"
	.string "もう　{STR_VAR_2}の　とりこ　です⋯⋯$"

ContestLiveUpdates_Text_GotStartled::
	.string "かんきゃく“{STR_VAR_2}が　ほかの\n"
	.string "ポケモンの　アピールに　おどろいた　ときは\l"
	.string "もう　なきそうに　なっちゃいました！\p"
	.string "{STR_VAR_2}\n"
	.string "がんばったねー！　えらい！$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "かんきゃく“ああ⋯⋯\n"
	.string "{STR_VAR_2}の　{STR_VAR_3}！\l"
	.string "{STR_VAR_2}の　{STR_VAR_3}！\l"
	.string "{STR_VAR_2}の　{STR_VAR_3}！\l"
	.string "なんで　あんなに　ステキなんだー！$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "しかい“⋯⋯いやー　すごいですね\n"
	.string "{STR_VAR_1}ファン　いっしょくです\p"
	.string "その　ほかの　トレーナーさんと　ポケモンで\n"
	.string "わたしの　いんしょうに　のこったのは⋯⋯\l"
	.string "{STR_VAR_2}さんと　{STR_VAR_3}ですね\p"
	.string "{STR_VAR_2}さんの　{STR_VAR_3}は⋯⋯$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "きんちょうして　2じしんさで　1かいも\n"
	.string "アピールが　できませんでした\p"
	.string "つぎは　1かい　だけでも　{STR_VAR_1}の\n"
	.string "アピールを　みたいものです$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "1じしんさも　2じしんさも\n"
	.string "ダントツで　ビリでした\p"
	.string "{STR_VAR_1}さんには　{STR_VAR_2}を\n"
	.string "きたえ　なおして\l"
	.string "ビリから　ぬけだして　ほしいです$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "かいじょうが　もりあがっている　ときに\n"
	.string "ふさわしい　アピールが　できません　でした\p"
	.string "{STR_VAR_1}さんには　ながれを　よんで\n"
	.string "つぎこそ　かいじょうを　エキサイト　させて\l"
	.string "さいこうに　もりあげて　ほしいです$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "1じしんさで　いちばん　だったのに\n"
	.string "2じしんさの　アピールが　うまくいかず\l"
	.string "ぎゃくてん　まけを　してしまいました\p"
	.string "きっと　いまごろ　{STR_VAR_1}さんは\n"
	.string "アピールに　ついて\l"
	.string "べんきょう　していると　おもいます$"

ContestLiveUpdates_Text_NeverExciting::
	.string "2じ　しんさの　アピールで　1ども\n"
	.string "かんきゃくが　もりあがり　ませんでした\p"
	.string "ほかの　ポケモンの　ことは　きにせず\n"
	.string "もっと　かんきゃくに　むかって\l"
	.string "アピールをして　ほしいです$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "{STR_VAR_1}さんの　{STR_VAR_2}と\n"
	.string "ちょっとの　さで　まけて　しまいました\p"
	.string "あと　すこしで　ゆうしょう　だったのに\n"
	.string "とっても　ざんねんです\p"
	.string "いまごろ　{STR_VAR_3}さんは\n"
	.string "ないていると　おもいます$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "おなじ　アピールを　つづけて　しんさいんに\n"
	.string "がっかりされて　しまいました\p"
	.string "コンテストで　やっては　いけない\n"
	.string "ミスを　したのが　いたかったですね\p"
	.string "いまごろ　{STR_VAR_1}さんは\n"
	.string "じぶんを　せめていると　おもいます$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1}さん　なりに　がんばって\n"
	.string "いたのですが⋯⋯\p"
	.string "けっかてきに　ビリに　なってしまいました\p"
	.string "{STR_VAR_1}さんには　まけた　りゆうを\n"
	.string "かんがえて　つぎに　つなげて　ほしいです$"

ContestLiveUpdates_Text_Outro::
	.string "それでは　さいごに　みなさんと　ごいっしょに\n"
	.string "{STR_VAR_1}さんと　{STR_VAR_2}に\l"
	.string "ひとこと　おくりたいと　おもいます\p"
	.string "しかい“みなさん　いいですかー？　せーの\p"
	.string "みんな“{STR_VAR_1}さん！　{STR_VAR_2}！\n"
	.string "コンテスト　ゆうしょう　おめでとうー！$"
