GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "マリ“おっ　こんなところに\n"
	.string "つよそうな　トレーナー　はっけん！\p"
	.string "よーし　カメラを　まわして\n"
	.string "インタビュー　かいしよ！$"

GabbyAndTy_Text_GabbyIntro:
	.string "マリ“あ！　あなたは\n"
	.string "このあいだの　{PLAYER}さん！\p"
	.string "よーし　どのくらい　つよく　なったか\n"
	.string "さっそく　インタビュー　かいしよ！$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "マリ“わたしの　めに　くるいはないわ\n"
	.string "すごい　トレーナーの　はっけんよ！$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "マリ“すごい！　すごい！\n"
	.string "あなた　いったい　なにもの！？\p"
	.string "さすが　わたしたちが\n"
	.string "めを　つけただけ　あるわ！\p"
	.string "⋯⋯あっ　じつは　わたしたち\n"
	.string "いろんな　ばしょの　いろんな　トレーナーを\l"
	.string "インタビューして　まわっているのよ\p"
	.string "だから　すこしだけ\n"
	.string "インタビュー　させて　もらえないかな？$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "マリ“‘{STR_VAR_1}！'\p"
	.string "おぼえてる？　まえに　たたかった　とき\n"
	.string "あなたが　いった　きめゼリフよ\p"
	.string "わたしたち　ちゃーんと\n"
	.string "おぼえてるん　だからね！$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "そうそう　まえに　たたかった　ときは\n"
	.string "ても　あしも　でなかった　のよねぇ⋯⋯\p"
	.string "ところで　どう？\n"
	.string "また　インタビュー　うけてみる？$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "そうそう　まえに　たたかった　ときは\n"
	.string "ボールを　なげられ　たんだっけ⋯⋯\p"
	.string "もう　びっくりして　みんなに\n"
	.string "いいふらし　ちゃったわよ！\p"
	.string "ところで　どう？\n"
	.string "また　インタビュー　うけてみる？$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "そうそう　まえに　たたかった　ときは\n"
	.string "どうぐを　うまく　つかわれて\l"
	.string "まけちゃった　のよね\p"
	.string "ところで　どう？\n"
	.string "また　インタビュー　うけてみる？$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "そうそう　まえに　たたかった　ときは\n"
	.string "けっこう　いいしょうぶ　だったんだよね⋯⋯\p"
	.string "ところで　どう？\n"
	.string "また　インタビュー　うけてみる？$"

GabbyAndTy_Text_InterviewAgain:
	.string "ところで　どう？\n"
	.string "また　インタビュー　うけてみる？$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "ほんと！？\n"
	.string "ありがとう！\p"
	.string "じゃあ　たたかいの　あとの\n"
	.string "かんそうを　ビシッと　ひとことで\l"
	.string "どうぞ！$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "マリ“んー！\n"
	.string "さいこうの　きめゼリフね\p"
	.string "なんか　いいテレビばんぐみが\n"
	.string "できそうな　よかん！\p"
	.string "もしかしたら　このことを\n"
	.string "テレビで　ほうそうするかも　しれないから\l"
	.string "テレビの　チェックを　わすれないでね！\p"
	.string "それじゃあ\n"
	.string "また　どこかで！$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "マリ“そう⋯⋯\p"
	.string "でも　これからも　がんばってね！\n"
	.string "あなたのこと　ちゅうもく　してるわ！$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "マリ“あなたの　こと\n"
	.string "ちゅうもく　してるわ！$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "マリ“ポケモンを　いっぱい　つれてる\n"
	.string "つよい　トレーナーって　いない　かしら？$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "マリ“うーん　さすがね！\p"
	.string "まえに　たたかった　ときより\n"
	.string "ずっと　つよく　なってる！\p"
	.string "やっぱり　わたしたちが　みつけた\n"
	.string "トレーナー　よね！\p"
	.string "ところで　どう？\n"
	.string "こんどこそ　インタビューを\l"
	.string "うけて　もらえないかな？$"

GabbyAndTy_Text_GabbyDefeat:
	.string "マリ“すごい　たたかいだったわ！\n"
	.string "ほら　ちゃんと　カメラにとった！？$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "ダイ“おっ　こんなところに\n"
	.string "つよそうな　トレーナー　はっけん！\l"
	.string "さっそく　ろくが　かいしだ！$"

GabbyAndTy_Text_TyIntro:
	.string "ダイ“きみは　このあいだの！\p"
	.string "よーし　この　たたかいを\n"
	.string "すべて　カメラに　おさめてやる$"

GabbyAndTy_Text_TyPostBattle:
	.string "ダイ“さすがだな！\n"
	.string "いい　えいぞうを　とることが　できたよ！$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "ダイ“きみは　1ぴきしか　ポケモンを\n"
	.string "もって　ないのかい？\p"
	.string "ポケモンが　いっぱい　いたほうが\n"
	.string "いい　えいぞうに　なるんだが⋯⋯$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "ダイ“すごい　トレーナーの　はっけんだ\n"
	.string "これは　だいスクープだぞ！$"

GabbyAndTy_Text_TyDefeat:
	.string "ダイ“いまの　たたかいの　すべてが\n"
	.string "この　カメラのなかに！$"
