gTVNameRaterText00::
	.string "“せいめい　はんだん”の\n"
	.string "じかんが　やって　まいりました\p"
	.string "あなたの　つけた　ニックネームから\n"
	.string "ポケモンの　ことを\l"
	.string "うらなって　さしあげます\p"
	.string "すこしでも　アドバイスに\n"
	.string "なれば　よいと　おもいますな\p"
	.string "きょうは　{B_COPY_VAR_1}さんの　ポケモン\n"
	.string "{B_COPY_VAR_2}の　‘{B_COPY_VAR_3}'の\l"
	.string "ニックネームを　うらなって　みますかな\p"
	.string "ふむふむ⋯⋯\p"
	.string "うーむ\n"
	.string "この　ニックネームは⋯⋯$"

gTVNameRaterText01::
	.string "いろいろな　ところで　さいのうを\n"
	.string "はっき　できる　ニックネーム　ですなぁ！\p"
	.string "こんご　いろいろな　ことに\n"
	.string "チャレンジ　すると　よいと　おもいますよ$"

gTVNameRaterText02::
	.string "{B_COPY_VAR_1}さん　との　あいしょうが\n"
	.string "とても　よい　ニックネーム　ですなぁ！\p"
	.string "いきの　ぴったり　あった\n"
	.string "よい　コンビに　なると　おもいますよ$"

gTVNameRaterText03::
	.string "とても　こせいてきな　ポケモンに\n"
	.string "なる　ニックネーム　ですなぁ！\p"
	.string "きちんと　そだてて　やれば　その　こせいが\n"
	.string "おおきく　はな　ひらくと　おもいますよ$"

gTVNameRaterText04::
	.string "とても　おもいやりの　ある\n"
	.string "ポケモンに　なる　ニックネーム　ですなぁ！\p"
	.string "きちんと　そだてて　やれば\n"
	.string "それに　こたえて　くれると　おもいますよ$"

gTVNameRaterText05::
	.string "しょうらい　おおものに　なる\n"
	.string "とても　よい　ニックネーム　ですなぁ！\p"
	.string "しょうらいが　とても\n"
	.string "たのしみな　ポケモン　ですな$"

gTVNameRaterText06::
	.string "とても　けんこうてきな　ポケモンに\n"
	.string "なる　よい　ニックネーム　ですなぁ！\p"
	.string "いつまでも　げんきで\n"
	.string "いて　くれる　でしょう$"

gTVNameRaterText07::
	.string "とても　かつどうてきな　ポケモンに\n"
	.string "なる　よい　ニックネーム　ですなぁ！\p"
	.string "ポケモンしょうぶ　では\n"
	.string "おおいに　かつやく　すると　おもいますよ$"

gTVNameRaterText08::
	.string "とても　あいきょうの　ある\n"
	.string "ポケモンになる　ニックネーム　ですなぁ！\p"
	.string "ポケモンコンテスト　では\n"
	.string "とても　かつやく　できると　おもいますよ$"

gTVNameRaterText09::
	.string "この　‘{B_COPY_VAR_1}'という　ニックネームは\n"
	.string "‘{B_COPY_VAR_3}'の　もじを　ちゅうしん　として\l"
	.string "これに　‘{B_COPY_VAR_2}'が　つくことで\p"
	.string "どっしり　とした\n"
	.string "よい　ニックネームに　なっていますな$"

gTVNameRaterText10::
	.string "この　‘{B_COPY_VAR_1}'という　ニックネームは\n"
	.string "とても　かたちの　よい\l"
	.string "ニックネーム　ですなぁ\p"
	.string "ニックネームに　‘{B_COPY_VAR_2}'と　‘{B_COPY_VAR_3}'が\n"
	.string "はいって　いるのが　とても　よい！$"

gTVNameRaterText11::
	.string "この　‘{B_COPY_VAR_1}'という　ニックネームは\n"
	.string "とても　ながれの　よい\l"
	.string "ニックネーム　ですなぁ\p"
	.string "‘{B_COPY_VAR_2}'の　もじの　あとに\n"
	.string "‘{B_COPY_VAR_3}'がくる　ながれが　とても　よい！$"

gTVNameRaterText12::
	.string "⋯⋯さて　そのほかに\n"
	.string "よい　ニックネームの　れい　として$"

gTVNameRaterText13::
	.string "トレーナーの　{B_COPY_VAR_1}さんの\n"
	.string "なまえを　もってきて\p"
	.string "‘{B_COPY_VAR_2}{B_COPY_VAR_3}'と　いうのも\n"
	.string "とても　よい　ニックネーム　ですなぁ$"

gTVNameRaterText14::
	.string "もしくは　‘{B_COPY_VAR_2}{B_COPY_VAR_3}'と\n"
	.string "いうのも　よい　ニックネーム　ですな$"

gTVNameRaterText15::
	.string "もとの　ポケモンの　なまえ\n"
	.string "{B_COPY_VAR_2}から　すこし　もらって\p"
	.string "‘{B_COPY_VAR_1}{B_COPY_VAR_3}'や$"

gTVNameRaterText16::
	.string "‘{B_COPY_VAR_1}{B_COPY_VAR_3}'と　いうのも\n"
	.string "よい　ニックネーム　ですなぁ$"

gTVNameRaterText17::
	.string "まちがっても　ほかの　ポケモンの　なまえ\n"
	.string "たとえば　{B_COPY_VAR_2}の　なまえを　つけて\p"
	.string "‘{B_COPY_VAR_1}{B_COPY_VAR_3}'の　ような\n"
	.string "ニックネームに　しては　いけませんな$"

gTVNameRaterText18::
	.string "うむ　それにしても　‘{B_COPY_VAR_1}'は\n"
	.string "なかなか　よい　ニックネーム　ですな\p"
	.string "これからも　‘{B_COPY_VAR_1}'の　ことを\n"
	.string "たいせつに　して　ほしい　ものですなぁ\p"
	.string "それでは　また\n"
	.string "ごえんが　あれば$"
