gTVPokemonTodayFailedText00::
	.string "こんにちはー！\p"
	.string "“きょうの　ポケモン”の\n"
	.string "じかんだよー！！\p"
	.string "おねえさん“こんにちは　みんな　げんき！\n"
	.string "きょうは　{B_COPY_VAR_1}さんの　ポケモン\l"
	.string "{B_COPY_VAR_2}の　しょうかいを　するよ！\p"
	.string "おにいさん“するぞー！$"

gTVPokemonTodayFailedText01::
	.string "あ！\n"
	.string "{B_COPY_VAR_1}さん　といえば⋯⋯\p"
	.string "おねえさん　このまえ\n"
	.string "ぼく　みちゃった！！\p"
	.string "おねえさん“みちゃった　って\n"
	.string "なにを　みちゃったの？\p"
	.string "おにいさん“このまえ\n"
	.string "{B_COPY_VAR_2}に　でかけたとき\l"
	.string "{B_COPY_VAR_1}さんを　みかけたんだ\p"
	.string "ちょうど　{B_COPY_VAR_3}を　つかまえてる\n"
	.string "ところ　だったん　だけど⋯⋯$"

gTVPokemonTodayFailedText02::
	.string "とちゅうで　ポケモンに\n"
	.string "にげられ　ちゃったんだよ！！\p"
	.string "ボールを　{B_COPY_VAR_2}こも　なげたのに\n"
	.string "ぜんぶ　むだ⋯⋯\p"
	.string "ポケモンに　にげられた　ときの\n"
	.string "{B_COPY_VAR_1}さんの　くやしがった　かお\l"
	.string "すごかったなぁ⋯⋯$"

gTVPokemonTodayFailedText03::
	.string "とちゅうで　まちがって　ポケモンを\n"
	.string "たおし　ちゃったんだよ！！\p"
	.string "ボールを　{B_COPY_VAR_2}こも　なげたのに\n"
	.string "ぜんぶ　むだ⋯⋯\p"
	.string "ポケモンを　たおしちゃった　ときの\n"
	.string "{B_COPY_VAR_1}さんの　あぜんと　した　かお\l"
	.string "なんとも　いえなかったなぁ⋯⋯$"

gTVPokemonTodayFailedText04::
	.string "おねえさん“こらこらっ！\n"
	.string "たにんの　ふこうを　わらっちゃ　だめだよ\p"
	.string "あぁ　{B_COPY_VAR_1}さん\n"
	.string "とっても　かわいそう⋯⋯\p"
	.string "おにいさん“はーい！\n"
	.string "わらって　すいませーん$"

gTVPokemonTodayFailedText05::
	.string "おねえさん“プッ！\p"
	.string "おにいさん“あ！　いま\n"
	.string "わらったでしょ！？\p"
	.string "おねえさん“え！？\p"
	.string "わらってない\n"
	.string "わらってないよ！\p"
	.string "あぁ　{B_COPY_VAR_1}さん\n"
	.string "とっても　かわいそう⋯⋯\p"
	.string "おにいさん“⋯⋯$"

gTVPokemonTodayFailedText06::
	.string "おねえさん“じゃあ　きを　とりなおして\n"
	.string "ポケモンの　しょうかいを⋯⋯\p"
	.string "え？\n"
	.string "もう　じかんが　ない？\p"
	.string "もう！　ポケモンの　しょうかいが\n"
	.string "できなかった　じゃない！\p"
	.string "おにいさん“また　じかい　あおうぜ！\p"
	.string "おねえさん“かってに　しめるなー！！$"

gTVPokemonTodaySuccessfulText00::
	.string "こんにちはー！\p"
	.string "“きょうの　ポケモン”の\n"
	.string "じかんだよー！！\p"
	.string "おねえさん“こんにちは　みんな　げんき！\n"
	.string "きょうは　{B_COPY_VAR_1}さんの　ポケモン\l"
	.string "{B_COPY_VAR_2}の　しょうかいを　するよ！\p"
	.string "おにいさん“するぞー！$"

gTVPokemonTodaySuccessfulText01::
	.string "おねえさん“{B_COPY_VAR_1}さんは\n"
	.string "{B_COPY_VAR_2}に　‘{B_COPY_VAR_3}'って\p"
	.string "ニックネームを　つけて　たいせつに\n"
	.string "そだてて　るんだって！$"

gTVPokemonTodaySuccessfulText02::
	.string "おにいさん“ちなみに\n"
	.string "ボールを　ぜんぶで　{B_COPY_VAR_3}こ　なげて\p"
	.string "さいごは　{B_COPY_VAR_2}で\n"
	.string "つかまえたって　うわさだよ！$"

gTVPokemonTodaySuccessfulText03::
	.string "おねえさん“そんなに　かんたんに\n"
	.string "つかまえる　なんて\p"
	.string "{B_COPY_VAR_1}さんと　{B_COPY_VAR_2}の\n"
	.string "であいは　きっと　うんめい　だったのよ！$"

gTVPokemonTodaySuccessfulText04::
	.string "おねえさん“くろうして　やっと\n"
	.string "つかまえた　ポケモンは\l"
	.string "だいじに　されるって　いうしね！$"

gTVPokemonTodaySuccessfulText05::
	.string "おねえさん“{B_COPY_VAR_1}さんの\n"
	.string "{B_COPY_VAR_2}は　だいじな　マスターボールを\p"
	.string "つかって　やっと　つかまえた\n"
	.string "おもいでの　ポケモン　なんだって！\p"
	.string "おにいさん“えー！　すごいねー！\p"
	.string "おねえさん“{B_COPY_VAR_1}さん　ほんとうに\n"
	.string "{B_COPY_VAR_2}を　つかまえ　たかったんだね！$"

gTVPokemonTodaySuccessfulText06::
	.string "おにいさん“でも　その\n"
	.string "{B_COPY_VAR_2}に　‘{B_COPY_VAR_3}'って\p"
	.string "ニックネームを　つけるあたり\n"
	.string "{B_COPY_VAR_1}さんの　センスが　わかるね！\p"
	.string "おねえさん“そうだねー$"

gTVPokemonTodaySuccessfulText07::
	.string "わたしなら　{B_COPY_VAR_3}　とかに\n"
	.string "そのニックネームを　つけちゃう　けどね！\p"
	.string "おにいさん“おー！\n"
	.string "それ　なかなか　あたらしいかも！$"

gTVPokemonTodaySuccessfulText08::
	.string "‘{B_COPY_VAR_2}'かー\n"
	.string "まさに　{B_COPY_VAR_1}って　かんじよね！\p"
	.string "ほら！　もじの　ふんいきとか　なんとなく\n"
	.string "{B_COPY_VAR_1}って　かんじが　するもの！\p"
	.string "おにいさん“⋯⋯そうだね$"

gTVPokemonTodaySuccessfulText09::
	.string "わたしの　しってるかぎり　{B_COPY_VAR_1}に\n"
	.string "‘{B_COPY_VAR_2}'って　ニックネームを\l"
	.string "つけている　トレーナーなんて　いないよ！\p"
	.string "おにいさん“それだけ　ニックネームをつける\n"
	.string "センスが　いいって　ことだよ！$"

gTVPokemonTodaySuccessfulText10::
	.string "わたしも　こんど　ポケモンを　つかまえたら\n"
	.string "‘{B_COPY_VAR_2}'って　つけて　みようかな？\p"
	.string "おにいさん“え？　じゃあ　ぼくも\n"
	.string "‘{B_COPY_VAR_2}'って　つけよー！$"

gTVPokemonTodaySuccessfulText11::
	.string "おねえさん“あ！　もう　こんなじかん！\p"
	.string "それでは　また　じかいの\n"
	.string "ほうそうで　おあいしましょう\p"
	.string "おにいさん“つぎは　あなたの　ポケモンを\n"
	.string "しょうかい　するかもよ！$"
