gTVPokemonBattleUpdateText00::
	.string "“ポケモン　たいせん　そくほう！”\p"
	.string "さきほど　おこなわれた　ポケモンバトルの\n"
	.string "けっかを　おつたえします$"

gTVPokemonBattleUpdateText01::
	.string "{STR_VAR_1}さん　たい\n"
	.string "{STR_VAR_2}さんの　{STR_VAR_3}バトルは⋯⋯\p"
	.string "{STR_VAR_1}さんが\n"
	.string "しょうり　しました！$"

gTVPokemonBattleUpdateText02::
	.string "バトルは　{STR_VAR_1}さんの\n"
	.string "{STR_VAR_2}が　{STR_VAR_3}を　つかって\l"
	.string "だいかつやく　しました！$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}さんに　とっては\n"
	.string "{STR_VAR_2}が　ブレーキ　だったのが\l"
	.string "いたかった　ようです$"

gTVPokemonBattleUpdateText04::
	.string "しょうりを　おさめた\n"
	.string "{STR_VAR_1}さん！\l"
	.string "おめでとう　ございました！\p"
	.string "やぶれて　しまった\n"
	.string "{STR_VAR_2}さん！\l"
	.string "つぎは　がんばって　ください！\p"
	.string "いじょう\n"
	.string "“ポケモン　たいせん　そくほう！”　でした$"

gTVPokemonBattleUpdateText05::
	.string "{STR_VAR_1}さん　チーム　たい\n"
	.string "{STR_VAR_2}さん　チームの\l"
	.string "マルチバトルの　けっかは⋯⋯\p"
	.string "{STR_VAR_1}さん　チームが\n"
	.string "しょうり　しました$"

gTVPokemonBattleUpdateText06::
	.string "バトルは　{STR_VAR_1}さん　チームの\n"
	.string "{STR_VAR_2}が　{STR_VAR_3}を　つかって\l"
	.string "だいかつやく　しました！$"

gTVPokemonBattleUpdateText07::
	.string "{STR_VAR_2}さん　チームに　とっては\n"
	.string "{STR_VAR_3}が　ブレーキ　だったのが\l"
	.string "いたかった　ようです\p"
	.string "しょうりを　おさめた\n"
	.string "{STR_VAR_1}さん　チーム！\l"
	.string "おめでとう　ございました！\p"
	.string "やぶれて　しまった\n"
	.string "{STR_VAR_2}さん　チーム！\l"
	.string "つぎこそ　がんばって　ください！\p"
	.string "いじょう\n"
	.string "“ポケモン　たいせん　そくほう！”　でした$"
