gTVThePokemonBattleSeminarText00::
	.string "“ポケモン　バトル　こうざ！”\p"
	.string "きょうも　みなさんと　ごいっしょに\n"
	.string "バトルに　ついて　べんきょう　しましょう\p"
	.string "きょうの　もんだいは\n"
	.string "{STR_VAR_1}さんの　バトルに　ついてです\p"
	.string "{STR_VAR_1}さんは　{STR_VAR_2}で\n"
	.string "{STR_VAR_3}と　たたかったの　ですが⋯⋯$"

gTVThePokemonBattleSeminarText01::
	.string "{STR_VAR_2}に　たいして\n"
	.string "‘{STR_VAR_3}'を　やってしまいました⋯⋯\p"
	.string "うーん⋯⋯　{STR_VAR_1}さん！\n"
	.string "これは　いけませんね⋯⋯$"

gTVThePokemonBattleSeminarText02::
	.string "{STR_VAR_1}は　そのほかに⋯⋯$"

gTVThePokemonBattleSeminarText03::
	.string "‘{STR_VAR_1}'　‘{STR_VAR_2}'\n"
	.string "‘{STR_VAR_3}'　⋯⋯を　おぼえていました$"

gTVThePokemonBattleSeminarText04::
	.string "‘{STR_VAR_1}'　‘{STR_VAR_2}'\n"
	.string "⋯⋯を　おぼえていました$"

gTVThePokemonBattleSeminarText05::
	.string "‘{STR_VAR_2}'\n"
	.string "⋯⋯を　おぼえていました$"

gTVThePokemonBattleSeminarText06::
	.string "この　なかで　いちばん　よいのは\n"
	.string "⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯\p"
	.string "‘{STR_VAR_1}'　ですね！\p"
	.string "‘{STR_VAR_2}'より\n"
	.string "ぜったい　‘{STR_VAR_1}'です\p"
	.string "テレビの　まえの　みなさんも\n"
	.string "よーく　かんがえて　バトルを　しましょう！\p"
	.string "それでは　さようなら！$"
