SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "わあ！\p"
	.string "きみ　その　{B_COPY_VAR_1}を　とても\n"
	.string "だいじに　している　みたいね！\p"
	.string "{B_COPY_VAR_2}　って　いうんだ⋯⋯\p"
	.string "そうだ！\p"
	.string "いま　わたし　テレビの　しゅざいで\n"
	.string "ポケモンの　アンケートを　してるんだけど\p"
	.string "すこしだけ　しつもんに\n"
	.string "こたえて　くれないかな？$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "ありがとう！\p"
	.string "じゃあ　きくね\n"
	.string "ずばり　ひとことで　こたえて！$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "きみが　{B_COPY_VAR_1}と\n"
	.string "であったときって\p"
	.string "なにか　かんじた？\n"
	.string "どう　おもったか　おしえて！$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "きみの　かわいがってる　{B_COPY_VAR_1}！\p"
	.string "もし　なにか　すきなものに　たとえると\n"
	.string "すれば　なんだと　おもう？$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "きみの　かわいがってる　{B_COPY_VAR_1}！\p"
	.string "きみは　{B_COPY_VAR_1}の　どこに\n"
	.string "ひかれたの？$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "うーん　なるほどね\p"
	.string "じゃあ　つぎは　ちょっと\n"
	.string "むずかしい　しつもんを　するね！\p"
	.string "じゃあ⋯⋯\p"
	.string "きみに　とって　ポケモンって\n"
	.string "ひとことで　いうと　なんだと　おもう？$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "なるほどー！\p"
	.string "ふむふむ⋯⋯\p"
	.string "あ！\n"
	.string "きょうりょく　ありがとうね！\p"
	.string "いろいろ　はなしが　きけて\n"
	.string "おもしろ　かったよ\p"
	.string "このはなし　もしかしたら　テレビで\n"
	.string "ながすかも　しれないから　きたい　しててね\p"
	.string "じゃあね\n"
	.string "バイバイ！$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "そっか⋯⋯\p"
	.string "じゃあ　また　ポケモンの　ことを\n"
	.string "はなしたく　なったら　いつでも　きてね$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "ここに　いると　いろんな　ポケモンの\n"
	.string "はなしが　きけるから　おもしろいわ$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "きみの　その　{B_COPY_VAR_1}と\n"
	.string "とても　なかが　よさそうね\p"
	.string "そうだ！　いま　わたし\n"
	.string "テレビの　しゅざいで\p"
	.string "いろんな　ポケモンの　はなしを\n"
	.string "きいて　まわってるんだけど\p"
	.string "よかったら　きみの　{B_COPY_VAR_1}の\n"
	.string "はなしを　きかせて　くれないかな？$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "わあ！\n"
	.string "ありがとう！\p"
	.string "じゃあ　{B_COPY_VAR_1}の　はなし\n"
	.string "なんでも　いいので　きかせてよ！$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "へー⋯⋯\n"
	.string "おもしろい　はなし　だね！\p"
	.string "きみは　ほんとうに　{B_COPY_VAR_1}と\n"
	.string "なかが　いいんだね\p"
	.string "うーん　なんか　このはなしで\n"
	.string "いい　ばんぐみが　できそうな　よかん！\p"
	.string "きっと　おもしろい　ばんぐみに\n"
	.string "するから　たのしみに　まっててね\p"
	.string "じゃあ　ありがとうね\n"
	.string "バイバイ！$"

gTVFanClubOpinionsText00::
	.string "“ぼくたち！\n"
	.string "ポケモン　だいすきクラブ！”\p"
	.string "はい　はじまりました！\p"
	.string "このばんぐみは　みなさんの\n"
	.string "いけんを　このわたしが\l"
	.string "かわりに　さけんで　しまおう！\l"
	.string "という　すごい　ばんぐみ！！\p"
	.string "さて　きょうは　ポケモンだいすきクラブ　に\n"
	.string "いって　いろんな　はなしを　きいてきた\l"
	.string "リポーターからの　じょうほうだ！\p"
	.string "さて　きょうの\n"
	.string "ポケモンだいすき　にんげんは？\p"
	.string "んー⋯⋯\p"
	.string "{B_COPY_VAR_1}さんだー！！\p"
	.string "それでは　ごじぶんの　ポケモン\p"
	.string "{B_COPY_VAR_2}の　‘{B_COPY_VAR_3}'に\n"
	.string "ついての　あつい　きもちを\p"
	.string "かわりに　この　わたくしが　テレビに\n"
	.string "むかって　さけんで　あげましょう！\p"
	.string "うー！！\p"
	.string "レッツ　シャウト！！！$"

gTVFanClubOpinionsText01::
	.string "さて　{B_COPY_VAR_1}さんが　はじめて\n"
	.string "{B_COPY_VAR_2}と　あったとき　ちょっかんてきに\l"
	.string "おもった　ことは⋯⋯\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "んー　いい　さけびだ！\p"
	.string "まるで　そのときの　おもいでが\n"
	.string "よみがえる　ようだー！！$"

gTVFanClubOpinionsText02::
	.string "さて　{B_COPY_VAR_1}さんの　だいすきな\n"
	.string "{B_COPY_VAR_2}を　なにかに　たとえると　したら\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "んー　すごい　はっそうだ！！\p"
	.string "はげしい　{B_COPY_VAR_2}への　おもいこみが\n"
	.string "かんじられるねー！$"

gTVFanClubOpinionsText03::
	.string "さて　{B_COPY_VAR_1}さんが　{B_COPY_VAR_2}に\n"
	.string "ひかれた　りゆうは⋯⋯\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "おー！！　すんばらしい　いけんだー！\p"
	.string "{B_COPY_VAR_2}を　どんなに　すきか\n"
	.string "ビンビン　つたわって　くるねー！$"

gTVFanClubOpinionsText04::
	.string "んー？　まだ　つづきが　ありますねー\n"
	.string "よんで　みましょう！\p"
	.string "えーと⋯⋯\p"
	.string "{B_COPY_VAR_1}さんに　とって　ポケモンを\n"
	.string "ひとことで　たとえると　すれば　それは！\l"
	.string "⋯⋯\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "ブラボー！！\p"
	.string "いままでの　なかで　いちばん\n"
	.string "いい　さけび　だったー！\p"
	.string "‘{B_COPY_VAR_3}！！'\p"
	.string "なんども　さけびたくなる　ことばだねー！\p"
	.string "それでは　いいさけびと　であった　ところで\n"
	.string "また　じかい　おあいしましょう！\p"
	.string "さいごに　もういちど\n"
	.string "みんなで　さけびましょう！\p"
	.string "‘{B_COPY_VAR_3}！！'$"

gTVFanClubText00::
	.string "“ぼくたち！\n"
	.string "ポケモン　だいすきクラブ！”\p"
	.string "はい　はじまりました！\p"
	.string "じゃあ　きょうは　ポケモンアンケートの\n"
	.string "コーナーから！\p"
	.string "かずある　ポケモンと　トレーナーの\n"
	.string "はなしの　なかから\p"
	.string "きょうは　どんな　はなしが\n"
	.string "とびだして　くるのでしょうか！？\l"
	.string "さて　きょうの　はなしは？\p"
	.string "んー⋯⋯\p"
	.string "これだ！\p"
	.string "では　てがみの　しょうかい　から！！\p"
	.string "{B_COPY_VAR_2}の　ことに　ついて\n"
	.string "{B_COPY_VAR_1}さん　からの　おてがみだー\p"
	.string "では　どれだけ　{B_COPY_VAR_2}への\n"
	.string "あつい　いけんが　かいてあるか\l"
	.string "よませて　もらいましょう！\l"
	.string "えーと⋯⋯$"

gTVFanClubText01::
	.string "おー！！\n"
	.string "なんて　すばらしい　てがみなんだ！！$"

gTVFanClubText02::
	.string "きにいったから　もういちど！$"

gTVFanClubText03::
	.string "いい　てがみは\n"
	.string "なんど　きいても　いいねー！！$"

gTVFanClubText04::
	.string "‘{B_COPY_VAR_3}'　っていう　ことばの\n"
	.string "おかげで　グッと　こころに　つたわってくる\l"
	.string "いい　てがみに　なっているねー！！$"

gTVFanClubText05::
	.string "とくに‘{B_COPY_VAR_3}'って　ところ！\p"
	.string "‘{B_COPY_VAR_3}'っていう　ところが\n"
	.string "きにいったぞー！$"

gTVFanClubText06::
	.string "ところで　あんまり　かんけい　ないけど\n"
	.string "‘{B_COPY_VAR_3}'って　いいことば　だよね\p"
	.string "じつは　おれも　‘{B_COPY_VAR_3}'って\n"
	.string "ことば　さいきん　よく　つかうんだよね$"

gTVFanClubText07::
	.string "このてがみ　じぶんてきには\n"
	.string "{B_COPY_VAR_3}てん　ていう　かんじかなー！\p"
	.string "つぎは　もっと　いい　てがみを\n"
	.string "きたい　してるよ！　{B_COPY_VAR_1}さん！！\p"
	.string "おっと　もう　こんなじかんだ！\n"
	.string "それでは　また　じかい\l"
	.string "みなさま　おあい　しましょう！！$"
