SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "おや？\n"
	.string "あなたも　ポケモンのことが　おすきで？\p"
	.string "わたくし　テレビきょくの　もので\n"
	.string "さいきん　おきた\p"
	.string "トレーナーと　ポケモンの　できごとを\n"
	.string "きいて　まわって　いるのです\p"
	.string "もし　よければ　なにか\n"
	.string "はなしを　きかせて　くれませんかね？$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "いま　さいきん　おきた\n"
	.string "トレーナーと　ポケモンの　できごとを\l"
	.string "きいて　まわって　いるのですが\p"
	.string "もし　よければ　なにか\n"
	.string "はなしを　きかせて　くれませんかね？$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "おお　きかせて　くれますか！\n"
	.string "ありがとう　ございます\p"
	.string "では　さいきん　おきたこと　なら\n"
	.string "なんでも　よいので\l"
	.string "はなしを　きかせて　ください！$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "そうですか⋯⋯\p"
	.string "では　また　なにか　おもしろい　はなしが\n"
	.string "あったら　きかせて　くださいね$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "⋯⋯おお\n"
	.string "なんて　いいはなしだ！\p"
	.string "このはなし　テレビで\n"
	.string "つかわせて　いただきます！\p"
	.string "いつか　ほうそう　するかも　しれないので\n"
	.string "たのしみに　まっていて　くださいね$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "うーん\n"
	.string "いい　テレビばんぐみが　できそうだ！\p"
	.string "いそいで　まとめないと！$"

gTVRecentHappeningsText00::
	.string "“さいきんの　できごと”\p"
	.string "ポケモントレーナーに　とって\n"
	.string "まいにちが　ものがたりです\l"
	.string "その　ものがたりを　すこしでも\l"
	.string "しょうかい　できたら　うれしいですね\p"
	.string "さて　きょうは　トレーナーの\n"
	.string "{B_COPY_VAR_1}さんの　おはなしです\p"
	.string "{B_COPY_VAR_1}さん　さいきん\n"
	.string "どんなことが　あったんで　しょうか？\l"
	.string "さっそく　みてみることに　しましょう\p"
	.string "えーと⋯⋯$"

gTVRecentHappeningsText01::
	.string "なるほど　{B_COPY_VAR_1}さんの\n"
	.string "まわりで　さいきん　おきている　ことが\l"
	.string "てに　とるように　わかりますね$"

gTVRecentHappeningsText02::
	.string "‘{B_COPY_VAR_3}'という　ことばが\n"
	.string "おはなしに　ストーリーを　かんじさせますね$"

gTVRecentHappeningsText03::
	.string "‘{B_COPY_VAR_3}'という　ことばの\n"
	.string "おかげで　まるで　じょうけいが\l"
	.string "うかんで　くるようですね$"

gTVRecentHappeningsText04::
	.string "このおはなしは　‘{B_COPY_VAR_3}'という\n"
	.string "ぶぶんが　とても　いんしょうてき　ですね$"

gTVRecentHappeningsText05::
	.string "{B_COPY_VAR_1}さんは　とても　いい\n"
	.string "おはなしを　きかせて　くれましたね\p"
	.string "これで　あなたの　こころにも\n"
	.string "{B_COPY_VAR_1}さん　という　ストーリーが\l"
	.string "きざみ　こまれましたよ\p"
	.string "それでは　また　じかいの\n"
	.string "ほうそうで　おあいしましょう$"
