gTVSecretBaseVisitText00::
	.string "みなさん　こんにちは！\n"
	.string "“ひみつきち　ほうもん！”の　じかんです\p"
	.string "きょうは　{STR_VAR_1}さんの　ひみつきちに\n"
	.string "おじゃま　させて　いただきます\p"
	.string "{STR_VAR_1}さんの　きちは　どんな\n"
	.string "おへやに　なっている　のでしょうか？\p"
	.string "さっそく　はいって　みましょう！\n"
	.string "⋯⋯⋯　⋯⋯⋯　⋯⋯⋯　⋯⋯⋯$"

gTVSecretBaseVisitText01::
	.string "おおー！\p"
	.string "こんな　ところに　‘{STR_VAR_2}'が！\n"
	.string "すばらしい　ですねー$"

gTVSecretBaseVisitText02::
	.string "おおー！\p"
	.string "なんと！\n"
	.string "グッズが　なにも　ありません！\p"
	.string "ふつうの　ひとには　まね　できない\n"
	.string "この　だいたんさ！\p"
	.string "シンプルで　ありながら\n"
	.string "あふれでる　この　ワイルドさ！\p"
	.string "いやー\n"
	.string "さすが　{STR_VAR_1}さん　ですねー$"

gTVSecretBaseVisitText03::
	.string "ああー！　なるほど！\p"
	.string "ここに　‘{STR_VAR_2}'　ですか！\n"
	.string "これは　こうかてき　ですねー$"

gTVSecretBaseVisitText04::
	.string "ああー！　なるほど！\p"
	.string "ここには　わざと　グッズを　おかずに\n"
	.string "あけて　いるのですねー\p"
	.string "これは　こうかてき　ですねー$"

gTVSecretBaseVisitText05::
	.string "ふぇー！\p"
	.string "‘{STR_VAR_2}'と\n"
	.string "‘{STR_VAR_3}'の　くみあわせ！\p"
	.string "ゆめの　がったいに　なっていますねー$"

gTVSecretBaseVisitText06::
	.string "ふぇー！\p"
	.string "ここに　‘{STR_VAR_2}'ですか！\n"
	.string "ひみつきち　ぜんたいに　きいていますねー$"

gTVSecretBaseVisitText07::
	.string "ふぇー！\p"
	.string "ここには　なにも　おいていません\p"
	.string "いやー　この　なにもない　スペースが\n"
	.string "ひみつきち　ぜんたいに　きいてますねー$"

gTVSecretBaseVisitText08::
	.string "あっ！\n"
	.string "{STR_VAR_1}さんが　いらっしゃいます！\l"
	.string "さっそく　たいせん　してみましょう！\p"
	.string "⋯⋯　⋯⋯　⋯⋯　⋯⋯\n"
	.string "⋯⋯　⋯⋯　⋯⋯　⋯⋯$"

gTVSecretBaseVisitText09::
	.string "はぁー！\n"
	.string "さすが　{STR_VAR_1}さん　です\p"
	.string "チャンピオンと　よぶに　ふさわしい\n"
	.string "つよさの　ポケモン　でした\p"
	.string "{STR_VAR_1}さんの　ちからづよさが\n"
	.string "とっても　でていましたよ\p"
	.string "とくに　{STR_VAR_2}に\n"
	.string "‘{STR_VAR_3}'　なんて\l"
	.string "{STR_VAR_1}さん　らしいですねー\p"
	.string "いやー　べんきょう　させて　いただきました$"

gTVSecretBaseVisitText10::
	.string "ひぃー！\n"
	.string "さすが　{STR_VAR_1}さん　です\p"
	.string "ものすごく　つよい　ポケモン　でしたよ\p"
	.string "{STR_VAR_1}さんの　がんばりやさんな\n"
	.string "ところが　でていましたよ\p"
	.string "とくに　{STR_VAR_2}に\n"
	.string "‘{STR_VAR_3}'　なんて\l"
	.string "{STR_VAR_1}さん　らしいですねー\p"
	.string "いやー　べんきょう　させて　いただきました$"

gTVSecretBaseVisitText11::
	.string "ふぇー！\n"
	.string "さすが　{STR_VAR_1}さん　です\p"
	.string "バランスよく\n"
	.string "そだてられた　ポケモン　でしたよ\p"
	.string "{STR_VAR_1}さんの　きくばり　じょうずな\n"
	.string "ところが　でていましたよ\p"
	.string "とくに　{STR_VAR_2}に\n"
	.string "‘{STR_VAR_3}'　なんて\l"
	.string "{STR_VAR_1}さん　らしいですねー\p"
	.string "いやー　べんきょう　させて　いただきました$"

gTVSecretBaseVisitText12::
	.string "ほぉー！\n"
	.string "さすが　{STR_VAR_1}さん　です\p"
	.string "しょうらいの　せいちょうが\n"
	.string "たのしみな　ポケモン　でしたよ\p"
	.string "{STR_VAR_1}さんの　ゆめと　きぼうが\n"
	.string "でていましたよ\p"
	.string "とくに　{STR_VAR_2}に\n"
	.string "‘{STR_VAR_3}'　なんて\l"
	.string "{STR_VAR_1}さん　らしいですねー\p"
	.string "いやー\n"
	.string "べんきょう　させて　いただきました$"

gTVSecretBaseVisitText13::
	.string "いやー\n"
	.string "すばらしい　おへや　でしたねー\p"
	.string "みなさんも　いちど　{STR_VAR_1}さんの\n"
	.string "ひみつきちを　ごほうもん　されてみては\l"
	.string "いかが　でしょうか？\p"
	.string "では　また　じかい　おあいしましょう！\n"
	.string "さようなら！$"
