TVSecretBaseSecrets_Text_Intro::
	.string "“ひみつきちの　ヒミツー！”\p"
	.string "ひみつきちで　トレーナーは　いったい\n"
	.string "どんな　こうどうを　とる　のでしょうか？\p"
	.string "きょうは\n"
	.string "{STR_VAR_1}さんの　ひみつきちです\p"
	.string "⋯⋯さあ　{STR_VAR_2}さんが\n"
	.string "あそびに　いらした　ようですね！\p"
	.string "さっそく　のぞいてみましょう！\p"
	.string "まず　{STR_VAR_2}さんは⋯⋯$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "{STR_VAR_2}さんは　つぎに⋯⋯$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "この　あと\n"
	.string "{STR_VAR_2}さんは⋯⋯$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "⋯⋯と　いうような　かんじで\n"
	.string "{STR_VAR_2}さんは\l"
	.string "{STR_VAR_1}さんの　きちを\l"
	.string "{STR_VAR_3}ほ　あるいて　かえりました$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "⋯⋯うーん\p"
	.string "どうやら　{STR_VAR_2}さんは\n"
	.string "{STR_VAR_1}さんの　ひみつきちに\l"
	.string "きょうみが　わかなかった　ようですね⋯⋯$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2}さんは\n"
	.string "{STR_VAR_1}さんの　ひみつきちを\l"
	.string "とっても　たのしんだ　ようですね$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2}さんは\n"
	.string "{STR_VAR_1}さんの　ひみつきちマニアに\l"
	.string "なった　ようですね$"

TVSecretBaseSecrets_Text_Outro::
	.string "テレビの　まえの　みなさんも\n"
	.string "{STR_VAR_1}さんの　ひみつきちを\l"
	.string "たずねて　みては　いかがでしょうか？\p"
	.string "それでは　また　だれかの　ひみつきちで\n"
	.string "おあいしましょう！　さようなら！$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "⋯⋯たちどまって　しまいました！\p"
	.string "ぜんぜん　うごきません！\p"
	.string "{STR_VAR_1}さんの　ひみつきちが\n"
	.string "きに　いらなかった　のでしょうか？$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "⋯⋯たちどまって　しまいました！\p"
	.string "ぜんぜん　うごきません！\p"
	.string "⋯⋯つかれちゃった　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "いすに　すわりましたー！\p"
	.string "とっても　うれしそうです\p"
	.string "すわりごこちが\n"
	.string "よかった　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "ふうせんに　とつげきだー！\p"
	.string "わっちゃいました！\p"
	.string "ちょっと　おとに\n"
	.string "ビックリ　しています$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "テントに　はいったー！\p"
	.string "はしりまわって　います！\p"
	.string "あばれまわって　います！\p"
	.string "テントの　おおきさに\n"
	.string "びっくり　しています！！$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "はちうえを　かんさつ　しています！\p"
	.string "いがいに　アダルトな　しゅみを\n"
	.string "もっていますね⋯⋯$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "きんのたてを　みています！\p"
	.string "キラキラと　めを\n"
	.string "かがやかせて　いますね$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "ぎんのたてを　みています！\p"
	.string "めを　まるーく　していますね$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "ガラスのオブジェを　みています⋯⋯\p"
	.string "あっ！\p"
	.string "さわっちゃいました⋯⋯\p"
	.string "しもんを　ペタペタ　つけています$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "テレビを　みています！\p"
	.string "かなりの　テレビっこ　みたいですねー$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "どろだんごを　ふみつけましたー！\p"
	.string "とっても　うれしそうです$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "⋯⋯おや？\p"
	.string "とつぜん　バッグの　なかみを\n"
	.string "ガサガサと　いじりだしましたよ！\p"
	.string "そして　{STR_VAR_2}を\n"
	.string "とりだしたー！\p"
	.string "{STR_VAR_2}を　もって\n"
	.string "スマイル！　スマイル！！\p"
	.string "テレビの　コマーシャル　みたいだー！$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "クッションを　つかんで⋯⋯$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "たたいてます！\p"
	.string "だいぶ　ストレスが\n"
	.string "たまっている　のでしょうか？$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "だきついたー！\p"
	.string "なにか　いいことでも　あった　のでしょうか？$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "{STR_VAR_1}さんと　はなしています！\p"
	.string "どうやら　ポケモンバトルを　やるようです\p"
	.string "そして⋯⋯\p"
	.string "かったー！！\p"
	.string "うれしがっています$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "{STR_VAR_1}さんと　はなしています！\p"
	.string "どうやら　ポケモンバトルを　やるようです\p"
	.string "そして⋯⋯\p"
	.string "まけたー！！\p"
	.string "がっかり　しています$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "{STR_VAR_1}さんと　はなしています！\p"
	.string "どうやら　ポケモンバトルを　やるようです\p"
	.string "そして⋯⋯\p"
	.string "いや　ことわった！\p"
	.string "たいせんを　ことわりました！\p"
	.string "{STR_VAR_1}さんの　ことが\n"
	.string "きに　いらなかった　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "ポスターを　じーっと　みつめています！\p"
	.string "きに　いった　のでしょうか？\p"
	.string "⋯⋯でも\n"
	.string "ちょっと　めつきが　やばいですねー$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "おんぷマットに　のったー！\p"
	.string "⋯⋯うーん\n"
	.string "ふしぎな　きょくを　つくっちゃいました⋯⋯$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "{STR_VAR_1}さんと　はなしています！\p"
	.string "どうやら　ポケモンバトルを　やるようです\p"
	.string "そして⋯⋯\p"
	.string "ひきわけたー！\p"
	.string "ふたりとも　とっても　くやしそうです$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "くるっとマットに　のったー！\p"
	.string "めが　まわった　ようです！\p"
	.string "クラクラ　しています$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "すなのおきものに　てを　ふれて⋯⋯\p"
	.string "あっ！\p"
	.string "こわしちゃいましたー！\p"
	.string "かおが　すこし　ひきつっています$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "つくえの　うえを\n"
	.string "ゆびで　さわっています！\p"
	.string "どうやら　ほこりが\n"
	.string "きに　なっている　みたいです！\p"
	.string "いやー\n"
	.string "いがいに　こまかい　ですねー$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "レンガを　じーっと　みつめています！\p"
	.string "この　レンガにあう　グッズの　ことでも\n"
	.string "かんがえている　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "じょうぶないたの　うえを　あるいています！\p"
	.string "ちょっと　したを　きにしています\p"
	.string "いがいに　きが　ちっちゃいですねー$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "さくを　じーっと　ながめています！\p"
	.string "あたらしい　トラップでも\n"
	.string "ひらめいた　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "きらきらマットに　のったー！\p"
	.string "いろんな　ポーズを　きめています！\p"
	.string "きぶんは　アイドル　でしょうか？$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "タイヤを　じーっと　みつめています！\p"
	.string "この　タイヤで　はしる　くるまの　ことでも\n"
	.string "かんがえている　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "おおきなだいに　のぼりました！\p"
	.string "{STR_VAR_1}さんの　きちを\n"
	.string "うえから　みわたしています！\p"
	.string "⋯⋯そして\p"
	.string "さけんだー！$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "やぶれるドアに　むかって　とつげきー！\p"
	.string "わらっています⋯⋯$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "ぬいぐるみに　はなし　かけています！\p"
	.string "ちょっと　こわい　ですね⋯⋯$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "すべりだいの　はしごを　のぼりました！\p"
	.string "⋯⋯そして\p"
	.string "すべったー！\p"
	.string "とっても　たのしそうだ！$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "すべりだいの　はしごを　のぼりました！\p"
	.string "⋯⋯そして\p"
	.string "もどったー！\p"
	.string "ハシゴを　おりて　ひきかえしました！\p"
	.string "こわくなった　のでしょうか？$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "ジャンプマットに　のったー！\p"
	.string "ジャンプを　1かい！\p"
	.string "ジャンプを　2かい！\p"
	.string "ちゃくち　せいこう！\p"
	.string "⋯⋯ひとりで　じぶんに\n"
	.string "はくしゅを　おくっています$"
