SmartShopper_Text_Intro::
	.string "こんにちは\p"
	.string "“きょうの　かいもの　じょうず”の\n"
	.string "じかん　です\p"
	.string "インタビュアー“みなさん　おげんきですか？\p"
	.string "きょうは　{B_COPY_VAR_2}の\n"
	.string "おみせに　きています\p"
	.string "さいきん　なにが　うれているのか\n"
	.string "チェック　してみましょう！$"

SmartShopper_Text_ClerkNormal::
	.string "それでは　てんいんさんに\n"
	.string "インタビュー　してみましょう\l"
	.string "どうですか　うれて　いますか？\p"
	.string "てんいん“はい　おかげさまで\p"
	.string "とくに　{B_COPY_VAR_2}が\n"
	.string "いま　うれて　いるんですよ\p"
	.string "このまえも　{B_COPY_VAR_1}さん　という\n"
	.string "かたが　{B_COPY_VAR_3}こも　かって　いかれました$"

SmartShopper_Text_RandomComment1::
	.string "インタビュアー“{B_COPY_VAR_2}を\n"
	.string "{B_COPY_VAR_3}こも　かうなんて　すごいですね！\p"
	.string "もしかしたら　{B_COPY_VAR_1}さんは\n"
	.string "これから　とおくまで　いくための\l"
	.string "たびじたくを　していたのかも　しれませんね\p"
	.string "やっぱり　たびには　{B_COPY_VAR_2}ですね！$"

SmartShopper_Text_RandomComment2::
	.string "インタビュアー“{B_COPY_VAR_2}　といえば\n"
	.string "わたし　なんか　このまえ\l"
	.string "{B_COPY_VAR_3}こも　かいましたよ！\p"
	.string "{B_COPY_VAR_2}って　いいですからねー！$"

SmartShopper_Text_RandomComment3::
	.string "インタビュアー“{B_COPY_VAR_2}を！！\n"
	.string "{B_COPY_VAR_3}こも！？\p"
	.string "⋯⋯そんなに　かうひとが\n"
	.string "いるなんて　しらなかったわ\p"
	.string "わたし　なんか　せいぜい　1こか　2こしか\n"
	.string "かわないから⋯⋯$"

SmartShopper_Text_RandomComment4::
	.string "インタビュアー“わたしも　むかし\n"
	.string "{B_COPY_VAR_2}を　たくさん　かったことが\l"
	.string "あったん　ですけど\p"
	.string "あまって　しまって\n"
	.string "こうかい　したわ⋯⋯\p"
	.string "それからと　いうもの　ひつような\n"
	.string "ぶんだけ　かうように　してるの⋯⋯\p"
	.string "おっと！\p"
	.string "わたしの　ことを　はなしても\n"
	.string "しょうがない　ですね！$"

SmartShopper_Text_SecondItem::
	.string "てんいん“{B_COPY_VAR_1}さんは　そのほかにも\n"
	.string "{B_COPY_VAR_2}を　{B_COPY_VAR_3}こ\l"
	.string "まとめて　かわれましたよ\p"
	.string "インタビュアー“おー　{B_COPY_VAR_2}も\n"
	.string "なかなか　よい　ですもんね！$"

SmartShopper_Text_ThirdItem::
	.string "てんいん“ついでに　{B_COPY_VAR_2}も\n"
	.string "{B_COPY_VAR_3}こ　かわれて　いきました$"

SmartShopper_Text_DuringSale::
	.string "てんいん“しかも　おおやすうりの　とき\n"
	.string "ですから　さすが　ですよね！$"

SmartShopper_Text_OutroNormal::
	.string "インタビュアー“うーん⋯⋯\n"
	.string "{B_COPY_VAR_1}さんって　かなりの\l"
	.string "かいものじょうず　なのかも　しれませんね！\p"
	.string "これで　ごうけいは⋯⋯\p"
	.string "{B_COPY_VAR_2}えん！？\n"
	.string "さすが　ですね！\p"
	.string "おっと　それでは　またじかいの\n"
	.string "ほうそうで　おあい　しましょう！$"

SmartShopper_Text_IsVIP::
	.string "てんいん“{B_COPY_VAR_1}さんは　ほんとうに\n"
	.string "だいじな　おきゃくさま　ですよ$"

SmartShopper_Text_ClerkMax::
	.string "それでは　てんいんさんに\n"
	.string "インタビュー　して　みましょう\l"
	.string "どうですか　うれて　ますか？\p"
	.string "てんいん“はい　おかげさまで\n"
	.string "うれてうれて　こまって　ますよ！\p"
	.string "このまえ　{B_COPY_VAR_1}さん　というかたが\n"
	.string "{B_COPY_VAR_2}を　たくさん　かわれまして\p"
	.string "みせのなかに　{B_COPY_VAR_2}が\n"
	.string "なくなって　しまいそう　だったんですよ！\p"
	.string "わたくしも　{B_COPY_VAR_2}を　そんなに\n"
	.string "かう　おきゃくさまが　いるなんて\l"
	.string "ゆめにも　おもいません　でした　からね！\p"
	.string "インタビュアー“と　いうことは⋯⋯\n"
	.string "100こ　とか　200こ　とか　ですか？\p"
	.string "てんいん“いや　もっと　でしたよ！\p"
	.string "インタビュアー“うひゃー！\n"
	.string "{B_COPY_VAR_1}さんって　すごい　ですね！\p"
	.string "てんいん“{B_COPY_VAR_1}さんは　ほんとうに\n"
	.string "だいじな　おきゃくさま　ですよ$"

SmartShopper_Text_OutroMax::
	.string "インタビュアー“うーん　すごい　ですね\p"
	.string "でも　なんで　そんなに\n"
	.string "いっぱい　かったので　しょう？\p"
	.string "⋯⋯\p"
	.string "なぞは　ふかまる　ばかりですが\n"
	.string "じかんの　ようなので\l"
	.string "またじかい　おあい　しましょう！\p"
	.string "それに　しても\n"
	.string "{B_COPY_VAR_1}さんって　なぞだわ⋯⋯$"
