
gTV3CheersForPokeblocksText01::
	.string "ゴクリン“グビィ！　グビィ！\p"
	.string "しかい“おお！　とっても　{B_COPY_VAR_1}くて\n"
	.string "‘{B_COPY_VAR_2}！'と　いってますね\p"
	.string "きっと　これは　{B_COPY_VAR_3}さんが\n"
	.string "がんばって　まわした　おかげですね！\p"
	.string "{B_COPY_VAR_3}さん！\n"
	.string "ごちそうさま　でした！$"

gTV3CheersForPokeblocksText02::
	.string "こんかい　いまいち　だった\n"
	.string "{B_COPY_VAR_1}さんが\l"
	.string "もっと　じょうずに　まわすことが　できれば\l"
	.string "さらに　おいしく　なるかも　しれませんよ！$"

gTV3CheersForPokeblocksText03::
	.string "ゴクリン“グビィ！　グビィ！\p"
	.string "しかい“うーん⋯⋯　ちょっと　{B_COPY_VAR_1}すぎて\n"
	.string "‘{B_COPY_VAR_2}！'と　いってますね⋯⋯\p"
	.string "やっぱり　{B_COPY_VAR_3}さんの　しっぱいが\n"
	.string "いたかった　ですね⋯⋯$"

gTV3CheersForPokeblocksText04::
	.string "こんかい　いちばん　がんばっていた\n"
	.string "{B_COPY_VAR_1}さんが　かわいそうです⋯⋯\p"
	.string "⋯⋯{B_COPY_VAR_2}さん！\n"
	.string "つぎは　がんばって　ください！$"

gTV3CheersForPokeblocksText05::
	.string "では　また　おあいしましょう！\n"
	.string "あいことばは　“ポロック　バンザイ！”$"
