gTVTodaysRivalTrainerText00::
	.string "“きょうの　ライバル　トレーナー”\p"
	.string "ポケモン　トレーナーの　みなさん！\n"
	.string "ごきげん　いかがですか？\p"
	.string "きょうも　みなさんの　ライバルたちの\n"
	.string "ようすに　ついて　おつたえします！$"

gTVTodaysRivalTrainerText07::
	.string "こんかいの　トレーナーは\n"
	.string "げんざい　{B_COPY_VAR_3}に\l"
	.string "いらっしゃる　{B_COPY_VAR_1}さん　です！\p"
	.string "{B_COPY_VAR_1}さんは\n"
	.string "ポケモン　ずかんを　{B_COPY_VAR_2}ひき\l"
	.string "とうろく　されていますねー！$"

gTVTodaysRivalTrainerText08::
	.string "こんかいの　トレーナーは\n"
	.string "げんざい　ひみつきちに\l"
	.string "いらっしゃる　{B_COPY_VAR_1}さん　です！\p"
	.string "{B_COPY_VAR_1}さんは\n"
	.string "ポケモン　ずかんを　{B_COPY_VAR_2}ひき\l"
	.string "とうろく　されていますねー！$"

gTVTodaysRivalTrainerText09::
	.string "こんかいの　トレーナーは\n"
	.string "{B_COPY_VAR_1}さん　です！\p"
	.string "げんざい　{B_COPY_VAR_1}さんは\n"
	.string "ポケモン　ずかんを　{B_COPY_VAR_2}ひき\l"
	.string "とうろく　されていますねー！$"

gTVTodaysRivalTrainerText10::
	.string "こんかいの　トレーナーは\n"
	.string "げんざい　れんらくせんに　のっている\l"
	.string "{B_COPY_VAR_1}さん　です！\p"
	.string "{B_COPY_VAR_1}さんは\n"
	.string "ポケモン　ずかんを　{B_COPY_VAR_2}ひき\l"
	.string "とうろく　されていますねー！$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "バッジは　{B_COPY_VAR_1}こ\n"
	.string "かくとく　されていますよー！$"

gTVTodaysRivalTrainerText02::
	.string "バッジは　まだ　1こも\n"
	.string "かくとく　されていませんねー！$"

gTVTodaysRivalTrainerText03::
	.string "バトルフロンティアの　シンボルは\n"
	.string "1こも　かくとく　されていませんねー！$"

gTVTodaysRivalTrainerText04::
	.string "バトルフロンティアの　シンボルは\n"
	.string "ゴールドシンボルを　{B_COPY_VAR_1}こ\l"
	.string "シルバーシンボルを　{B_COPY_VAR_2}こ\l"
	.string "かくとく　されていますねー！$"

gTVTodaysRivalTrainerText05::
	.string "バトルフロンティアでの\n"
	.string "バトルポイントは　げんざい\l"
	.string "{B_COPY_VAR_1}　BP　あつめていますねー！$"

gTVTodaysRivalTrainerText06::
	.string "{B_COPY_VAR_1}さんの　ようすは\n"
	.string "みなさんと　くらべて　いかが　でしたか？\p"
	.string "まだまだ　ぼうけんは　つづきます\p"
	.string "トレーナーの　みなさん！\p"
	.string "ライバルたちに　まけずに\n"
	.string "がんばって　くださいねー！$"
