LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "やあ！\p"
	.string "ボク　{B_COPY_VAR_1}の　ファン　なんだけど\n"
	.string "{B_COPY_VAR_1}　って　どう　おもう？$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "なるほどねー\n"
	.string "そんな　ふうに　おもっているんだね！$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "{B_COPY_VAR_1}の　こと\n"
	.string "わすれちゃったの⋯⋯？$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "ボク　{B_COPY_VAR_1}の　ファン　なんだけど\n"
	.string "{B_COPY_VAR_1}　って　どうおもう？$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "じゃあ　こんどは\n"
	.string "{B_COPY_VAR_1}の　つよさを\l"
	.string "てんすうで　おしえてくれる？$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "{B_COPY_VAR_1}の　こと\n"
	.string "わすれちゃったの⋯⋯？$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "そっか！\n"
	.string "こんど　{B_COPY_VAR_1}に　あってみてよ！\l"
	.string "きみも　きっと　ファンに　なっちゃうよ！$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "そうなんだー！\p"
	.string "ありがとう！\n"
	.string "とっても　さんこうに　なったよ！\p"
	.string "さっそく　{B_COPY_VAR_1}の　ファン　みんなで\n"
	.string "この　ことに　ついて　はなしあって　みるよ！$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "もうすぐ　{B_COPY_VAR_1}に　ついての\n"
	.string "テレビ　ばんぐみが　ほうそう　されるんだ！\p"
	.string "きみも　ぜひ　みてね！$"

gTVTrainerFanClubSpecialText00::
	.string "“トレーナー　ファンクラブ\n"
	.string "　{B_COPY_VAR_1}　スペシャル！”\p"
	.string "ホウエン　かくちに　いらっしゃる\n"
	.string "{B_COPY_VAR_1}ファンの　みなさま\l"
	.string "おまたせしました！\p"
	.string "きょうは　{B_COPY_VAR_1}さんが\n"
	.string "‘どのように　おもわれているか？'を\l"
	.string "いっしょに　かんがえて　いきましょう！\p"
	.string "ほかの　トレーナーさんを　だいひょうして\n"
	.string "{B_COPY_VAR_2}さん　から　ごいけんを\l"
	.string "いただきました！\p"
	.string "まず　{B_COPY_VAR_1}さんを\n"
	.string "ひとことで　いい　あらわすと⋯⋯\p"
	.string "‘{B_COPY_VAR_3}'\p"
	.string "さすが　{B_COPY_VAR_2}さん！\n"
	.string "よく　みて　いらっしゃいますね！\p"
	.string "‘{B_COPY_VAR_3}　{B_COPY_VAR_1}！'\n"
	.string "いいですねー\p"
	.string "つづいて　{B_COPY_VAR_1}さんの　つよさに\n"
	.string "てんすうを　つけると⋯⋯$"

gTVTrainerFanClubSpecialText01::
	.string "‘{B_COPY_VAR_3}てん！'\p"
	.string "すごい　こうとくてん　ですね\n"
	.string "{B_COPY_VAR_2}さんは　{B_COPY_VAR_1}さんを\l"
	.string "とっても　そんけい　していますね$"

gTVTrainerFanClubSpecialText02::
	.string "‘{B_COPY_VAR_3}てん！'\p"
	.string "いい　てんすう　ですね\n"
	.string "{B_COPY_VAR_2}さんは　{B_COPY_VAR_1}さんを\l"
	.string "ライバル　として　みていますね$"

gTVTrainerFanClubSpecialText03::
	.string "‘{B_COPY_VAR_3}てん！'\p"
	.string "ちょっと　いまいち　ですね\n"
	.string "{B_COPY_VAR_2}さんは　{B_COPY_VAR_1}さんを\l"
	.string "じぶんの　こぶん　として　みていますね$"

gTVTrainerFanClubSpecialText04::
	.string "‘{B_COPY_VAR_3}てん！'\p"
	.string "ひどい　てんすう　ですね\n"
	.string "{B_COPY_VAR_2}さんは　{B_COPY_VAR_1}さんを\l"
	.string "したっぱ　として　みていますね$"

gTVTrainerFanClubSpecialText05::
	.string "いやー　なるほど！\p"
	.string "{B_COPY_VAR_1}さんに　ついて\n"
	.string "あたらしい　はっけんが　ありましたね！\p"
	.string "では　さいごに　{B_COPY_VAR_2}さんの\n"
	.string "ことばで　おわかれ　しましょう！\p"
	.string "{B_COPY_VAR_1}　{B_COPY_VAR_3}！$"
