gTVTrainerFanClubText00::
	.string "せーの！\n"
	.string "“トレーナー　だいすき　クラブ！！”\p"
	.string "しかい“みんなー　げんきかーい！？\n"
	.string "きょうは　いま　だいにんきの　トレーナー\l"
	.string "{STR_VAR_1}さんの　ファンに\l"
	.string "あつまって　もらったよ！\p"
	.string "ファン“ワアアアアアアアアアーーー！\p"
	.string "ファン“{STR_VAR_1}さまーーーー！\p"
	.string "しかい“みんなー！\n"
	.string "{STR_VAR_1}さんの　ことは　すきかいー？\p"
	.string "ファン“だいすきー！！\p"
	.string "しかい“どんな　ところがー？$"

gTVTrainerFanClubText01::
	.string "ファン“モンスターボールを　なげる　しぐさが\n"
	.string "かっこいい　ところ！！$"

gTVTrainerFanClubText02::
	.string "ファン“はしる　すがたが\n"
	.string "かわいい　ところ！！$"

gTVTrainerFanClubText03::
	.string "ファン“ポケモンバトルで\n"
	.string "ここ　いちばんに　つよい　ところ！！$"

gTVTrainerFanClubText04::
	.string "ファン“ポケモンの　ことに　ついて\n"
	.string "くわしい　ところ！！$"

gTVTrainerFanClubText05::
	.string "ファン“ポケモンに　たいして\n"
	.string "いつも　やさしい　ところ！！$"

gTVTrainerFanClubText06::
	.string "ファン“じてんしゃを　あやつる\n"
	.string "テクニックが　すごい　ところ！！$"

gTVTrainerFanClubText07::
	.string "ファン“アイテムの　かいかたが\n"
	.string "ごうかいな　ところ！！$"

gTVTrainerFanClubText08::
	.string "ファン“ポケモンに　つける　ニックネームが\n"
	.string "おちゃめな　ところ！！$"

gTVTrainerFanClubText09::
	.string "ファン“ひみつきちの　センスが\n"
	.string "いい　ところ！！$"

gTVTrainerFanClubText10::
	.string "ファン“わざマシンの　つかい　かたが\n"
	.string "だいたんな　ところ！！$"

gTVTrainerFanClubText11::
	.string "しかい“そんな　ホットな\n"
	.string "{STR_VAR_1}さん　ファンの　あいだには\l"
	.string "とくべつな　あいことばが　あるんだよー！\p"
	.string "しかい“{STR_VAR_1}　といえば⋯⋯\p"
	.string "しかい“{STR_VAR_2}！\p"
	.string "ファン“{STR_VAR_3}！\p"
	.string "しかい“{STR_VAR_2}！\p"
	.string "ファン“{STR_VAR_3}！\p"
	.string "しかい“{STR_VAR_1}　といえば⋯⋯\n"
	.string "{STR_VAR_2}　{STR_VAR_3}\l"
	.string "うーん！　いい　ひびきだねー！\p"
	.string "{STR_VAR_1}さんの　ファンに\n"
	.string "なっちゃうのも　わかる　きが　するよー！\p"
	.string "よーし！　テレビの　まえの　みんなも\n"
	.string "いっしょに　いってみよー！！\p"
	.string "しかい“{STR_VAR_1}　といえば⋯⋯\p"
	.string "しかい“{STR_VAR_2}！\p"
	.string "ファン“{STR_VAR_3}！\p"
	.string "しかい“{STR_VAR_2}！\p"
	.string "ファン“{STR_VAR_3}！\p"
	.string "しかい“{STR_VAR_1}さん　ファンの\n"
	.string "みんなー　ありがとーーー！！\l"
	.string "それじゃー　またねー！！\p"
	.string "しかい“{STR_VAR_1}　といえば⋯⋯\p"
	.string "しかい“{STR_VAR_2}！\p"
	.string "ファン“{STR_VAR_3}！$"
