TrendWatcher_Text_Intro::
	.string "“ムロタウン\n"
	.string "　りゅうこう　じょうほうきょく”\p"
	.string "しかい“さあ　きょうも　ムロタウンの\n"
	.string "りゅうこうを　いちはやく　おとどけします\p"
	.string "ゲストは　ムロタウン　いち\n"
	.string "ものしり　という　この　おじいさんです！\p"
	.string "ろうじん“⋯⋯ふむ　よろしくじゃ\p"
	.string "しかい“さっそく　ですが　ムロタウンで\n"
	.string "いま　はやっている　ことと　いえば⋯⋯\p"
	.string "ろうじん“{STR_VAR_1}　{STR_VAR_2}\p"
	.string "しかい“{STR_VAR_1}　{STR_VAR_2}\n"
	.string "⋯⋯ですか？\p"
	.string "ろうじん“⋯⋯いいや！\n"
	.string "{STR_VAR_1}　{STR_VAR_2}　は\l"
	.string "まったく　はやらんかった　のじゃ⋯⋯\l"
	.string "この　はなし　ききたいか　のう⋯⋯？\p"
	.string "しかい“いや　いまの　りゅうこうを⋯⋯$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "ろうじん“{STR_VAR_1}　{STR_VAR_2}　は\n"
	.string "ミシロから　きた　{STR_VAR_3}くんが\l"
	.string "おしえて　くれたの　じゃがのう⋯⋯$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "ろうじん“{STR_VAR_1}　{STR_VAR_2}　は\n"
	.string "ミシロから　きた　{STR_VAR_3}ちゃんが\l"
	.string "おしえて　くれたの　じゃがのう⋯⋯$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "まったく　ダメ　じゃった⋯⋯\p"
	.string "{STR_VAR_1}　{STR_VAR_2}　まつり！\p"
	.string "{STR_VAR_1}　{STR_VAR_2}　たいかい！\p"
	.string "わしも　みんなに　いっしょうけんめい\n"
	.string "おしえたの　じゃがのう⋯⋯\p"
	.string "‘{STR_VAR_1}'が　わるかったのか　のう⋯⋯\p"
	.string "しかい“⋯⋯すいませんが\n"
	.string "いまの　りゅうこうを⋯⋯$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "ろうじん“{STR_VAR_3}くん！\n"
	.string "{STR_VAR_1}　{STR_VAR_2}　より\l"
	.string "すごい　こと　また　おしえて　おくれー$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "ろうじん“{STR_VAR_3}ちゃん！\n"
	.string "{STR_VAR_1}　{STR_VAR_2}　より\l"
	.string "すごい　こと　また　おしえて　おくれー$"

TrendWatcher_Text_Outro::
	.string "しかい“⋯⋯えーと　⋯⋯はい！　ということで\n"
	.string "{STR_VAR_1}　{STR_VAR_2}　は⋯⋯\l"
	.string "ムロタウンで　はやらなかった！\p"
	.string "⋯⋯いじょうを　おつたえしました\p"
	.string "ろうじん“{STR_VAR_1}　{STR_VAR_2}$"
