gTVWhatsNo1InHoennTodayText00::
	.string "“ホウエン　きょうの\n"
	.string "　なんでも　ナンバー1！！”\p"
	.string "テレビの　まえの　みなさん\n"
	.string "がんばってますかー？\p"
	.string "きょうも　いちにちで　いちばん　がんばった\n"
	.string "トレーナーを　しょうかい　しますよ！\p"
	.string "⋯⋯さあ\n"
	.string "きょうの　ナンバー1　トレーナーは⋯⋯\l"
	.string "{STR_VAR_1}さんです！！$"

gTVWhatsNo1InHoennTodayText01::
	.string "{STR_VAR_1}さんは　ゲームコーナーの\n"
	.string "スロットを　いちにちで\l"
	.string "{STR_VAR_2}　かい　まわしました！\p"
	.string "{STR_VAR_1}さんは　あそんで　いるときに\n"
	.string "‘スロットが　とまって　みえる⋯⋯！'と\l"
	.string "ブツブツ　ぶきみに\l"
	.string "つぶやいていた　そうですよ！$"

gTVWhatsNo1InHoennTodayText02::
	.string "{STR_VAR_1}さんは　ゲームコーナーの\n"
	.string "ルーレットを　いちにちで\l"
	.string "{STR_VAR_2}　かい　まわしました！\p"
	.string "{STR_VAR_1}さんは　あそんで　いるとき\n"
	.string "‘ボールの　うごきが　よめた⋯⋯！'と\l"
	.string "めを　まっかにして\l"
	.string "それは　すごい　かおで\l"
	.string "さけんでいた　そうですよ！$"

gTVWhatsNo1InHoennTodayText03::
	.string "{STR_VAR_1}さんは　やせい　ポケモンと\n"
	.string "いちにちで　{STR_VAR_2}　かい　たたかいました！\p"
	.string "{STR_VAR_1}さんの　ポケモンたちは\n"
	.string "いぜんと　くらべものに　ならないほど\l"
	.string "つよくなった　らしく⋯⋯\p"
	.string "だれかと　ポケモンしょうぶが　したくて\n"
	.string "たまらない　そうですよ！$"

gTVWhatsNo1InHoennTodayText04::
	.string "{STR_VAR_1}さんは　きのみブレンダーを\n"
	.string "いちにちで　{STR_VAR_2}　かい　まわしました！\p"
	.string "さすがに　さいごの　ほうでは\n"
	.string "{STR_VAR_1}さんの　めも\l"
	.string "くるくる　まわってしまい\l"
	.string "まるで　パッチールの　ように\l"
	.string "なってしまった　そうですよ！$"

gTVWhatsNo1InHoennTodayText05::
	.string "{STR_VAR_1}さんは　きのみを\n"
	.string "いちにちで　{STR_VAR_2}　こ　うえました！\p"
	.string "{STR_VAR_1}さんの\n"
	.string "ふくは　まっくろに　なりましたが⋯⋯\p"
	.string "きのみを　うえた　ところには\n"
	.string "きれいな　はなが　たくさん　さきほこり\l"
	.string "みる　ひとの　こころを\l"
	.string "なごませている　そうですよ！$"

gTVWhatsNo1InHoennTodayText06::
	.string "{STR_VAR_1}さんは　きのみを　いちにちで\n"
	.string "{STR_VAR_2}　こ　とりました\p"
	.string "{STR_VAR_1}さんの　バックは\n"
	.string "きのみで　いっぱいに　なり\l"
	.string "あるくのも　たいへんだった　そうですよ！$"

gTVWhatsNo1InHoennTodayText07::
	.string "{STR_VAR_1}さんは　いちにちで\n"
	.string "バトルポイントを\l"
	.string "{STR_VAR_2}　BP　ためました！\p"
	.string "{STR_VAR_1}さんは　\n"
	.string "たまった　バトルポイントで\l"
	.string "すごい　グッズを　もらうべきか⋯⋯\l"
	.string "すごい　アイテムを　もらうべきか⋯⋯と\l"
	.string "ニタニタ　しながら\l"
	.string "ずっと　なやんでいた　そうですよ！$"

gTVWhatsNo1InHoennTodayText08::
	.string "いやー　すごい　ですね！\p"
	.string "{STR_VAR_1}さん！\n"
	.string "あなたが　きょうの　ナンバー1です！！\p"
	.string "テレビの　まえの　みなさんも\n"
	.string "{STR_VAR_1}さんに　まけずに\l"
	.string "いちにち　がんばりましょうね！$"
