gTVWorldOfMastersText00::
	.string "“めいじんの　せかい”\p"
	.string "みなさん　こんにちは\p"
	.string "みなさんは　{B_COPY_VAR_1}さん　という\n"
	.string "トレーナーを　しってますか？\p"
	.string "{B_COPY_VAR_1}さんは　ポケモンを　つかまえる\n"
	.string "めいじん　として　ゆうめい　なんです\p"
	.string "{B_COPY_VAR_1}さんの　ポケモンさがしは\n"
	.string "あるきまわる　ところから　はじまります\p"
	.string "このまえは　ポケモンを　さがすために\n"
	.string "1にちで　{B_COPY_VAR_2}ほ　いじょうも　あるき\p"
	.string "つかまえた　ポケモンの　かずは\n"
	.string "なんと　{B_COPY_VAR_3}　ひきにも　なったとか！$"

gTVWorldOfMastersText01::
	.string "きっと　あいぼうの　{B_COPY_VAR_1}と\n"
	.string "しんらい　しあっている　からこそ\l"
	.string "こんな　すごいことが　できるんですね$"

gTVWorldOfMastersText02::
	.string "めいじんは　さいごに\n"
	.string "{B_COPY_VAR_2}で\l"
	.string "{B_COPY_VAR_3}を　つかまえ\p"
	.string "きねんの　ポケモンとして　だいじに\n"
	.string "している　らしいですよ\p"
	.string "じしんのある　トレーナーは　このきろくに\n"
	.string "ちょうせんして　みては　いかがですか？\p"
	.string "それでは　また\n"
	.string "じかい　おあいしましょう$"
